### ISSUE TITLE
Properties erased by group instance

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#100]
Yo. It looks like an object's properties are completely erased by its group instance (if it belongs to one); shouldn't those properties be added to or overwritten by similarly named properties on group instances? For example:

On Guard, there's a property named "behavior", set to "stand". It also has a property named "health", set to 100. That makes it so that guards will, by default, stand there with 100 health (you could do this in code, of course, but this is an example).

But then, you decide that you want a specific guard to walk left. So, on a group instance of a Guard, you set the "behavior" property to "walk left"; I would then expect this instance of the Guard object to have a "behavior" property set to "walk left" *and* a "health" property set to 100, rather than just have a "behavior" property set to "walk left".

**Comment by GoranM** [comment]
Raf's code doesn't merge properties.

I don't know if he would be interested in adding that support, but I guess you can assign this to him for now, and see what he says.

**Comment by rafcolson** [comment]
I will look into it today.

**Comment by rafcolson** [comment]
@SolarLune
This was something I overlooked totally. Right now properties are replaced completely, and that's not how it should be. See [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L311).

To merge both JsonValues I think I have to convert to HashMaps, or could there be another way doing this with JsonValues? I suggest to change GameObject.props to an HashMap instead then.

**Comment by GoranM** [comment]
> I have to remember not to put references in the commit description until it is complete. It seems, that every time I change something to it, it will reference the issue also.

It's good to have a record of changes; shows how the solution evolved.

Don't remove the reference, just take the time to ensure that the commit is ready before you push to your github branch; GitHub only knows about the commits that you actually push.

**Comment by rafcolson** [comment]
>Don't remove the reference, just take the time to ensure that the commit is ready before you push to your github branch; GitHub only knows about the commits that you actually push.

You're right. I shouldn't push every time I make a change.

**Comment by GoranM** [comment]
It's up to the person who opened the bug (@SolarLune in this case) to confirm that it's resolved, and to ultimately close.

**Comment by rafcolson** [comment]
Oh, I'm sorry.

**Comment by SolarLune** [comment]
In my quick tests, it would appear that everything works as it should - object properties can be retrieved, and group instance properties of the same name overwrite the "original" object properties.

Thanks, @rafcolson. Issue's closed.
