### ISSUE TITLE
SpriteAnim.uvScale() not working correctly

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#1002]
Hello. 

It seems that SpriteAnim.uvScale() isn't working correctly - I believe the bug must have been introduced in the PR for #995. It seems like you can set the UV scale once to something other than 1, but after that, a positive value (like 1) reverses the UV scale each time the function is called...? This is incorrect behavior - the function should be consistent and set the UV scale each time it's called, of course. 

Here's a blend that illustrates the issue more effectively. Each time you press the left or right arrow key, it should flip the sprite if the key hadn't been pressed before. Now, though, after pressing left, it no longer works, and pressing right always flips the sprite..

https://www.dropbox.com/s/wvztgxk2gi443xn/SpriteAnimTest.blend?dl=0

**Comment by rafcolson** [comment]
PR submitted. I'm sorry for the trouble.

**Comment by SolarLune** [comment]
Nah, no problem.

**Comment by SolarLune** [comment]
Yo, that PR was merged, so I'll close this now. Thanks!
