### ISSUE TITLE
Suggestion: GameObject.updateBody(boolean reAddToWorld)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1007]
Replacing meshes, as well as transforming meshes cause some inconsistent behavior with `TRIANGLE_MESH` shaped objects. It seems that geometries are not properly recognized after such alterations. Removing and re-adding the body to the world solves it. (Activating or even force activating the body of touching objects won't help. My suspicion is that it is necessary to [recreate the proxy](https://github.com/bubblecloud/jbullet/blob/master/src/main/java/com/bulletphysics/collision/dispatch/CollisionWorld.java#L120-L127), although I'm not sure).

This `Sacky.java` will illustrate the issue:
```java
package yourPackage;

import javax.vecmath.*;

import com.nilunder.bdx.*;
import com.nilunder.bdx.gl.Mesh;
import com.nilunder.bdx.utils.JoinData;

public class Sacky extends GameObject{
	
	public void init(){
		scene.meshes.get("Platform").autoDispose = false;
	}
	
	private void updateWorld(GameObject g){
		scene.world.removeRigidBody(g.body);
		scene.world.addRigidBody(g.body);
	}
	
	private void platformMeshEditTransform(){
		GameObject platform = scene.objects.get("Platform");
		Matrix4f t = Matrix4f.identity();
		t.position(new Vector3f(-5, 0, 0));
		platform.mesh().transform(t);
		platform.updateBody();
	}
	
	private void platformMeshEditGeometry(){
		GameObject platform = scene.objects.get("Platform");
		Mesh m = scene.meshes.get("Platform");
		JoinData joinData = new JoinData();
		Matrix4f t = Matrix4f.identity();
		t.position(new Vector3f(-5, 0, 0));
		joinData.add(m, t);
		Matrix4f t2 = Matrix4f.identity();
		t2.position(new Vector3f(5, 0, 0));
		joinData.add(m, t2);
		platform.mesh(new Mesh(joinData, scene, "JoinedMesh"));
		platform.updateBody();
		//updateWorld(platform);
	}
	
	public void main(){
		if (Bdx.keyboard.keyHit("space")){
			//platformMeshEditTransform();
			platformMeshEditGeometry();
			activate();
		}
	}
	
}
```
Do note that Sacky will fall down as expected when calling `platformMeshEditTransform()` but this will not be true in all cases. For example, if the platform would have a gap or hole in it.

Also note that Sacky will fall down if only one transformed mesh is added to the joined mesh.

But if not, `updateWorld(platform)` has to be called in order for Sacky to fall down.

So my suggestion would be to either remove and re-add the body to the world when calling `GameObject.updateBody()` or, to have a method to do this separately: `Scene.updateWorld(GameObject g)`. Maybe the latter would be safest, as the former might affect some existing projects, performance-wise.

So what do you guys think?

**Comment by GoranM** [comment]
I don't think "updateWorld" makes sense in this context. I generally don't think we need an additional function, but if we did, "reAddBody", or something like that, would be more descriptive.

Anyway, if updateBody needs to re-add the body in order to properly reflect data changes, than that's something to consider. I don't think it would affect existing projects, in terms of performance, assuming that you would only re-add in the specific cases you outlined, where that would actually be necessary.

**Comment by rafcolson** [comment]
In my tests, it seems to be affecting performance considerably, especially on low-end devices (I'm testing with Samsung J5 smart phone).

>assuming that you would only re-add in the specific cases you outlined, where that would actually be necessary

I take it that you meant: "assuming that you would only _be updating the body_ in that specific case". Well, that's not the case. Calling `updateBody()` would be necessary to determine if the `GameObject` should be rendered, through `insideFrustum()`. Unless the latter is done without using the body (which I think should be possible, if `origin` and `dimensionsNoScale` are properly updated).

So how about adding an argument: `GameObject.updateBody(boolean reAddToWorld)`, making it optional?

**Comment by GoranM** [comment]
> So how about adding an argument: GameObject.updateBody(boolean reAddToWorld), making it optional?

That's fine.

**Comment by rafcolson** [comment]
This was merged. Thanks.
