### ISSUE TITLE
SpriteAnim doesn't work correctly for added objects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#101]
Yo, so I'm seeing the BDX equivalent of the "shared mesh = shared animations" conundrum that one could see in using sprites in the BGE. Basically, added objects share meshes, and so share UV / animation changes. This could be solved under the BGE by either making a unique version of the mesh using LibNew(), or replacing the mesh itself using replaceMesh() to display the animation.

This should be able to be worked around in BDX by adding a "makeUnique()" function or something to the GameObject (or, better yet, a Mesh class that represents the game object's model) to allow sprite objects that share meshes to be unique. This way, you'd be able to have objects that you want to share animations (torches, water) as well as those that you don't (enemies, weapons, etc). 

But yeah, it's kinda difficult to make a game of any magnitude without having unique sprites, so a proposed solution would be appreciated.

**Comment by GoranM** [comment]
We could write code in the SpriteAnim constructor, to make a copy of the Model referenced by the current modelInstance, and then generate (and use) a new modelInstance from that new Model copy.

I don't think there's a built-in way to just "copy" the Model; we'll have to re-create it ourselves.

I'll look into it.

**Comment by rafcolson** [comment]
I think it would be more practical to manually generate a new modelInstance, because there might be cases where instances both need unique animations and mesh deformations.

**Comment by GoranM** [comment]
> there might be cases where instances both need unique animations and mesh deformations

If/when mesh deformation is supported, that's something we can talk about, but for now, it makes sense to solve the problem at hand, and not assume too much about what we "might" need.

**Comment by SolarLune** [comment]
I can tell you from experience that I've used both shared and unique meshes, and most likely will continue to do so in the future. Making an option to manually make the model unique over forcing that into SpriteAnim is most likely the best choice. 

If you're concerned about usability, you could put the unique() function somewhere, like in the GameObject class, and then have the SpriteAnim component call unique() on the provided sprite object by default, with an optional argument in the constructor to disable this. That way, people who don't know about it won't have to worry about it, and people who do can control it.

**Comment by GoranM** [comment]
Ok, that should do it.

**Comment by SolarLune** [comment]
Thanks a lot, this is good. The only thing is that SpriteAnim calls useUniqueMesh() by default, which isn't always desired (for example, if you have a single animation that "runs" throughout multiple objects, like background sprites or water running). It'd be nice if this depended on an argument (which could be hidden by default), or if it just didn't call it and it'd be up to the user to make the mesh unique.

**Comment by GoranM** [comment]
> if you have a single animation that "runs" throughout multiple objects, like background sprites or water running

If all those objects ran the same animation, at the same time, wouldn't the result be the same, even if they used unique meshes?

**Comment by SolarLune** [comment]
If they share meshes, then they don't all have to animate their sprite. Just one object has to animate its sprite, and the changed mesh is propagated to the others as well. That's why it's useful for objects that are animated but that don't need to have individual animations (like water currents) .

**Comment by GoranM** [comment]
> It's an optimization

I'm not sure if it would be all that relevant for small-to-medium size independent games (which is what I would like to target with BDX); I don't want our design decisions to be driven by performance concerns, until we actually have demonstrable performance problems.

Anyway:

The SpriteAnim constructor now supports an additional boolean argument (uniqueMesh), which can be set to false if necessary.

**Comment by SolarLune** [comment]
Thanks.

And yeah, I understand, but I'm pretty sure that it would be a nice thing to have nonetheless. This includes games with a lot of animation; not just "large" ones. A small game can be resource intensive and demanding on CPU as well. 

Anyway, issue closed.
