### ISSUE TITLE
Suggestion: Bdx.end() -> System.exit(0) on Android

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1014]
It seems that this would be an issue in some cases because after calling `Bdx.end()` the android application will still be running, but will be missing some of its resources, such as the `Bdx.display.clearColor` (or Blender's _Horizon Color_).

I'm not sure about the solution. Following the [Libgdx And Android Application Lifecycle](http://bitiotic.com/blog/2013/05/23/libgdx-and-android-application-lifecycle/) it seems to be required to call `BdxApp.pause()` before calling `BdxApp.dispose()`. But I couldn't find where either of those functions are called in BDX. Wouldn't `AndroidLauncher.java` have to be calling `BdxApp.dispose()` at some point?

Edit:

It seems that after calling `System.exit(0)` the android application will still be running, but will NOT be missing some of its resources. So this would be a better alternative for now.

A test shows that on Desktop `BdxApp.dispose()` is definitely being called after `Bdx.end()`, respectively `Gdx.app.exit()`. But after `System.exit(0)` it will not, as expected.

On Android `System.exit(0)` will definitely clear all memory.

```java
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Application.ApplicationType;

import com.nilunder.bdx.Bdx;

...

	if (Gdx.app.getType().equals(ApplicationType.Android)){
		System.exit(0);
	}else{
		Bdx.end();
	}

...
```

**Comment by GoranM** [comment]
I was under the impression that `Gdx.app.exit()` calls `System.exit` at some point, as part of the termination sequence.

**Comment by rafcolson** [comment]
It probably does, but the issue here is that the android application will still show up as "paused" after calling `Bdx.end()`. And when resuming the app some resources are gone. If the background color was white, now it will be black, for example.

But I guess I should check first if `BdxApp.dispose()` is called on Android as it is on Desktop...

**Comment by rafcolson** [comment]
I'm changing this to a suggestion. `System.exit(0)` doesn't really break the game on android, so I'd like to add this check to `Bdx.end()`:
```java
	if (Gdx.app.getType().equals(ApplicationType.Android))
		System.exit(0);
```

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR merged. Thank you.
