### ISSUE TITLE
API: Warning not to scale with CYLINDER, CAPSULE and CONE

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1017]
When scaling objects with bounds of type `CYLINDER`, `CAPSULE` and `CONE`, the bounds will not be updated. No problems with `BOX` and `SPHERE`. Unfortunately I didn't find a solution to fix this issue so I think we should document that objects with bounds of these three types should not be scaled.

In this [Debug](https://www.dropbox.com/sh/2hi7uswegitciis/AADNCEl_HegGIL6cmeScaTEJa?dl=0) folder you'll find _debug_aabb.blend_ , which can be used to test this issue. Just activate the lines where the cubes are scaled. Click with the mouse on screen to walk through the tests.

**Comment by GoranM** [comment]
Well, whether or not they should be scaled is for the developer to decide. We should simply document that scaling objects with those bounds will not scale their physics body.

**Comment by rafcolson** [comment]
Yes, that's better. Thanks.

**Comment by rafcolson** [comment]
[API](https://github.com/GoranM/bdx/wiki/General-Overview/_edit#bounds-types) updated.
