### ISSUE TITLE
Suggestion: rename currBodyType and currBoundsType

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1018]
Initially I had chosen these descriptions for an arbitrary reason: `bodyType` and `boundsType` less confusing. This should have no impact on projects as those field are not exposed.

**Comment by SolarLune** [comment]
OK.

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thank you both.
