### ISSUE TITLE
Suggestion: Refine InputMaps Gamepad descriptor search

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1019]
Currently, if a [descriptor](https://github.com/GoranM/bdx/wiki/API-InputMaps#customDescriptorsHDU) contains the character `"g"` it will be detected as `Gamepad`, which is not so convenient. I'd like to refine the search to `{"g", "g0", "g1", "g2", "g3", "g4", "g5", "g6", "g7", "g8", "g9"}`.

**Comment by GoranM** [comment]
...?

The "g" is supposed to specify the gamepad device.

Please provide a use-case that clearly illustrates the problem at hand.

**Comment by rafcolson** [comment]
>Please provide a use-case that clearly illustrates the problem at hand.

Of course. If I'm adding `"vgp"` or `"virtual_gamepad"` or some description containing a `"g"` to [customDescriptorsHDU](https://github.com/GoranM/bdx/wiki/API-InputMaps#customDescriptorsHDU), [InputMaps](https://github.com/GoranM/bdx/wiki/API-InputMaps) will not detect the descriptor properly, because it will specify it as a gamepad device.

>The "g" is supposed to specify the gamepad device.

Everything will stay the same, each item in `["g", "g0", "g1", ...]` will still specify a gamepad device.

**Comment by GoranM** [comment]
Oh, I see.

Ok.

**Comment by rafcolson** [comment]
PR merged. Thanks!

**Comment by SolarLune** [comment]
Hey, "g:left" no longer identifies an input as "left" on the gamepad - you have to specify a number, which is incorrect.

**Comment by rafcolson** [comment]
Ok. I see.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by Gerkinfeltser** [comment]
Hello! I attempted to use your patched bdx build @rafcolson & I'm still having issue (though I could be confused as to what is going on or proper usage of imaps). This also happens with the latest offical release of BDX as well.

`Bdx.imaps.put("jump", "g:ls-right");` results in the following error and the game ending as soon as it starts in-spite of the "BUILD SUCCESSFUL".:
```
Controllers: added manager for application, 1 managers active
Exception in thread "LWJGL Application" java.lang.RuntimeException: Invalid descriptor "g:ls-right".
        at com.nilunder.bdx.inputs.InputMaps$Input.<init>(InputMaps.java:132)
        at com.nilunder.bdx.inputs.InputMaps.put(InputMaps.java:283)
        at net.treefish.bdxsandbox.Sacky.init(Sacky.java:8)
        at com.nilunder.bdx.Scene.initGameObject(Scene.java:590)
        at com.nilunder.bdx.Scene.init(Scene.java:408)
        at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:126)
        at net.treefish.bdxsandbox.BdxApp.create(BdxApp.java:22)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

BUILD SUCCESSFUL
```
The following runs without issue though:
`Bdx.imaps.put("jump", "g0:ls-right");`

**Comment by rafcolson** [comment]
Okay. So [this folder](https://www.dropbox.com/sh/xfuaiguy97p7msq/AACF8uxPnOGGFhIt6p5L5Rkua?dl=0) contains the most recent build. I think the build you were referring to is the one before version 2.8 had been drafted. It was outdated so I removed it. But this one has the patch for the gamepad. I'll keep this folder updated for future issues.

I'm sorry for causing any delay in your development process. I made a mistake with the last commit. Sorry, guys.

**Comment by Gerkinfeltser** [comment]
That seems to has done the trick @rafcolson! Thanks! I should mention though, it appears I didn't update/create a new project to try your previous build so it could have been that. :( If anything, I know it works for me as intended now though so thank either way! 😀

**Comment by rafcolson** [comment]
PR merged. Thanks!
