### ISSUE TITLE
Incorrect children end()ing.

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#102]
Hey, there. Basically, there was an error dealing with looping through children and end() not working correctly as the children list would be changed when children were de-parented after being removed from the scene. Adding a PR to address this.

**Comment by GoranM** [comment]
It would probably be a good idea to provide the actual error.

I assume it was a ConcurrentModificationException, but I shouldn't have to assume in a bug report.

**Comment by SolarLune** [comment]
I didn't particularly feel the need to provide a lot of information given that I noticed the bug and provided a patch for it immediately.

In any case, that was the error, if I recall correctly. I'll keep it in mind in the future.

**Comment by SolarLune** [comment]
Merged. Thanks, Goran.
