### ISSUE TITLE
Question: multiple blend files in the Wiki?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1022]
I didn't find any information in the Wiki on using multiple blend files and using the *Post-Export-Program* field. But maybe it is there somewhere. I probably should be asking @SolarLune as he added that part of the code. Thanks.

**Comment by SolarLune** [comment]
Hey, there. 

Sorry for the late response - you can use multiple blend files by ticking "Multi-blend Export". Note that this will save the blend file for you when exporting from multiple blend files, so be aware beforehand. It probably would be a good idea for you to have differential exporting enabled, as well. The wiki talks a bit more about it in the Workflow section [here](https://github.com/GoranM/bdx/wiki/General-Overview#workflow).

**Comment by rafcolson** [comment]
Oh, I see. I totally missed that. Thanks.
