### ISSUE TITLE
Suggestion: GameObject.groups & Scene.groups() & Scene.group(String groupName)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1023]
For my project I'd like to utilize Blender's Object groups. BDX should not have to maintain anything with methods in `Scene` to collect group objects.
```java
GameObject.groups - ArrayList<String>
Scene.group(String groupName) - ArrayListGameObject
Scene.groups() - HashMap<String, ArrayListGameObject>
```
Ideas?

Edit: Happy Newyear
Edit: Added Scene.groups()

**Comment by GoranM** [comment]
Ok.

---

Happy new year :tada:

**Comment by rafcolson** [comment]
Thanks 🍦 
PR submitted.

**Comment by rafcolson** [comment]
Merged. Thanks.
