### ISSUE TITLE
Bug: GameObject.bodyType(bt) crashes BDX with touching STATIC TRIANGLE_MESH objects

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#1034]
May be related to [#60](https://github.com/GoranM/bdx/issues/60#issuecomment-72342234), that's to say if that crash isn't limited to ending STATIC ghost objects.

In my case the solution was to re-add the body to the world.
```java
...
g.bodyType(GameObject.BodyType.STATIC);
...
g.scene.world.removeRigidBody(g.body);
g.scene.world.addRigidBody(g.body);
```
It is a well-known Bullet (C++) limitation/restriction of usage, to be obligated to re-add the body when replacing the collision shape of the body, or so it seems. See [Jbullet: NPE when removing body with TRIANGLE_MESH shape](https://pybullet.org/Bullet/phpBB3/viewtopic.php?f=9&t=10628).

And so, in some (not all) circumstances, especially with touching STATIC TRIANGLE_MESH objects, issues occur during simulation (with ghost), or with removing objects, and in this case, when changing the body type.

This may also be related to the inconsistent detection behavior, described in #1007, because the solution there also was to re-add the body.

I'm not sure how to proceed from here. We might consider to:
- either re-add all kinematic bodies always
- or only re-add if TRIANGLE_MESH
- or to add a method `GameObject.reAddToWorld()` with a special note for it's use cases in the wiki, [here](https://github.com/GoranM/bdx/wiki/General-Overview#collision-detection) I suppose.

Thoughts?

**Comment by GoranM** [comment]
I don't really know.

I mean, the whole jbullet port is kind of weird to begin with, so it's hard to say if the cause is actually in bullet, or in the jbullet port.

It would help to really narrow the issue down to a very specific case, so that we can say for sure when and how it happens.

**Comment by rafcolson** [comment]
Ok. I'm on it.

**Comment by rafcolson** [comment]
I've done [a collision test with all body and bounds types](https://www.dropbox.com/s/dbifjfaa82ak7tz/debug_collision.blend?dl=0). But I can't reproduce this issue. Closing for now until I can.
