### ISSUE TITLE
bdx/blender - sacky doesnt jump 

### ISSUE THREAD

**Issue by breakdancin** [GoranM/bdx#1036]
hi im new to bdx. i usually use the 2.78 blender. and ive read that earlier versions work better for bdx. but im now on 2.73 and 2.73a and i am having the same issue. the sacky character never jumps. i press p in 3d view. i hit export and run bdx. nothing. i have gradle already. i kept relocating the outputs to sdks and such. stomped. cant get past the very first thing here.

**Comment by breakdancin** [comment]
nevermind got it! didnt have ant lol

**Comment by SolarLune** [comment]
Where did you read that earlier versions worked better for BDX?

Also, you don't need ant to use BDX, you just need it to build BDX if you were editing the source.
