### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by breakdancin** [GoranM/bdx#1038]
hey im in the middle of makin a game with you guy's bdx/blender engine. i checked out the tutorials the video ones and written ones from youtube and github. what im doin in particular , you guys dont have a video tutorial for..  and that is for the setup of virtual android controller for 3d mario64 type style games. maybe the side scroller, but im trying to pull off the mario64 style.

and i was not only gonna have it for android but also have it multiplayer online

wonderin if you guys can make a video tutorial for those?

i see plenty of help from unity but i wouldnt be able to use unity.

**Comment by breakdancin** [comment]
oh sorry. everytime i write these i dont know how to close them. i figured out another way getting my problem solved. and alright rafcolson. ill hit you up on reddit in the future.

**Comment by rafcolson** [comment]
Not a problem at all. You can close this issue by clicking the "Close issue" button at the bottom of an issue, next to the "Comment" button. Good luck!
