### ISSUE TITLE
cant play 3D animation 

### ISSUE THREAD

**Issue by exaxeeae** [GoranM/bdx#1042]
can you share any example about plying 3d animation seams the code didn't work for me

**Comment by rafcolson** [comment]
Are we talking about the [components](https://github.com/GoranM/bdx/wiki/API#comnilunderbdxcomponents) or what do you refer to as "3d animation"? A code example?

**Comment by exaxeeae** [comment]
excuse my english , i did some movement as simple animation in the blender file , 
 meshAnim = new MeshAnim(this);
        meshAnim.add("Action" , new String[]{"PlayerMT"} , 12 , true);
        components.add(meshAnim);
i call it in init with meshAnim.play("Action")
nothing happen , i didt with libgdx whay and its the same result , i couldn't find any example for it , can you please share example ?

**Comment by rafcolson** [comment]
No problem @exaxeeae 

Is the component is on the actual object you want to animate?

```java
package com.raco.test;

import com.nilunder.bdx.GameObject;
import com.nilunder.bdx.components.MeshAnim;

public class Sacky extends GameObject{
	
	public void init(){
		MeshAnim ma = new MeshAnim(children.get(0));
		ma.add("Flipper" , new String[]{"Platform", "G_Sacky"} , 12 , true);
		components.add(ma);
		ma.play("Flipper");
	}
	
}
```
This should work with the default Sacky scene.

PS: when writing your comment you can start your code with **```java**

and end with **```**

**Comment by exaxeeae** [comment]
thx for your respond , i will test it , i hope u make some tutorials in you tube that s will be perfect

**Comment by rafcolson** [comment]
In the future, for questions about **how** to use the engine, go to the [Community/Support](https://github.com/GoranM/bdx/wiki) section at https://www.reddit.com/r/bdx/.

This repository's Issues section is intended for development (bug reports, suggestions for the engine and such).

**Comment by rafcolson** [comment]
This can be closed I guess.
