### ISSUE TITLE
Cannot Find Symbol (GameObject Array)

### ISSUE THREAD

**Issue by stamoksa** [GoranM/bdx#1044]
Hello,
When i try to make Arraylist of GameObject to make loop of it to clone an object  Like eg. (Obj1,Obj2,Obj3)
I want clone them to Obj0 in series it gives me this error "Cannot Find Symbol" I've tried different codes as : 
 ```java

      public class MainObject extends GameObject(){
         public void main(){
             ArrayList<GameObject>Objects = new ArrayList<GameObject>();
		Objects.add(Obj1);
		Objects.add(Obj2);
		for(int x=0; x<=1; x++){
			GameObject Objects.get(x) = scene.add("MainObject"); 
		}
}
}
```
or 
```Java
public class MainObject extends GameObject(){
         public void main(){
             GameObject Objects[] = {Obj1,Obj2,Obj3};
		for(int x=0; x<=4; x++){
			GameObject Objects[x] = scene.add("MainObject"); 
		}
}
}
```
If the problem is not clear due to my english or insufficient information please tell me
Thanks.

**Comment by rafcolson** [comment]
@stamoksa 
Could you please repeat your question in the community/support section at https://www.reddit.com/r/bdx/ ?

This Issues section is merely for bug reports and other engine related issues.

**Comment by stamoksa** [comment]
Ok thanks will communicate with you there.
