### ISSUE TITLE
Splash screen android

### ISSUE THREAD

**Issue by mintarasss** [GoranM/bdx#1047]
Hi,

Is there a way to add Splash screen in android with bdx lib?

**Comment by rafcolson** [comment]
No. To incorporate a system with a splash screen you can use an overlay scene.

**Comment by mintarasss** [comment]
but if all scenes took long time to load. or scene loads async?

**Comment by rafcolson** [comment]
You can start the game with the splash screen and then add the scene with your game stage beneath the splash screen scene. You can channel the loading progress to the splash screen scene if you want to visualize this with a loading bar.

It might be better to continue thus topic on Reddit as it has nothing to do with bdx development.

Hope this helps.
