### ISSUE TITLE
3D Animation in BDX

### ISSUE THREAD

**Issue by doppelgangerdev** [GoranM/bdx#1049]
Hi! I know this belongs more in the bdx subreddit but I have not gotten an answer on there or on blender stack exchange and my game has been in development hell for nearly a month. There are no tutorials on 3D animation in BDX. There is API for MeshAnim and tutorials for SpritAnim but that's it. 

I can make animations in blender using keyframes and curve paths but there are no tutorials online on how to export these if they're even exportable to bdx (Not talking about fbx exporting and importing in bullet 3D in LibGDX). There's a button on one of the panels that says record animation but it only appears on static bodies and clicking it appears to do nothing. The only bdx tutorials I could find feature sprite animation but not mesh animation (can find API for) nor loc/rot/scale animation (can't find API for but apparently it does exist). I don't want to switch engine entirely or move back to libgdx because bdx is so much easier in every other way but I've made no progress on this game in a week. Video of my "animations": https://www.youtube.com/watch?v=WXtFb46 ... e=youtu.be

**Comment by SolarLune** [comment]
Sorry to tell you this, but there is no 3D keyframe animation built-in to BDX; development ended before it got to implementing it. 

If you need 3D animation and don't want to switch back to LibGDX, it was possible, as I recall, to load and animate meshes using normal LibGDX methods. It's a cludge, but it works.

**Comment by doppelgangerdev** [comment]
Oh 

> Sorry to tell you this, but there is no 3D keyframe animation built-in to BDX; development ended before it was implemented.
> 
> If you need 3D animation and don't want to switch back to LibGDX, it was possible, as I recall, to load and animate meshes using normal LibGDX methods. It's a cludge, but it works.

Oh god I was hoping that wasn't the only way, I had so many issues getting that working before I found out about BDX. Oh well. Thank you for the reply!

**Comment by SolarLune** [comment]
No problem, and sorry about that! Hope everything works out for you with your project.
