### ISSUE TITLE
Random.direction not normalized?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#105]
Hey, there. It seems like Random.direction() isn't normalized; shouldn't it be?

**Comment by GoranM** [comment]
I didn't feel it was necessary.

As far as I know, "direction" is not a concept that implies a specific magnitude. Also, one would typically want to set the length to something specific anyway, so normalizing it before-hand seemed like just wasting cycles.

**Comment by SolarLune** [comment]
It seems like a direction would indeed imply a specific magnitude of 1 no matter what direction gets generated. If it's not normalized, then the length can vary widely, which contradicts the idea of generating a direction, since there's more data that varies - it's a random Vector, not a random direction (carried by a Vector). 

In addition, this opens up a position for bugs for users if they use the function expecting a vector of length 1 and then try using scale or mul instead of setting the length directly.

If you want both for efficiency, then this could be renamed to random.Vector, and random.Direction could return a normalized random.Vector.

**Comment by rafcolson** [comment]
I would agree. However, I would just keep it at renaming to random.vector. And just add a method to Vector3f to normalize. So you could write: ```Vector3f v = random.vector().normalized()```

**Comment by GoranM** [comment]
> If it's not normalized, then the length can vary widely, which contradicts the idea of generating a direction

I don't see how that would contradict the "idea of generating a direction": Vector(1, 1, 1) represents the same direction as Vector(99, 99, 99) - Direction is about where the arrow is pointing, not its length.

In any case: I don't mind much one way or another, so if you want Random.direction() to return a normalized vector, feel free to make that PR.

**Comment by SolarLune** [comment]
It contradicts the idea because it's not generating a vector with random direction, it's generating a random vector. The difference is that you don't know what length the function will generate before-hand.

@rafcolson - There's already a normalized() function in Vector3f's. What do you think about having it return a normalized vector? Alternatively, @GoranM, what about renaming it random.Vector?

**Comment by rafcolson** [comment]
@SolarLune Calling ```Random.vector()``` should return a random vector, not a random normalized vector, in my opinion. Having a method ```Random.vectorNormalized()``` seems a bit redundant if you could just call ```Random.vector().normalized()```.

**Comment by GoranM** [comment]
> It contradicts the idea because it's not generating a vector with random direction, it's generating a random vector.

A random vector is in fact a vector with random direction.

I agree that people would probably expect it to be of unit length (for historical reasons), and for that reason I'm fine with changing Random.direction to return that, but I wouldn't agree that Vector(1, 1, 1) and Vector(1, 1, 1).normalized() don't represent the same direction - It's the same direction.

> what about renaming it random.Vector?

Random is a static class in the utils package (java doesn't have a module system, so classes are typically used to make something similar - when appropriate). In Java, it's convention for class names to start with a capital letter, so I'm not sure if it would be wise to go against that.

If we were to do that, then, to keep it consistent, we would also have to rename Bdx to bdx ... I don't know - I think Random.direction is fine.

**Comment by rafcolson** [comment]
I would prefer ```Random.vector```, because it wouldn't be so confusing when getting random "positions", or "scales" for that matter.

I'm not so comfortable with for example: ```g.position(Random.orientation())```

**Comment by SolarLune** [comment]
> A random vector is in fact a vector with random direction.

And length.

> I wouldn't agree that Vector(1, 1, 1) and Vector(1, 1, 1).normalized() don't represent the same direction - It's the same direction.

I never said they weren't.

> In Java, it's convention for class names to start with a capital letter, so I'm not sure if it would be wise to go against that.

I meant renaming it from "Direction" to "Vector". Of course we wouldn't change the package name.

I think I'm going to normalize the vector returned by this and name it "vector()" instead of "direction()".

**Comment by GoranM** [comment]
> I never said they weren't.

I think that your emphasis on a specific length, as a defining component of direction, would imply that.

If I misunderstood your argument, please elaborate.

> I meant renaming it from "Direction" to "Vector". Of course we wouldn't change the package name.
>
> I think I'm going to normalize the vector returned by this and name it "vector()" instead of "direction()".

You mean rename Random.direction to Random.vector, and then create a new Random.direction that returns normalized?

If so, I think that would be fine.

**Comment by SolarLune** [comment]
> I think that your emphasis on a specific length, as a defining component of direction, would imply that.

Well, no, a direction doesn't have a length, but random.direction() doesn't just return a random direction, y'know? People won't use Vectors just for their "direction", but rather as the basis for directional movement altogether. For example, `float moveVec = random.Direction().mul(moveSpd)`. That is screwed up if the returned vector is of indeterminate length.

In any case, I suppose it's alright; it seems like with a second added function that basically does the same thing (return a normalized random vector) this is becoming a bit of additional cruft that doesn't need to be added to the code-base. Just having an API doc mentioning that the returned vector isn't normalized is enough for now.

**Comment by GoranM** [comment]
> a direction doesn't have a length

Exactly.

> it seems like with a second added function that basically does the same thing

I don't follow.

Look at your changes [here](https://github.com/SolarLune/bdx/commit/c6ff9e18c31b3f45f1be23c4f68d52e62afc75b0): I think they're fine.

Just make a PR, and I'll merge it.

**Comment by SolarLune** [comment]
Done, and changed name as to @rafcolson 's request.

**Comment by SolarLune** [comment]
Merged. Thanks for your help and input.
