### ISSUE TITLE
setVisible function?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#106]
Hey, there. I think a recursive setVisible function would be useful. Currently, you have to loop through the children of whatever parent object to set their visible field.

**Comment by GoranM** [comment]
It would probably be best to follow the existing convention demonstrated by GameObject.end, and GameObject.endNoChildren.

So, `visible(boolean visible)` and `visibleNoChildren(boolean visible)` would seem like the right way to go.

**Comment by SolarLune** [comment]
visibleNoChildren is the same as setting the visible property directly, but that's fine.

PR submitted.

**Comment by GoranM** [comment]
I assumed that you would make `visible` private, and have a `boolean visible()` getter.

**Comment by SolarLune** [comment]
@GoranM - Fixed.

**Comment by SolarLune** [comment]
Merged, so I'm gonna close this. Thanks!
