### ISSUE TITLE
Override GameObject.toString()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#115]
Hey there. 

When you print out information about a collection of game objects (like the children list for GameObject), the console won't print out particularly useful information, but rather just a list of objects whose base class is "GameObject". 

It might be nice to override the GameObject's toString() function to print out its object name and hashstring (or even game object ID, if you wanted to create that field that increments with every added game boject and put that in there), rather than class name and hashstring to help you understand what objects are contained in what collections.

**Comment by GoranM** [comment]
Instead of:

```
com.nilunder.bdx.GameObject@ffacb2
```

Something like:

```
Name<GameObject>@ffacb2
```

Would probably be better.

**Comment by SolarLune** [comment]
Done; PR submitted.

**Comment by SolarLune** [comment]
New PR submitted (rebasing didn't appear to solve the issue).

**Comment by SolarLune** [comment]
PR's been merged. Thanks!
