### ISSUE TITLE
ghost toggle

### ISSUE THREAD

**Issue by Nona2** [GoranM/bdx#118]
In blender the only way i know how to toggle ghost is to parent it to a dumby object in the scene and set it to ghost.  Then to un ghost it i just unparent it.  Any chance of the ghosting being added to parent function or even better a toggling ghost function?

also if you are aware of a better way to toggle ghost in BGE that could be helpful too

**Comment by rafcolson** [comment]
It's something on my most wanted list too. I think I can do it, so I'll give it a try.

@GoranM & @SolarLune : please say if I should stop assigning myself. I realize that I'm not that experienced and I don't like it when I'm slowing everything down.

**Comment by SolarLune** [comment]
@rafcolson Psh, nah, man. You're doing great, and your solutions are solid. You're not slowing anything down.

**Comment by GoranM** [comment]
You can't really slow anything down. I mean, if we know you're working in a particular area of the code base, we might keep that in mind, and try to stay out of your way (to help you avoid merge conflicts), but there's nothing about your work that could fundamentally prevent anyone from doing their work.

Worst case scenario: It takes you a bit more time, and you'll have to resolve some conflicts before your work can be merged.

In either case, you shouldn't rush: Quality > speed.

**Comment by rafcolson** [comment]
I have a couple of suggestions with this. I would like to shorten the code to get ```meshName``` a bit. No need for ```mesh``` in [Scene.java#L177](https://github.com/rafcolson/bdx/blob/ghost/src/com/nilunder/bdx/Scene.java#L177).

I also like to rename keys [```"body"```](https://github.com/rafcolson/bdx/blob/ghost/blender/bdx/exporter.py#L413) and  [```"bounds"```](https://github.com/rafcolson/bdx/blob/ghost/blender/bdx/exporter.py#L414) to [```"body_type"```] and [```"bounds_type"```].

**Comment by GoranM** [comment]
It all sounds good.

You can include those changes into the current PR for ghost, if you want. Or if you want to make a different PR with those commits, that would also be fine.

**Comment by SolarLune** [comment]
@Nona2 - A ghost() function was merged to allow you to toggle ghosting for objects; it should be what you need, and enable you to close this issue.

**Comment by Nona2** [comment]
thx guys
