### ISSUE TITLE
Need some help with storing variables

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#120]
Hi,

I've been searching for a way to store a value into a variable of GameObject, but nothing helps.

GameObject.java: ```public String bodyType;```
Scene.init(): ```g.bodyType = gobj.get("physics").get("body").asString();```

I'm always getting ```null```. I tried the same thing with storing ```g.ghost``` but this always returns ```false```.

I'm confused because when I look at Bullet.makeBody(), there seems to be no problem with getting:
```String body_type = gobj.get("physics").get("body").asString();```

Thanks for your help.

Edit: Even if I do: ```g.bodyType = "Hello World";``` it will return ```null```. It's so strange.

**Comment by SolarLune** [comment]
Hmm, I'm not sure where the issue's lying; it seems to work somewhat OK for me. Where are you putting 
`g.bodyType = gobj.get("physics").get("body").asString();`?

For me, it's in `Scene.init()`. The little test I'm running is `g.ghost = gobj.get("physics").getBoolean("ghost");`. G.ghost becomes true, but the ghost field is set to false anyway when I print it out from the GameObject.

**Comment by GoranM** [comment]
GameObjects in the scene are just clones of templates that are created in Scene.init. The implementation of that cloning process is defined in cloneNoChildren, which copies the value of relevant fields from template to new instance.

I assume that you only set the value of ghost for the template object (in Scene.init); you would also need to set it for each instance (in cloneNoChildren) to get the behavior you want.

**Comment by rafcolson** [comment]
Okay, thanks. That's helpful.
