### ISSUE TITLE
Get all scenes function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#121]
Hey, there. I think a convenience function to return a list of all scenes that exist (and so can be added) would be nice. Seems like it could either use Gdx.files.internal or OS-specific functions, maybe?

For some background on why I want this, I'm trying to implement a kind of "sanity check" to ensure I don't make a level that's not in my level list. (I have a list of levels to allow me to shuffle them around as I work on the game to ensure the pacing's OK, apart from Blender.)

**Comment by GoranM** [comment]
If you try to load a scene that doesn't exist, BDX will crash with an exception that references the file in question.

Doesn't that serve as a "sanity check"?

**Comment by SolarLune** [comment]
It does, but that's not what I was talking about. My apologies, as I explained myself incorrectly.

Basically, the function would be used to ensure that I didn't make a scene that I don't already have in my level path, not that my path uses a scene that I haven't made. The level scenes are "unlinked" from each other to allow myself to rearrange the path at will (to go from level 1 > 2 > 4 > 3 > 6 > 5, for example, without having to rename them all). I could use the function to see if there are levels that I made and haven't placed in the level path - that's the sanity check.

Of course, the function could also have other real-world applications in the future, like for modding potential.

**Comment by GoranM** [comment]
Ok.

> Seems like it could either use Gdx.files.internal or OS-specific functions, maybe?

Use Gdx.files.internal - OS-specific functions are ... well ... OS-specific; we want this to work cross-platform.

**Comment by SolarLune** [comment]
Sorry, I meant functions that would be found in a Java OS / System package (like the os module for Python), not OS-specific methods. I'll see if Gdx.files.internal can return a listing of files.

Where do you think the function should be located?

**Comment by GoranM** [comment]
I don't know if Java's built-in filesystem methods would export properly to HTML5 ... I'm not that sure about mobile, either. Gdx.files.internal is guaranteed to be there, and to work in all circumstances.

> Where do you think the function should be located?

Bdx.ArrayListScenes.available() could return an ArrayList<String> of available scenes.

**Comment by SolarLune** [comment]
Cool, it works. PR submitted.

**Comment by SolarLune** [comment]
PR merged. Thanks!
