### ISSUE TITLE
Optimize Scene.updateVisuals()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#127]
Currently modelInstances of objects with bodyType "STATIC" (and "SENSOR") and "NO_COLLISION" are updated on every frame, while these should be updated only when moving, rotating or scaling (transforming).

"NO_COLLISION" modelInstances also could be transformed directly instead of through the body, so they don't need a body.

**Comment by rafcolson** [comment]
Currently modelInstances of objects with bodyType "STATIC" and "NO_COLLISION" are updated on every frame, while this only should be updated when moving, rotating or scaling.

**Comment by Nona2** [comment]
when i make a hittable box that are seperate from the physics boxes of the character which physics type do u suggest i use

**Comment by rafcolson** [comment]
For hit boxes I suggest you use "SENSOR" or "STATIC" with ghost enabled.

**Comment by Nona2** [comment]
thats how i have been doing it in bge good to know no changes are needed

**Comment by rafcolson** [comment]
Yes, it's pretty much the same.

**Comment by SolarLune** [comment]
This sounds like a pretty good idea and optimization, especially considering how many static objects a game might have in a single scene.

**Comment by rafcolson** [comment]
I wouldn't be surprised that this causes the bottleneck with BDX on android.

It should be more helpful if we would be having a profiler. But to be honest, I don't have a clue of where to begin making it.

**Comment by GoranM** [comment]
You don't have to "make" a profiler.

There are already various profiling tools available for Java, and Java on Android. You can experiment with those, or you can time the functions yourself (#76).

In either case: You need reliable performance data to effectively direct any optimization efforts.

**Comment by rafcolson** [comment]
But I'm not sure how to measure those results.
Let's say I want to measure how much Scene.updateVisuals() takes in percentage, should I then do this?
```
int frameRate = 60;
float percentage = delta / (1000 / frameRate);
```

**Comment by GoranM** [comment]
The desired framerate is irrelevant; The measure of each function call should be relative to the total time it takes to produce a new frame (including logic, rendering - everything).

In BdxApp.java, the render method represents that overall code. So first, you would time that, to get `totalTime`, and then you would time the relevant function, so you can calculate the percentage:

```
toPercent = 100 / totalTime
percentage = toPercent * delta
```

**Comment by rafcolson** [comment]
Thanks, Goran, that's very helpful. I'm almost done with it.

**Comment by rafcolson** [comment]
>The desired framerate is irrelevant; The measure of each function call should be relative to the total time it takes to produce a new frame (including logic, rendering - everything).

But this doesn't actually say how much influence a piece of the code has on performance, does it? Shouldn't a profiler measure relative to capacity, or in other words: the maximum time all of the code can take without causing frame drops?

**Comment by GoranM** [comment]
I don't really understand what you mean:

It doesn't matter if the frame rate is 1 or 60 - how much influence a piece of code has on overall performance is measured by how much time it takes to execute that code, relative to how much time it takes to execute everything, all together.

**Comment by rafcolson** [comment]
I believe what you are saying. But then I wonder if the profiler of the BGE is doing that. If Logic increases, then Render, ... won't decrease, for example.

**Comment by GoranM** [comment]
I think the BGE profiler uses the same basic algorithm: frametime is totalTime, and each subsystem times its own delta, the percentage for which is calculated by the same method I outlined above.

> If Logic increases, then Render, ... won't decrease, for example.

That's because Render still takes the same amount of time, more or less, in that particular case; The percentages will change - how much depends on the increase relative to other subsystems, but they all have to add up to 100%, so as percentage increases for one, it drops for others.

**Comment by rafcolson** [comment]
Okay, I get it now. Thanks.

**Comment by rafcolson** [comment]
If my Profiler works correctly then it would seem that ```Scene.updateVisuals()``` doesn't to take so much time relative to the rest. I'm closing this.
