### ISSUE TITLE
Disable internal java file execution

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#131]
Hey, there. Basically, BDX has a nice base for modding potential as .bdx scenes are converted scenes from Blender. This is good, since it's easy to distribute new, custom content through this means; a user can package textures and (naturally, meshes) in there easily, and only needs the engine source to convert everything.

I was just thinking that a security issue could arise from this, though, since .blend files / .bdx files can also contain Java source files that can be run unbeknownst to the user. It might be nice to add an option to disable internal java source file execution. That way, if someone wants to run code, they either have to enable internal java source file execution in the source .blend file / .bdx file, or put the source files external to the scene / bdx file and load them in.

**Comment by GoranM** [comment]
Only .blend files can contain Java source that BDX could potentially use, and all that code is clearly visible in the internal text editor, so I don't see how it could run "unbeknownst to the user".

**Comment by SolarLune** [comment]
^ That's right, I was thinking .bdx files can contain java source files, but BDX saves the internal files out to the source folder on run, doesn't it. I suppose just warning users to check .blend file text resources to ensure they don't do anything unexpected is good enough. Issue closed.
