### ISSUE TITLE
scene.gravity

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#136]
It'd be nice to get and set the gravity of the scene through scene.gravity() functions.

**Comment by SolarLune** [comment]
@rafcolson I wonder, is it necessary to have an internal gravity private property? You could just set and get the gravity directly. Thanks for the addition, though!

**Comment by rafcolson** [comment]
Committed.

**Comment by rafcolson** [comment]
@SolarLune This probably can be closed since it was committed. Just reminding.

**Comment by SolarLune** [comment]
Ah, yes. Thanks.
