### ISSUE TITLE
Saving method?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#139]
Yo! So, saving data is an important part of game development, of course. And I'm not suggesting some sort of "automatic save" ability to save each element of each game object in the game, or anything like that; just a basic method to read and write game data.

It would seem that LibGDX preferences
https://github.com/libgdx/libgdx/wiki/Preferences
exist for saving data, and that doing so works cross-platform and even on browsers, which is nice. The only thing is the "only writes primitive data types" thing; that's a bit awkward to use. Would there be an ability to expand it to include other types as well?

It would seem that other people use other libraries and methods like Kryo, LibGDX's files package, and/or Json to handle saving; should it be a concern for BDX? Maybe it should just be left up to the developer to decide how to approach things?

What do you guys think?

**Comment by GoranM** [comment]
What users decide to save, and how, is up to them, and the specific requirements of their game.

Our responsibility should not extend beyond providing access to cross-platform storage, where one can simply store a json file. I don't know if libgdx provides something along those lines, but if we only have what "Preferences" provides, then we can write code that would "flatten" arbitrary json to fit there (I don't think it would be too difficult).

**Comment by rafcolson** [comment]
>What do you guys think?

I think something like a ```Bdx.write(String filepath, JsonValue data)``` method and  ```Bdx.read(String filepath)``` would be a nice.

Couldn't we just use ```java.io.*``` for this?

**Comment by SolarLune** [comment]
Hey, I'm looking into this now because my current project will require saving and loading of some description.

> Couldn't we just use java.io.* for this?

I think there are alternatives that LibGDX provides for saving, but the Wiki says that Preferences are the only way to save data from a browser, so that's our method forward, I guess. It seems like Preferences provide enough of an entry point to saving and loading where we might just write a function to return a LibGDX Preferences object? 

> I don't know if libgdx provides something along those lines, but if we only have what "Preferences" provides, then we can write code that would "flatten" arbitrary json to fit there (I don't think it would be too difficult).

I don't think we really need to do that, do we? I mean, if you have an object and can convert its relevant attributes (or the entire object) to JSON, then you can just write it and retrieve it as a string in the Preferences.

**Comment by GoranM** [comment]
> I don't think we really need to do that, do we? I mean, if you have an object and can convert its relevant attributes (or the entire object) to JSON, then you can just write it and retrieve it as a string in the Preferences.

Assuming there are no silly restrictions on string length, then yes, we can just write the json string.

> Actually, Vectors are pretty common and would be nice to have standard support for saving and loading, so maybe we could have our own Preferences-like class?

I don't think we need additional abstractions for this. I mean, as the developer, you need to decide what data you need/want to serialize, and then create a function that does that.

**Comment by SolarLune** [comment]
OK, so I guess we don't really need to add anything here; we can just point to LibGDX's preferences as the suggested method to save data. Fair enough! 

Closing this topic.
