### ISSUE TITLE
Text objects share meshes

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#140]
Hey, there. So, by default, text objects share meshes; if you add one in-game, for example, and edit it, any others you add will similarly be edited. I think they should by default get unique meshes, since you rarely (if ever) want one text object to mirror another.

**Comment by rafcolson** [comment]
Yes I think that would best.

**Comment by GoranM** [comment]
Yea, I think it should just be a matter of calling useUniqueMesh on new instances of Text.

**Comment by SolarLune** [comment]
OK, I'll assign this to myself, then.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by GoranM** [comment]
Please remember to close resolved issues.
