### ISSUE TITLE
scenes.set()?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#142]
Hey, there. So, a function to replace a scene with another one would be appreciated. It's kinda awkward doing this by hand, even for just a game with two or three scenes active at a time.

**Comment by GoranM** [comment]
Assuming that `set(int index, E element)` is implemented with calls to `remove(int index)` and `add(int index, E element)`, this might already work, without the need to additionally override set.

Did you try it?

**Comment by SolarLune** [comment]
The built-in set function doesn't use any add or remove calls. I haven't tried it yet; I assume that the scene needs to be cleaned up in some respect, or would the set() function still work fine?

**Comment by SolarLune** [comment]
Hey, thanks, this works OK, but I think I'm getting an error regarding order of scenes being added and replaced. Basically, your function adds the scene in, and *then* removes the "to be replaced" scene. This causes a problem for me because the added, initialized scene also adds in a scene of its own. So basically, Scene 1 adds scene 2, scene 2 adds scene 3 on top, and then scene 1 removes scene 3, instead of itself, because scene 3 is now on top.

I think this should be able to be rectified by just removing the unwanted scene and *then* adding the wanted one in the set function.

**Comment by GoranM** [comment]
Oh, yeah, my mistake.

> I think this should be able to be rectified by just switching the order of operations

Well, not quite, because if dealing with the last element in the list, removing the old one first would make the list shorter, and then you would be trying to add the new one into an index that was out-of-bounds at that point.

**Comment by SolarLune** [comment]
Eh? Do you mean removing the last element (of 2 or more) in a last, or the only element (the literally last element) in a list?

I can't visualize this problem; if you have an empty scenes list, adding a scene at index 0 will put a list at index 0. If you have two scenes in the list, and try to set a scene at, say, index 1, it will remove the scene at index 1 (thereby making the list of size 1), and then add a new scene at index 1, making the list size 2 again.

**Comment by GoranM** [comment]
> If you have two scenes in the list, and try to set() a scene at, say, index 1, it would remove the scene at index 1 (thereby making the list of size 1), and then add a new scene at index 1

In a list with only one element, index 1 should be out of bounds, logically, so I assumed that referencing that index in add would throw an exception (just as it would with get), but that doesn't seem to be the case ...

My mistake, again.

*EDIT - Oh, it's actually in the [fine print](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#add(int,%20E)): (index < 0 || index > size()) for add, as opposed to (index < 0 || index >= size()) for get.

**Comment by SolarLune** [comment]
OK, that seems to have solved it. Thanks!
