### ISSUE TITLE
Make scenes.add consistent

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#148]
Hey, there. So, scenes.add is a bit inconsistent at the moment compared to game object instantiation, as you have to actually create a new scene to add it in. I think it should just be like the GameObject variant, where you just provide the name of the scene to add.

**Comment by GoranM** [comment]
I don't know ... I mean, for scene.objects, it's just a matter of adding a new GameObject to the end of the list (you don't have to - and you're not supposed to - fiddle with the order), but for Bdx.scenes, you might not want to always create a new scene at the end.

Maybe you have a reference to an old scene (with the old state preserved), and you want to add it back at a specific index.

**Comment by SolarLune** [comment]
> for Bdx.scenes, you might not want to always create a new scene at the end.

My point wasn't to change how the add works in terms of ordering scenes, but rather just the ability to pass a name of a scene and have BDX instantiate it, like scene.add() works.

> Maybe you have a reference to an old scene (with the old state preserved), and you want to add it back at a specific index.

Wouldn't that be a purpose best served by just using the SceneArrayList to swap and slide around existing scenes? Perhaps a new function to handle moving a scene from one index to another? Maybe functions to move a scene up and down the list?

However this particular problem is solved, I don't think it makes much sense to store references to scenes *outside* of an area specifically created to handle and keep track of those references. As it stands now, there's no way to re-order an existing scene without destroying another one or re-instantiating it. This might be an oversight.

**Comment by GoranM** [comment]
> I suppose another variant of add() would do this, if you want both.
> ...
> Wouldn't that be a purpose best served by just using the SceneArrayList to swap and slide around existing scenes? Perhaps a new function to handle moving a scene from one index to another? Maybe functions to move a scene up and down the list?

Isn't that a bit too much, just to avoid typing "new Scene"?

> However this particular problem is solved

I don't understand what you mean. Which problem?

> I don't think it makes much sense to store references to scenes outside of an area specifically created to handle and keep track of those references. 

Bdx.scenes was not "specifically created to handle and keep track" of scene references. It simply serves as a container of currently active scenes.

One might want to store a scene outside that list, so they can place it back without loosing state, or with a state that was crafted off-screen.

**Comment by SolarLune** [comment]
> Isn't that a bit too much, just to avoid typing "new Scene"?

I don't think an additional function to bring it in line with existing adding functions present in the code-base is a bit much. It's up to you though; it's not a big change.

> I don't understand what you mean. Which problem?

The problem you brought up - keeping a reference to an old scene that you want to add back at a specific index.

> Bdx.scenes was not "specifically created to handle and keep track" of scene references. It simply serves as a container of currently active scenes.

Not trying to argue semantics here, but it sounds like you created the scenes list for this specific purpose - to handle (add and remove) and keep track of (re-index, allow BDX to loop through them) active game scenes. It's not like it's just a "helper" list for the developer - this is the core of how BDX works with scenes. You even have a special class of named list specifically for handling scene references.

But whatever - this issue is just concerning making `Bdx.scenes.add()` work similarly to `scene.add()`. If you don't think it's necessary, then it's fine.

**Comment by GoranM** [comment]
> I don't think an additional function to bring it in line with existing adding functions present in the code-base is a bit much. 

Well, I don't think we can leave it at just add - I mean, you would also want add at index, and set.

So, that's 3 additional methods.

> The problem you brought up - keeping a reference to an old scene that you want to add back at a specific index.

I didn't say it was a "problem" - I simply wanted to impress that Bdx.scenes has more varied use cases than scene.objects, and so, maybe the fact that we do something for scene.objects doesn't imply that we should also do it for Bdx.scenes.

> If you mean that it wasn't created to handle additional, "inactive" scene references, or to be the only method by which to do so, then yeah, it's not the end-all-be-all.

Yes. It wasn't designed to keep/manage all existing scene references - it was designed to just serve as a container for active scenes.

But, either way:

If you want to add those 3 methods, ok - I'll merge that PR.

**Comment by SolarLune** [comment]
Nah, it's cool. It's not that big of a deal; just something that I thought might be good for users. It's fine the way it is.
