### ISSUE TITLE
Suggestion: Component on boolean

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#152]
Hey, there. I think components would benefit from a simple "on" boolean to determine if they're on or not (to make it easier to trigger / toggle them).

**Comment by rafcolson** [comment]
How about "active"? I like that semantics more. Just suggesting.

**Comment by SolarLune** [comment]
^ That's fine.

**Comment by rafcolson** [comment]
@SolarLune Isn't [[```state```|API-State]] already doing this?

**Comment by GoranM** [comment]
> Isn't state already doing this?

[Yes](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L569).

**Comment by SolarLune** [comment]
Hmm, so setting state to null is effectively turning it off. Thanks, that's good to know. Issue closed.
