### ISSUE TITLE
Fullscreen & resolution

### ISSUE THREAD

**Issue by Nananas** [GoranM/bdx#153]
Is it useful to have fullscreen/resolution functions inside Bdx?

Like getting a list of `DisplayMode`'s, setting/toggling fullscreen, adjusting resolutions for fullscreen, active/optimal resolution for fullscreen...

You can perfectly use the libgdx functions for this though... :speak_no_evil:

**Comment by GoranM** [comment]
I guess it would be a good idea to make BDX methods that wrap the relevant libgdx functions.

I have yet to actually look at that - Do you have any suggestions, relating to how the API should look?

**Comment by Nananas** [comment]
Well, I think the problem lies in having the correct resolution for fullscreen. Only a certain set is allowed, if a different `DisplayMode` resolution is used, setting fullscreen will fail.

Is there a situation where you would not want the highest available resolution/desktop resolution?

**Comment by Nananas** [comment]
Libgdx supplies a list with all available resolutions with`getDisplayModes()`. 
So I see these options:
- Fullscreen takes the highest possible resolution
- Fullscreen takes a `DisplayMode` as parameter to set the resolution. It is the task of the developer to get the right one (maybe using an options menu)
- Fullscreen takes the resolution the closest to the window size - but this is going to scale the game = bad

I think the two first options should be implemented both. But then the developer has to juggle with the `DisplayMode` class from libgdx...

**Comment by SolarLune** [comment]
If written correctly, I don't think the developer would have to worry about using the DisplayMode class at all. For example, in my code, I do this to toggle full-screen mode:
```
if (Bdx.keyboard.keyHit("f4")){ // Fullscreen changing
            Graphics.DisplayMode dm = Gdx.app.getGraphics().getDesktopDisplayMode();
            Gdx.app.getGraphics().setDisplayMode(dm.width, dm.height, Gdx.app.getGraphics().isFullscreen());
        }
```

If you were to make a fullscreen function that takes a width and height, then you should be able to just pass that info to setDisplayMode(). It shouldn't require the developer to handle anything extra.

**Comment by GoranM** [comment]
Maybe something like:

```java
Bdx.display(width, height, fullscreen=false);
```

?

**Comment by SolarLune** [comment]
^ Hm, I think I would feel better about putting that in another package. It'd be the only function on that package level.

**Comment by Nananas** [comment]
> Bdx.display(width, height, fullscreen=false);

Ok, but you will still have problem with incompatible resolutions. If I have a game of 400 by 400, I won't be able to do just `Bdx.display(400, 400, true);` as this will fail!

I guess most of the time, one would just chose the highest resolution (?) (=desktop resolution). This can be done with: `getDesktopDisplayMode().width;` etc.

So I propose at least an additional function
```java
Bdx.display(fullscreen=false) {
    Bdx.display(getDesktopDisplayMode().width
        , getDesktopDisplayMode().height
        , fullscreen);
}
```

Also: [Viewport scaling](https://github.com/libgdx/libgdx/wiki/Viewports)
This might be a solution for the stretching when using a different aspect ratio.

**Comment by GoranM** [comment]
> It'd be the only function on that package level.

Bdx is a class with static members, not a package; I don't think it would be problematic to have methods there.

Although, I would agree that `Bdx.display.whatever` would make more sense, organizationally.

> If I have a game of 400 by 400, I won't be able to do just Bdx.display(400, 400, true); as this will fail!

We could just catch that exception, print a warning (explain why provided values were invalid), and then use closest valid values.

As for "viewport scaling": I think we would just need to recalculate the projection matrix to account for the new aspect ratio.

**Comment by SolarLune** [comment]
> As for "viewport scaling": I think we would just need to recalculate the projection matrix to account for the new aspect ratio.

So that would be an additional function, right? Perhaps it would take an aspect ratio, which you could get and call from the Blender standalone settings?

This wouldn't be automatically done when you reset the viewport, since sometimes you want "stretched" viewports vs. "extended" viewports, right?

**Comment by GoranM** [comment]
> This wouldn't be automatically done when you reset the viewport, since sometimes you want "stretched" viewports vs. "extended" viewports, right?

Would you ever really want stretched?

I wouldn't want to use anything but fitted; It's guaranteed to display the game correctly, and it eliminates a whole slew of display issues that one would have to handle with extended viewports (lining up your HUD to fit with the extended edges, for example).

There's a potential for black lines, yes, but if you work in 16:9 (which is basically a standard now), a very, very small portion of your players would actually see those, and of those that do, I doubt that very many would care.

> Well yeah, but it'd still be the first function there. I think having a display, or maybe system package to store this kinda stuff in would be good.

By "package", do you mean com.nilunder.bdx.display (that's a java package), or an instance of a Display class, as a static member on Bdx?

I think the latter would be fine (not so sure about the former).

**Comment by SolarLune** [comment]
Could you clarify the distinction between stretched and fitted (as opposed to extended)?

By "package", I suppose I would mean a static member on Bdx. Like, "Bdx.system.display()", or "Bdx.display.fullscreen()" or something like that.

**Comment by Nananas** [comment]
@SolarLune Did you check the link I gave about Viewports? The images are quite clear.

**Comment by SolarLune** [comment]
@Nananas - Ah, I didn't see that. Thank you!

@GoranM 

> Would you ever really want stretched?

Yeah, I would.

> but if you work in 16:9 (which is basically a standard now)

Not everyone will for every project.

**Comment by GoranM** [comment]
> Yeah, I would.

Why? I mean, wouldn't that look deformed?

> Not everyone will for every project.

Well, let's say that you're working at 4:3, and someone plays your game full screen on a 16:9 display (very high probability), you would want to stretch out to that? Even extending would probably be unacceptable at that point, because your field of view would change quite a bit.

**Comment by Nananas** [comment]
I would use Fit, and maybe Stretch. I don't think I would ever use Extend though.

**Comment by SolarLune** [comment]
> Why? I mean, wouldn't that look deformed?

Yeah, but some people would rather have a full screen with deformations than a screen with bars on the sides and no deformation. If you were, for example, making a game in a style of SNES or NES games, you might choose a really low square-ish resolution / aspect ratio like 256x224 or 320x240 or something. Best to support it and give the developer or even the player the option of which to go with.

> you would want to stretch out to that?

Yeah, probably.

I think Extend would be good to have, perhaps for situations or game styles where the GUI is minimal, or for special setups.

**Comment by rafcolson** [comment]
@Nananas I'm not sure, but this probably can be closed, right? Display methods for full screen and windowed modes were added, as well as Viewport functionality.

**Comment by Nananas** [comment]
Well, I'm not really following this as closely anymore :innocent:. I will just believe you and close this then.

**Comment by rafcolson** [comment]
Thanks.
