### ISSUE TITLE
Suggestion: music and sound device?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#154]
Hey, there. 

I think it'd be nice to have a static device for playing back music and sound to be able to easily control volume from it. Currently, when you play a sound or music, you can adjust the playback of the sound afterward. This can be a bit tedious if you have a lot of sounds and want to change something later. 

With the device, you could adjust it globally to more easily and consistently control volume and panning. The actual sound and music playback system would be basically the same. For example:

```
Bdx.audio.device.masterVolume = 0.5f;

Bdx.audio.device.musicVolume = 0.75f;

// Default volume of 100%, or 1.0 for soundVolume, musicVolume, and masterVolume

Music levelBGM = Bdx.audio.device.loadMusic("Level1BGM"); 

levelBGM.play(); // Plays back at a volume of 75% of 50%, or 37.5%

Sound jumpSound = Bdx.audio.device.loadSound("Jump"); // Volume of 50%.

jumpSound.play();

jumpSound.volume = 0.5f; // Jump sound is now playing at 25% volume
```

**Comment by GoranM** [comment]
The ability to control overall volume would be useful, but I don't think the implementation would require a significant change in the API. You could just have:

```java
Bdx.music.volume
Bdx.sounds.volume;
Bdx.audioVolume;
```

BTW: `music` and `sounds` are designed to behave like hashmaps, so you can just use get("sound_name") - you're not supposed to call load directly.

As for the API, in general: I didn't want to add more levels of indirection than necessary, but, organizationally, I guess it would make more sense to have everything stem from Bdx.audio:

```java
Bdx.audio.music.volume
Bdx.audio.sounds.volume
Bdx.audio.volume
```

It's a bit longer to type:

```java
Bdx.audio.sounds.get("name").play();
// vs
Bdx.sounds.get("name").play();
```

I guess people could alias, if necessary:

```java
Music music = Bdx.audio.music;
music.get("name").play();
```

But then, there could be a clash between libgdx Music and bdx Music, so maybe we could rename bdx Music to Musics ... ?

Or maybe all this stuff should just be available directly from the GameObject itself?

All our logic runs on the GameObject to begin with, and we already have "scene" there, so why not other things?

**Comment by SolarLune** [comment]
I like the idea of just putting that stuff in the music and sound stores. There's not many locally available options for music and sound in LibGDX (just panning, volume, and looping), so it wouldn't be difficult or too invasive to put it in there.

> All our logic runs on the GameObject to begin with, and we already have "scene" there, so why not other things?

What, you mean like store a local reference to the static music property through the GameObject `(GameObject.music)`? `scene` is the local spatial scene the object is stored in; I guess you could say `music`, `sound`, and `audio` are the "local aural versions" of those spaces as well...

Would "clashes" really happen, though? When I code, I can import either of the Music classes, but after I do so, any other imports use the fully-qualified classpath, so I don't think any issues would arise other than the developer having to deal with it.

**Comment by GoranM** [comment]
> What, you mean like store a local reference to the static music property through the GameObject (GameObject.music)?

Yes - references to relevant global instances on Bdx. It's not really something that belongs on GameObject, but it would be less typing, and less code to look at.

So instead of:

```java
if (Bdx.mouse.keyHit("left"))
    Bdx.audio.sounds.get("name").play();
```

You could do:

```java
if (mouse.keyHit("left"))
    sounds.get("name").play();
```

But that means we have to set those references in Scene.init, and cloneNoChildren, so it's a bit more to worry about in the implementation ... I don't know if it's worthwhile, but it's something to think about.

> Would "clashes" really happen, though? When I code, I can import either of the Music classes, but after I do so, any other imports use the fully-qualified classpath, so I don't think any issues would arise other than the developer having to deal with it.

If the distinction is made with a fully qualified name, there would be no clash, but it would look ugly.

**Comment by SolarLune** [comment]
Hey, so I'm looking at this in the API. I think a simple volume field would work well for the Bdx.music and Bdx.sounds spaces - no need for a global one, I think. I think we should keep the namespace simple like this as well; not really a need for a Bdx.audio space.

We'd have to make our own Sound and Music classes that set their volume to the values in the hashmaps when they're played for the global volume settings to work, though. Is that OK?

**Comment by SolarLune** [comment]
Hey, so I'm looking at this again, and it seems like you can't actually modify properties like volume, panning, etc. before playing the actual sound or music instance. I'm not sure what I was looking at previously.

We'd have to make an audio device class of our own if we wanted to proceed with more fine control over sound properties (i.e. easy fading in and out of sounds, cutting off all sounds, etc).

**Comment by GoranM** [comment]
Couldn't you simply extend libgdx Sound?

**Comment by SolarLune** [comment]
Ah, I see, perhaps I can - I thought LibGDX had different Sound derivative classes for each platform because Sound was an interface, but it looks like LWJGL has a class (OpenALSound) that implements the base Sound interface, and then other Sound / Music classes that extend that OpenALSound to load in and play back data effectively. 

So if we have a class that extends OpenALSound, maybe it would work? What kind of API would we be looking at?

**Comment by GoranM** [comment]
Well, for an interface, you could create a class that implements that interface, and then defers to whatever implementation is returned by `Audio.newSound()`. I don't think you can just extend the OpenAL implementation, because that's unique to a particular platform, so it's not guaranteed to work on all platforms supported by libgdx.

I think the aforementioned "Bdx.audio" structure would make for a sensible API. "Bdx.audio" would provide methods for setting global audio properties, with music and sounds providing methods to further control their respective subgroups.

**Comment by SolarLune** [comment]
> Well, for an interface, you could create a class that implements that interface, and then defers to whatever implementation is returned by Audio.newSound().

Hmm, I'm not sure if I follow you - I tested things out, and it seems like an interface can't have defined functions with bodies, and a class can't extend an interface. I could make a new class that implements an interface, but then we'd be copying a lot of code from desktop sound classes to actually build the functions in (because the interface doesn't contain any data for how the functions work), so I don't quite know what to do.

Could you give me an example?

> I think the aforementioned "Bdx.audio" structure would make for a sensible API. "Bdx.audio" would provide methods for setting global audio properties, with music and sounds providing methods to further control their respective subgroups.

That sounds cool. We would need volume / panning adjustment functions that would loop through playing streams and update them, right?

**Comment by GoranM** [comment]
>I could make a new class that implements an interface, but then we'd be copying a lot of code from desktop sound classes to actually build the functions in (because the interface doesn't contain any data for how the functions work), so I don't quite know what to do.
>
>Could you give me an example?

You just need to write a class that implements the Sound interface, where each method calls the corresponding method on the base implementation already returned by Audio.newSound:

```java
class BdxSound implements Sound{
    Sound base;

    public BdxSound(FileHandle sound_file_path){
        base = Audio.newSound(sound_file_path);
    }

    public long play(){
        long stream = base.play();
        // do something with the stream id, or whatever ...
    }

}
```

> We would need volume / panning adjustment functions that would loop through playing streams and update them, right?

Right.

**Comment by SolarLune** [comment]
OK, PR updated - I think that should be it.

**Comment by SolarLune** [comment]
PR was merged, so I'll close this now. Thanks!
