### ISSUE TITLE
Suggestion: destroy() function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#156]
Hey, there. 

I was thinking that it might be a good idea to add a destroy() function that would be overloaded to the GameObject class (like the init() and main() functions). That way, you could run something on a GameObject's destruction (removal from its scene using end()). So the process of a GameObject would now be:

```
init() (called once, when the GameObject is created)

main() (loops, as long as the GameObject is active)

destroy() (called once, when the GameObject is ended / removed)
```

For example, you could spawn particles if it's an enemy, up the player's score, change a variable in the global game state, whatever. Otherwise, you'd have to make your own destruction function (which would do these things when called, when you want to remove the object from the scene); it's not too big a deal, just seems like something that could be useful.

**Comment by GoranM** [comment]
You could just override endNoChildren, but if you really want destroy, I don't mind having it in.

**Comment by rafcolson** [comment]
@SolarLune What would be the difference between end() and destroy() then?

**Comment by SolarLune** [comment]
Oh, destroy() wouldn't be to end the object; it would be called when the object is destroyed, like how init() is called when the object is initialized.

@GoranM - Well, I don't really want to add additional junk if it's unnecessary... You'd have to remember to call super.endNoChildren() if you overloaded the function, though, which could be a bit annoying. It reminds me of how components only used to run if you called super.main() (though that's more restricting for more reasons).

**Comment by GoranM** [comment]
> You'd have to remember to call super.endNoChildren() if you overloaded the function, though, which could be a bit annoying.

Good point.

Maybe "onEnd()" would be more consistent with existing semantics?

**Comment by SolarLune** [comment]
^ That's fine.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR merged. Thanks, Goran! Issue closed.
