### ISSUE TITLE
[Question] 2D draw functions

### ISSUE THREAD

**Issue by Nananas** [GoranM/bdx#160]
I don't know if this is planned (Is Bdx 3D only?), or unnecessary. 
Drawing 2d textures currently need a plane geometry, right? Or how would you draw a HUD without a model? Are you planning on implementing 2D `GameObjects` like a `Sprite`?

(Also, is there an easier way to ask questions then making an issue for it?)

**Comment by GoranM** [comment]
I don't plan on adding any 2D specialization for BDX - It's a 3D engine.

> (Also, is there an easier way to ask questions then making an issue for it?)

How is it difficult to make an issue? I think it's fine, as long as you close it when it's resolved.

**Comment by Nananas** [comment]
Okie

> How is it difficult to make an issue? I think it's fine, as long as you close it when it's resolved

Haha, not difficult no. Bad word. I meant *faster* I think. 
I was thinking in a direction of a chat. Something like gitter.im/slack.com could prevent some clutter in the issues-box, when the engine becomes more mature/popular.
