### ISSUE TITLE
Bug: Music not playing in desktop distribution

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#167]
Hey, there. So I put my music in the `android/assets/audio/music` folder (correctly, I thought), and music playback via Bdx.music.playMusic() works. However, when I distributed a desktop version of my game, the music doesn't play at all. No error message either. Interestingly, the sound seems to play fine; just not the music.

I used a simple test project to test this out further and, again, no music playback. I can upload it if necessary, but it's pretty much just an object that plays a song and the song in the music folder. Works in Blender, doesn't work when as a standalone .jar. It should be able to be replicated fairly easily.

**Comment by SolarLune** [comment]
OK, it's probably not BDX, considering how it basically is just a wrapper for LibGDX when it comes to some things (like sound and music playback). [I think the problem can be solved by switching file formats](http://stackoverflow.com/questions/22469319/eclipse-and-libgdx-problems-with-playing-music-on-exported-jar); I'll check and confirm.

**Comment by GoranM** [comment]
> Bdx.music.playMusic()

... ?

There is no "playMusic" method on Bdx.music.

> I think the problem can be solved by switching file formats; I'll check and confirm.

It shouldn't be the fileformat - In that SO thread, it seems like the IDE (Eclipse) was causing trouble, and there were some issues with the file size, so converting to wav's to mp3's made them smaller, and that solved the problem.

This is clearly not a BDX issue, but, if you want, I can look at it:

Make a simple example for me, that demonstrates the problem (I think "Create packed BDX blend" should pack the audio resources properly - good opportunity to test that, as well).

**Comment by SolarLune** [comment]
Hey, so I converted the audio from WAV to OGG, and it did fix the problem; maybe it was a matter of file size. I can only imagine that Java does this loading process concurrently or something, and I would need to call playMusic() multiple times for it to actually trigger (since the music isn't loaded yet for a WAV file). I dunno.

I wasn't using IntelliJ to export the jar files, as I did it via command-line, so I don't think it was an IDE issue in mycase. I'm sure it's not something to do with BDX, though, so it's fine; maybe just a quirk with LibGDX. 

Anyway, issue closed.

**Comment by GoranM** [comment]
> I can only imagine that Java does this loading process concurrently or something, and I would need to call playMusic() multiple times for it to actually trigger (since the music isn't loaded yet for a WAV file). I dunno.

It might have something to do with the fact that there is no "playMusic" method on Bdx.music.

**Comment by SolarLune** [comment]
I don't understand why you would comment that again. It was an obvious mistake because I clearly said "music playback via blahblahblah *works*". If I was calling a non-existent function, it wouldn't work at all.

Let me be clear; I was mistaken, I apologize. `Bdx.music.playMusic()` not the correct location of the playMusic() function. I am using the playMusic() function correctly. It works in Blender. It doesn't work in a standalone jar file when I use WAV files. It does when I use OGG files, as that SO thread indicated. The problem lies elsewhere.

**Comment by GoranM** [comment]
> I don't understand why you would comment that again. It was an obvious mistake

You didn't confirm that it was a mistake; I wasn't sure that you actually understood what I was trying to say.
