### ISSUE TITLE
Suggestion: Method to rotate vectors

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#170]
Hey. It'd be nice to have a method to rotate vectors; it'd be useful to pivot, for example, positions around other points or objects without having to resort to using game objects and parenting.

EDIT: Looking it over, it looks like it might be possible to do a bit using utils.Bullet.rotMatrix() function, but it's a bit tough to understand, I think...

**Comment by GoranM** [comment]
> Looking it over, it looks like it might be possible to do a bit using utils.Bullet.rotMatrix() function, but it's a bit tough to understand, I think...

It takes an axis of rotation, and an angle by which to rotate. The concept doesn't seem that difficult to me.

However, it is in the wrong place, in Bullet.java - it should be a static method on Matrix3f.

**Comment by SolarLune** [comment]
OK, I was mistaken; that's easy enough to understand, but it's still a bit awkward to use just to rotate a vector. You'd have to use the function to get a matrix, convert that matrix back to a vector, and then probably re-set its length, right? 

A simpler way to rotate a vector might be nice.

**Comment by GoranM** [comment]
> You'd have to use the function to get a matrix, convert that matrix back to a vector, and then probably re-set its length, right?

Given a matrix R, which encodes the desired rotation, you can simply do:

```java
vec = R.mult(vec);
```

> A simpler way to rotate a vector might be nice.

Well, I'm open to suggestions, but I don't think it's a good idea to stray from the "matrix transforms vector" paradigm, because it's already so prevalent in computer graphics.

Also, less important, but still relevant: When applying the same rotation to multiple vectors (typical case), it's more efficient to simply make one matrix, and apply that to multiple vectors, then it would be to call something like Vector3f.rotate, which would have to create the same matrix over and over again.

**Comment by SolarLune** [comment]
> Well, I'm open to suggestions, but I don't think it's a good idea to stray from the "matrix transforms vector" paradigm, because it's already so prevalent in computer graphics.

Fair enough, but for people who aren't too familiar with matrices, a simple function to rotate a vector around would probably be advisable, as it's easy to understand. 

Doing it myself, I see it's as simple as adding a mult() call to the end of rotMatrix(), so maybe this wouldn't be that useful. Maybe the rotMatrix() function could be moved out of Bullet? It's not currently in the API.

**Comment by GoranM** [comment]
> Maybe the rotMatrix() function could be moved out of Bullet?

Yes, as I said:

> it is in the wrong place, in Bullet.java - it should be a static method on Matrix3f.

So, I think I'll make a `Matrix3f.rotation(axis, angle)`.

**Comment by SolarLune** [comment]
Guess this ended up being solved. Issue closed!
