### ISSUE TITLE
Bug: BDX crashes if you rename an image

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#172]
Hey, there. So BDX crashes on export of a project if you rename a resource (like an image). It looks like BDX uses the resource name in Blender (the name of the image, for example) as opposed to the path to the file as the filename of the resource to use.

**Comment by GoranM** [comment]
You can fix it [here](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L437), if you want.

**Comment by SolarLune** [comment]
PR Submitted.

**Comment by SolarLune** [comment]
PR Merged. Thanks! Issue closed.
