### ISSUE TITLE
Suggestion: Reversing SpriteAnim speed

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#176]
Hey. SpriteAnim's main state uses Math.abs() on the speed variable, so it's impossible to reverse an animation; you can currently only slow it down or speed it up. Is there anything that could be done for this?

**Comment by GoranM** [comment]
Yes, it should be fairly easy to add support for reverse playback.

**Comment by SolarLune** [comment]
Cool, that'd be nice.

**Comment by GoranM** [comment]
Ok, that should do it.

**Comment by SolarLune** [comment]
Thanks! I'll close this and re-open if I find an issue with it later.
