### ISSUE TITLE
Suggestion: Have SpriteAnim.current() return null

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#177]
Hey, there. If you haven't played an animation in a SpriteAnim component, current() won't return null, but rather a string - "BDX_NONE". It seems like it'd be better to just have it return null, like other functions that would return null.

EDIT: OK, I think I see in practice why this is allowed; it lets you use string functions even though the component may not have an animation assigned to it yet. That's sensible. Perhaps "null" would be better?

**Comment by GoranM** [comment]
> Perhaps "null" would be better?

If there's a decent rationale to support that change, I wouldn't mind.

**Comment by SolarLune** [comment]
Well, I guess the question is "Why "BDX_NONE"? Is it a constant? What made you name it that in particular?" I guess it doesn't really matter in the end, as long as it's documented.

**Comment by GoranM** [comment]
For a string in this engine, which represents none, this seemed like a reasonable choice.

If something else would be better, I'm willing to change it.

Although, with the new approach I outlined in #178, I don't think a string of any kind would be necessary.

**Comment by SolarLune** [comment]
OK, it makes sense. Thanks!
