### ISSUE TITLE
Suggestion: Expand SpriteAnim animation array from just int[]

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#179]
Hey, there. It'd be nice if SpriteAnim's animation adding function took more than just int[] for the frames list. Maybe an ArrayList by default would be a better choice, or better yet something more generalized...?

**Comment by Nona2** [comment]
this is all just convenience stuff ive thought about-

to create a punch with 7 frames of start up 3 frames of active and 9 frames of recovery i did:
sa.add("punch", 0, new int[]{0,0,0,0,0,0,0,1,1,1,2,2,2,2,2,2,2,2,2},60,false);

it would be very convenient to be able to to do it like
new init []{0,1,2} #for the frames followed by
new init[]{7,3,9} #for the number of ticks at the constant fps (in my case 60) the frame of animation is active for

seems like that would make it easy to create and tweek dynamic animations.

i thought about using the .speed inside the punch state set on the .frame() but it feels like that would be messier than my original example.  Plus setting an anim speed in a state that might be ended abruptly might cause issues.

**Comment by GoranM** [comment]
A regular int array seems sufficient.

However, if there's a decent rationale to support a new method, like add(String, List, ...), I wouldn't mind.

> sa.add("punch", 0, new int[]{0,0,0,0,0,0,0,1,1,1,2,2,2,2,2,2,2,2,2},60,false);

I would just do this:

sa.add("punch", 0, new int[]{0,0,1,2,2,2},20,false);

**Comment by SolarLune** [comment]
Well, it's just kinda awkward to store and use straight arrays. It seems easier to support ArrayList, especially for its easy reversing ability through Collections. It's also easier to put things into ArrayLists than it is to create the array once and then convert ints to Integer arrays and so on.

**Comment by GoranM** [comment]
> easy reversing ability through Collections

Once #176 is implemented, and you can simply set an animation to play in reverse, will that still matter?

**Comment by SolarLune** [comment]
Nope, that should be good. Although, you might want to store and manipulate animations, which ArrayLists are generally better suited for. Is there a reason not to use ArrayLists instead of int[]s? Would it be possible to support both?

**Comment by GoranM** [comment]
It's certainly possible to just create one more add method, which takes a List instead of an int[] type, but it doesn't make sense to add that code unless it's truly necessary/helpful.

If you can provide a non-contrived example, where that method would have clear benefits, that would help.

**Comment by SolarLune** [comment]
Don't think I can, unfortunately. It's just that transferring between int[]s and ArrayLists is a huge pain if you want to store animations, and it seems like a good idea to make the default animation type ArrayLists versus the much less versatile int[].

**Comment by SolarLune** [comment]
Since it seems this is just a matter of personal preference, I'll close this issue.
