### ISSUE TITLE
Bug: Collision Callback not Disposed

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#180]
Hey. The collision callback in line 397 in Scene.java is never disposed, which can apparently cause a memory leak. Thanks to mk1 on the LibGDX IRC channel for the assistance.

**Comment by GoranM** [comment]
It has to be disposed? How?

As far as I know, there is no dispose method on ClosestRayResultCallback.

**Comment by SolarLune** [comment]
Hm, he must have been mistaken; I notice no memory leak in my tests. I apologize; I'll be sure to check things out before making a report for it first. If I find any leaks in regards to this, I'll reopen it.
