### ISSUE TITLE
Build error Ubuntu

### ISSUE THREAD

**Issue by AlexKraak** [GoranM/bdx#181]
Created a project as instructed in tutorial, On run "BDX BUILD FAILED"
I am using blender 2.73, ubuntu x64 and java 8

**Comment by SolarLune** [comment]
What does the console say when you do this?

(To enable the console on Linux, start Blender from a console.)

**Comment by AlexKraak** [comment]
Ok apparently i am a liar, It worked after i restarted my pc. This is a fresh install of Linux and java may have wanted to reboot, at least thats the only thin i can think of that would change
