### ISSUE TITLE
Suggestion: new Component: "Follow"

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#183]
Hi guys,

It would be nice to have some build-in features such as following a target. This especially would be useful to add to a Camera. For 3D games the Camera would also need to track the target. But that's another component, which I'll present later.

I already pulled a request for this. To use it you can do for example this:

```java
package com.raco.game;

import com.nilunder.bdx.*;
import com.nilunder.bdx.components.*;

import javax.vecmath.Vector3f;

public class Cam extends Camera{
    private static Follower follower;
    private static GameObject target;

    public void init(){
        target = scene.objects.get("Sacky");
        float lerp = 0.05f;
        Vector3f offset = new Vector3f(0, -5, 0);
        follower = new Follower(this, target, lerp, offset);
        components.add(follower);
    }
    
    public void main(){
    }
    
}
```
Any suggestions are more than welcome.

**Comment by GoranM** [comment]
I would name it "Follow"; Follower implies a GameObject, not a component.

That said: I'm not sure this is general enough, because it's using a specific method of motion (position displacement, instead of force, or linear velocity, or whatever else the developer would want for their movement logic).

> I already pulled a request for this.

You made a pull request; It's up to me to pull it - You didn't pull anything.

Making a pull request != pulling a request. Do you understand what I mean?

Also, you shouldn't make a pull request for a suggestion that wasn't approved.

**Comment by rafcolson** [comment]
Yes Goran, I understand what you mean. I'm sorry for being so annoying. I should have said that I made a new pull request.

>I'm not sure this is general enough, because it's using a specific method of motion (position displacement, instead of force, or linear velocity, or whatever else the developer would want for their movement logic).

I was thinking the same thing. I'm gonna try and add those options. But I'm guessing I will not be able to get the motion with those three states exactly the same. So putting this on hold for now.

**Comment by rafcolson** [comment]
My guess was wrong. There's no difference in motion between using ```move``` and ```velocity```. So could I create a PR for this?

**Comment by GoranM** [comment]
Technically, I think that bullet handles displacement in a different way when compared to setting instant velocity, but even if not, using force would be visibly different.

Overall, I don't think this is general enough to be a default component, and I don't think it has a significant utility: With the Track component, the user can simply apply the necessary motion, with the proper method for the given circumstances.

**Comment by rafcolson** [comment]
Okay, thanks. So to make it more general how would I go ahead on this? An extra variable in the constructor to define the mode? Integer {0, 1, 2} or String {"move", "velocity", "force"}?

**Comment by GoranM** [comment]
It's not an inherently general component - I don't think we benefit from trying to force it into that category. 

Also, it doesn't provide significant utility.

As I said before: With the Track component, the user can simply apply the necessary motion, with the proper method for the given circumstances.

> Could you explain why it would be beneficial for the user to define motion with "force"?

Changing position, or setting instant velocity for a given object is a somewhat "violent" act, as far as the physics engine is concerned; when pushing against other objects, you can see tunneling, and shaking.

Force doesn't have those problems.

**Comment by rafcolson** [comment]
It was sort of my goal to have this Follow component work with the Track component for camera movement, comparable to the Camera Actuator in the BGE. Even on itself (so without Track) it can serve for camera movement in 2D games as well. I think it would be convenient for the user to be able to use such a built-in component.

Actually the Track component is pretty standard too. It's manipulating orientation, and no angular velocity, it always sticks to the target, so no interpolation. These things could also be added, but i don't see why that would be really necessary. In most cases the user won't need anything more than it is. I feel the same way about the Follow component, if it were to be implemented.

But if you're really sure it better not, then okay. I'll just keep it somewhere in my library.

**Comment by GoranM** [comment]
> I'll just keep it somewhere in my library.

For now, I think that would be best.

**Comment by rafcolson** [comment]
Okay. Closing then.
