### ISSUE TITLE
Suggestion: new Component: "Track"

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#185]
Hi guys,

It would be nice to also have a Component to follow a target. This especially would be useful to add to a Camera with 3D games, in combination with the "Follow" component.

I didn't pull a request for this, because I stumbled into some issues with [alignAxisToVec](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/GameObject.java#L469). Like it is in the BGE, the orientation gets messed up after a while. So maybe there would be a better way to track to the target?

This is what I have now:

```java
package com.nilunder.bdx.components;

import com.nilunder.bdx.Component;
import com.nilunder.bdx.GameObject;
import com.nilunder.bdx.State;

import javax.vecmath.Vector3f;

public class Tracker extends Component {
	public GameObject target;
	public int axis;
	public Vector3f offset;
	
	public void set(GameObject target, int axis, Vector3f offset){
		this.target = target;
		this.axis = axis;
		this.offset = offset;
	}

	public Tracker(GameObject g, GameObject target, int axis){
		super(g);
		set(target, axis, new Vector3f());
		state = track;
	}
	
	public Tracker(GameObject g, GameObject target, int axis, Vector3f offset){
		super(g);
		set(target, axis, offset);
		state = track;
	}
	
	private State track = new State(){
		public void main(){
			if (!target.valid()){
				g.components.remove(this);
				return;
			}
			Vector3f vec = target.position().plus(offset).minus(g.position());
			vec.normalize();
			g.alignAxisToVec(axis, vec.plus(offset));
		}
	};
}
```

**Comment by GoranM** [comment]
A "Track" component sounds like a good idea.

You can make a pull request for this, if you wish, and we can discuss the implementation there.

**Comment by rafcolson** [comment]
Changed the title to "Track" and making a pull request now.

**Comment by rafcolson** [comment]
PR merged.
