### ISSUE TITLE
Question: Matrix3f.rotation()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#187]
Could it be that this method exists in BDX, but isn't exposed to the API yet? Because I couldn't find it in the [javax.vecmath.Matrix3f](http://docs.oracle.com/cd/E17802_01/j2se/javase/technologies/desktop/java3d/forDevelopers/j3dapi/javax/vecmath/Matrix3f.html).

I'm asking because I could find it is used here: https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/GameObject.java#L473

**Comment by GoranM** [comment]
BDX uses a slightly modified version of javax.vecmath, with some additional methods, which are documented: https://github.com/GoranM/bdx/wiki/API#javaxvecmath

I just forgot to update the documentation for Matrix3f - It should be there now: https://github.com/GoranM/bdx/wiki/API-Matrix3f#rotation

**Comment by rafcolson** [comment]
Okay, thanks.
