### ISSUE TITLE
Suggestion: Mouse cursor hiding functions

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#188]
It'd be nice to have an ability to hide the system mouse cursor without capturing it. It looks like mouse.setCursorImage() does it; perhaps the ability to provide a null argument to just replace the cursor with a blank image / pixmap would be good?

**Comment by GoranM** [comment]
Sounds good.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR merged. Thanks!
