### ISSUE TITLE
Bug: Static Ghost Crash Without Static Ghost Objects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#191]
Hey, there. 

So I'm getting a crash when BDX throws an exception because objects are static and ghost with a triangle mesh bounds type, but none of the objects in my scene are ghosts. They're just standard static objects.

Another bug that also appears to be visible in this test is that groups from another scene (Resources, in the test blend file) are added into the game scene and visible there. In this test, the "ChairU" object in Resources is added into the Game scene, and when it comes into contact with the Bounds object, invokes the crash. Moving it away from the bounds fixes it.

I've attached a test blend file. There's no textures.

https://www.dropbox.com/s/ss7v8z2hxwba2sm/physicsbug.blend?dl=0

**Comment by GoranM** [comment]
> Another bug that also appears to be visible in this test is that groups from another scene (Resources, in the test blend file) are added into the game scene and visible there.

I'm not sure how, but that seems to lead to the physics exception; After I fixed that, everything seems to be ok.

**Comment by SolarLune** [comment]
Yep, that did solve it, thanks. Maybe the group was being spawned in as a static ghost object somehow. Anyway, issue closed.

**Comment by SolarLune** [comment]
Hey, I'm reopening this because I seem to be getting the same issue again. The objects are being instanced correctly, but I'm getting the "static-static triangle mesh ghost" collision problem without any ghost objects in the scene. Here's a test blend file:

https://www.dropbox.com/s/uwsrbhsmfomcuf4/physicsbug2.blend?dl=0

**Comment by GoranM** [comment]
If you move the plane 0.1 units up or down, everything works fine ...

I don't know. I couldn't find anything online that would explain this.

**Comment by rafcolson** [comment]
@SolarLune I'm not sure when, but this seems to be fixed.

**Comment by SolarLune** [comment]
Cool, I'll close this then. Thanks for your help!
