### ISSUE TITLE
Suggestion: average fps or actual fps?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#196]
Or maybe other ways to cancel out gravity on a GameObject?

```java
g.velocity(g.velocity().minus(g.scene.gravity().mul(ticRate)));
```

**Comment by SolarLune** [comment]
The FPS is hard-coded to 60 all of the time at the moment, so just using `Bdx.TICK_TIME` should work until an actual "getFrameRate()" function is made that returns the average framerate the game's running at.

**Comment by rafcolson** [comment]
Okay, thanks. And would you also do this to cancel out gravity on a GameObject?

**Comment by SolarLune** [comment]
Seems like a good way to go, yeah. I'd probably spread it out a bit more, but I think this looks fine.

Oh, and also use applyForce() with negative gravity to keep it from applying more.

**Comment by rafcolson** [comment]
>Oh, and also use applyForce() with negative gravity to keep it from applying more.

What do you mean by keeping it from applying more?

**Comment by SolarLune** [comment]
@rafcolson - Ah, I just tested it and I was wrong, haha! As it turns out you can just use velocity() to stop objects in mid-air.
`
public void main(){
Vector3f grav = scene.gravity();
grav.negate();
velocity(grav.mul(Bdx.TICK_TIME));
}
`
Works fine, so I was a bit mistaken. I thought you had to apply a negative gravitational force as Bullet was continually adding force downward, but I guess velocity() counteracts this outright. My mistake!

**Comment by rafcolson** [comment]
No big deal. And yeah, it was also a bit of a pleasant surprise to me, as this wouldn't be working (perfectly) in the BGE.

Come to think of it. The built-in Profiler actually calculates the time between two calls. So I'll change this to a suggestion:

Shall I add the code to update ```Bdx.TICK_TIME``` to ```Bdx.profiler.totalDeltaTime```?

Or should I add another variable ```Bdx.TICK_TIME_AVG``` (average)?

**Comment by SolarLune** [comment]
The `Bdx.TICK_TIME` variable is supposed to be a constant (which is why it's in caps); an average frame rate could be nice to add to the profiler?

**Comment by rafcolson** [comment]
```Bdx.profiler.totalDeltaTime``` actually is the average tick time. So the average tick rate would be ```1 / Bdx.profiler.totalDeltaTime```, right?

**Comment by SolarLune** [comment]
Bdx.profiler doesn't have a property named "totalDetalTime" - it's just a local variable in the update() function, right? 

The average frame rate could probably just be gotten by measuring the number of frames completed (updated and rendered) over the course of one second, though that won't give you partials (i.e. 57.98 frames per second). 

So maybe it would extrapolate based on the amount of time a single frame takes, and use those values to average the total. 

So, if one frame takes three quarters of a second, then the FPS for that frame would be 1.33. If the following frames all take 1/60th of a second, then the FPS for those 15 frames would be 60.0. When averaged out, the first frame would properly "bog down" the total FPS at the end of the second, and so you'd end up with a lower average frame rate. So:

` ( ( 1.33 + ( 60.0 * 15 ) ) / 60 ) = 15.022 FPS`

I think that's right, anyway.

**Comment by rafcolson** [comment]
>Bdx.profiler doesn't have a property named "totalDetalTime" - it's just a local variable in the update() function, right?
Yes.

Hmm, may I ask, why do you think the Profiler could use this kind of average frame rate instead of the actual frame rate (which is "totalDetalTime")?

**Comment by SolarLune** [comment]
Ah, I see. I think I misunderstood you because of semantics. 

"Framerate" to me is the rate at which the game plays back; 60 is the game's framerate (60 FPS). This delta time variable is the >tickrate< of the game (i.e. 16 milliseconds). It's the rate at which a single tick of the game plays; the hard programmed TICK_TIME variable is 1 second / the target of 60 FPS, or roughly 16 milliseconds.

It seems easier to understand an average framerate over a tickrate, since you can see a larger view of the changes on a game's updating process.

**Comment by GoranM** [comment]
I don't really see why you would need "average fps", but assuming that there is a compelling reason, it's something that should reside on the profiler.

As for negating gravity, this seems to work fine:

```java
applyForce(scene.gravity().negated());
```

The bullet simulation time is locked to 16 milliseconds per frame, regardless of the actual frame rate, so there is no need to involve "time", or "framerate", or anything else, when calculating a gravity negation vector - It should just be gravity negated.

**Comment by rafcolson** [comment]
In case of setting a velocity with ```velocity(vector)```, would it be okay to subtract the vector by the gravity per tic, instead of adding an additional operation ```applyForce(scene.gravity().negated())```? Or is it not done?

**Comment by GoranM** [comment]
In bullet, gravity is applied as a force - Countering force with force would probably produce the best results (if your goal is to simply negate gravity).

**Comment by rafcolson** [comment]
Okay, thanks. It's probably cleaner to add that additional line then.
