### ISSUE TITLE
Consolidation of Random.Vector and Random.Direction

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#198]
Hey, there. I was just using Random's vector randomization functions when I realized they could easily be consolidated and expanded into a single, more useful function. It would take a minimum and a maximum length and return a random vector within that range. 

That would afford you the ability to do what Direction does by just having both min and max be 1, and gives you more control than Vector does. The function call with no arguments would just be the same as vector() worked, and give you a random vector between 0 and 1 length.

**Comment by GoranM** [comment]
The methods in question are Random.vector and Random.direction, not Random.Vector and Random.Direction.

> That would afford you the ability to do what Direction does by just having both min and max be 1, and gives you more control than Vector does. The function call with no arguments would just be the same as vector() worked, and give you a random vector between 0 and 1 length.

Random.vector is supposed to return a vector with random *components* in range [-1,1].

**Comment by SolarLune** [comment]
> The methods in question are Random.vector and Random.direction, not Random.Vector and Random.Direction.

Yes? Does it matter? You know what I'm talking about, right?

> Random.vector is supposed to return a vector with random components in range [-1,1].

OK, so then the function call with no arguments can return that, and the argumented function will return one of those vectors, but normalized, with a set length between the minimum and maximum values.

**Comment by GoranM** [comment]
> Does it matter?

I believe so: By using the correct names, you spare your readers the otherwise required double take ... It also implies that you took the time to really think about, and subsequently craft your post.

> OK, so then the function call with no arguments can return that, and the argumented function will return one of those vectors, but normalized, with a set length between the minimum and maximum values.

I don't see how that would be better.

**Comment by SolarLune** [comment]
>I believe so: By using the correct names, you spare your readers the otherwise required double take ... It also implies that you took the time to really think about, and subsequently craft your post.

I hardly see how a change in capitalization would require a double take (it's the same word), or imply that I didn't take the time to think about or craft my post. Did you have trouble understanding my question?

> I don't see how that would be better.

I thought it'd be useful to be able to create a vector randomization function that allows one to specify the range of the randomness. I could alter the direction() function to account for this, but I don't think we want to have multiple functions that do very similar things.

**Comment by rafcolson** [comment]
> I hardly see how a change in capitalization would require a double take (it's the same word), or imply that I didn't take the time to think about or craft my post.

I think what Goran means is that it gets confusing if you don't use the proper coding syntax. That wouldn't be the case if you would have "described" those methods as "getting a random Vector or random direction". But since you used the dot, it implies you're talking about code. Visitors of this site (or even myself) could mistakenly adapt this incorrect syntax. I also think we should avoid that.

This must sound a bit freakish, but just wanted to say that I understand why Goran would make this remark.

**Comment by GoranM** [comment]
Java is a case-sensitive language. Random.Vector is not the same as Random.vector; they don't identify the same field.

My personal ability to interpret your intended meaning is irrelevant: It's better to use correct names.

> I thought it'd be useful to be able to create a vector randomization function that allows one to specify the range of the randomness. I could alter the direction() function to account for this, but I don't think we want to have multiple functions that do very similar things.

If we agree that a random direction is a vector of unit length, which is distinct from a random vector composed of float components within some defined range, it doesn't make sense to conflate the two (component range is distinct from length range).

You could make a Random.vector(min, max), where those arguments would default to -1, and 1, respectively.

**Comment by SolarLune** [comment]
> I think what Goran means is that it gets confusing if you don't use the proper coding syntax. That wouldn't be the case if you would have described those methods as "getting a random Vector or random direction". But since you used the dot, it implies you're talking about code. Visitors of this site (or even myself) could mistakenly adapt this incorrect syntax. I also think we should avoid that.

> This must sound a bit freakish, but just wanted to say that I understand why Goran made this remark. Not to be unfriendly.

> Java is a case-sensitive language. Random.Vector is not the same as Random.vector; they don't identify the same field.

> My personal ability to interpret your intended meaning is irrelevant: It's better to use correct names.

OK.

> If we agree that a random direction is a vector of unit length, which is distinct from a random vector composed of float components within some defined range, it doesn't make sense to conflate the two (component range is distinct from length range).

> You could make a Random.vector(min, max), where those arguments would default to -1, and 1, respectively.

Perhaps Random.vector(min, max, normalize)? That would cover all use cases, I think. The default (no arguments) would behave the same as Random.vector does now.

**Comment by GoranM** [comment]
Vector3f already has a normalize method, which you can simply call if you need it to be of unit length. In that sense, the normalize argument seems like redundant functionality.

**Comment by SolarLune** [comment]
> Vector3f already has a normalize method, which you can simply call if you need it to be of unit length. In that sense, the normalize argument seems like redundant functionality.

With Random.vector(min, max, normalize), we wouldn't really need to have the direction() function; the vector() function would serve the purpose of both.

**Comment by GoranM** [comment]
Why do we need the normalize argument, if Vector3f already has a normalize method?

**Comment by SolarLune** [comment]
Fine, then just the minimum and maximum values?

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
Hm, my new version (which uses Random.random()) gives a possibility of returning 0,0,0, theoretically, which is why I used that if statement there. Any thoughts?

```java
public static Vector3f vector(float min, float max){
		Vector3f v = new Vector3f(
				Random.random(min, max),
				Random.random(min, max),
				Random.random(min, max));
		if (v.length() == 0)
			v = new Vector3f(1, 0, 0);
		return v;
	}

	public static Vector3f vector(){
		return vector(-1, 1);
	}
```

**Comment by GoranM** [comment]
A random vector should include the possibility of 0 for all three components.

You should change Random.direction.

**Comment by SolarLune** [comment]
Done. PR Submitted (#201).

**Comment by SolarLune** [comment]
I think everything involved with this issue was worked out in the end. No consolidation of those two functions have been done, though Direction now never returns a zero-length vector.

Issue closed.
