### ISSUE TITLE
Suggestion: Convex Hull Collision Type

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#200]
It'd be nice to have. I have a need for it, so I'm gonna look into it.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR submitted!

**Comment by rafcolson** [comment]
Nice!

**Comment by SolarLune** [comment]
Thanks!

Tweaked it to remove some extra unnecessary imports that I made in the process of writing it. :|

**Comment by SolarLune** [comment]
Cool, it's been merged. Thanks! PR closed.
