### ISSUE TITLE
Dev: python script for replacing BDX add-on repo

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#203]
So when we are developing BDX we often have to re-install the BDX add-on. After a while I got tired of clicking, so some time ago I wrote a simple Python script that, if run, does the following:

If BDX is installed, it will uninstall and close Blender, else it will install BDX from the specified location and close Blender.

```python
import bpy

addon = "bdx"
path = "D:/BLENDER/BDX/development/GitHub/bdx/blender/bdx.zip" # path of your add-on repo

addons = bpy.context.user_preferences.addons.keys()
if addon in addons:
    bpy.ops.wm.addon_disable(module=addon)
    bpy.ops.wm.addon_remove(module=addon)
    bpy.ops.wm.save_userpref()
else:
    bpy.ops.wm.addon_install(filepath=path)
    bpy.ops.wm.addon_enable(module=addon)
    bpy.ops.wm.save_userpref()
bpy.ops.wm.quit_blender()
```

So you're actually two mouse clicks away from creating a new project with your BDX repo.

I'd like to share this somewhere in the Wiki. So could I do that, maybe under "BDX Engine Dev" ?

**Comment by GoranM** [comment]
Actually, there's no need to re-install the add-on, assuming you set up the proper symlinks to relevant directories in the github repo:

https://github.com/GoranM/bdx/wiki/Building-BDX#streamlining

**Comment by rafcolson** [comment]
Again something I missed along the way. Thanks! I'll check it out.
