### ISSUE TITLE
Dev: use command line to build BDX add-on repo

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#204]
For Windows users you can easily make a small application to automatically build your BDX repo. Of course you need *ant* for this.

To make the application you add a new shortcut. Give it a target: ```C:\Windows\System32\cmd.exe /k ant``` Then, in the properties, change the path to start in into the path of your bdx repo. In my case this is: ```D:\BLENDER\BDX\development\GitHub\bdx```

Now your repo will be build in one mouse click.

Would this also be useful to put in the "BDX Engine Dev" section?

**Comment by GoranM** [comment]
I would assume that most developers will use a terminal to run build commands, as opposed to "desktop shortcuts", but, in either case:

I don't think that teaching the basics of Windows, or any other operating system, is something that belongs in the BDX wiki.

**Comment by rafcolson** [comment]
Yes you're right.
