### ISSUE TITLE
Dev: need some help with creating a scene

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#205]
Hi guys, not sure I could post this at GitHub. Tried at reddit, but couldn't find appropriate code tags.

I'm trying to write the code for the Profiler scene. But I'm getting an error on line 37: ```modelBatch.begin(orthoCam);```

Could someone help me with this please? If I could just get this simple scene to run independently, then I think I can manage the rest myself.

Thanks!

```java
package com.nilunder.bdx;

import java.util.ArrayList;

import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.g3d.Material;
import com.badlogic.gdx.graphics.g3d.attributes.ColorAttribute;
import com.badlogic.gdx.graphics.g3d.utils.ModelBuilder;
import com.badlogic.gdx.graphics.VertexAttributes.Usage;
import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.graphics.g3d.ModelBatch;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.math.Matrix4;
import com.badlogic.gdx.Gdx;

public class ProfilerScene{
	private static Material barMaterial;
	private static Model barModel;
	private static ModelInstance barModelInstance;
	private static OrthographicCamera orthoCam;
	private static ArrayList<ModelInstance> modelInstances;
	private static ModelBatch modelBatch;
	
	public static void init(){
		orthoCam = new OrthographicCamera(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		barMaterial = new Material(ColorAttribute.createDiffuse(1, 1, 1, 1));
		barModel = new ModelBuilder().createRect(0,0,0, 1,0,0, 0,1,0, 1,1,0, 0,0,1, barMaterial, Usage.Position);
		barModelInstance = new ModelInstance(barModel, new Matrix4().setToTranslation(0, 0, -5));
		modelInstances = new ArrayList<ModelInstance>();
		modelInstances.add(barModelInstance);
		modelBatch = new ModelBatch();
	}
	
	public static void update(){
		Gdx.gl.glClear(GL20.GL_DEPTH_BUFFER_BIT);
		modelBatch.begin(orthoCam);
		modelBatch.render(barModelInstance);
		modelBatch.end();
	}
}
```

**Comment by GoranM** [comment]
There should be no need to use the libgdx api directly; The profiler scene could just be a regular BDX scene.

**Comment by SolarLune** [comment]
So the scene would be packaged in the scenes resource directory, along with the actual game scenes that BDX exports?

P.S. How's that vertex normal export addition going, Goran? I think we'll need it to do fog or lighting or whatever, right?

**Comment by rafcolson** [comment]
>There should be no need to use the libgdx api directly; The profiler scene could just be a regular BDX scene.

I honestly believe the script for the profiler scene wouldn't be larger than 60 or 80 lines. I think it's worth considering not to use external files for this one.

I was hesitant to use the normal BDX scene, because 95% of the code we don't need for the profiler scene. No use for bodies for example.

Please, could you help me on my way, so I could show you what I mean? The profiler scene would only consist out of text and white planes, organized according to the content of Bdx.profiler.

**Comment by GoranM** [comment]
> I honestly believe the script for the profiler scene wouldn't be larger than 60 or 80 lines. I think it's worth considering not to use external files for this one.

Shipping an extra resource file is much easier/simpler than creating a custom scene class for the profiler.

> The main reason is that I want to create a scene that will cost the least in performance as can be.

The performance characteristics of a scene are not fixed - They depend on content, so if the scene only contains a few Text objects, the cost should be negligible.

> So the scene would be packaged in the scenes resource directory, along with the actual game scenes that BDX exports?

Yes. I think that would be the most straightforward way.

> How's that vertex normal export addition going, Goran?

It's done - check the commit log.

**Comment by SolarLune** [comment]
> It's done - check the commit log.

Cool, I'll start work on some more stuff then!

**Comment by rafcolson** [comment]
Okay. I will expand from the Scene class then.
