### ISSUE TITLE
Suggestion: Compound Physics Type

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#207]
Hey, there. I think I could also make use of compound physics, so I'm going to take a look into that.

UPDATE: I think I have it working fairly satisfactorily. It works with parenting both in Blender as well as in-game. Parenting and de-parenting updates the compound meshes as expected. Multiple compound objects can also be parented together to form a larger compound object with no problems (as far as a bit of testing shows).

A problem I do see, though, is that it seems like this doesn't adjust the center of mass for the object when multiple objects are parented. I'm not quite sure how to best approach this so that it reacts accordingly. I see that there's a center adjustment function on the GameObject's body (parent.body.setCenterOfMassTransform). EDIT: Ah, it doesn't seem to be what this function does. Seems like I might have to take an alternative approach.

Should the center of mass be the average center point between all objects? Should it take into account the actual objects' respective sizes? What about their mass amounts? Or is it not really worth it? It doesn't seem to me like it's updating, but maybe Bullet's doing things behind the scenes and my test is just skewed...? Any thoughts?

UPDATE 2: After doing some reading, it would appear that Bullet has no knowledge of the center of mass point for objects and doesn't do anything regarding it. So I think I'll have to update it.

**Comment by GoranM** [comment]
I would assume that bullet has some facilities to create compound objects, which would account for all the relevant attributes (position, mass, etc).

I have yet to research any of this, so, at this point, your guess is as good as mine.

As long as the PR is not too involved, and it works, I'll merge it.

**Comment by SolarLune** [comment]
OK. I think I managed to get everything but adjusting the center-of-mass to work. I'll submit a PR after the physics bug I just reported is resolved, as that solution will probably touch the same files in the same places I'm working with.

**Comment by SolarLune** [comment]
Cool, that was merged. PR submitted.

**Comment by SolarLune** [comment]
Thanks for the merge. Issue closed.
