### ISSUE TITLE
Suggestion: Filter Stack

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#210]
Hey, there. 

I'd like to work on filter stacks now, I think; seems like it'd be useful to have. The idea is that each Scene just has an ArrayList of Filters, and you can directly work with them from there to add a filter, re-order a filter, or whatever (Scene.filters.add, Scene.filters.set, etc). 

The new implementation should render the same as the scene filter system works now, in how each scene's filter captures the scenes below it.

**Comment by GoranM** [comment]
> The new implementation should render the same as the scene filter system works now, in how each scene's filter captures the scenes below it.

I would agree that Scene.filters should be applied in order, to accumulated results of previous filter passes on that scene. However, as I stated in #211, I'm not sure if it's wise to include the rendered results of underlying scenes in that process.

This is something that we need to clear-up before doing anything else.

**Comment by SolarLune** [comment]
Cool, that was ironed out, so I submitted a PR for the filter stack.

**Comment by SolarLune** [comment]
PR Merged. Thanks! Issue closed.
