### ISSUE TITLE
Bug: 2D Filters Don't Affect Lower Scenes

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#211]
Hey, there. So, 2D filters don't affect the lower scenes anymore (i.e. apply a filter to an "overlay" scene, and the lower scene is unaffected). 

I'll see if I can fix this and add it in to the 2D filter improvement commit.

EDIT: This seems like it might be a bit involved, so I might set this up as a separate commit.

**Comment by GoranM** [comment]
I was under the impression that this was desired behavior ...

I don't think we can assume that users want filters in overlay scenes to affect the rendered output of the scenes below. Actually, I can't say that I really understand the utility of that process.

Why would you prefer to have overlay filters which affect underlying scenes? What is the overall effect that you wish to implement?

Anyway, as it stands now, the code seems pretty clear: The scene is drawn to an offscreen buffer, and that buffer is drawn, with an applied filter, to the main render buffer. The offscreen buffer is then cleared, to be used for a different scene.

There is no filter acting on the main render buffer itself, so, naturally, the previously rendered scenes are not affected.

I wouldn't really classify this as a bug - More of a misunderstanding.

**Comment by SolarLune** [comment]
I was under the impression that it wasn't; that it was supposed to work like the BGE's filter system did. I like the idea that each scene is rendered with its filters independently, as it gives the most control. 

However, it's also the more inefficient system, since you have to run another filter on each scene that you want to have an effect (i.e. if you want to blur the entire game, you have to blur each scene, rather than blur the GUI scene only). On desktop, this isn't too bad, but I'd imagine it'd be a gamebreaker for mobile platforms where framebuffer usage might already be rather intensive. 

Perhaps an ability to switch between these two modes would be something to put on the TODO list for eventual inclusion.

**Comment by GoranM** [comment]
I think it would be best to have Bdx.filters, which would be applied to the final rendered image.

**Comment by SolarLune** [comment]
Hm, okay, that sounds like a pretty good compromise. I can work that into another commit another time (if I remember, haha).

Thanks, issue closed.
