### ISSUE TITLE
Suggestion: Additional Built-in Uniforms for Filters

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#214]
Hey, there. I know we should be careful to keep the engine light, but I think we could stand to have a couple of additional uniform values for Filters.

I think it'd be nice if there was a "u_bufferTexture" uniform property that links to the texture rendered from the previous frame. It'd be useful for blurring, fog, and ghosting effects, I think.

A "time" uniform that just links to BDX's time property would be nice as well, since a lot of GLSL shaders rely on passing time.

**Comment by GoranM** [comment]
> I think it'd be nice if there was a "u_bufferTexture" uniform property that links to the texture rendered from the previous frame. It'd be useful for blurring, fog, and ghosting effects, I think.

I don't see how it would be useful for blurring, or fog. I'm not really sure what you mean by "ghosting effects".

> A "time" uniform that just links to BDX's time property would be nice as well, since a lot of GLSL shaders rely on passing time.

That sounds fine.

**Comment by SolarLune** [comment]
> I don't see how it would be useful for blurring, or fog. I'm not really sure what you mean by "ghosting effects".

I meant like motion blur, or a soft fading effect. This GLSL sandbox is what gave me the idea, since it's not really something that the user would be able to easily patch into the filter: http://glslsandbox.com/e#23433.10

**Comment by GoranM** [comment]
Ok, but I'm not really sure if "u_bufferTexture" is the best name - Why not "lastFrame"?

**Comment by SolarLune** [comment]
"lastFrame" is fine; I thought "u_bufferTexture" because the default texture uniform name LibGDX provides for the first texture is "u_texture". So, I thought keeping with that convention would be a good idea.

**Comment by GoranM** [comment]
If following the convention has clear, and significant benefits, then it would but a good idea, but not otherwise.

**Comment by SolarLune** [comment]
Uh, it's just a name. There's no benefits other than being different; either one is clear and easy to understand, so I don't really mind either way. 

I don't really see the need to have a separation between "how we do things" and "how LibGDX does things". If the user's going to see "u_texture" in their shader, seems like "u_bufferTexture" tells you pretty much everything you need to know - it's the buffered version of the texture that you already have. "lastFrame" is equally descriptive, but it doesn't tell you implicitly that it's the same as "u_texture". But like I said, I don't really mind; it's up to you.

**Comment by GoranM** [comment]
> Uh, it's just a name.

In programming, names matter.

> If the user's going to see "u_texture" in their shader, seems like "u_bufferTexture" tells you pretty much everything you need to know - it's the buffered version of the texture that you already have.

Without previously established context, I would have no idea what "the buffered version of the texture that you already have" actually refers to. I mean, given that I can have a variety of different textures, all stored in their own buffers, "u_bufferTexture" seems like a completely generic name that could refer to any one of them.

"lastFrame" is the last frame.

> it doesn't tell you implicitly that it's the same as "u_texture".

You mean "explicitly", right?

I don't think this kind of "hungarian notation" is particularly useful, especially in a typed language, because it's just repeating information already present in the type system (uniform sampler2D).

The type is obvious, from both the declaration, and use context: If you understand what texture2D takes for arguments, you don't need a "u" prefix or a "texture" label to know what you're dealing with.

**Comment by SolarLune** [comment]
> You mean "explicitly", right?

No, I meant "implicitly".

Like I said, I don't care - "lastFrame" is fine. 

I'll see if I can make some headway into it; it seems like getting the non-processed texture for the current scene from the last frame will involve some greater framebuffer shuffling.

**Comment by GoranM** [comment]
> No, I meant "implicitly".

Implicitly means: "in a way that is not directly expressed" - The "u_" prefix is an explicit reference to a uniform; there's nothing "indirect" about that.

> non-processed texture for the current scene from the last frame

I don't really understand what you mean here.

The "lastFrame" should simply be the last rendered frame (the final output that was actually visible on-screen), not a "non-processed" version of that.

**Comment by SolarLune** [comment]
> Implicitly means: "in a way that is not directly expressed" - The "u_" prefix is an explicit reference to a uniform; there's nothing "indirect" about that.

Never mind.

> The "lastFrame" should simply be the last rendered frame (the final output that was actually visible on-screen), not a "non-processed" version of that.

After finally getting it to work, I found that the non-processed texture is just a single frame, which isn't very useful, hah. I ended up making it the last rendered frame for that scene.

PR Submitted.

**Comment by SolarLune** [comment]
PR merged in; thanks. Issue closed.
