### ISSUE TITLE
Bug: Parented Objects Stop Reporting Collisions

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#216]
Hey, there. So if you parent an object, it will stop reporting collisions if it's not in collision with any object other than its parent after about a second. If you remove that parenting link, it's fine.

Attached is a simple test blend file.

https://www.dropbox.com/s/2nwhus4nw6r96p0/sensorParentingBugPacked.blend?dl=0

I'm guessing it's related to the fix for bug #208, as it only happens with parented objects, regardless of collision type. Also, in a similar manner to that bug, using "body.activate(true)" fixes it, but only for sensor type objects.

**Comment by GoranM** [comment]
I'm not sure, but I suspect that setMassProps is wiping the flags. I'll have to research that further, but for now, transform can simply force activate.

**Comment by SolarLune** [comment]
Cool, I'll try it when I can. Getting the same build error as Raco's getting in #221, it seems.

**Comment by SolarLune** [comment]
Hey, this seems to have solved the issue. Thanks, issue closed.
