### ISSUE TITLE
Suggestion: Capsule Bounds

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#218]
Hey, it'd be nice to have the capsule collision bounds type implemented. I have a character who needs to walk up stairs, and I think the capsule type would help a lot (though I know it's possible to do myself with a mesh and convex hull collision bounds). I'll look into it.

**Comment by GoranM** [comment]
If you want to implement a bound that bullet supports, feel free to do so (you don't have to make suggestions for that).

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR Merged. Thanks! Issue closed.
