### ISSUE TITLE
Bug: Sphere Collision Type Incorrect Size

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#219]
Hey, there. 

So the Sphere collision type gives an incorrect size; I think it's due to mesh.calculateRadius returning a wrong value in Bullet. It's returning a radius of 1.131 for a block that's 2 BU tall and .75 BU wide and deep. Maybe it's testing the wrong axis or something, I dunno.

A simple solution would be to use half of the largest value for Sphere (which is how it's visualized in Blender).

**Comment by GoranM** [comment]
I can't reproduce.

Can you please make a demo that clearly shows the nature of the issue?

**Comment by SolarLune** [comment]
I'm kinda surprised you can't reproduce it. Here's a demo blend file.

https://www.dropbox.com/s/0fhioebvr7yp92q/spheretestpacked.blend?dl=0

- In the demo, the cube with Sphere bounds type doesn't sit on the ground. 

- Printing out the object's modelInstance.model.meshes.first().calculateRadius() (which is what Bullet.java uses to calculate the radius of the sphere collision shape) returns 1.7320508, even though the cube is 2x2x2, and so the radius of its sphere collision object should just be 1.

**Comment by GoranM** [comment]
> Basically, I'd expect a sphere inside of the cube in the demo; I think it's returning a sphere that can contain the cube in the demo.

Yea. It makes sense for a collision shape to contain the mesh.

**Comment by SolarLune** [comment]
I don't know about it making sense; it's a way to go. Just as equally as a collision shape being inside the mesh.

The main problem seems to stem from the fact that the visualization in Blender shows the collision shape inside the mesh. That means you have no real indication of where the collision mesh is; even worse when the shape is complex (Blender shows the capsule inside the object when it would really be surrounding the object, if I were to make the capsule "correctly"). It's probably best to just use the maximum value of the width, depth, or height of the bounds of the object rather than to actually get the shape that should "contain" the object.

**Comment by GoranM** [comment]
If you want to export and use the bound values, I think that would be fine.

**Comment by SolarLune** [comment]
I don't think that's necessary - just getting the bounding box and using half of the maximum amount out of all of the axes should be fine, right?

PR Submitted.

**Comment by GoranM** [comment]
> I don't think that's necessary - just getting the bounding box and using half of the maximum amount out of all of the axes should be fine, right?

That still has the potential to be confusing, because it's not guaranteed to match the bounds visualization in blender.

But, if that's fine with you, than I'm ok with it.

**Comment by SolarLune** [comment]
> That still has the potential to be confusing, because it's not guaranteed to match the bounds visualization in blender.

How so?

**Comment by GoranM** [comment]
Oh, I confused the hull with the little radius visualization visible in wire-frame mode.

Never mind.

**Comment by SolarLune** [comment]
Ah, yeah, that's also visible. Anyway, thanks for the merge!

Issue closed.
