### ISSUE TITLE
Installation & setup problems

### ISSUE THREAD

**Issue by xaccrocheur** [GoranM/bdx#222]
Hi; I followed [the installation tutorial](https://www.youtube.com/watch?v=NQbtNYwRkwI) and hit a few bumps. I'm using Blender 2.74RC3 on GNU/Linux Ubuntu 14.0 64 Bits. My JDK is 

```java -version 
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)```

I had trouble at first, when creating the BDX project, because the `local.properties` file was referencing an imaginary SDK located somewhere in my `~/.local/Trash` path.

Where I am now, is that I can create the project, only not without errors:

```
found bundled python: /home/px/Downloads/blender-2.74-rc4-linux-glibc211-x86_64/2.74/python
Android SDK location '/home/px/.local/share/Trash/files/daypatrol.2/android-sdk' doesn't contain an SDK
Executing '/home/px/tmp/BDXDEV/daypatrol/gradlew clean'
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> The SDK directory '/home/px/.local/share/Trash/files/daypatrol.2/android-sdk' does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.745 secs
read blend: /home/px/tmp/BDXDEV/daypatrol/blender/game.blend

```

And, see? The android SDK is still in referenced as being in the trashcan..? BUT I can see Sacky :) AND I can launch the game, only it kills Blender dead.

I made numerous other tests, using various versions of Blender ranging from 2.69 to 2.74RC3, but this is as close as I got.

EDIT Now I broke everything; I tried to delete my ~/.config/blender/2.74/ but now I can't activate BDX anymore, after I "install from file" I get

```reloading addon: bdx 1427673904.3953106 1427674191.1392953 /home/px/.config/blender/2.74/scripts/addons/bdx/__init__.py
Modules Installed from '/home/px/Downloads/BLENDER/bdx.zip' into '/home/px/.config/blender/2.74/scripts/addons' ()```

But upon clicking "activate":

```
Traceback (most recent call last):
  File "/home/px/.config/blender/2.74/scripts/addons/bdx/ui.py", line 27, in draw
    if ut.in_bdx_project():
  File "/home/px/.config/blender/2.74/scripts/addons/bdx/utils.py", line 103, in in_bdx_project
    return p.isdir(p.join(project_root(), "android", "assets", "bdx"))
  File "/home/px/.config/blender/2.74/scripts/addons/bdx/utils.py", line 19, in project_root
    return p.abspath(root)
  File "/home/px/Downloads/blender-2.74-rc4-linux-glibc211-x86_64/2.74/python/lib/python3.4/posixpath.py", line 361, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

location: <unknown location>:-1

location: <unknown location>:-1

```

Is there another place I should look for (Besides the downloaded 2.74 Blender archive addons dir, and the one in my ~/.config) in order to start from scratch?

BTW DBX is really impressive, thanks.

**Comment by GoranM** [comment]
When the project is created, it's going to say BUILD FAILED if you didn't specify a path to the android sdk (by default, it is set to your current working directory), but that only means that the android project failed - everything else should work fine, as I demonstrated in the video.

> I tried to delete my ~/.config/blender/2.74/ 

Did you actually delete it?

**Comment by xaccrocheur** [comment]
> Did you actually delete it?

Maybe not, because I just re-tried and now I can install BDX again, activate it and open the test game file, but when I try to launch it, Blender freezes.

Is it a java problem? what can I do to get information about what is going on?

**Comment by GoranM** [comment]
When you start the game, blender will freeze (that's normal), and the game should start running in a different window (as demonstrated in the tutorial). If that new window doesn't become immediately visible, it might be in the background somewhere.

What kind of window manager are you using? Do you have something like a taskbar, where you can see all existing application windows?

Assuming you can find, and switch to that window, you'll be able to play the game there. When you close that window, blender will unfreeze, and you'll be able to edit the scene.

I don't think this is a java problem.

Is the "suspended" message something that you initiated, or is it something that happens automatically when you start the game?

**Comment by xaccrocheur** [comment]
> Is the "suspended" message something that you initiated, or is it something that happens automatically when you start the game?

YES! IT WORKS NOW (oops sorry I yelled, I'm quite excited) your question put me on tracks: I launch all my programs in a sub-shell (the & at the end) to regain control afterwards w/o having to lanch a second shell, and BDX (or maybe only Blender... But it never did that in years... Wait, maybe it did, come to think of it... Oh well) somehow doesn't like that. By launching Blender in its own shell, I get my test game, and when I press p the console says:

```
------------ BDX START --------------------------------------------------
 
Configuration on demand is an incubating feature.
:core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:core:processResources UP-TO-DATE
:core:classes
:core:jar
:desktop:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:desktop:processResources UP-TO-DATE
:desktop:classes
:desktop:run

BUILD SUCCESSFUL

Total time: 25.365 secs
 
------------ BDX END ----------------------------------------------------
```

Thank you very much for your patience & guidance, Goran

Phil "xaccrocheur" CM
