### ISSUE TITLE
Scene Restart Prints Line

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#226]
Hey, there. So, requesting a scene restart prints out a line that says that a restart was requested. I assume this was for debugging purposes while the engine was still in early development and never taken out.

**Comment by GoranM** [comment]
Oh, yea, feel free to take that out.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR merged, issue closed. Thanks.
