### ISSUE TITLE
Gamepad() throws due to empty controllers array

### ISSUE THREAD

**Issue by milkotv** [GoranM/bdx#227]
Hi Goran,
I am having the following issue: Gamepad() constructor throws IndexOutOfBounds due to empty Controllers array being dereferenced. 
Could you please advice ?

Thanks

**Comment by GoranM** [comment]
This was a bug.

It should be fixed in the latest release (0.1.5).

**Comment by SolarLune** [comment]
So is this fixed?

**Comment by GoranM** [comment]
If you can run BDX without a controller plugged in, and you don't get the same error, then it's fine.

I'm pretty sure it's fine, so I'll close this.
