### ISSUE TITLE
Suggestion: UV Scrolling Component

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#228]
Hey, there. I think I suggested it awhile ago, but maybe it was put on the backburner because BDX was still in an alpha status? Anyway, a UV scrolling component would be nice to have, I think.

**Comment by GoranM** [comment]
Didn't we agree to do that after we make a new vertex interface?

**Comment by SolarLune** [comment]
Ah, yeah, that might have been the outcome. OK, that answers this issue, then. Closed.
