### ISSUE TITLE
About Mist

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#229]
Hey, there. So I've tried to get mist up and running in BDX, and got almost all of it working, but I was never able to get mist / fog to show up. I'm wondering if there's something that BDX is missing in exporting the meshes that's keeping it from working? Seems like it relies on depth to work - is LibGDX polling a camera that's never moving for its depth buffer or something? 

(As a side-note, I was able to get ambient light coloring working fine.)

**Comment by GoranM** [comment]
> I've tried to get mist up and running in BDX, and got almost all of it working, but I was never able to get mist / fog to show up.

I'm not sure what you mean by "almost" - Is there a way to get mist/fog to work partially?

Either it shows up, and it works, or it doesn't ... right?

> I'm wondering if there's something that BDX is missing in exporting the meshes that's keeping it from working?

We export everything except vertex color - Does your method for creating fog/mist require that?

> is LibGDX polling a camera that's never moving for its depth buffer or something?

I don't know.

**Comment by SolarLune** [comment]
> I'm not sure what you mean by "almost" - Is there a way to get mist/fog to work partially?

I mean I got almost all of it working - exporting the existing mist color from Blender, rendering the meshes with a new environment, adding an AmbientLight to make them show up. I just could never get the models to visually render with mist; it's just ignored. I've tried just today as well as awhile ago and couldn't manage it.

> We export everything except vertex color - Does your method for creating fog/mist require that?

No, I'm just using the default LibGDX Fog ColorAttribute. As far as I can tell, it should work, so I'm unsure where the issue could lie. I guess I'm missing something basic, because implementing it seems really simple otherwise. 

Perhaps I'll ask on the LibGDX forums in case I'm missing something.

**Comment by portjos** [comment]
Did you ever find the solution to this? I'm also trying to use environment.set(new ColorAttribute(ColorAttribute.Fog etc etc) as per fogtest.java. Like the post above, ambient light is visible but not the fog.

**Comment by SolarLune** [comment]
Hey, there! No, I never figured it out; it must be something we're missing. In the meantime, it would seem that it might be possible to use custom shaders to support fog, but I'm not 100% sure.

**Comment by portjos** [comment]
Thanks for responding anyway! Yeah I was going to try that if I can't figure it out, I'll let you know if I solve it!

**Comment by portjos** [comment]
Seems to be the far setting on the camera - setting it further away seemed to thin out the mist too much around my objects. I'm trying to figure a way to set it closer and still have my objects in the distance rendered.

**Comment by SolarLune** [comment]
So you managed to get the mist working? IIRC, there aren't any controls for mist like density or height or anything like that - it's just a straight up "near = 0%, far = 100%" kind of curve.

**Comment by portjos** [comment]
Yeah I know,  it would be very handy to control it. I'm starting to play around with a version of the default vertex shader. There's a section that starts with #ifdef fogFlag and I think the formula of the mist output can be changed in there, tried a few things and it seemed to affect the distance but I'm still experimenting

**Comment by SolarLune** [comment]
Hey, did you ever make any progress on this, @portjos? Or do you mind sharing the code you changed that shows what you did to get mist working?

**Comment by portjos** [comment]
Hey there, yeah i did. I'll take a look at the code when i get home. I think i just took the square root but not sure. Might be a little different for your model though but give it a go.


Sent from my Samsung GALAXY S5

-------- Original message --------

**Comment by SolarLune** [comment]
PR submitted for this.

**Comment by SolarLune** [comment]
PR was merged, so I'll close this now. Thanks!
