### ISSUE TITLE
About Gamepads

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#230]
Yo! I saw that gamepad support and input maps were added into master, which is awesome. I saw, though, that input maps only support buttons and not axes or hats; is this planned to be added? If so, it seems like "ga" would be good for gamepad axes, "gh" for gamepad hats, and "gb" for gamepad buttons. 

Also, perhaps the deadzone for the axes could also be set either on the Gamepad class or on the InputMaps as a static variable? Although, it'd be nice to have it per-gamepad, in case you're designing a multiplayer game and different people have different feels for it.

**Comment by GoranM** [comment]
> input maps only support buttons and not axes or hats; is this planned to be added?

Yes.

Instead of "hats" being some unique input control, I plan to simply create buttons that would map them: "up", "down", "left", "right".

I would do the same for axes, but just prefix the four directions with "la-" for "left axis", or "ra-" for "right axis".

> Also, perhaps the deadzone for the axes could also be set either on the Gamepad class or on the InputMaps as a static variable?

We could have a Gamepad.Axis class, with a deadzone field, and then a `HashMap<String,Axis> axes`, so you can do `Bdx.gamepad.axes.get("left").deadzone = ...`, or something like that.

**Comment by GoranM** [comment]
@SolarLune 

Can we close this now?

**Comment by SolarLune** [comment]
I guess I was waiting until the rest of the inputs are added to the InputMap, but okay. Issue closed.

**Comment by GoranM** [comment]
I'm not really sure what you mean - They should all be available at this point.

**Comment by SolarLune** [comment]
Ah, okay, cool. I didn't notice any commits to InputMaps, so I didn't think it had been done already. Nice! Would you mind updating the API Reference to reflect this (the InputMaps page)?

**Comment by GoranM** [comment]
There was no need to modify InputMaps (neither code, nor documentation), because non-button inputs were "buttonized" (which is documented on the Gamepad api page), so it all works in exactly the same way as before.

**Comment by SolarLune** [comment]
But wait, the InputMaps API page doesn't mention anything about the non-button inputs.

**Comment by GoranM** [comment]
I don't see why the InputMaps API page would need to mention anything about non-button inputs. As far as InputMaps are concerned, there are no "non-button" inputs, because Bdx.gamepad effectively buttonized those, and that's documented on the Gamepad API page.

**Comment by SolarLune** [comment]
I guess I think it might just be a bit helpful to give a couple of Gamepad inputs in that code example to help people grasp that the inputs have been buttonized.

**Comment by GoranM** [comment]
There's nothing different about the InputMaps API, or the code. It's used in the exact same way as before. The Gamepad is the only thing that changed, with the addition of a few extra buttons.

It doesn't make sense for Gamepad informaton to reside on the InputMaps page.

> It'd also be nice if the classes specified linked to the API pages (i.e. Bdx.Keyboard linked to the Keyboard API page).

Yes, that would be nice.
