### ISSUE TITLE
Suggestion: Sorting GameObjects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#232]
Hey, there. It might be nice to have the ability to sort game objects by name inherently (by providing a compareTo() function, I suppose).

**Comment by GoranM** [comment]
In ArrayListNamed?

I'm not sure that this requirement is common enough to justify additional code.

**Comment by SolarLune** [comment]
I thought that the compareTo function would reside in the GameObject, which would be called when you try to sort a list that contains GameObjects...?

**Comment by GoranM** [comment]
There is a Collections.sort that takes a list and a Comparator object. That should enable users to sort a list of arbitrary objects, in whatever way they see fit.

**Comment by SolarLune** [comment]
Yeah, that's true; the user always has the ability to do things as they wish. It just seems logical that if you do a default sort on a list of GameObjects, it'd be sorted by their names (how else would it be done by default?) as opposed to simply not working at all.

**Comment by GoranM** [comment]
> the user always has the ability to do things as they wish

Making this a matter of convenience, and as I said: I'm not sure that this requirement (to sort objects by name) is common enough to justify additional code.

**Comment by SolarLune** [comment]
OK. Issue closed.
