### ISSUE TITLE
Suggestion: Field of View / Orthographic Scale

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#233]
Hey, there. I'm making a 2D game, and I'd like to be able to "zoom in" on the orthographic camera. Would it be possible to add an orthographic scale property on Cameras to allow this? A FOV property for cameras would also be useful for 3D games, since that would allow for cool effects as well.

**Comment by GoranM** [comment]
Yes, that would be useful.

**Comment by SolarLune** [comment]
@GoranM - Cool. I'm not familiar with camera projections and stuff to do orthographic scale, so are you willing to work on it at some point in the future?

**Comment by GoranM** [comment]
Try that.

**Comment by SolarLune** [comment]
Cool, this is great! 

I think there might be something up with the calculation, though - an orthographic scale of 16 in Blender is 9 when fov() is returned, and (naturally) this changes what fov() does when setting a field of view or orthographic scale.

Seeing these numbers, 16 and 9, I wonder if you missed something to do with the aspect ratio? Maybe it's just a coincidence.

**Comment by GoranM** [comment]
The value in blender doesn't seem to represent the actual value encoded in the exported projection matrix; Note that blender fov remains the same even when you change the resolution.

**Comment by SolarLune** [comment]
> The value in blender doesn't seem to represent the actual value encoded in the exported projection matrix;

For usability, even if it's incorrect, it might be worth it for BDX to also be incorrect to maintain usability and parity with Blender (for now, anyway). I don't think most developers would actually calculate FOV settings mathematically to figure out which one they want to go with for a game camera; they'd more probably dial it in with Blender. This isn't that useful if the fov() function doesn't work the same (since you can't alter it in-game without it seeming to "mess up").

Maybe another function or something could be created to use an incorrect FOV value? Or, I guess, submit a patch to Blender's bug tracker to fix it?

**Comment by GoranM** [comment]
> I don't think most developers would actually calculate FOV settings mathematically to figure out which one they want to go with for a game camera

They don't have to: The camera view in blender corresponds to the starting view in BDX.

If you want to zoom-in/out from there, you can simply add to, or subtract from existing fov: `scene.camera.fov(scene.camera.fov() + delta)`

The fact that the actual fov values are different shouldn't matter for that.

> Maybe another function or something could be created to use an incorrect FOV value? Or, I guess, submit a patch to Blender's bug tracker to fix it?

I'm not sure if this is a blender bug, or just the way that blender works.

I'll look into it.

**Comment by SolarLune** [comment]
Okay, thanks. Issue closed. If I have any further questions about this topic, I'll reopen.
