### ISSUE TITLE
Suggestion: Have objects in group inherit instance scale

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#234]
Hey, there. So if you make a group instance and then change the instance's scale, the objects in the group appear to be unscaled. It'd be nice if they changed scale as well.

**Comment by GoranM** [comment]
I guess so.

**Comment by SolarLune** [comment]
Cool. I got the root parent object to be scaled by scaling it in the clone() function, like so:
```java
private GameObject clone(GameObject gobj){
		String instance = gobj.json.get("instance").asString();

		GameObject inst = gobj;
		if (instance != null)
			gobj = templates.get(instance);

		GameObject g = cloneNoChildren(gobj);

		for (GameObject c : gobj.children){
			GameObject nc = clone(c);
			nc.parent(g);
		}

		if (instance != null){
			g.position(inst.position());
			Matrix3f ori = inst.orientation();
			ori.mul(g.orientation());
			g.orientation(ori);
			g.scale(inst.scale());
						
			g.props = new HashMap<String, JsonValue>(g.props);
			g.props.putAll(inst.props);

			for (GameObject c : inst.children){
				GameObject nc = clone(c);
				nc.parent(g);
			}
		}

		return g;

	}
```

However, children of the root object aren't offset correctly like they appear in Blender. They just position themselves like they would be if the object weren't scaled. Are objects positioned or transformed initially somewhere else after the clone function is run?

**Comment by GoranM** [comment]
> Are objects positioned or transformed initially somewhere else after the clone function is run?

Not to my knowledge.

**Comment by SolarLune** [comment]
Hm, I guess I was just mistaken the first time I tried to do this. Got it working. PR submitted.

**Comment by SolarLune** [comment]
This was merged in, so issue closed. Thanks!
