### ISSUE TITLE
Suggestion: GameObject.components.get() Component Class

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#236]
Hey, there. I think it'd be useful to have a get() function in the components list that allows you to get a component by a specific class (i.e. components.get(Halo)). The only way it seems to be possible to do this currently would be to store references in the GameObject and pull them from there, but that's not always possible (like in my current case).

**Comment by GoranM** [comment]
> but that's not always possible (like in my current case).

What case, specifically?

**Comment by SolarLune** [comment]
I have a PlayerControl component (that extends from Component) that exists in a separate file from the Player. Its GameObject reference doesn't point to the Player, but rather a GameObject that is the Player (so I can't access Player-specific code). Basically, "g" is hardwired to be a GameObject, not an instance of the Player class, and I'd rather not do some "hack" to create a Player specific variable in the PlayerControl component. 

I thought the idea was for components to be re-useable - it doesn't work as well if you program them to work with one kind of object.

Some sort of messaging system might also help with this.

**Comment by GoranM** [comment]
> I thought the idea was for components to be re-useable

They are, for objects that can actually use them.

If PlayerControl requires access to Player specific fields/methods, it is a Player specific component - You can't expect to use it on objects that don't actually support the requirements.

> Basically, "g" is hardwired to be a GameObject, not an instance of the Player class, and I'd rather not do some "hack" to create a Player specific variable in the PlayerControl component.

I don't see how a "messaging" system, or your original suggestion, would actually resolve that issue ... Seems like you're jumping to a completely different topic here.

If that's really your core issue - having to cast to a specific type  - then maybe you should change the topic title to something more relevant.

That said: We could employ generics to have `Component<T extends GameObject>`, where T could be specified on extension, to make `g` the proper type.

**Comment by SolarLune** [comment]
> If PlayerControl requires access to Player specific fields/methods, it is a Player specific component - You can't expect to use it on objects that don't actually support the requirements.

It doesn't. It requires data from another component. Thinking about it now, I can pass that other component as a reference to the PlayerControl component.

 >I don't see how a "messaging" system, or your original suggestion, would actually resolve that issue ... Seems like you're jumping to a completely different topic here.

Well, I wouldn't need a hardwired dependency on a Player class, I could just get a component if it exists, or check for a message, if it was sent. The PlayerControl component would then at least work on all objects, even if it would need other components to work correctly. I think ideally, there wouldn't be a "Player" class at all; just the normal GameObject classes as a container for components, and a way to set the relevant components on the game objects (so the Player object is just a default GameObject with Player-related components). It might also be worth it to keep in mind to add this "component adding" functionality to the planned Blender panel.

Casting might also work.

Employing generics sounds like it might be a good idea, though I don't quite see how that would work. If you specify the type on extension of the Component, doesn't that mean that it's no longer generic to GameObjects, but rather becomes specified to the type of GameObject (Player, Enemy, etc)?

**Comment by GoranM** [comment]
> It doesn't.

You said:

> I can't access Player-specific code

... I guess I don't really understand the fundamental problem that you're trying to solve.

> It requires data from another component. Thinking about it now, I can pass that other component as a reference to the PlayerControl component.

Yes, if one component depends on another, I think it's a good idea to make that explicit.

You can watch me do that in my tutorial series: https://www.youtube.com/watch?v=7rNA94YtOMo#t=11m16s

> If you specify the type on extension of the Component, doesn't that mean that it's no longer generic to GameObjects, but rather becomes specified to the type of GameObject (Player, Enemy, etc)?

If the component requires access to a specific extension of the GameObject class (like Player, Enemy, or whatever), it is a component specific to that class - It can't be "generic to GameObject" ...

Extending from `Component<Player>` would enable access to player specific fields/methods from the existing `g` reference, so you don't have to cast it to Player, or make an additional reference (I thought that was your core problem, but it seems that I misunderstood).

**Comment by SolarLune** [comment]
OK, I wasn't clear enough in my original post. 

It boils down to one component checking a field from another. Giving and holding component references works okay, but a simple function on the GameObject to easily get an existing component seems like it'd be a good idea to add.

**Comment by GoranM** [comment]
> Passing component references into the components' constructors works okay

It also makes component dependencies explicit, which contributes to overall clarity.

> a simple function on the GameObject to easily get an existing component seems like it'd be a good idea to add

Why does that seem like a good idea?

**Comment by SolarLune** [comment]
I don't know, it just seems like something that would be in this kind of system. Having a component system with no direct way to get a component seems odd, as a user might not always want to pass references and create local variables to "know about" other components.

**Comment by rafcolson** [comment]
I guess it makes sense to automatically store references to components in ```g.components``` when adding those, instead of having the user do this manually in ```g``` or somewhere else. And there's no doubt references are necessary in many cases.

Also, I naturally assumed those references where already stored in ```g.components```. But I wondered how to actually get them. By class seems the most straightforward way.

**Comment by SolarLune** [comment]
So I'm making a game with components, and I'm trying to do a "TouchDamage" component that decreases the Health component of other objects that it touches if they have a Health component. 

This being the case, it'd be nice not to have to loop through each component in each object to see if it has a Health component. Is there another way to do this that is more elegant than a get() function?

**Comment by GoranM** [comment]
I think that would justify the addition.

**Comment by SolarLune** [comment]
OK, so it seems like one can't pass an actual class directly into a function (like, `components.get(Halo)`). It seems like the options would be to either go with the class object (`components.get(Halo.class)`), or go with the name of the class (`components.get("Halo")`). Am I correct?

**Comment by SolarLune** [comment]
Well anyway, I submitted a PR for how I did it using the name of the class, rather than the class "object" itself. The limitations here is that it won't work for multiple instances of the same type of component (not a huge deal), and that it won't work for multiple instances of different components with the same name (i.e. mycomponents.Halo and bdx.components.Halo or whatever), I think.

**Comment by SolarLune** [comment]
PR merged, issue closed. Thanks for the review.
