### ISSUE TITLE
Suggestion: Gamepad buttons shouldn't be capitalized

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#237]
Hey, there. It seems like the Gamepad buttons are capitalized ("X", "Y", etc) from looking at the API reference. I'd think having everything be lower-case would be wise, since every other input constant already is.

**Comment by GoranM** [comment]
It seemed sensible to mirror labels on the actual gamepad, for buttons that have them.

If you want to change it to lower case, I'm ok with that.

**Comment by SolarLune** [comment]
Well, most keyboard keys are capital letters, not lower-case, so it should extend to keyboard keys as well if you wanted to do it that way.

I guess I don't mind leaving it the way it is, though.

**Comment by SolarLune** [comment]
This ended up bothering me still, so I'm reopening and submitting a PR to fix it.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR merged. Issue closed. Thanks!
