### ISSUE TITLE
Bug: missing text object "shadeless" attribute

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#241]
Hello,

If the project contains a text object BDX will fail at [```Bdx.scene.init()```](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L143).

I'll create a PR for this.

**Comment by GoranM** [comment]
Good catch.

Thanks!

**Comment by rafcolson** [comment]
You're welcome. I stumbled into this working on the Profiler scene. Thanks for the merge.
