### ISSUE TITLE
Text Is Always Shadeless?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#245]
Hey, thanks for fixing that bug, @rafcolson. I noticed, though, that the Text's material always is set to shadeless under the hood - should this be the case? Seems like a user might want to light dynamic text sometimes (i.e. for flashy, "immersive" GUI stuff)?

**Comment by rafcolson** [comment]
You're probably right. While you're adjusting this, could you also maybe check if there are no errors with objects or text without a material? Because I remember getting an exception with text without a material.

**Comment by SolarLune** [comment]
There shouldn't be any errors if objects (text or otherwise) don't have materials now. 
Material-less objects can be shadeless, as well.
PR submitted.

**Comment by SolarLune** [comment]
PR merged, so issue closed! Thanks!
