### ISSUE TITLE
Question: formatting Text

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#248]
Hello guys,

I've searched all over the Java docs, tried several stuff, but couldn't actually reproduce a table view for the profiler display. For example, I have something like this now for every category:
```text.set(String.format("%-10s %4.1f %4.1f", categoryName, millis, percent));```

How could I make it so all ```millis``` and ```percent``` will end at the same place horizontally?

I'm sorry if this is a newbie question.

Thanks

**Comment by GoranM** [comment]
Try `%04.1f`

**Comment by rafcolson** [comment]
I'm guessing that the default font type is the problem here.

**Comment by GoranM** [comment]
Well, it's not a monospaced font, so it's not going to align perfectly.

You could use two text objects per line: One for category names, and the other for the actual numbers.

**Comment by rafcolson** [comment]
Could I add an open font, such as [Consolas](http://en.wikipedia.org/wiki/Consolas)?

**Comment by GoranM** [comment]
It seems like it would be easier to just have extra objects, but if you really want to include a new font, I'm ok with that.

**Comment by rafcolson** [comment]
I don't know how to include a new font, so I've made the extra objects. Thanks.
