### ISSUE TITLE
Suggestion: reduce file size of default game.blend

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#252]
It's just a suggestion. It could be reduced with about 530K. (so it's 94K). I left out a couple of Screen Layouts too:
- Compositing: BDX doesn't use nodes
- Default: Quite the same as BDX Layout
- Game Logic: BDX Layout now includes Game Properties Panel
- Motion Tracking: Not applicable
- Scripting: Text Editor for java files in BDX Layout

I mimicked the rest of the Screen Layouts with some slight adjustments to the 3D View Properties panel.

It's not really necessary, but I think it would be preferable. I personally prefer to work with small files. Also it will enable to upload most small blend files at forums with an upload limit, such as [BlenderArtists](http://blenderartists.org/).

I'll wait for an okay before submitting PR.

**Comment by GoranM** [comment]
Since .blends are binary files, github can't show me a diff of what you changed, but assuming that you simply removed redundant views, I think that would be fine.

**Comment by rafcolson** [comment]
I must say that originally this was a modified blend from years ago. I can't remember who, but a user on Blenderartists removed all unnecessary data from it. I never had any problems with it . But I'm not exactly sure what was removed.

**Comment by GoranM** [comment]
Hopefully, we won't have any problems.

Merged.

**Comment by rafcolson** [comment]
Hope so too.
