### ISSUE TITLE
Suggestion: Vector3f.zero() function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#254]
Hey there. A zero() function for Vector3f's (and 2f and 4f's, I suppose) would be nice, as it seems that manually setting the length to 0 can cause NaN components. This is bad, as this causes crashes with the physics engine (which appears unrelated until one tracks down the 0 length setting line). A zero function that manually sets the components to 0 would be helpful for "nullifying" vectors.

**Comment by rafcolson** [comment]
Sounds reasonable.

**Comment by GoranM** [comment]
By "manually setting the length to 0", I assume you mean calling `vector.length(0)`?

Looking at the implementation of that method:

```java
   public final void length(float n){
	   normalize();
	   scale(n);
   }
```

I think the NaNs result from attempting to normalize a zero length vector.

This would probably fix it:

```java
   public final void length(float n){
       if (length() == 0)
	       normalize();
	   scale(n);
   }
```

**Comment by SolarLune** [comment]
^ That doesn't make sense? That's normalizing a zero-length vector?

**Comment by GoranM** [comment]
Obviously a typo. Fixed.

... Even better:
```java
   public final void length(float n){
       if (length() == 0)
           return;
	   normalize();
	   scale(n);
   }
```

**Comment by SolarLune** [comment]
OK, I see, that seems like it'd work well.

**Comment by SolarLune** [comment]
OK, so it looks like you'll have to do this, Goran, as we can't access the vecmath source files.

**Comment by GoranM** [comment]
Done.

**Comment by SolarLune** [comment]
Cool, I'll close this now. If I have any other issues I'll reopen this or open a new issue. Thanks!
