### ISSUE TITLE
About Particle System

### ISSUE THREAD

**Issue by EdwardAngeles** [GoranM/bdx#255]
Is there a way to implement particles? I took a look to the API and I found nothing about it.
In the game "Kiro" by SolarLune, there's a particle effect on the dyamond. How can he do it? Instancies several litles object or something like that?

(I'm learning english, sorry if I make some mistake).

**Comment by GoranM** [comment]
The issue tracker is for bugs, or matters relating to engine development.

General questions about using BDX to develop games should be posted on [r/bdx](http://www.reddit.com/r/bdx)

@SolarLune can answer your question there.
