### ISSUE TITLE
Suggestion: Improvements to States

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#258]
Hey, there. So, one of the things I like about the GDX-AI project is their [state machines](https://github.com/libgdx/gdx-ai/wiki/State-Machine). The ability to switch between states and trigger events on entering and exiting states seem really useful (i.e. starting or stopping timers, incrementing the amount of times a state has been triggered, etc).

I was wondering if it were advisable to add enter() and exit() functions to States, seeing that our implementation actually also is a state machine. This would require a function to change states to trigger them on Components, though, which would be different from the default "direct state variable setting process" that we have now. Also, these additional `enter()` and `exit()` functions would have to be implemented in each extended State, even if they're empty.

**Comment by GoranM** [comment]
> Also, these additional enter() and exit() functions would have to be implemented in each extended State, even if they're empty.

I'm pretty sure we can change State to be a regular class, which would make overrides optional.

Then we could simply add State.enter and State.exit methods (which do nothing by default), and we can add a state method to Component, which will set state:

```java
state.exit();
state = newState;
state.enter();
```

This way, the old methods still work: If people want to simply set state, they can still do that, but if they want enter/exit to be called, they would have to use the new state method.

**Comment by SolarLune** [comment]
Cool, yeah. PR submitted.

**Comment by SolarLune** [comment]
PR merged. Issue closed. Thanks!
