### ISSUE TITLE
Bug: alignAxisToVec Not Working on Objects in Front or Behind

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#259]
Hey, there. So alignAxisToVec isn't working correctly. If the targeted vector is just positive or negative 1 for the Y axis from the calling object, it doesn't align correctly. For example, imagine an arrow directly north of (-Y) a cube. The arrow won't point southward toward the cube correctly. Not sure exactly what the issue is myself; maybe someone else can look into it.

Here's a test blend file to explain it a bit better.

https://www.dropbox.com/s/ezoq9uw3paordyy/alignAxisVecProblem.blend?dl=0

**Comment by GoranM** [comment]
Oh, yeah, I forgot to handle the special cases.

**Comment by SolarLune** [comment]
Yep, that seems to fix it. Thanks! PR closed.
