### ISSUE TITLE
Suggestion: Text.set() support for "\n"

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#260]
Setting a Text object to a String containing a line break "\n" will give an exception, as mentioned in #51.

@GoranM Are you planning to add support for this shortly? It really would come in handy now, as I'm modifying the display of the BDX profiler to only one text object.

**Comment by GoranM** [comment]
The problem in #51 was about a python exception, raised during export. I should have done the same in the actual engine, but I forgot, so, even though it's related, this is a different bug.

All unsupported characters should now be converted to space. In the future, this will change, but it's best to make those changes after the Mesh api; To work properly, and to remove existing code duplication, Text will need to leverage that.

For now, it's ok to just use multiple text objects.

**Comment by rafcolson** [comment]
Okay. thanks.
