### ISSUE TITLE
Suggestion: Export and Run Not Blocking Blender

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#264]
Hey, there. So I think it'd be nice if using BDX to run your game wouldn't block Blender from executing - that way, we could continue to edit the game while the build is running, rather than having to wait until it's finished for Blender to un-freeze and be able to do anything. Is it possible?

**Comment by GoranM** [comment]
It's possible (we could just run the engine in a different thread) but I'm not sure about the overall utility of that, and whether it would justify the additional code complexity.

I mean, do you really need to edit the scene while you play? You're going to have to re-export to see your changes, so you would have to kill the game either way.

**Comment by SolarLune** [comment]
That's true, but for me, running the game can take a bit of time. To be simply waiting when that time could be better spent modeling or whatever seems a bit like a waste.

**Comment by GoranM** [comment]
But the changes that you make while waiting for the game to start wouldn't be visible, because they wouldn't be included in the running export, so what's the point?

Either way: The game shouldn't take that long to start - It should be a few seconds at the most, assuming scenes of moderate complexity.

**Comment by SolarLune** [comment]
> But the changes that you make while waiting for the game to start wouldn't be visible, because they wouldn't be included in the running export, so what's the point?

To not have Blender freeze. That's it.

> Either way: The game shouldn't take that long to start - It should be a few seconds at the most, assuming scenes of moderate complexity.

Well, it's not just one or two seconds on my machine, and those seconds add up if you're tweaking something or fixing a simple error, and seems to multiply with more and more scenes. 

How much more complex would it be to use a thread for the second process? Seems like there should be a way to simply run it in such a way that Blender's not waiting for the process to pass "control" back to it, with subprocess or something.

**Comment by GoranM** [comment]
> To not have Blender freeze.

I don't understand the utility, because the changes you make, while BDX is still exporting, will not be visible when game actually starts.

> How much more complex would it be to use a thread for the second process? Seems like there should be a way to simply run it in such a way that Blender's not waiting for the process to pass "control" back to it, with subprocess or something.

We could just run the gradle task from a different thread (that should be fairly straightforward), but we would also have to write additional code to prevent certain actions that assume we're not in the export process (like the export process itself, and maybe some other things).

The difficulty of implementation is not really the issue - No matter how trivial, additional code increases the overall code complexity of the project, and so, it needs to be justified.

If export is too slow, we need to understand why, so that we can solve the actual problem at hand.

Profiling the "srl_" methods in the exporter would be a good place to start.

**Comment by SolarLune** [comment]
> I don't understand the utility, because the changes you make, while BDX is still exporting, will not be visible when game actually starts.

There is no utility. The changes won't be applied while the game is exporting or running - that's fine. I just don't want Blender to freeze when running BDX. It breaks the flow of development and testing to have the editor freeze.

> If export is too slow, we need to understand why, so that we can solve the actual problem at hand.
> Profiling the "srl_" methods in the exporter would be a good place to start.

Perhaps that would be wise.

**Comment by GoranM** [comment]
> It breaks the flow of development and testing to have the editor freeze.

The details you provided indicate that slow export time is the core problem - If export was fast enough (a few seconds), the state of the editor (during testing) would be irrelevant, wouldn't it?

**Comment by SolarLune** [comment]
> The details you provided indicate that slow export time is the core problem - If export was fast enough (a few seconds), the state of the editor (during testing) would be irrelevant, wouldn't it?

Not quite irrelevant, but the issue would be mitigated. Slow export time is an issue, and perhaps even the main issue here, but Blender freezing when performing an operation isn't great. When we think of what Blender can do already without freezing (rendering scenes, outputting video, etc), I think it'd be nice for BDX to work at a similar level of quality if possible.

**Comment by GoranM** [comment]
Putting aside how blender typically handles rendering tasks, and how we define "quality": Is there any utility in keeping blender active while the game is running, assuming export takes no more than a few seconds?

I mean, if the game is running, you're testing it, right? While you're testing, you're not using blender, so why does blender state matter during that time?

> However, if it's gonna double the code count to do or drastically up the complexity of the code-base, then I suppose it's not important enough to fix.

It's not a bug, and it's not about the size - as I said: No matter how trivial, additional code increases the overall code complexity of the project, and so, it needs to be justified.

**Comment by SolarLune** [comment]
> Putting aside how blender typically handles rendering tasks, and how we define "quality": Is there any utility in keeping blender active while the game is running, assuming export takes no more than a few seconds?

If we can get exporting down to a few seconds max, then it should be fine.

**Comment by GoranM** [comment]
With that in mind, I think it would probably be best to close this issue, and open a new one, with a title that relates to the problem at hand.

A few things that would be helpful there:

* A .blend example where export time is too long.
* Measured execution times for "srl_" functions, relative to the execution time of the export function.

**Comment by SolarLune** [comment]
OK, I'll make a new issue for this particular problem if I find the export times get too long. Thanks.
