### ISSUE TITLE
Discussion: Object Panel

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#265]
Hey, there. 

I think an idea we had at some point was to create a new panel in the object properties panel to allow us a few conveniences? 

As I recall, it would be able to:

- Customize which class an object ran aside from the default "name-based" approach,
- Assign new game properties to the object (rather than having to use the Game Logic panel for it), and 
- Tweak execution priority to execute some objects before others.

Am I correct? Discuss!

**Comment by rafcolson** [comment]
You're correct.

**Comment by GoranM** [comment]
Yes, I think we agreed on something like that.

**Comment by rafcolson** [comment]
I'd like to add something:

- a check box "Show Profiler" and another check box "Small" next to it (which will become active when the "Show Profiler" box is checked).

**Comment by GoranM** [comment]
The "Object Panel" is for object specific data, not game specific options. The settings that already exist in blender are sufficient.

Also, I don't think there's a need to have size options for the profiler - It doesn't really matter that much, as long as the info is readable.

**Comment by rafcolson** [comment]
Okay.But is it okay to make the profiler's display size around 81.25% of the current size? Or 87.5%?

**Comment by GoranM** [comment]
I think that's fine.

**Comment by rafcolson** [comment]
Someone working on this? Any progress?

**Comment by SolarLune** [comment]
Ah, no, I started, but I'm really rusty with the add-on API and didn't get very far. If anyone else thinks they can take a crack at it, lemme know.

**Comment by rafcolson** [comment]
Okay, thanks. I'll let you know if I will do that.

**Comment by rafcolson** [comment]
So, I'm having a go at this. If you have any design preferences, please share. This is what I had in mind:
______________
\/ Java Script
[field for Script] [checkbox for Execution Priority]

\/ Properties [same as in Logic Editor]
+ Add Game Property
______________

**Comment by SolarLune** [comment]
Very cool. I'd change the Java Script section. I think it should be called "Java Class", and there should be a checkbox to enable the custom class. If enabled, then the field for the class is enabled and you can type in the name of the class the object should correspond to. Execution Priority shouldn't just be a boolean, but rather an integer spinner. 

Ideally, we would sort the objects by priority and execute them in that order. I'd guess we'd just store a Hashmap of integer numbers (priority) to ArrayLists of objects. BDX would place the objects into the relevant lists for their priorities, and then loop through them from the "top down" to execute objects' logic.

@GoranM can weigh in on his preferences, but a boolean seems too "tight" for possible situations (like where you would want, say, something related to input to run before the player object, but setting up the entire level to run before anything else).

**Comment by rafcolson** [comment]
Here's what I had in mind.

Note: When setting a Priority the Priorities of other objects will not be changed. To make this possible a list of sorted objects should be updated when objects are removed or added, which would get complicated. And I don't even know how to change those properties. A possibility would be to use Game Properties instead of Custom Properties.

**Comment by SolarLune** [comment]
Wow, looks pretty good so far. Nice work.

**Comment by rafcolson** [comment]
@GoranM @SolarLune
Feel free to make adjustments or suggestions.

**Comment by GoranM** [comment]
What exactly is the utility in being able to specify execution priority for more than one object?

**Comment by rafcolson** [comment]
SolarLune said:
>@GoranM can weigh in on his preferences, but a boolean seems too "tight" for possible situations (like where you would want, say, something related to input to run before the player object, but setting up the entire level to run before anything else).

**Comment by SolarLune** [comment]
I can't think up a use case that would require setting the priority for more than one "tier" of objects, but it's something I've run into before. You want something to run before everything else (input / game level or world based), but you have something else that needs to run before that. Again, this is just based off of my personal experience. 

If you want to just have boolean, that's fine, but I think the benefits of multiple priorities outweigh the negatives of slightly more complex code.

**Comment by GoranM** [comment]
> I guess a possible case would be wanting a "System" object to handle spawning and managing game objects, including the Player, but also wanting the Player object to run before everything else (except for the System object) to have priority in game situations (collision, attacking, etc).

I don't understand why "handling spawning" and "managing game objects" would require execution priority.

As for "priority in game situations": If Player and Enemy are both attacking each-other, on the same frame (an unlikely circumstance to begin with), it doesn't really make sense to prioritize the Player - As far as human perception is concerned, it's happening at the same time, so either order would perfectly reasonable, and is therefore something that should be determined by "fate" (aka: the incidental state of the system).

**Comment by SolarLune** [comment]
> I don't understand why "handling spawning" and "managing game objects" would require execution priority.

It might, depending on the circumstances (spawning the game world, if it's randomly generated, for example). I can't come up with an exact usage case that would require multiple stages of execution priority, though.

>  is therefore something that CAN be determined by "fate" (aka: the incidental state of the system.

That's up to the developer to decide, not you or me.

In any case, fair enough. Let's go with boolean priority. If I feel the need for multiple levels (I probably won't), then I'll raise a stink about it later. :p

Thanks for your assistance and patience as well, @rafcolson.

**Comment by GoranM** [comment]
> That's up to the developer to decide, not you or me.

Actually, people who develop the engine have a responsibility to keep a balance between flexibility and system complexity. To do that effectively, they have to put limits on what developers can do within the confines of the system.

It's good to keep the [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) principle in mind.

**Comment by rafcolson** [comment]
>Thanks for your assistance and patience as well, @rafcolson.

No big deal, @SolarLune. I'll change it to a boolean then and submit a PR.

>To do that effectively, they have to put limits on what developers can do within the confines of the system.

I agree. Eventually if it turns out to be a necessity, we could change to Integer.

**Comment by SolarLune** [comment]
Sweet, this works! Thanks a lot, @rafcolson. Issue closed!
