### ISSUE TITLE
Question! Easy way to change Screen Orientation to Portrait?

### ISSUE THREAD

**Issue by benkaranja** [GoranM/bdx#271]
Hey. I have been struggling to change the default screen to portrait with no luck. Rotating Blender Camera or Changing settings has no effect. Iscene.java & BdxApp.Java have no camera attributes also. I am not a pro Blender user so i hope it's not a really lame question. 

Thanks in advance

**Comment by SolarLune** [comment]
Ah, I think I see - you should be able to just change the output resolution. There are resolution spinners under the properties panel's render section (the button that looks like a camera). If you're in Blender Render mode, it'll be in the Dimensions section. If you're in Blender Game render mode (at the top of the window), the Embedded Player's dimensions controls it.

![resolutionlocation](https://cloud.githubusercontent.com/assets/4733521/7347995/901e2dcc-eca2-11e4-9a6d-6221911c6b7e.png)

Also, this is mainly for discussion on working on the engine - we encourage people to use the subreddit at /r/bdx for discussion on using the engine.

**Comment by GoranM** [comment]
Yes, this belongs in r/bdx, so I'm going to close this one.

**Comment by songproducer** [comment]
In your project's android folder -> AndroidManifest.xml:
make sure:
android:screenOrientation="portrait"
