### ISSUE TITLE
Bug?: a lot of errors

### ISSUE THREAD

**Issue by Ratinod** [GoranM/bdx#272]
Please help to understand what the problem is.
BDX - 0.1.7
JDK - 1.7.0_79
http://i.imgur.com/d3db9X0.png (screenshot)

**Comment by rafcolson** [comment]
Did you do something to the scene or is it a fresh install? It shows the message to run once without Text objects, but I don't see any Text objects.

**Comment by Ratinod** [comment]
Yes. This project was completely fresh. (I didn't change it.)
I re-downloaded the 0.1.7. Install it.Shows the same set of error. So this is exactly 0.1.7.
And how to deal with this problem fonts?

**Comment by rafcolson** [comment]
I don't know for sure. It has to be system related. Are you using Linux or iOs? Because on my Windows 7 64bit there's no problem with it.

**Comment by GoranM** [comment]
This was a bug - There's a new release out (0.1.8), so give that a try.

> It shows the message to run once without Text objects, but I don't see any Text objects.

They're in the profiler scene.

**Comment by rafcolson** [comment]
Thanks Goran.

**Comment by Ratinod** [comment]
Ok. Now a bunch of error disappeared.
Now there is only one error: "BDX Build Failed". ( http://i.imgur.com/qYhU1dd.png )
And compilation does not start.
Requires necessarily specify the folder with the Android SDK?

**Comment by GoranM** [comment]
Did you remove the old project directory before creating the new one? If not, make sure to do that, and try again.

If that doesn't work:

We need to see the information that you're putting into the BDX panel, before you click "Create BDX project".

It would also help if you could provide the [console](http://wiki.blender.org/index.php/Doc:2.6/Manual/Interface/Window_system/Console_window) output.

**Comment by Ratinod** [comment]
After pressing "P" : http://i.imgur.com/WTCtEHT.png
Ok. Now I realized that the problem was in the name of the folders. D: \ () WORK \ () Blender \ BDX \ test99 ( "(" and ")" is bad characters for the name of the folders) 
And yet it was necessary to set a variable JAVA_HOME.
Now everything works. Thank you very much for helping deal with all problems. :)

**Comment by GoranM** [comment]
I thought that somehow BDX was adding those parens, but if that was the actual path, and it's valid on windows, it should still work (python should be able to parse it properly) ... It's possible that gradle can't figure it out, but I'm not really sure.

Anyway, as long as you use normal directory names, it should be fine.

I'll close this issue now.
