### ISSUE TITLE
Suggestion: function to quit the game

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#274]
Right now you can quit the game by closing the window (or a System command such as Alt+F4 on Windows). On android you could just close the app. But most applications will have a "quit game" button or something like that.

And currently there's no way to end a scene, is there? I've seen nothing in the API.

That's why I think ```Bdx.end()``` and ```Scene.end()``` could be useful additions. What do you think?

**Comment by GoranM** [comment]
That sounds fine.

**Comment by rafcolson** [comment]
I have a couple of questions:

There is the method to quit the application: ```System.exit(0)```. But I noticed ```Bdx.java``` also has a ```dispose()``` method that will dispose applications run by Bdx, but not Bdx itself. But would it be necessary to dispose of these if we're already destroying the application with ```System.exit(0)```, or would that cause a memory leak? You guys probably know more about this.

**Comment by SolarLune** [comment]
You should be able to "end" a scene by just removing it from the scenes list, right? No need for a specific function? Something to end the game sounds good, though.

Anyway, @rafcolson - I'm not personally sure on what circumstances "dispose()" methods are called, but as a guess, it'd be when the object is destroyed by the garbage collector. If you call System.exit(), I'd imagine it would destroy all objects in memory in Java, which this kinda-on-topic SO thread talks about: http://stackoverflow.com/questions/13360430/jframe-dispose-vs-system-exit

**Comment by rafcolson** [comment]
Thanks, @SolarLune . Probably best to use ```System.exit(0)``` then, I suppose. And no reason to dispose those other things, since everything is cleared.

>You should be able to "end" a scene by just removing it from the scenes list, right? No need for a specific function? Something to end the game sounds good, though.

Yes, it seems like it. But just for convenience sake I could add ```remove(String sceneName)```, because currently you have to get the scene or give the index: ```remove(int index)``` and ```remove(Scene scene)```.

**Comment by GoranM** [comment]
Yes, when you terminate the application, all the memory used by the process should be reclaimed by the OS, automatically, so there's no need to clean up in that case.

> I'm not personally sure on what circumstances "dispose()" methods are called, but as a guess, it'd be when the object is destroyed by the garbage collector.

I'm not sure that actually happens; The whole point of dispose is to allow cleanup management independent of the garbage collector. To find out for sure, print something in dispose - If it's called by the garbage collector, you should see the printed output shortly after loosing the reference. If that doesn't happen, it means that we'll need to ensure that it's called, at some point, to avoid memory leaks.

**Comment by rafcolson** [comment]
PR merged. Thanks.
