### ISSUE TITLE
Does BDX support Java 1.8?

### ISSUE THREAD

**Issue by skypatcher** [GoranM/bdx#277]
Hi:

My System is Win 8.1 (Intel 64 bit). The Android SDK is at C:\AndroidSdk. I just installed the BDX plugin 0.1.8 to Blender 2.74. When I click 'Create BDX project'. I got the following message in Blender's system console:
![bdx-error](https://cloud.githubusercontent.com/assets/6044891/7420481/d2794d0a-ef4a-11e4-8e1c-03c5a178d75b.png)

**Comment by SolarLune** [comment]
BDX does support Java 1.8 - it's what I'm running on my machine. Do you only have Java 1.8 installed? Can you make a project without the Android SDK? What happens if you type `java -version` into a command prompt?

**Comment by rafcolson** [comment]
JDK is installed, but not JRE?

**Comment by GoranM** [comment]
Assuming that `javac -version` prints something higher than or equal to 1.7, it should work.

Looking at your error, I'm reminded of [this post](https://github.com/GoranM/bdx/issues/182#issuecomment-81018425). As you can read there, it seems like the problem stems from having both java 7 and java 8 installed.

You can confirm that by running this python code:

```python
import subprocess
subprocess.check_call(["javac", "-version"])
```

If that prints 1.7, while `javac -version` prints 1.8, that's the problem.

**Comment by skypatcher** [comment]
Thanks for everyone's suggestion. 

When I type java -version, it tells me 1.8, but when I type javac -version, it said unrecognized command.  Turns out JAVA_HOME was pointing to an old JDK folder (Java 7, which I have already uninstalled a while back).

After I fix the JAVA_HOME, I can now get version 1.8.0_31 from both java -version, and javac -version prompt.

But when I restart Blender and create a new project, I get the following error. I saw something about -source 1.6. Don't know if it is because my JDK installation is still corrupted?

![bdx-1](https://cloud.githubusercontent.com/assets/6044891/7433023/30bf96de-effb-11e4-89f0-da2e2afcec8f.png)

![bdx-2](https://cloud.githubusercontent.com/assets/6044891/7433031/3aca91b0-effb-11e4-8016-1af5406ffe21.png)

**Comment by rafcolson** [comment]
I think you didn't specify the correct SDK path. On my system for example it's:  ```C:\Users\Acer\AppData\Local\Android\sdk```. Something like ```\android-sdk``` to me doesn't seem valid.

**Comment by skypatcher** [comment]
My Android SDK is installed at the root directory, so I can get to it easily. I have been using this folder for many years on many machines with Eclipse and Android Studio without any problem.

**Comment by GoranM** [comment]
It seems that the android sdk changed a bit, and that the way in which we parse the build tools version is no longer correct - instead of a number that we can feed to int, we get the "build-tools-21" string, and that raises an exception, which in turn prevents the project creation process from properly finishing.

If you create a project without specifying the android sdk path, that should work fine, but if you're going to use the same project path, and directory name, you'll need to remove the old project directory first.

> I think you didn't specify the correct SDK path.

By default, BDX assumes an incorrect path to the Android SDK, as you can see in his output, when he created a project without specifying the SDK path:

```
The SDK directory 'C:\\My\MyBdx\BdxProject\android-sdk` does not exist.
```

That's perfectly normal, so providing an incorrect path shouldn't break the project.

**Comment by skypatcher** [comment]
Thanks @GoranM:

I restart the whole thing and retried the project with Android SDK field blank, and it said BUILD FAILED, but I can see the sample game. When I export and run it, I can make Sacky jump by pressing space key.  BTW, does the warning: [options] bootstrap class path not set in conjunction with -source 1.6 has any real significance?

Thanks! Keep up the good work!

**Comment by GoranM** [comment]
> BTW, does the warning: [options] bootstrap class path not set in conjunction with -source 1.6 has any real significance?

According to [the docs](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javac.html#crosscomp-example): It's just a java compiler warning that you get when targeting a specific version of the java VM, but without specifying the correct version of the bootstrap classes - I guess the libgdx gradle build does that, and that's why you see the warning - It shouldn't cause any trouble (I get it too).

**Comment by skypatcher** [comment]
thanks for the explanation

**Comment by SolarLune** [comment]
So was there any outcome as to how to get Android working, or is it broken for now?

**Comment by GoranM** [comment]
I would assume that it's broken when used with the latest android sdk.

@rafcolson wrote the code that sets the build tools version for android, so it would probably be best for him to test with the latest android sdk, and make the required changes.

**Comment by rafcolson** [comment]
Okay, I'll do some tests.

**Comment by rafcolson** [comment]
I've updated to Android SDK Build-tools version 22.0.1 but could not reproduce the error.

**Comment by skypatcher** [comment]
I just added some debug message (the red box) in the file createproj.py. I have SDK build-tool version 19, 20, 21, and 22 (the blue box) It seems that Android SDK uses a string for version 21 (the yellow box).  

![bdx-err](https://cloud.githubusercontent.com/assets/6044891/7467231/df07c72a-f2c1-11e4-83bd-0d7324a99fd4.png)

**Comment by skypatcher** [comment]
Since I already have build-tool ver 22, I decided to uninstalled build-tool version 21, Strange things happen, the script choke on another non-integer.

![bdx-err2](https://cloud.githubusercontent.com/assets/6044891/7467316/1e34a66e-f2c4-11e4-924e-750676109422.png)

**Comment by skypatcher** [comment]
@rafcolson Good news. I just uninstalled SDK build version 21 and 20 L. Now the build is successful without any problem!

**Comment by rafcolson** [comment]
I think I understand what was happening here. For some reason the SDK build-tools version you previously had installed is not ```21.1.2``` but ```build-tools-21.1.2```. Now that you removed this, I wonder. In your SDK manager, if you install ```21.1.2``` will still be installed with that name? When I install this version, a folder with the name ```21.1.2``` is added to my ```build-tools``` directory. So I wonder if our SDK managers are pointing to different source files or something?

Also I couldn't find ```Android L preview``` anywhere in my updates. So I wonder what could be the reason for this.

Anyway, if by installing any of these you get errors, this has to be fixed. I'll submit a PR for this soon.

Thanks for your help!

**Comment by skypatcher** [comment]
@rafcolson  Unfortunately I've  already uninstalled my previous 21.1.2, so I can't determine the original folder name, actual location; or hunt down the origin of the version string "build-tools-21.1.2"

I just reinstalled 21.1.2 and ran the BDX build inside Blender. It works fine now.  Based on the debug message, the build-tool version for the new 21.1.2 is consistent with what your Python script expected. I don't know why the version string was different before. 

![bdx-err3](https://cloud.githubusercontent.com/assets/6044891/7472900/ff4660c6-f304-11e4-9dc7-2ed96ce7ff71.png)

"L Developer Preview is the preview of Android 5.0.  The L SDK when released will have the number 21".   The API 20L preview is no longer available for installation.  So API 20L is a non-issue now.

I am glad we solved the mystery of my Android SDK installation. I have never touched the internals of Android SDK before; may be Android have attempted to use a verbal format string. If so, the change must have been very short-lived, otherwise more people would have encountered similar problem. Thus my situation may be very rare, it may not warrant a change in the Python script. May be just a note for others to uninstall old 21.1.2 and reinstall new 21.1.2 (or 22+) when similar situation arise.

Thanks for looking into the matter with me.

**Comment by rafcolson** [comment]
Thank you, @skypatcher.

**Comment by skypatcher** [comment]
@rafcolson  I tested BDX on another machine (also with 21.1.2 installed a while back). Everything is OK.  All The SDK build tools version strings parsed correctly; and there is no funny SDK API version number neither.

You are welcome.

**Comment by skypatcher** [comment]
My issues are resolved.  Should I or the developers close it? Thanks.

**Comment by SolarLune** [comment]
You can close it. If anybody needs to pick up the conversation, a new issue can be created.

**Comment by skypatcher** [comment]
Ok, I'll close it now. Thanks
