### ISSUE TITLE
Suggestion: GameObject.replaceModel()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#279]
Well, I think it would be nice to be able to replace the mesh of the object. Similar to the BGE: ```replaceMesh(String meshName, boolean useDisplayMesh, boolean usePhysicsMesh)``` and ```replaceMesh(String meshName)``` with ```useDisplayMesh = true``` and ```usePhysicsMesh = false``` as the default.

Only difference is that the mesh is replaced by a unique mesh. So we're not replacing one of the ```models```, we're adding a new model, being a copy of the specified model.

What do you think? Any suggestions? Improvements?

**Comment by GoranM** [comment]
We don't actually have a Mesh concept in BDX - We use libgdx models, and representative model instances, so the name "replaceMesh" doesn't really cover existing semantics. Something like "replaceModel" would make more sense, in my view.

That said: This seems like it would be a useful feature, so you can make the PR, and I'll review the code there.

**Comment by rafcolson** [comment]
@GoranM 
@SolarLune 

I think you're right. A ```Model``` is described as an owner of meshes, materials and textures, as been documented [here](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/g3d/Model.html). And currently ```replaceMesh()``` is replacing the entire Model.

Maybe we could change ```useUniqueMesh()``` to ```useUniqueModel()``` or ```cloneModel``` too? I'll make a separate PR for this and I'll try to replace ```mesh``` with ```model``` were needed. But first let me know what you think.

**Comment by GoranM** [comment]
Yes, "useUniqueModel" would probably make more sense.

If you're going to change it, be sure to do it in all places where it's used.

**Comment by rafcolson** [comment]
Okay, I'll do.

**Comment by rafcolson** [comment]
PR's merged. Thanks!
