### ISSUE TITLE
Suggestion: API - linking primitive types

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#282]
However it may not be really necessary (assuming anyone can find the documentation) I think this would improve the readability of the API. Especially when a lot of those are in the constructor, as you can see [here](https://github.com/GoranM/bdx/wiki/API-GameObject#replaceModelPhysics).

**Comment by SolarLune** [comment]
Eh, I don't think it's so necessary since built-in types are basic programming pieces that are used rather frequently in the API reference. People can just look up "boolean Java" or "String Java" to see what it is or how it works.

**Comment by rafcolson** [comment]
Okay. Thought so.
