### ISSUE TITLE
Suggestion: additional methods for Bdx.display

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#283]
I'd like to add following methods:
- ```Bdx.display.size(float width, float height)```
- ```Bdx.display.size()```
- ```Bdx.display.isSized()```

**Comment by SolarLune** [comment]
What would "isSized()" do?

**Comment by rafcolson** [comment]
```isSized()``` evaluates if the display size has changed since the last check.

**Comment by GoranM** [comment]
I don't understand the utility of isSized, but the size functions sound fine.

**Comment by rafcolson** [comment]
Okay, I'll leave that out then.

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
Oh, I forgot ```Bdx.display.center()```. This especially useful with odd screen resolutions.

**Comment by SolarLune** [comment]
This was merged, right?

**Comment by rafcolson** [comment]
Right, I forgot to close this. Thanks.
