### ISSUE TITLE
Bug: parent(null)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#289]
Currently, ```parent(null)```
- breaks NO_COLLISION. (fixed)
- breaks RIGID_BODY: for example, an unparented cube that falls down will bounce, but keeps rotating slowly in one random direction, until it gets stationary. Edit: it turns dynamic only.

**Comment by GoranM** [comment]
> breaks RIGID_BODY: for example, an unparented cube that falls down will bounce, but keeps rotating slowly in one random direction, until it gets stationary.

I can't seem to reproduce this. Can you make a simple example?

**Comment by rafcolson** [comment]
Here's an [example](https://www.dropbox.com/s/nd6u69j2sfhmksg/physics_unparent_rigidbody_bug.blend?dl=0).

I think the reason why in my other file the box momentarily turned was because it collided at the moment it was unparented. In this example it's just a cube falling down and you'll notice it turns dynamic (only).

**Comment by GoranM** [comment]
I just see a box that falls to the ground ... It doesn't turn.

Are you on the master branch? Did you recompile?

**Comment by rafcolson** [comment]
>I just see a box that falls to the ground ... It doesn't turn.

That's exactly the problem. I'm working on a fix right now.

>Are you on the master branch? Did you recompile?

Yes.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged.
