### ISSUE TITLE
Bug: Android Won't Compile

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#291]
Hey, there. So basically, I can't compile an Android APK using gradle's command-line interface like I can for desktop. I try to run `gradlew android:installDebug`, but I get an error:

```

UNEXPECTED TOP-LEVEL EXCEPTION:                                                    
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version 
(0034.0000)                                                                        
        at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472
)                                                                                  
        at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
                                                                                   
        at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(Di
rectClassFile.java:388)                                                            
        at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:2
51)                                                                                
        at com.android.dx.command.dexer.Main.processClass(Main.java:704)           
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)       
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)              
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)     
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.
java:284)                                                                          
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java
:166)                                                                              
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:14
4)                                                                                 
        at com.android.dx.command.dexer.Main.processOne(Main.java:632)             
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)        
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)             
        at com.android.dx.command.dexer.Main.run(Main.java:246)                    
        at com.android.dx.command.dexer.Main.main(Main.java:215)                   
        at com.android.dx.command.Main.main(Main.java:106)                         
...while parsing com/nilunder/bdx/Bdx$ArrayListScenes.class                        
                                                                                   
1 error; aborting                                                                  
:android:preDexDebug FAILED                                                        
                                                                                   
FAILURE: Build failed with an exception.                                           
                                                                                   
* What went wrong:                                                                 
Execution failed for task ':android:preDexDebug'.                                  
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:     
        C:\tools\android-sdk\build-tools\22.0.1\dx.bat --dex --output C:\Users\Sola
rLune\My Projects\BDX\TestDroid\android\build\intermediates\pre-dexed\debug\bdx-1fc
6946e2e3244f8337cce9201422eabe0f6d992.jar C:\Users\SolarLune\My Projects\BDX\TestDr
oid\core\libs\bdx.jar                                                              

```

I'm working with JDK 8, Windows 8 64-bit, and the latest version of BDX built from source. 

Trying `gradlew android:assembleRelease` also doesn't work, with the console complaining of:

`Error processing C:\Users\SolarLune\My Projects\BDX\TestDroid\core\libs\bdx.jar:com\nilunr\bdx\Bdx.class: broken class file?`

for each, apparently, BDX class.

**Comment by rafcolson** [comment]
Well, I have some good news and some bad news.

I'm guessing you're having the same problem as I am having for quite some time now. The problem is our own builds. I can't seem to export for Android with my own builds, but with the official release there's no problem. Just wait until Goran releases 0.1.9 and you probably will be able to export with that version.

The bad news that I don't have a clue why my ant is not building as it should. Maybe my zip file is corrupted? I don't know. Maybe @GoranM could give us some specifics on what versions of ant and 7-zip (assuming he's using this) he is using.

**Comment by GoranM** [comment]
> With the official 0.1.8 everything works fine.

It's probably because I used java 7 to compile the 0.1.8 release, which gives the android SDK the expected bytecode.

Android can't seem to deal with jars that are compiled with java 8, so unless you're using java 7 to compile your custom version of bdx, you need to use the official bdx release when building for android.

**Comment by rafcolson** [comment]
That's good news in a way. It's not like we need Java 8 or anything.

**Comment by rafcolson** [comment]
@GoranM If I may ask. Which (exact) versions are you using of JDK, SDK and ant?

I'm really having trouble with getting jdk-7u79-windows-x64 to work. It's strange, but ant complains about my compiler wanting to upgrade to a higher version. More specifically to 52 which means JDK8.

Okay, I didn't try to restart my system. Maybe that's it.

**Comment by rafcolson** [comment]
@SolarLune 

Good news! Everything works fine now. I just compiled the latest BDX from my repo and built ```android:assembleDebug``` with:
- Java: [jdk-7u79-windows-x64.exe](http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html) (JDK + JRE).
- Android: [android-studio-bundle-141.1890965-windows.exe](https://developer.android.com/sdk/index.html#win-bundle)
- Ant: [apache-ant-1.9.4-bin.zip](http://ant.apache.org/bindownload.cgi)

Added system variables are ```JAVA_HOME``` and ```ANT_HOME``` set to the path of ```bin``` (for each).
Added value to system variable ```PATH```: ```%JAVA%\bin;```

I think it was important that every trace of JDK 8 was erased before installing everything from scratch. Good luck!

**Comment by SolarLune** [comment]
Hmm, that's unfortunate. If it's something that we can't prevent, then it should be possible to get a JDK 7 from somewhere...

**Comment by rafcolson** [comment]
As a side-note, according to the Android installation page JDK 7 is a system requirement, so no support for JDK 8 yet.

http://developer.android.com/sdk/installing/index.html?pkg=studio

**Comment by SolarLune** [comment]
Thanks for the tip. I was able to compile Android this time around with JDK 7, and install it on my Android phone. Unfortunately, it crashed on first run, but that could be due to a number of reasons and is a separate issue from this. Anyway, thanks! Issue closed.
