### ISSUE TITLE
Performance issues:Unnecessary calculations during matrix "normalize"

### ISSUE THREAD

**Issue by moshme** [GoranM/bdx#292]
Hi, After updating the bdx version from 0.78 to the recent version. I discovered that the performance decreased. On My android phone i was losing about ten frames. Causing lacks in a testlevel, which worked well with the older version.

I then installed and tried the different versions and checked every time the fps second of my testlevel to find where the lack first occurs. When i found the two release version where difference occurs(between version 0.8 and 1.0), i refined the search by checkin out different commits and recomiled bdx for that specific commit. This pointed me to  the commit with SHA 196e606cf87f7b689a337ce76ad53e6ad1d5b533 (Move lin algebra methods from Bullet.java to proper place in gwt-vecmath.jar (#170)).

Inside that commit there where three math functions replaced through functions of the gwt-vecmath library. Then re-replacing each of this functions showed me that the difference in the fps where caused by the normalize function inside the transform Function of the GameObject.

 A closer look to the old and new function showed the following:
In the old version the function has just normalized the column vectors of the matrix. This own coded version was then replaced by a function of the Matrix Class in the gwt-vecmath library. But this function did a way more complicated calculation called "single value decomposition".

Goran mentioned:
>Floating point is not perfectly accurate, so after a number of operations, the values drift to where the axis vector lengths are something other than 1, and that makes the object in question appear deformed.
We normalize to avoid that.>

This and the fact that i diddnt see any deformations on the models while using the old function version, makes me believe the old function is sufficent for the job while having a far better performance than the gwt-vecmath normalize function. In other words: The library functions does a lot of unnessary calculations for our task.

I could not found any function in the Matrix Class of the library that normalizes the Matrix in that way, that only column vectors of the matrix where normalized.( Dont know really why, maybe they consider this kind of normalization as to low level to implement as function, maybe its only a cg graphic specific way to normalize a matrix like that )

So i propose to re-replace the unnessary complicated libraray function.
Maybe best would be a new function inside the vecmath library, but i have no idea if the developers are interested in that. But as long as that could not be achieved... placing a helper function somwhere inside bdx.utils would be nice.

**Comment by rafcolson** [comment]
Thanks for looking into this @moshme.

**Comment by GoranM** [comment]
You could just replace the `t.basis.normalize()` call in transform() with:

```java
Vector3f v = new Vector3f();
for (int i = 0; i < 3; ++i){
	t.basis.getColumn(i, v);
	v.normalize();
	t.basis.setColumn(i, v);
}
```

I think that would be fine.

Do you want to make that patch, @moshme ?

**Comment by moshme** [comment]
Ok, i created a pull request.

**Comment by GoranM** [comment]
Merged.
