### ISSUE TITLE
Proposal: Convenience load() static function for Filter

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#293]
Hey, there. I think a static convenience function to load a filter without having to specify LibGDX FileHandles would be nice and useful. I'm thinking it'd take two strings, one for the path to the vertex shader, and one to the fragment shader. The function would load the shaders from those files (call super() with created file handles).

That way users wouldn't have to deal with LibGDX to load in a filter from a file.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
This was merged, so I'll close this. Thanks!
