### ISSUE TITLE
Question: multiple materials and friction

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#295]
Hi,

Momentarily, is friction supported with multiple materials on the same mesh? Because when I do some tests, it seems BDX only takes the friction of the "selected" material in the Material Tab of Blender for calculation.

Any idea?

Thanks.

**Comment by GoranM** [comment]
BDX uses gbullet, which a port of jbullet, which is a port of Bullet 2.72, which (as far as I know) doesn't support multiple materials.

So, yes, we only use the physics settings of the selected material.

**Comment by rafcolson** [comment]
Okay, good to know. Thanks.
