### ISSUE TITLE
Bug: 2D Filter Corrupted

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#301]
Hey, there. So I'm working on something that uses 2D filters, and I think I've found out that the way we render our filters out is corrupting them. Note this example image. It's a bloom filter with the strength turned way up to show the issue. Basically, there's a tear running down the screen, from the top-right to the bottom-left corner.

![bloomtear](https://cloud.githubusercontent.com/assets/4733521/7550720/8f651372-f621-11e4-9f4c-55c9294f30c4.png)

Here it is fixed - I just took out the framebuffer's drawing to itself in Bdx.java (which is used for the Filter stack) and had it draw straight to the screen. 

![bloomfixed](https://cloud.githubusercontent.com/assets/4733521/7550723/993d079c-f621-11e4-8084-132d2aab6a0f.png)

It's just a theory at the moment, but I think we might need to add a temporary buffer to prevent drawing to the buffer we're reading from for 2D filters, as the process can corrupt it.

Feel free to test it out yourself with the bloom shader.

```cpp

#pragma optionNV(strict on)

#ifdef GL_ES
    precision mediump float;
#endif

varying vec4 v_color;
varying vec2 v_texCoords;
uniform sampler2D u_texture;
uniform mat4 u_projTrans;

float luminance(vec4 color) {
	
	return (((color.r * 2) + color.b + (color.g * 3)) / 6);
	
}

void main() {

    int sampleNumX = 4; 				// Number of samples on X and Y axes
    int sampleNumY = 4;					// (To be exact, it's (X*2)*(Y*2) number of samples)
    float width = 0.002;  				// Percent of the screen to sample in width and height
    float height = 0.002;
    float threshold = 0.25;  			// The luminosity threshold of the surrounding pixels to trigger the effect
    float strength = 0.5;  				// The strength of the overall bloom effect
    vec4 tintColor = vec4(1, 1, 1, 1);  // The color to tint the bloom effect

    vec4 base = texture2D(u_texture, v_texCoords);
    vec4 bloom = vec4(0);  
    vec4 bloomCol = vec4(0);
    vec2 coords;
    
    for (int i = -sampleNumX; i < sampleNumX; i++) {
    	
    	for (int j = -sampleNumY; j < sampleNumY; j++) {
    		
    		coords.x = v_texCoords.x + (i * width);
    		coords.y = v_texCoords.y + (j * height);
    		    		
    		bloomCol = texture2D(u_texture, coords);
    		
    		if (luminance(bloomCol) > threshold)
    			bloom += bloomCol;
    		
    	}
    	
    }
    
    bloom /= (sampleNumX * 2) * (sampleNumY * 2);
        
    bloom *= tintColor;
    
    gl_FragColor = base + (bloom * strength);

}


```

**Comment by SolarLune** [comment]
Oh, and P.S., would you guys want to include a few filters like these (Bloom, Blur, Motion blur) with BDX? They'd go next to the defaultFilters.

**Comment by rafcolson** [comment]
Yes! Bloom, Blur, Motion blur would be great. Nice to hear you could fix the issue.

**Comment by GoranM** [comment]
> It's just a theory at the moment, but I think we might need to add a temporary buffer to prevent drawing to the buffer we're reading from for 2D filters, as the process can corrupt it.

The next step would be to test the theory.

> Oh, and P.S., would you guys want to include a few filters like these (Bloom, Blur, Motion blur) with BDX? They'd go next to the defaultFilters.

I think it would be a good idea to include some common filters, but in order to make them available, we would need to place them into the generated project, not in `src/com/nilunder/bdx/shaders/`.

**Comment by SolarLune** [comment]
> The next step would be to test the theory.

I guess you didn't see my later posts - I tested it, and the theory is confirmed. PR submitted.

> I think it would be a good idea to include some common filters, but in order to make them available, we would need to place them into the generated project, not in src/com/nilunder/bdx/shaders/.

I guess I'll make a different issue for that, then. I suppose the normal shaders can be moved out from there? Perhaps into a directory for it - would it be possible to place into the `android/assets/shaders/` directory?

**Comment by GoranM** [comment]
Yes, we could move them there during project creation, or we could just include them as static final strings on the Filter class itself.

**Comment by SolarLune** [comment]
Thanks for the merge.

I think I would rather go the string method, but there's no way to construct multi-line strings in Java like Python, which means that the result would be pretty ugly and ungainly. So I guess the project creation step would be the advised approach.

**Comment by GoranM** [comment]
Well, you could do this:

```java
String s = "It was the best of times, it was the worst of times,\n"
         + "it was the age of wisdom, it was the age of foolishness,\n"
         + "it was the epoch of belief, it was the epoch of incredulity,\n"
         + "it was the season of Light, it was the season of Darkness,\n"
         + "it was the spring of hope, it was the winter of despair,\n"
         + "we had everything before us, we had nothing before us";
```

Which doesn't seem that bad.

**Comment by rafcolson** [comment]
Well, it's mixed, so it's not good either. :smile_cat:

**Comment by SolarLune** [comment]
^ Yeah, it's not ideal. It also doesn't encourage extension as it's not easily extend-able (as you can't just type; you have to add lines to type into). Maybe I'll just go the folder route.. Anyway, this issue's finished. Closed!
