### ISSUE TITLE
Question: Dev: Should we avoid using the switch statement?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#308]
This because only Java 1.7 supports ```switch```. So if anyone should have Java 1.6 on their system BDX wouldn't work properly.

**Comment by skypatcher** [comment]
Based on the following blog:

https://github.com/libgdx/libgdx/wiki/Setting-up-your-Development-Environment-%28Eclipse%2C-Intellij-IDEA%2C-NetBeans%29

Libgdx seems to require JDK 1.7+. If BDX is built on top of libgdx, then we should insists Java 1.7+.

**Comment by rafcolson** [comment]
Hey thanks.
Op 10-mei-2015 18:57 schreef "skypatcher" <notifications@github.com>:

**Comment by skypatcher** [comment]
you are welcome

**Comment by SolarLune** [comment]
So... That's it, right?

**Comment by rafcolson** [comment]
Not exactly. As I suspected BDX still uses parts of 1.6, even though I "only" installed 1.7. According to the Oracle documentation JDK 1.7 supports String in switch, but I'm getting this warning:

```
------------ BDX START --------------------------------------------------

Configuration on demand is an incubating feature.
:core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
D:\BLENDER\BDX\projects\Test\test\core\src\com\raco\game\Sacky.java:9: error: st
rings in switch are not supported in -source 1.6
        switch (s){
                ^
  (use -source 7 or higher to enable strings in switch)
1 error
1 warning
:core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 2.519 secs

------------ BDX END ----------------------------------------------------

Error: BDX BUILD FAILED
```

**Comment by GoranM** [comment]
I don't think libgdx gradle files specify java 7 as the minimum required version, so even though java 7 is used to compile, I would guess that the system is attempting to keep the bytcode backward compatible with the java 6 vm.

Just use if statements - It's not a big deal.

**Comment by rafcolson** [comment]
No, it isn't, but I had to know for sure, that's all. (Maybe it was a bug). Thanks for your comments.

So no switch.

**Comment by skypatcher** [comment]
I tried to force sourceCompatibility and targetCompatibility to 1.7 in Bdx's build.gradle, it just doesn't seem to work. It seems Libgdx insists 1.6.  Here is the most recent post I found on the topic. 

http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=18936&p=79544&hilit=bootstrap+conjunction+source+1.6#p79544
