### ISSUE TITLE
Question: Is there something wrong with the jsonvalue?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#309]
Hi guys,

I'm having a hard time figuring out why the ```name``` variable (of ```GameObject```) can be initialized, but parts of the JsonValue can't. For example, I try to initialize ```gobj.get("physics").get("body_type").asString()```, but all I get is ```null``` which means it wasn't initialized at all. (Even in GameObject.main() it's returning ```null```).

Beneath is some test you can look at that shows this simple operation. Thanks for your help.

**Comment by GoranM** [comment]
You're not initializing "parts of the JsonValue", you're trying to initialize the `bodyType` field, so I don't really understand your question.

Are you saying that `physics.get("body_type").asString()` returns null?

If that were true, Bullet.makeBody would throw an exception.

**Comment by rafcolson** [comment]
Thanks for your reply. I meant what you said. But should this code work? And if so, how is it becoming ```null```?

**Comment by rafcolson** [comment]
I feel ridiculous. Of course there's no "body_type" in the physics, it's "bounds_type"!

**Comment by rafcolson** [comment]
I'm sorry guys. I made a mistake thinking I solved the issue. So I'm reopening this. Could anyone tell me why setting this variable to a value that obviously is a string, will result in null?

**Comment by SolarLune** [comment]
Are you setting the bodyType variable for the clones? If I'm not incorrect, basically, when a Scene's created, it sets up game objects as templates, which it then clones to actually place objects in game (and when you call Scene.add()). Make sure you set the variable on the game object in the Scene's init() there where you have it, but also in cloneNoChildren().

**Comment by rafcolson** [comment]
Ah yes. That must be it! Thanks a million.
Op 12-mei-2015 00:24 schreef "SolarLune" <notifications@github.com>:
