### ISSUE TITLE
Built-in Filters

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#310]
Hey, there.

So this issue is going to serve as a consistent issue that can be used to commit new filters to the engine. I guess I'll close it after I create this post, and it will serve as a "base point" and discussion area for future filters to add in (since it's still functional as an issue even if it's closed, it's probably going to be an on-going thing as we think up and create more useful filters (like depth of field or something like that), and I can re-open it later if need be).

I'm going to start off with a couple of popular and useful ones.

- Bloom
- Blur
- Contrast
- Desaturation
- Tint (can be added after desaturation to achieve sepia or a night-time filter, for example)
- Frame-based motion blur

I plan to alter BDX to add a new folder to house these filters on project creation: `android/assets/bdx/filters`. I also plan to rename the `defaultFilter` files to simply `default.vert` and `default.frag`, and move them from the shaders directory from BDX's source into this new folder. This means that the shaders package can be removed.

For future reference (for myself and others), filter files submitted should:

- Not reference variables that aren't used in the script (i.e. `lastFrame`).
- Not take uniforms for customization, as they should work out of the box. If someone wants to customize / alter a filter while it's running, they can put a uniform into a Filter themselves easily.
- Use variables as easy access to alter the properties of a filter's behavior. Put them at the top of the main function.
- Always be visibly changing the scene by default (i.e. don't make a Desaturation filter with the strength set to 0 by default).
- Not alter the alpha component in such a way so as to hide underlying scenes (yes, this is possible). Unless, of course, that behavior is the goal of the filter.
- Fragment shaders should end in `.frag` and vertex shaders in `.vert` to differentiate them.
- Comments should use spaces, not tabs, as it doesn't show up correctly in GitHub's code preview for some reason.

Just some general guidelines.

**Comment by GoranM** [comment]
A closed topic is closed.

If an issue serves a relevant purpose, for some period of time, it should remain open for that period of time.

That said: I don't think it's necessary in this case, because shaders are code like any other, so contributing shaders shouldn't require a "special issue".

If there's something wrong with the code, we can discuss it in the PR, as for every other code review.

**Comment by SolarLune** [comment]
Hm, okay, then. I guess this'll just be for the filters above, then. Once whatever the issue is that's preventing me from creating a new project is solved, I'll create a PR for these.

**Comment by SolarLune** [comment]
PR Submitted.

**Comment by SolarLune** [comment]
PR merged, so this can be closed. Thanks!
