### ISSUE TITLE
Bug:While switching dynamics, mass is only restored when set manually

### ISSUE THREAD

**Issue by moshme** [GoranM/bdx#317]
When i have an GameObject with dynamics and then turn them off and afterwards on again, i loose the mass of the object. As long as i see, it is because the variable lastNonZeroMass of the GameObject class is only set correctly when you invoke the mass setter method manually. But not on creation of the object.

**Comment by rafcolson** [comment]
This is a bug. The ```lastNonZeroMass``` is not set correctly at Game creation, because the variable is not set in ```cloneBody()```. It would be fixed with the ```bodyType``` PR, but maybe it could take some time for this to get merged. So here's the fix:

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged.
