### ISSUE TITLE
Suggestion: Adding frustum culling 

### ISSUE THREAD

**Issue by moshme** [GoranM/bdx#321]
Hi there,
I discovered that there is no frustum culling implemented yet. Neither in bdx or libgdx.
I made some tests with a lot of big objects at the edge of the scene (to be sure they are not inside the camera frustum). Some simple sysouts showed me that they were sent to the modelbatch to be rendered. And also i recognized that the fps dropped signicantly. So i implemented some simple frustum culling with the help of this [tutorial] (http://xoppa.github.io/blog/3d-frustum-culling-with-libgdx/). I took the approach with a sphere to include all the possible rotations of the object.

In my testcases  it increases the the performance a lot. 
Should i make a PR with the solution i came up with and we can discuss my approach to the problem?

**Comment by SolarLune** [comment]
Frustum culling sounds good, yeah. I think using the bounding box of the object is how most engines handle it (so rotating the object can make it appear or disappear, rather than the orientation not affecting it).

**Comment by GoranM** [comment]
The libgdx Camera has a [Frustum object](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/Camera.java#L59), which we update on every frame, as can be seen [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L670). I assumed that libgdx used that to do frustum culling, but if that's not the case, then we should definitely add that feature.

So, yes, you can make that PR.

> I think using the bounding box of the object is how most engines handle it

Yes, that seems like the best way, and since bullet already recalculates the AABB for each object, on every frame, we should be able to simply use that information.

**Comment by moshme** [comment]
Ok, i tried to to implement it with AABB, but this works only for Objects which are added to the bullet world and failed for Objects set to "no collosion". I will have a closer look at this tommorow.

**Comment by rafcolson** [comment]
>Ok, i tried to to implement it with AABB, but this works only for Objects which are added to the bullet world and failed for Objects set to "no collosion". I will have a closer look at this tommorow.

Checkout ```GameObject.dimensions()```. This method uses ```getAabb()``` and doesn't fail with "NO_COLLISION" objects.

**Comment by moshme** [comment]
Ok thanks for hint. Yes there are calculations for those objects, which are correct most of the time.

But yesterday i tested it with objects where the center of the model is translated in blender to the edge of the model and so does not match the center of the aabb. It is only this special case which let it fail.

In this case the min and max of the aabb for "NO_COLLISION" objects are messed up. The center of the aabb matches the position of the object(which is in this case not correct) and the box is not created around the model. When i change the physics type of the object to "STATIC" everything works fine. Dont know if this is a bug in Bullet, this needs further investigation.

**Comment by rafcolson** [comment]
Checkout ```bullet.makeBody()``` and ```bullet.cloneBody()``` where ```DefaultMotionState()``` has no [```centerOfMassOffset```](http://jbullet.advel.cz/javadoc/com/bulletphysics/linearmath/DefaultMotionState.html) parameter. Adding this parameter would solve the physics bounding box problem and maybe also the thing you described.

**Comment by moshme** [comment]
Ok i have made a PR because i think the problem mentioned should be fixed somewhere else.
