### ISSUE TITLE
Bug: children artifacts 

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#326]
- Open the default blend. Change "G_Sacky" to "SENSOR". Run the game and jump several times. BDX will crash.

- Now turn on Physics Visualization and change collision bounds for "G_Sacky" to "BOX". Run the game and jump several times. You'll see a stationary artifact of its body.

Conclusion: If children are BOX or CONVEX HULL there's no crash, but in any case there will be artifacts of their bodies.

Working on a solution.

**Comment by GoranM** [comment]
I can't reproduce.

Prior to testing, make sure that you:

* check out the master branch (I'm assuming your master branch is a clean, up to date version of GoranM/bdx)
* compile bdx (run ant)
* create a new project (may not be necessary if your core/libs is a symlink to plug-in libs)

**Comment by rafcolson** [comment]
Oh, alright. That's some good news then. My master branch should be clean, but I'll try updating to GoranM/bdx and see if I can't reproduce too.
