### ISSUE TITLE
Suggestion: Random.seed()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#327]
Hey, there. I think a seed() function would be nice to have in the Random class to allow one to generate numbers and values deterministically. It would help with random generation in games, as people would want to influence the seeds giving different effects to the generation.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR Merged. Thanks! Issue closed.
