### ISSUE TITLE
Suggestion: support for Blender Mesh Origin

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#328]
Currently there is no support for objects that have an origin that differs from the center of mass. The result is that the body will not match up with the model of the BDX GameObject.

I'm not exactly sure how to approach this, but I would like to have a go.

**Comment by GoranM** [comment]
The BGE doesn't support this either.

Actually, the outline of the hull, visible in blender, is drawn around the origin, not the mesh, so the user is guided to expect that.

**Comment by rafcolson** [comment]
Okay, but it's fairly easy to get the local origin of the mesh. I managed to get it, so it's only a matter of adding it to the motion state. If I'm finished with this I'll reference it, so you can have a look.

**Comment by GoranM** [comment]
It's not about the implementation; I'm not sure it's wise to do something that goes counter to what the editing environment implies (in blender, the bounds outline is drawn around origin, so if it's different in BDX, at runtime, it could be confusing).

I wonder what @SolarLune thinks.

**Comment by rafcolson** [comment]
I think you're right. That would be confusing with simple shapes. But with Convex Hull and Triangle Meshes this is not the case. That could be the reason why the BGE only supports origin offset with Convex Hull and Triangle Meshes. We could do the same. So if anyone's interested, I've got it as far as giving each GameObject a new variable "origin", which is the offset Vector.

I'll wait for SolarLune before closing this.

**Comment by SolarLune** [comment]
Hello! It should probably follow the GUI as closely as possible. So, Convex Hull and Triangle Mesh shapes can be offset fine, while the others can be locked to origin.

Having an origin vector that indicates how offset the mesh is from the center would be ridiculously helpful, in my opinion. Please feel free to add that in, haha.

**Comment by rafcolson** [comment]
Well, then the question is: should we implement origin in orientation and scale methods?

**Comment by SolarLune** [comment]
I'm not sure what you mean - could you explain a bit?

**Comment by rafcolson** [comment]
At first sight it might seem that the extra argument [```centerOfMassWorldTrans```](http://jbullet.advel.cz/javadoc/com/bulletphysics/linearmath/DefaultMotionState.html) will actually shift the center of mass, but it will only transform the initial ```startTrans```, if I'm correct.

So orientation and scale methods will still use the bounding box center. And so we should implement origin manually.

**Comment by GoranM** [comment]
> It should probably follow the GUI as closely as possible. So, Convex Hull and Triangle Mesh shapes can be offset fine, while the others can be locked to origin.

Yes, that seems right.

> Well, then the question is: should we also implement origin in orientation and scale methods?

I would expect those methods to operate relative to bounding box center, in all cases.

**Comment by rafcolson** [comment]
Maybe [this discussion](http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=2828) will clear up some things. In summary, in order to actually have support for origin we should add a parent compound shape and shift the child shape.

The extra argument ```centerOfMassWorldTrans``` and method for the body ```setCenterOfMassTransform()``` are a bit misleading in that respect.

**Comment by GoranM** [comment]
Sounds a bit too hacky ... It might be better to simply drop this.

**Comment by rafcolson** [comment]
Okay. Thanks for your replies. But just one last question @SolarLune : Would it still be useful to only have the origin vector as an attribute of the GameObject?

**Comment by SolarLune** [comment]
^ In my opinion, yeah, I think so. Knowing how far off from the center the object's mesh is can be important for some game concepts. It's something that I recently faced in a project, though I don't remember the exact use case in which I needed it.

Just having it as an option would be nice.

**Comment by rafcolson** [comment]
@GoranM What do you think? I can reference the commit if needed.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR merged. Thanks. I think this is a cool addition. However, I think I might have missed something, because ```dynamics(boolean)``` seems broken now. Please except my apologies. I'll be fixing it soon.
