### ISSUE TITLE
Blender Crashes After Exiting When Using BDX

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#33]
Hey. So basically, every time I exit Blender after using BDX in some respect, it crashes. The console remains open and says it's writing out a crash text file, but never finishes. The console's final line reads:

```
Writing: C:\Users\SOLARL~1\AppData\Local\Temp\game.crash.txt
```

indefinitely. That file doesn't contain anything, either. I'm guessing it might be some sort of open thread or handle that never gets closed that BDX is using (maybe the gradle daemon???).

**Comment by rafcolson** [comment]
@SolarLune 
Is it still crashing with you? And have you figured out it is/was caused by IntelliJ?
I'm asking because I was thinking about trying out IntelliJ.

**Comment by SolarLune** [comment]
@rafcolson - No, not really; the console stays open after closing, though. I've never lost data because of the "crashing" (it just printed it out in the console, not literally hard-crashing the actual Blender window). I'd recommend using IntelliJ, if only for developing BDX itself. It's a fairly comfortable IDE.

**Comment by rafcolson** [comment]
Oh, so you mean by crashing that the console stays open after closing?

In that case it couldn't be IntelliJ causing this, because I've always had this issue too. Thanks.

**Comment by SolarLune** [comment]
@rafcolson - That's the thing, it's sporadic. Sometimes it's a "crash" like I mentioned above; other times it's just that the console stays open. I'll close this issue, since it's either benign or non-existent.
