### ISSUE TITLE
Dev: polygon material indices change with upcoming Blender 2.75

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#330]
On [this page](http://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.75/Modeling) you can read about these changes:

>Material assignment
The Material Slot widget has the ability to rearrange the slot order. This affects polygons' material indices (since polygons reference their assigned material by its material slot index).

I'm not sure if this will be relevant to BDX, but I thought it was worth to mention anyhow.

**Comment by GoranM** [comment]
I don't think it affects us; It's just an ability to change the order in the material stack (if I understood correctly), so the underlying data representation should remain the same.

**Comment by rafcolson** [comment]
Okay. Thanks.
