### ISSUE TITLE
Suggestion: dynamicOrRigidBody / staticOrSensor / noCollision getters

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#331]
Hello guys,

Even though we have body types now, often we would only have to know if dynamics are enabled, or if the object is static in Blender terms. We then might want to check through  the ```bodyType()``` getter or the ```body```:
```java
!body.isKinematicObject() && body.isInWorld() // DYNAMIC or RIGID_BODY
body.isKinematicObject() // STATIC or SENSOR
!body.isInWorld() // NO_COLLISION
```
Currently the ```dynamics()``` getter is not exact. Also no collision objects are not kinematic. I noticed this yesterday.
```java
	public boolean dynamics(){
		return !body.isKinematicObject();
```
So my suggestion is to upgrade ```dynamics()``` to ```dynamicOrRigidBody()``` and add convenience methods ```staticOrSensor()``` and ```noCollision()```.

Here's the commit:

**Comment by GoranM** [comment]
Couldn't you simply fix `dynamics()`, to return the proper value for NO_COLLISION objects?

Additional methods seem unnecessary.

**Comment by rafcolson** [comment]
The alternative is to have these checks:
```java
if (bodyType().equals("STATIC") || bodyType().equals("SENSOR"))
	// do something

if (bodyType().equals("NO_COLLISION"))
	// do something
```
That's why I think it would be convenient to have those methods.

**Comment by GoranM** [comment]
If users need to make those checks so often, to where an additional abstraction would make things significantly more convenient, they can (and should) make that abstraction for themselves.

**Comment by rafcolson** [comment]
Okay, thanks.
