### ISSUE TITLE
Suggestion: activate touching objects on end and body type change

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#332]
As title.

**Comment by GoranM** [comment]
For bodyType, is it necessary to call activate on all touching objects?

In theory, you should just be able to activate yourself.

**Comment by rafcolson** [comment]
I guess so. But in order to do this, we maybe could have a convenience method: ```GameObject.activate()```. Users may not now they could activate the body because ```body``` is deliberately kept outside the API. I'll make a new suggestion for this.

**Comment by rafcolson** [comment]
That said, it also may be better to activate the touching objects manually through the ```onEnd()``` method. So I think I'll close this one.

**Comment by GoranM** [comment]
I don't think there's a need to expose activate as part of the public API.

You can just call `body.activate()` at the end of the `bodyType` method.

PS: Suggestion threads exist to determine if it's worthwhile to include the suggested feature. If we decide that it is worthwhile, a PR should be created, and details of implementation should be discussed there.

**Comment by rafcolson** [comment]
Maybe I'm missing something. Earlier you said:

>In theory, you should just be able to activate yourself.

So I would assume you mean that user should do this, whenever they would like to activate themselves:
```java
g.body.activate()
```
But ```body``` is no part of the ```GameObject``` API. And to keep it that way, wouldn't it therefore be be good to have ```GameObject.activate()``` as part of the public API?

**Comment by rafcolson** [comment]
PR merged. Thanks!
