### ISSUE TITLE
Bug: Can't Set Frame on SpriteAnim With Speed Set to 0

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#338]
Hey, there. So basically, you can't set the frame on a SpriteAnim component with its speed set to 0 - it never updates to the desired frame. I'd want to do this to do things like stop a playing animation and keep it stopped.

**Comment by GoranM** [comment]
That should do it.

**Comment by SolarLune** [comment]
Yep, I think that did it. Thanks!
