### ISSUE TITLE
Suggestion: Multiply Light Energy To Match Blender Viewport

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#339]
Hey there. So basically, a point light with an energy of 1.0 is barely visible in LibGDX, which means that generally, you're going to multiply it by a large margin. I propose multiplying it behind the scenes to match up with Blender's scene editor better.

**Comment by rafcolson** [comment]
I thought so of making the same suggestion.

**Comment by SolarLune** [comment]
I don't think I can; falloff and distance don't seem to be things that I can alter without changing the default shader. So I don't think it's possible at the moment.

If we were to create our own "BDX Default Shader", though, we could probably implement falloff and distance correctly, along with the long list of other graphical improvements that we could pull off.

**Comment by rafcolson** [comment]
Yeah, that would be nice. An off-topic question: could such shader also add smooth shading?

**Comment by SolarLune** [comment]
I think so, but I'm not sure. I can tell that the shader at the moment is lighting per-vertex, like Multitexture mode in the BGE, so a per-pixel shader would probably allow for smoother lighting, but I'm not sure about smooth shading like you get when you use Shade Smooth in Blender. 

As a guess, it feels like smooth shading interpolates lighting between faces, but I'm not 100% sure. It's something that can be looked into when we actually do something about it. @GoranM might know more.

**Comment by GoranM** [comment]
I didn't really look into this, but I would assume that there's some libgdx documentation on how one could implement per-pixel lighting in their "environment" system.

It's something to consider.

But, anyway: I don't really care about lighting, so I'm basically fine with whatever you want to do there.

**Comment by SolarLune** [comment]
OK. PR Submitted.

**Comment by SolarLune** [comment]
PR merged, so I'mma close this. Thanks.
