### ISSUE TITLE
Suggestion: GameObject.insideFrustum variable & scene.objectsVisible

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#340]
The ```insideFrustum()``` getter is called at every logic tic, unconditionally. I propose to update a boolean variable on the GameObject, ```insideFrustum```. Game developers might get this variable instead of calling the getter function even though it's already called internally. The getter then could be private.

It may also be convenient to update an ArrayList of id's of objects that are in the frustum. It could be a scene attribute ```insideFrustumHashCodes``` or something.

What do you think?

Edit: Come to think of it, it may well be a list of "visible" objects inside the frustum: ```scene.objectsVisible```.

**Comment by GoranM** [comment]
I think that would be premature optimization.

**Comment by rafcolson** [comment]
Yes, you're probably right. So maybe in the future then.
