### ISSUE TITLE
Bugs: parent(compoundObject)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#343]
Previous to #341 I found also bugs with parenting to compound objects.

A first is when an object is parented to a compound object, BDX will crash when unparenting. This [blend](https://www.dropbox.com/s/0urqszyt1erdgh0/unparent_compound_bug.blend?dl=0) will demonstrate that.

Edit: Can't seem to find a solution. It's the known ```"PHYSICS ERROR: Detected collision between Static objects set to Ghost, with Triangle Mesh bounds: Keep them seperated, or use different bounds."``` in ```Scene.update()```. However, also without ghost objects or triangle mesh bounds.

Edit: I found the fix. Quite happy about this.

**Comment by rafcolson** [comment]
**BugFix: Set margin of compound to zero**

- The total collision margin of a compound object (and its children) is the margin of the compound object plus the margin if the children.

**Comment by rafcolson** [comment]
**Fix: Remove and add the parent body in Parent(null)**

- Bug: crash when unparenting a compound parent.

**Fix: Set compound margin to zero**

- Bug: The total collision margin of a compound object (and its children) turns out to be higher as the margin in the Blender Collision tab. It's the total of two margins. The first is the margin of the compound object itself, the second is the margin of the children. If not set, the margin value will be 0.04, so it's necessary to set the margin of the compound object to zero.

**Fix: Remove bodies of children when compound**

- When a collision object is parented to a compound object, the shape of that object is added to the compound shape of the parent, leaving it obsolete. This causes collision interference when the child is not ghost and redundant physics calculation. Solution is to remove their bodies from the world when compound parenting.
- At initialization the children are hooked to their parents before they are added to the world for the first time, initializing collision groups and masks also. A private addToWorldNoChildren() enables hookParentChild() to happen after this. This changes nothing else. Initialization of collision groups and masks would get complicated if not doing this while adding to the world, so this seems to be the best solution.

**Fix: Compound only for collision objects**

- Bug: A child with NO_COLLISION affects the compound shape, which could be undesireable. And it doesn't make sense really for those to be part of any collision shape.
- To be able to do this anyway, the bodyType could always be changed to anything but NO_COLLISION before parenting to a compound object.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
So Compound parenting now only works with bodyTypes STATIC, DYNAMIC or RIGID_BODY (ghost or not ghost). Only NO_COLLISION and SENSOR will become regular children when parented.

@SolarLune @GoranM About the above. I would appreciate it if you would give your opinion about this. Is this change acceptable and could it be considered as a fix?

**Comment by GoranM** [comment]
... I'm not sure if you want us to discuss this in #347, or here?

I'll post in the new thread.

**Comment by rafcolson** [comment]
PR merged. Thanks a lot for this one!
