### ISSUE TITLE
Suggestion: Make templates public

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#345]
Hey, there. I'm trying to make a randomly generated game, and to do that, I need to know how large the blocks I'm placing are. I'd like to get the dimensions of an average block, but it's currently impossible to do anything with game objects that aren't currently in the game world. 

Making the scene.templates hash map public would allow for this.

**Comment by GoranM** [comment]
I'm not really sure what you mean by "average block", but given a specific object that you want to use, you should be able to simply add it, and then place it, based on dimensions or whatever else.

I don't understand why you need to know the dimensions of a given object before it's actually added to the scene.

**Comment by rafcolson** [comment]
I would strongly suggest against this. We should rethink potential implementation of a DimensionsLocal function, so we would have to take such detours.

**Comment by SolarLune** [comment]
> I'm not really sure what you mean by "average block", but given a specific object that you want to use, you should be able to simply add it, and then place it, based on dimensions or whatever else.

I don't understand why you need to know the dimensions of a given object before it's actually added to the scene.

Because I'm moving all blocks by a singular amount (i.e. the size of a generated room multiplied by the size of a block). I guess the question is, why not make templates public? It also would provide further knowledge into what objects can be placed in the game scene.

> I would strongly suggest against this. We should rethink potential implementation of a DimensionsLocal function, so we would have to take such detours.

Not sure if you're suggesting against my idea or Goran's idea. Whether there were a dimensionsLocal function or not, I'd still need public access to template objects to check their dimensions.

**Comment by rafcolson** [comment]
>Not sure if you're suggesting against my idea or Goran's idea. Whether there were a dimensionsLocal function or not, I'd still need public access to template objects to check their dimensions.

I was under the impression that you needed public access in order to get the dimensions. And I wouldn't think it's a good idea to do that in order to do the other, when the other could be implemented differently. That's all.

>It also would provide further knowledge into what objects can be placed in the game scene.

Could you maybe explain some more why you need access to the templates? I'm sure there's a good reason but I don't quite understand yet.

**Comment by SolarLune** [comment]
> I was under the impression that you needed public access in order to get the dimensions because the latter only works when adding objects to the scene. And I wouldn't think it's a good idea to do that in order to do the other, when the other could be implemented differently. That's all.

OK, I think I get you.

> Edit: Are templates a bit the same as Blender's objectsInactive?

Yeah, basically. Using scene.add() with a String as the argument just pulls the actual game object from the templates hashmap. Allowing access to the templates allows the user to see information about objects that can be spawned into the game world.

**Comment by rafcolson** [comment]
Oh, okay. In that case it would be good to have these public indeed.

**Comment by GoranM** [comment]
> Because I'm moving all blocks by a singular amount (i.e. the size of a generated room multiplied by the size of a block).

I still don't understand why that would require knowing the dimensions of a specific object before you add it to the scene. Couldn't you simply add the object first, and then move it?

> why not make templates public?

Because adding anything to the public API tends to increase overall project complexity.

**Comment by rafcolson** [comment]
>I still don't understand why that would require knowing the dimensions of a specific object before you add it to the scene. Couldn't you simply add the object first, and then move it?

As I tried to explain, yes, I could. But it would be far from ideal with Level Of Detail. For example this would have to be the code needed to update only one of the sections around the player, with your proposed implementation of ```dimensionsLocal```:
```java
public void generateTrees(){
	ArrayList<String> treeNames = new ArrayList<String>(asList("tree0", "tree1", "tree2", "tree3", "tree4"));
	int numTrees = 100;
	int size = 1000;
	
	int sectionRadius = (size / numTrees) * 0.5f;
	int numRowsColumns = (int)Math.sqrt(100);
	for (int x = 0;  x < numRowsColumns; x++){
		for (int y = 0;  y < numRowsColumns; y++){
			Vector3f treePosition = new Vector3f(x, y, 0).plus(Random.vector().mul(sectionRadius));
			Vector3f treeScale = Random.random() * 0.25f + 0.75f;
			GameObject tree = scene.add(Random.choice(treeNames));
			tree.position(treePosition);
			tree.scale(treeScale);
			Vector3f apePosition = new Vector3f(treePosition);
			apePosition.z = tree.dimensionsLocal().z * treeScale.z;
			GameObject ape = scene.add("ape");
			ape.position(apePosition);
		}
	}
}
```
But instead it just could be this, that is, if ```dimensionLocal``` wouldn't require adding objects to the scene first:
```java
// first generate data for trees at initialization (or while loading the game)
public void spawnTrees(int sectionIndex){
	HashMap trees = sections.get(sectionIndex).get("trees");
	for (Map.Entry<String, Object> data : trees.entrySet()){
		GameObject tree = scene.add(data.getKey());
		Vector3f[] properties = data.getValue();
		tree.position(properties[0]);
		tree.scale(properties[1]);
		GameObject ape = scene.add("ape");
		ape.position(properties[2]);
	}
}
```
So would it be to much for the programmer to ask to be able to have everything calculated at loading time? This is only a quick example, but you should see the drawback of your proposed implementation. As a programmer you'll be stuck to the limitation it holds.

Most programmers would naturally assume that you don't have to add any objects to the scene in order for something like ```dimensionsLocal``` to work. It sure would be an exception to the rule. Which other method in BDX needs this? Because of that I also think it would be confusing. You would have to add notes about this in the API to counter this, I'm sure.

**Comment by SolarLune** [comment]
> I still don't understand why that would require knowing the dimensions of a specific object before you add it to the scene. Couldn't you simply add the object first, and then move it?

Thinking about it, I suppose I could.

> Because adding anything to the public API tends to increase overall project complexity.

Could you explain? It is, of course, no extra code - the property is there already. How would making something public instead of private increase complexity? Is there some sort of inability or strong danger involved in reading or providing for the option of changing template objects?

**Comment by rafcolson** [comment]
I didn't realize before that there's not something like ```scene.objectsInactive``` in BDX. Of course in Blender these would be the objects in all inactive layers. But since BDX makes templates for all objects, regardless if they are inactive or not, ```scene.templates``` should be almost the same as ```scene.objectsInactive```. Both enable to get information about objects which are not added to the scene. I think we should have this feature because it has always been a useful feature in the BGE.

**Comment by GoranM** [comment]
> How would making something public instead of private increase complexity?

For one, it's an additional property in the API, which has to be documented, and then further considered in the future; changing anything in the public API can break user code.

Also, while a private field is guaranteed to be used within the hosting class, a public field can be modified by virtually anything, in any part of the system, so it's more difficult to reason about, from a developers perspective.

> Is there some sort of inability or strong danger involved in reading or providing for the option of changing template objects?

I don't think so, but if we make it public, that's something that we would have to think about.

**Comment by SolarLune** [comment]
OK, I suppose I understand. My personal opinion on this is that it'd be worth the risk. It's currently impossible to get that information for a developer who might need it, and there are use cases that would require this property. 

One example would be for the game to know how many unique weapons or items there are in the game. Rather than having to code in how many weapons, hair styles, etc. there are, the developer can just look through the templates hashmap and count the objects that have the property or name that he's looking for.

**Comment by GoranM** [comment]
> My personal opinion on this is that it'd be worth the risk.

Ok.

When you make the PR, I'll merge it.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
This is waiting on you, @GoranM.

**Comment by SolarLune** [comment]
PR merged. Thanks! I'll close the issue now.

**Comment by rafcolson** [comment]
@SolarLune Don't forget to expose ```templates``` in the API.

**Comment by SolarLune** [comment]
@rafcolson Hey, thanks. I did.
