### ISSUE TITLE
Suggestion: "Compound" and "Ghost" arguments for parent()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#347]
Additional method: ```parent(GameObject g, boolean compound, boolean ghost)```.
Existing method: ```parent(GameObject g)``` with  ```compound=true``` and ```ghost=false``` as defaults.

This would add the option to set the child to ghost while parenting, which is convenient. This would also remove **Fix: NO_COLLISION or SENSOR Compound child -> only if not** in #346. Because it enables to parent without affecting the compound shape of the parent.

Edit: This is also how it's done in the BGE, by the way. And if the additional ```ghost``` argument seems to much, because we could set to ghost manually with ```ghost(boolean)```, how about ``parent(GameObject g, boolean compound)```?

**Comment by GoranM** [comment]
If the system is unable to incorporate NO_COLLISION and SENSOR objects as part of a compound parent, then having a method that allows the user to specify whether or not a child should be incorporated doesn't solve the issue: You can still pass true for the compound argument, so you still need to check whether or not the child can be added.

The commit message still seems really confusing. You could just say: `Don't incorporate SENSOR or NO_COLLISION objects into compound shape.`.

**Comment by rafcolson** [comment]
Currently the system forces to incorporate all bodyTypes, including NO_COLLISION and SENSOR objects, as part of a compound parent.

So now the question is whether we should have the option to avoid this manually or automatically. The commit in #343 ensures it will be avoided automatically for NO_COLLISION and SENSOR objects, while an additional method ```parent(GameObject g, boolean compound)``` ensures to be avoided manually. I would prefer the latter, because it leaves it up to the user. So what do you suggest?

**Comment by GoranM** [comment]
Ok, that seems fine.

**Comment by rafcolson** [comment]
Thanks, I'm closing this after adding this to #343 to replace **Fix: NO_COLLISION or SENSOR Compound child -> only if not**.
