### ISSUE TITLE
Suggestion: smooth shading

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#349]
I practically don't know anything about shading, but I want to learn about it, just to get smooth shading in. For obvious reasons this would make the engine more attractive and so would be the games made with BDX.

As far as I know we'll need to export the normal of each vertex of each mesh and incorporate this somehow into a shader program.

Does anyone have any ideas about this or would it be good to ask some help in this area?

@GoranM Did I understand correctly that you're not particularly interested in adding smooth (Gouraud or something else) shading?

**Comment by GoranM** [comment]
> Did I understand correctly that you're not particularly interested in adding smooth (Gouraud or something else) shading?

Yes.

BDX was designed to support projects that focus on gameplay, not graphics.

If someone wants to add certain graphics features, I don't mind, but it's not a priority for me.

**Comment by rafcolson** [comment]
>If someone wants to add certain graphics features, I don't mind, but it's not a priority for me.

I'm having a hard time figuring out how you did the mesh conversion. So I hope you don't mind me asking some questions about this. I noticed you were getting the normal of the polygons in ```exporter.vertices()```, so I was thinking maybe you were taking the polygon normal as input for the vertex normal. Am I right?

Anyway, I would assume that ```ModelBuilder()``` in ```Scene.createModel()``` also needs the vertex normals, so for smooth shading to work I'll need the actual vertex normals when a poly has ```use_smooth == True```.

If you could help me a bit or give me some pointers, I would appreciate it.

**Comment by GoranM** [comment]
> I noticed you were getting the normal of the polygons in exporter.vertices(), so I was thinking maybe you were taking the polygon normal as input for the vertex normal. Am I right?

Yes. As you can see in the code:

```python
for v, uv in zip(poly_verts, poly_uvs):
    verts += v + list(poly.normal) + list(uv)
```

All polygon vertices are set to the same normal (that of the the polygon).

> Anyway, I would assume that ModelBuilder() in Scene.createModel() also needs the vertex normals, so for smooth shading to work I'll need the actual vertex normals when a poly has use_smooth == True.

Yes. It should be possible to simply get the vertex normal, instead of the polygon normal.

**Comment by rafcolson** [comment]
I thought so. That was easy. Thanks for your reply. Hope you don't mind I simplified ```exporter.vertices()``` by looping through the indices once instead of twice.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Thanks for the merge.
