### ISSUE TITLE
Bug: Objects' Dimensions Factor In Margin

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#350]
Hey, there.

So basically, the dimensions() function returns a Vector that includes the margin. I assume this is unintended, as this isn't the case for all objects, just some of them. It depends on which collision bounds type the object uses. 

I would recommend that the dimensions function just return the actual spatial dimensions of the mesh, not including any collision information (so basically, it should just match Blender's dimensions readout).

**Comment by rafcolson** [comment]
I noticed this too. Good reason to just export blender dimensions (inverse
scaled) for every model and store it on the GameObject for getting
dimensionsLocal (=model dimensions * scale), to mimic blender dimensions.
Op 5-jun.-2015 23:45 schreef "SolarLune" <notifications@github.com>:

**Comment by GoranM** [comment]
> It depends on which collision bounds type the object uses.

For which bound types is the margin included?

**Comment by SolarLune** [comment]
I'm getting different results for a Dynamic or a Static object. 

For a Dynamic object, with a margin of the default 0.04, where the object has a dimension of 1 on the X-axis, I get 1.08 for capsule and 1.16 for convex hull.  For other object types, it's correct.

For a Static object, Triangle Mesh also adds the margin in.

In other words, I'm getting different results for different body types and different physics types.

**Comment by rafcolson** [comment]
>In other words, I'm getting different results for different body types and different physics types.

That's bad. And it's kind of weird because margin was set manually, so I wonder what's causing this. For now we could just half margin values where needed. But this is a suggestion on its own.

**Comment by SolarLune** [comment]
Nope, feel free to hack at it, I guess. If we're not doing anything to change the margin and some body types are "getting it wrong", then I guess we should compensate...? Might be a bug in jBullet or somewhere else, I guess...

As for this particular bug, In its current state, if we're not doing anything in particular to add the margin into the dimensions calculation, the easiest and most reliable solution would probably be yours' Raco. Just record the dimensions when exporting the mesh from Blender.

**Comment by GoranM** [comment]
> Just record the dimensions when exporting the mesh from Blender.

That's what we're doing, at this point, so give that a try.

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR merged. @SolarLune Does this fix this issue?

**Comment by SolarLune** [comment]
Yeah, it seems like it does. Thanks! Issue closed.
