### ISSUE TITLE
Bug: Crash on Ending Parented Static Object

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#354]
Hey, there. I'm getting a crash when ending a static object that has a static child, when that child is also a parent to a static object. Here's a blend to illustrate the issue:

https://app.box.com/s/9jp39d2r3qc0s3q5jdcnidnsud9lzpo0

I'm wondering if it's related to #343.

**Comment by rafcolson** [comment]
I started out with the Gorans master. And I could avoid the crash by moving the little cube, or by unparenting it, or by setting Bounds to Box or Compound. What's also weird is that the little cube disappears when the game starts. But when I remove it and add another cube and parent it to the large cube I don't get a crash. My conclusion is that there's something wrong with that particular cube. I don't think it's related to the other thread, but it sure is related to bullet.

**Comment by SolarLune** [comment]
Okay, here's what I found.

Scaling doesn't seem to be part of the problem. It's the positioning of the 2nd child. Something's up with that, separately. 

After some tests, here are some additional findings:

1) Having the cubes positioned like this isn't a problem until we end them. However, if we add another cube and parent it to the last cube, BDX will crash because of the known "STATIC-STATIC COLLISION" bug.

2) The crash seems to appear, going from the child up to the grandparent (the ground) in the test blend file. It happens on the second object, Cube.001. I wonder if it's because the physics is reporting a collision between the bodies and crashing when one of these is removed. Perhaps there's some sort of "collision information queue" that we need to clear before removing objects from the physics world? Just guesses at this point.

3) The crash isn't caused by the objects being removed more than once (i.e. not being in the world, but having "end()" or "scene.remove()" called again).

@GoranM - Any thoughts? Both this and the "STATIC-STATIC" bug are rather annoying when trying to make levels out of individual pieces of geometry, especially randomly generated ones.

A possible hack that would probably work for this would be to move any objects that should be destroyed out to a specific location to ensure they don't collide with anything, or perhaps remake their collision bodies to be anything else. After one frame, we can actually remove it from the collision world... Blah.

**Comment by rafcolson** [comment]
But it only crashes with triangle meshes doesn't it?

**Comment by SolarLune** [comment]
Yeah, the crash only happens if the children have triangle meshes. The crash doesn't happen if their collision types are swapped out for Box or Convex Hull, for example.

**Comment by rafcolson** [comment]
I'm not sure if it could be related to #360, but you never know.

**Comment by SolarLune** [comment]
Maybe so; I'll check out the example blend now.

**Comment by GoranM** [comment]
> What's also weird is that the child cube disappears when the game starts.

I've pushed a fix for that.

As for the crash: I don't know why it's happening. I've made [a thread on the bullet forums](http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=10628), but I don't know how much they'll be able to help, because jbullet seems to be completely unsupported at this point.

We'll see.

**Comment by rafcolson** [comment]
Thanks for the scale fix and for making the thread. Hopefully someone will see what's the problem.

**Comment by rafcolson** [comment]
I've tested if this bug is still present in the current build and it's not. So this could be closed.

**Comment by SolarLune** [comment]
Sounds good, I'll close this, then. If I find the issue's still around, then I'll re-open it. Thanks!
