### ISSUE TITLE
Suggestion: Color() influencing children

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#355]
Hey, there. I think it'd be nice if the color() function influenced the children of an object; that would allow you to more effortlessly color objects that are comprised of other objects, or darken / lighten entire areas, etc.

As a side-note, is everyone still happy with the `function()` and `functionNoChildren()` approach to some GameObject functions? Would anybody rather want just an argument, like `color(float r, float g, float b, boolean children)`?

**Comment by GoranM** [comment]
> I think it'd be nice if the color() function influenced the children of an object; that would allow you to more effortlessly color objects that are comprised of other objects, or darken / lighten entire areas, etc.

I guess that would be fine.

> As a side-note, is everyone still happy with the function() and functionNoChildren() approach to some GameObject functions? Would anybody rather want just an argument, like color(float r, float g, float b, boolean children)?

I prefer the method-based approach, because the function name makes the results clear - An additional boolean argument is something that people would have to look-up.

**Comment by SolarLune** [comment]
Sounds fine. PR submitted.

**Comment by SolarLune** [comment]
PR merged, API updated. Issue closed. Thanks!
