### ISSUE TITLE
Question: useQuantizedAabbCompression for BvhTriangleMeshShape

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#357]
I'm looking into ```bullet.makeShape``` to add support for CONE and CYLINDER and to fix the margin issue. Then I noticed we do ```BvhTriangleMeshShape(mi, false)``` to make triangle meshes for the physics world.

The [docs](http://jbullet.advel.cz/javadoc/com/bulletphysics/collision/shapes/BvhTriangleMeshShape.html) say it's recommended to enable ```useQuantizedAabbCompression``` for better memory usage.  So is there any reason why it's not enabled in BDX? Otherwise I would make the suggestion to enable it.

**Comment by SolarLune** [comment]
> So is there any reason why it's not enabled in BDX?

Nope, not to my knowledge. If it's better on memory usage, we might as well enable it, I suppose.

**Comment by GoranM** [comment]
I didn't research this in depth, but the term "compression" implies a process that would need to decompress the data (somewhere along the line) in order to actually use it.

There are probably performance implications, and maybe other things that we don't know about.

So, that's why I don't use it.

**Comment by rafcolson** [comment]
Thanks for the aswers. I'm not sure what would be the best thing and I don't think it really matters, so I'm closing this.
