### ISSUE TITLE
Suggestions: additions to BDX Game Dev General Overview

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#362]
Among other things I would like to add this to the Wiki's **BDX Game Dev** [General Overview](https://github.com/GoranM/bdx/wiki/General-Overview):

># Object Physics
>...
>Attention: Triangle Mesh bounds is not supported with physics types Dynamic or Rigid Body!
>
>BDX also supports compound objects, which incorporate parented children into their collision shape.
>
>Physics types (or body types) can be replaced. Dynamics can be restored and suspended. Ghost can be enabled or disabled. Mass can be changed.
>
>```java
>bodyType("RIGID_BODY");
>dynamics(false);
>ghost(false);
>mass(1.5f);
>```

Beneath this I would like to add a new subtitle:

># Parent
>
>Objects can be parented or unparented. By default a child will be added to the compound shape of the parent, but this can be disabled.
>
>```java
>parent(null);
>parent(player);
>parent(player, false);
>```

Next I would like to add a new subtitle beneath **Spawning and Removing**:

># Object Mesh
>
>The mesh (or Model) of an object can be replaced, visually, physically or both.
>
>```java
>replaceModel("CarCrashed");
>replaceModel("PlayerCrawl", true, true);
>```

Finally, I would like to add:

># Profiling
>
>To show the BDX profiler, enable "Show Framerate and Profile" in Blender (in Game Info or Display panel of Render Properties). User created subsystems can be timed and will be displayed with internal subsystems. Details can be found in the [API reference](https://github.com/GoranM/bdx/wiki/API-Profiler).

**Comment by SolarLune** [comment]
> Physics types (or body types) can be replaced.

Do you mean that physics types can be changed, or collision types (Box, Cylinder, Convex Hull, etc) can be switched out?

> The mesh (or Model) of an object can be replaced, visually, physically or both.

You might want to mention where these meshes come from (is it the object's name in Blender, or the mesh's name in Blender?).

It all looks useful to know, though, so I'm for it.

**Comment by GoranM** [comment]
The general overview is meant to serve as a quick intro to the basics of the system; It's not meant to cover all available features, with all their details - We have the API docs for that.

If you want to write tutorials, you can, but I think that should be placed in the [written tutorials](https://github.com/GoranM/bdx/wiki/Written-Tutorials) section.

**Comment by rafcolson** [comment]
>The general overview is meant to serve as a quick intro to the basics of the system; It's not meant to cover all available features, with all their details - We have the API docs for that.

Right, I figured as much. I'll close this then. Thanks for you replies.
