### ISSUE TITLE
Suggestion: Make Material-less Objects Have Color Attributes

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#369]
Hey, there. Currently, BDX crashes if you try to color a material-less object; it'd be nice if material-less objects (objects with BDX's default material) allowed for coloring. That should probably also be done for alpha blending, as well.

**Comment by rafcolson** [comment]
That's great! I think this will allows to get rid of the background material of the Profiler.

**Comment by SolarLune** [comment]
Cool. The PR's been merged, so I'mma close this issue. Thanks!
