### ISSUE TITLE
Suggestion: Have Halo track on enter() as well as main()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#375]
Hey, there. 

So basically, if you apply a Halo component to a game object, it will take a frame to activate (which is noticeable). It might be a good idea to make the tracking function separate in the Halo state, and have enter() and main() call that function, thereby (hopefully) bypassing that initial frame.

**Comment by GoranM** [comment]
I'm not able to see it, and I'm not sure how you can:

Even for someone who is highly perceptive, a 16 millisecond delay should not be noticeable.

**Comment by rafcolson** [comment]
>Even for someone who is highly perceptive, a 16 millisecond delay should not be noticeable.

I beg to differ. It's very much noticeable when adding objects using Halo to the scene. Check out [this example](https://www.dropbox.com/s/q07m4nygmpu1ymg/Halo_issue.blend?dl=0).

I'm not sure about the solution though.

**Comment by SolarLune** [comment]
> I'm not able to see it, and I'm not sure how you can.

I don't know how you can't? It always happens. It's impossible to miss it 100% of the time...?

Perhaps some explanation would help. I'm working on a particle system, and so I'm using the Halo component to make the particles face the camera. It works fine, but it's noticeable that the particles are spawned and then, afterwards, face the camera. This is especially so with lots of particles, as they all exhibit the same "flippy" movement.

**Comment by GoranM** [comment]
Oh, you're talking about spawning-in objects with a Halo component - I was under the impression that you were adding a Halo component to an existing object in the scene.

Yes, that is definitely noticeable - I think you can just call state.main in the Halo constructor:

```java
	public Halo(GameObject g){
		super(g);
		state = track;
		state.main();
	}
```

**Comment by rafcolson** [comment]
>I think you can just call state.main in the Halo constructor

I'll have to check, but this solution may be relevant to the Track component also. I'll reference to this issue though.

**Comment by rafcolson** [comment]
PR merged.

**Comment by SolarLune** [comment]
Well there you go. Thanks, guys! Issue closed.
