### ISSUE TITLE
Suggestion: Add Depth Texture to Filters

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#378]
Hey, there. It'd be nice for SSAO and other effects for us to be able to have access to the depth texture. It would appear that the LibGDX Framebuffer already has a depth buffer texture, and we just need to add the uniform in and bind it? I'll take a look at it.

**Comment by SolarLune** [comment]
OK, so it looks like it's not that simple (of course). Seems like we'd have to render everything again to render it out to a depth texture, I guess...? I'll keep this in mind as I investigate around from time to time.

**Comment by GoranM** [comment]
You should not have to render the scene twice.

Can you use gl_FragCoord.z?

**Comment by SolarLune** [comment]
Hm, I'm not sure what you mean - how would I use gl_FragCoord.z in a fragment shader to use depth?

**Comment by GoranM** [comment]
gl_FragCoord.z should give you the depth of the currently processed fragment.

**Comment by SolarLune** [comment]
Tested this, but I didn't get anywhere - not sure if we need to add DepthTest attributes to our materials or something, but simply rendering out gl_FragCoord.z, linearized or not, isn't working.

**Comment by SolarLune** [comment]
Oh, hey, I never reported my findings on this.

It seems like the options might be to:

1) Render the scene multiple times (multi-pass), and provide the depth texture. Or,

2) Make use of GL extensions to allow us to use the depth texture when we render the FrameBuffer, but there's no way to ensure this'll work on all platforms. I think even if we do this, we'll have to detect that the extension isn't supported, and we'd have to fallback to multipass (or, I guess, just not have the depth texture available on those platforms) anyway.

I think I'll try the multipass rendering method first; if it's fast enough and simple enough, then it'll be fine.

**Comment by SolarLune** [comment]
PR submitted. Lemme know what you think. 

Is it possible to just use the distance from a vertex to the camera for the depth, like the fog variable in our default vertex shader? Or would that not work?

The three shaders included is a `depth.frag` shader, which is to show how to correctly render the depth texture, and `depthExtract` frag and vert, which is for correctly creating the depth texture.

**Comment by GoranM** [comment]
> Is it possible to just use the distance from a vertex to the camera for the depth, like the fog variable in our default vertex shader? Or would that not work?

It depends on the use case. For some things, that would probably be enough, but not if you need depth per fragment.

Anyway: I don't know what kind of troubles you had with getting linearized gl_FragCoord.z to work, but simply setting gl_FragColor to a vector where r, g and b are all set to linearized gl_FragCoord.z ... I think that should render the depth.

I don't know if you want to explore that further, or if you just want me to merge the existing PR.

**Comment by SolarLune** [comment]
I don't mind waiting on the PR, but every time I use gl_FragCoord.z, I just get a black screen. Are you sure that you've used BDX's ShaderProgram to visualize depth using that method? I think it used to work in the BGE, but that might've been because the render buffer was created with a depth extension to record the depth under OpenGL 2.1 (or whatever version the BGE was using). Meanwhile, OES_DEPTH_COMPONENT seems to be what we'd use for GLES2 and LibGDX, but I don't think it's supported on all devices. I believe I read that for us to get access to a depth texture on GLES2, we'd need to go for the render-out-to-a-texture-using-a-shader method.

Updated the PR with a type enum for the Camera class and corrected near() and far() functions for orthographic cameras.

**Comment by GoranM** [comment]
> Are you sure that you've used BDX's ShaderProgram to visualize depth using that method?

I didn't test this in BDX, but I used gl_FragCoord in other frameworks, and I know that it's a part of GLES2 (it's in the reference sheet).

gl_FragCoord.z should give depth data when rendering geometry, so I assume that you're seeing black because you're trying to run on an already rendered frame-buffer, where that dimension doesn't exist?

Anyway, tell me when the PR is ready to merge.

**Comment by SolarLune** [comment]
Hmm... Well, I dunno, I mean, it's definitely not working otherwise...
___
Yeah, the PR's ready.

**Comment by SolarLune** [comment]
PR was merged. Nice!

I'd like to add a few depth-related filters, next. I'll create a PR for those soon.

**Comment by SolarLune** [comment]
PR created. I added a little credit for each shader - I rewrote stuff, but got most of the code for the DOF shader from martinsh's, and for the outline shader from felipearts (lunarts, now).

**Comment by SolarLune** [comment]
Ah, whoops. Had to do a slight fix to the depth extraction shader and to transparency. Transparent objects weren't being rendered correctly (i.e. the outline shader just looked square on Sacky). Also, objects that had really low alpha values were still rendered.

Both fixed!

**Comment by SolarLune** [comment]
Sweet, that last PR was merged in, so I'll close this now.

Thanks!
