### ISSUE TITLE
Bug: after #385 the profiler display doesn't seem to work properly

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#386]
Rather peculiar. Now, after #385, the profiler is all messed up with zero's an such.

@billy1380 Did you change anything after my test? Because those commits I tested didn't change anything to the profiler visually, did they?

Edit: anyway, I checked it out. Left padding had to be a space and it seems that there were some redundant spaces in the rest of the line too.

Edit: PR submitted.

**Comment by billy1380** [comment]
It was the same code. Just put it on another branch :( before sending the pr. Thanks for fixing.

**Comment by billy1380** [comment]
@rafcolson I just checked out the or and those changes don't look quite right to me e.g. why remove the spend and replace them with param padding,  and why pad short floats with left spaces string.format would have padded those with 0s based on the format string.

**Comment by rafcolson** [comment]
>It was the same code. Just put it on another branch :( before sending the pr. Thanks for fixing.

Hmm, I don't know what's going on then, other than maybe I made a mistake by thinking I compiled it, but actually didn't.

>I just checked out the or and those changes don't look quite right to me e.g. why remove the appends and replace them with parameter padding, and why pad shorter floats with left spaces when string.format would have padded those with 0s based on the format string.

Visually, it didn't look like it was before but now it does. If you would like change appearance you could make another suggestion. String.format didn't pad those with zero's in contrary to what you are saying. String.format also doesn't add spaces after each formatted value, that's why I removed those.

>I am really struggling to test this because builds based on creating a test game from scratch based on the latest version of the source keep crashing with java.lang.NullPointerException in Scene... because of missing json parameters. I guess I will have to raise an issue about that.

I'm guessing you must be doing something wrong. I'll reply in the other issue.

**Comment by rafcolson** [comment]
PR merged. Thanks. @billy1380 If you can make it so that it works exactly like String.format does, then please do. But for now this will do just fine. It's supposed to be a temporal solution anyway, as @GoranM pointed out before.
