### ISSUE TITLE
Fresh test application crashes on launch.

### ISSUE THREAD

**Issue by billy1380** [GoranM/bdx#388]
Creating a fresh test application crashes after launch when the following steps are followed:

1. get latest version of bdx from github
- build (so that the blender folder contains the bdx build)
- compress the bdx folder into a zip
- from blender add the built zip blugin
- enable the plugin
- create a new bdx folder

If the profiler **has not** been enabled (by checking Framrate and Profile) the application crashes with

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at testgamesf2.inst.iScene.newObject(iScene.java:11)
	at com.nilunder.bdx.Scene.init(Scene.java:197)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:50)
	at testgamesf2.BdxApp.create(BdxApp.java:18)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

If the profiler **has** enabled it crashes with

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.nilunder.bdx.Scene.init(Scene.java:224)
	at com.nilunder.bdx.utils.Profiler.show(Profiler.java:67)
	at com.nilunder.bdx.utils.Profiler.init(Profiler.java:55)
	at com.nilunder.bdx.Scene.init(Scene.java:141)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:50)
	at testgamesf2.BdxApp.create(BdxApp.java:18)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

**Comment by rafcolson** [comment]
There must be something wrong with your setup because everything seems to work fine on my end.

What Blender version are you using and which OS?

Did you always have this problem or since which commit? I recommend you test it with your current setup. You can remove latest commits by resetting head on your repo. ```git reset HEAD^```. If with your current setup BDX fails where before it didn't fail, you'll know your setup has changed somehow.

Maybe you had to downgrade Java to 7? Then it's important your install is clean so it doesn't leave behind any traces of Java 8. You can have a look [here](#291#issuecomment-100217998) if you need to know more about this.

**Comment by billy1380** [comment]
>What Blender version are you using and which OS?

I am using Blender 2.74 on ubuntu 15.04 and that part has not changed.

>Did you always have this problem or since which commit?

I have problems with the contents of master as it stands even after resetting to HEAD but when I switch to the release v0.1.8 it is all good.

Also I just ran `java -version`

and the output is 

```
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

I never did get around to installing java8

Grrr! I will keep trying things, to see if I can find what the issue is. Thanks for the suggestions.

**Comment by GoranM** [comment]
What's the output of `git show HEAD`?

**Comment by billy1380** [comment]
commit 11d052d61498ca432bf87d1e8bfb181d8aadc3b4
Merge: d227669 edaead6
Author: Goran Milovanovic <goran@nilunder.com>
Date:   Thu Jun 18 17:02:51 2015 -0400
Merge pull request #385 from billy1380/stringformatinhtmlissue380
Fix for html build issue (String.format) #380

**Comment by rafcolson** [comment]
>I have problems with the contents of master as it stands even after resetting to HEAD but when I switch to the release v0.1.8 it is all good.

Did you ever successfully run BDX and at what point exactly (before which commit)? You can check this by keeping resetting head, and testing if you can run BDX.

**Comment by billy1380** [comment]
Alright... so started with HEAD set at 4 days ago and started rolling forward (zip, install, create new game, roll forward...) When I got to the current version, it just worked. I am going to send a pull request or the formatter... but the results are the same as @rafcolson just removes the spaces from the units. @rafcolson would you be alright to test that?

Thanks for all the help btw.
