### ISSUE TITLE
Bug: Shadeless Materials Aren't Really Shadeless

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#390]
Okay, so when you turn on Shadeless on a material, we apply an ambient lighting to the material to make it bright. However, these materials can still be lit by other lights. So basically, I'd like to look into making actual shadeless-ness possible, rather than the current simple "hack" that only works correctly when there aren't other lights around.

**Comment by SolarLune** [comment]
OK, looking at this, it looks like it's possible to override the light list for a given material (to make it not be shaded by those lights), but only with LibGDX 1.5.7 or above, not the version we're running. So until we get an update to a newer version of LibGDX, working on shaders would be the other way forward.

**Comment by GoranM** [comment]
I'll update our libgdx version sometime this week.
