### ISSUE TITLE
Html version of the game crashes after downloading the assets

### ISSUE THREAD

**Issue by billy1380** [GoranM/bdx#391]
Error in js console is
```
Uncaught java.lang.RuntimeException: java.lang.ClassCastException(anonymous function) @ html-0.js:13127
```
Error on LibGdx console is
```
GwtApplication exception: undefined
undefined
````

Recompiling so that code maps are emitted results in a different error
```
Uncaught java.lang.RuntimeException: java.lang.AssertionError$setupLoop @ GwtApplication.java:428update @ html-0.js:808onSuccess_2 @ Preloader.java:54onEvent @ html-0.js:3041(anonymous function) @ AssetDownloader.java:222
```

Stepping through the code; the problem does not seem to match the either exception very well. I found that gbullet seems to have an issue with static objects for some reason like the camera, light and the platform in the starter scene.

The exception seems to be triggered because of an assertion in TriangleMeshShape.java 

```java
	@Override
	public void calculateLocalInertia(float mass, Vector3f inertia) {
		// moving concave objects not supported
		assert (false);
		inertia.set(0f, 0f, 0f);
	}
```

**Comment by GoranM** [comment]
This only seems to happen with `html:superDev` - `html:dist` seems to work fine.

**Comment by SolarLune** [comment]
So can this issue be closed? Is the problem still there / unable to be worked around...?

**Comment by billy1380** [comment]
I am happy for it to be closed, not used bdx in a while so not sure if anything has changed.

**Comment by SolarLune** [comment]
@billy1380 - Could you close this then, if the issue isn't major? We'll have to keep it in mind if we can get around to fixing it sometime, though.

**Comment by billy1380** [comment]
No worries.
