### ISSUE TITLE
Completed test game (from tutorial series) crashes after moving to latest release of bdx

### ISSUE THREAD

**Issue by billy1380** [GoranM/bdx#396]
I have followed the instructions to migrate my existing (completed) implementation of the test game but the project crashes in Cloud.java because a null is returned when calling the parent method i.e. returns null when trying to find BL and TR empty(s).

```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.nilunder.testgame.Cloud.init(Cloud.java:25)
	at com.nilunder.bdx.Scene.initGameObject(Scene.java:394)
	at com.nilunder.bdx.Scene.init(Scene.java:269)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:56)
	at com.nilunder.testgame.Player.init(Player.java:25)
	at com.nilunder.bdx.Scene.initGameObject(Scene.java:394)
	at com.nilunder.bdx.Scene.initGameObject(Scene.java:399)
	at com.nilunder.bdx.Scene.init(Scene.java:269)
	at com.nilunder.bdx.Bdx$ArrayListScenes.add(Bdx.java:50)
	at com.nilunder.testgame.BdxApp.create(BdxApp.java:20)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
```

Has something changed in the way groups are treated? I have removed the cloud group and set it up again but still getting the issue.

**Comment by billy1380** [comment]
I have disabled the calls to parent() in the init() method of Cloud and the game works fine, the clouds are displayed, so it does not seem to be an issue with resources or anything like that. Obviously with the TR and BL finding code commented out the clouds do not move. Anyway, thought that might be relevant.

**Comment by GoranM** [comment]
It seems like this bug was introduced in https://github.com/GoranM/bdx/commit/4e51f8ccbffce3caf9aeebae1566150d0b3c274e - "Fix: Compound child collision detection -> remove body".

Example .blend, if anyone needs one: [group_instance_child.blend](https://www.dropbox.com/s/dmqanrgrlawn90t/group_instance_child.blend?dl=1)

@rafcolson 

I'm pretty sure the problem is in this part of hookParentChild:

```java
		for (GameObject g : objects){
			String parentName = g.json.get("parent").asString();
			if (parentName != null){
				g.parent(objects.get(parentName));
			}
		}
```

The json parent is the instance object, not the real object that the instance represents.

**Comment by rafcolson** [comment]
I'm sorry that I messed this up. Wasn't careful enough. I'm searching for a solution and will keep you posted.

**Comment by GoranM** [comment]
I think it would probably be best if we revert back to the original code, which worked properly, and then look for other ways to address the "compound child collision" bug.

**Comment by rafcolson** [comment]
If I'm not mistaken it's only because I changed the order of hookParentChild and addInstances. So I could make a commit to revert this. Would that be okay?

**Comment by GoranM** [comment]
A commit that would undo all the changes made to Scene.java would be fine.

**Comment by GoranM** [comment]
@billy1380 

It should work now.

**Comment by billy1380** [comment]
Nice one... will get the latest version and try it. Thanks.

**Comment by billy1380** [comment]
Like a Boss!
