### ISSUE TITLE
Bug: Framerate and Profiler Window White

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#398]
Hey, there. So, if you show the Framerate and Profiler with the most recent build of BDX, it will just appear as a white square in the corner of the window.

**Comment by rafcolson** [comment]
Are you sure everything's okay with your build? Because it's working on my end.

**Comment by SolarLune** [comment]
Ah, my mistake. I pulled from source, but didn't actually build it - I must have been running a older version. Thanks! Issue closed.
