### ISSUE TITLE
Suggestion: Vector.reflect()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#399]
Hey, there.So, it'd be nice if Vector2f and Vector3f had `reflect(normal)` functions that would take a normal vector and provide a reflected vector. I'm building a game that involves bouncing, and it, obviously, requires some form of reflection.

EDIT: And I don't want to use the built-in restitution as I want to be able to turn the bouncing on or off, not have it on at all times.

**Comment by GoranM** [comment]
Yes, that would be useful ... Actually, it might be a good idea to include gwt-vecmath and gbullet sources into the project, so I don't have to do this stuff myself, and so I can avoid manually swapping the jars.

I'll look into it.

**Comment by SolarLune** [comment]
^ Sounds like a good idea. If you wanted to also add in the reflect function when you push the sources in, it would seem this one works? More testing might be needed, though.

I just coded it from the theory from [this page](http://www.3dkingdoms.com/weekly/weekly.php?a=2).

```java
public static Vector3f reflect(Vector3f input, Vector3f normal){
	return normal.mul(-2 * input.dot(normal)).plus(input);	
}
```

The one for Vectors would operate on the input vector itself, of course, rather than taking an input and a normal vector.

**Comment by GoranM** [comment]
I've included the sources in the new extern directory, so you add this method - Building bdx as normal should automatically detect and compile whatever changes you make, in either library, so you don't need to do anything extra (just run ant in the root bdx directory, as before).

If you're returning a new vector, you should call the method "reflected" ("reflect" would be more fitting for a method that changes the existing vector).

**Comment by SolarLune** [comment]
PR submitted, but I couldn't really test it, as there's no resulting JAR when ant builds for those external source files...? Maybe I'm doing it wrong? Would I create a new project for each external source directory and build a new JAR for them to use them?

**Comment by SolarLune** [comment]
OK, I see that the JARs are automatically built in the libs directory, as before. It tested fine and should be OK to merge now.

**Comment by SolarLune** [comment]
Merged. I'll close this now. Thanks!
