### ISSUE TITLE
About GameObject Touching functions

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#400]
Hey, there. So there's two points I want to consider.

1) I feel like the current touching functions are OK, but also hold back a bit of information. For example, if you check if the player object is touching a game object named "Spikes", it won't return the game object you're touching if you are, but rather just a boolean. I know Java has something to do with that (it's more awkward to type `touching("blah") != null` vs. `touching("blah")`), but I think we should err on the side of providing too much information when we have these kinds of functions and properties. It makes things easier when it comes to doing more complex things, since you don't have to handle loops or checks yourself if you want to, say, damage the player for how much damage power a bullet has. Rather than checking to see if you've been hit, looping through objects to find the one you're looking for, and then checking its value, you can just check the function to see if it's true and get the GameObject itself to work with from there.

2) As a side-note, it'd be nice if there were a couple more functions for checking to see if a GameObject is touching a specific kind of object. Two identifying mechanisms in BDX at the moment are components and game properties. So, I propose two more functions, GameObject.touchingProperty() and GameObject.touchingComponent(). Both would take strings, and would be the name of the property to check for, or the name of the component to check for, respectively. They would loop through touchingObjects and check to see if the objects have a property or component by the name specified. If they find it, they would return a reference to the object (in line with the above point; otherwise, it'd just be a boolean).

These would both be nice because currently, there's no way to assign a "tag" to an object and check for that tag easily (i.e., how spikes, lava, or a bottomless pit can be hazardous to a player object).

hitComponent or hitProperty varients would also be appreciated.

**Comment by GoranM** [comment]
1:

If you look at the implementation of the "touching" method, you'll notice that it's simply a convenience for `touchingObjects.get("name") != null`.

So, if you need a reference to a touching object, you can get it like that.

BTW: Wouldn't it make more sense to have the bullet deal the damage, instead of having the object damage itself? That could also simplify your code somewhat, because you don't have to check for everything that could possibly damage you on every object that can take damage.

2:

I think we should follow existing conventions (which seem sensible), and have `touchingObjects.getByProperty` and `touchingObjects.getByComponent`.

If you want to have convenience methods that return booleans, `touchingProperty` and `touchingComponent` would make sense, as would the corresponding `hit*` methods.

**Comment by SolarLune** [comment]
1) Ah, I see.

Having the bullet deal damage would be better; it was just an example, though. I'm sure as gameplay becomes more complex, having direct access to the game object being touched might be a good idea, though.

2) That seems like a nice middle ground - that way you can get the objects if you need them, but have a simple boolean check if you just want to know.

PR submitted. I also rewrote the hit(objectName) function so that it doesn't fail when working with multiple objects. Basically, if one object is already touching the checking object, then subsequent ones of the same name wouldn't trigger a hit().

The current implementation adds a new class - ArrayListGameObject that has the additional methods and extends from ArrayListNamed. I'd rather not add a new class, but the only other way to do this would be to add get component and get property functions to ArrayListNamed and have them return null for lists that don't contain GameObjects.

I think this works rather well. It'd be nice if there was a way to get the exact object hit in the case of touching multiples (perhaps with an API a bit like the RayHit class), but I guess the developer can code and design their way around that one.

**Comment by GoranM** [comment]
I planned to update our libgdx version and push out a new bdx release last week, but I got sidetracked with other things, so I didn't get to it.

Once I merge in your latest patches, I'll try to get it done.

**Comment by SolarLune** [comment]
Sounds good. Once the PR is merged, I'll close this.

**Comment by SolarLune** [comment]
Thanks for merging this. I'll close it now.
