### ISSUE TITLE
Dev: building issue with jars

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#405]
Hi guys,

How have you been?

Today I deleted my previous fork and forked a fresh BDX repo.

As usual I then clone the repo to my local Github and build bdx in order to start testing the newest version.

But after building a couple of new files appear on my master as changes to be committed:

```
blender/bdx/libs/gbullet.jar
blender/bdx/libs/gwt-vecmath.jar
```

Now, what should I do? Should I commit these to master?

Thanks,

Raf

**Comment by GoranM** [comment]
> But after building a couple of new files appear on my master as changes to be committed

You mean they show up as untracked files?

Building bdx should not automatically stage anything.

> Should I commit these to master?

No.

We now ship the actual source code for those libs, which are built (when necessary) as part of the regular bdx build process.

So, like bdx.jar, they are now simply local data, which should not be tracked by git.

... And with that in mind, we should probably list them in the .gitignore file. 

You want to make that PR?

**Comment by rafcolson** [comment]
Thanks for elaborating.

I don't know how to list anything to the .gitignore file though. It's quite unfamiliar to me. So just go ahead if you want to. I could maybe learn how to do it, but this would have to wait at least a couple of days.

**Comment by GoranM** [comment]
If you google ".gitignore", the first result should give you all the relevant information you need - Basically, it's just a listing of file or directory names that you want git to ignore.

As [you can see](https://github.com/GoranM/bdx/blob/master/.gitignore), our .gitignore file already contains "bdx.jar", so you would just need to add "gbullet.jar", and "gwt-vecmath.jar".

**Comment by rafcolson** [comment]
As simple as that! Thanks for the pointers, Goran. PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks!
