### ISSUE TITLE
Bug: child compound physics initialization issue

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#408]
So after a necessary #397 some issues with compound physics remain.

Basically this is due to the fact that parenting the templates in ```Scene.hookParentChild()``` partially causes objects to be added to the scene twice or when it shouldn't be added at all.

I hope I'll find the solution soon, before the next release, since it's quite trivial that this works properly.

**Comment by GoranM** [comment]
The original problem had something to do with the fact that parenting objects, while they're outside the bullet world, doesn't properly create compound bodies ... Right?

We need to understand that problem in more detail - What is the core reason for that? Is it documented somewhere?

**Comment by rafcolson** [comment]
I'll try to make some time this week. If I don't find an adequate solution I'll give a detailed explanation of the problem, so you could have a look at it. It's a bit tricky, especially with ```Scene.addToWorld``` because this is the only means to apply *group and *mask properties. So basically, even when an object should not be in the world because it's compound parented, nonetheless, at initialization it should be added to the world in ```Scene.addToWorld```.

A quick solution could be to make children ghost instead of removing from the world, but if there's an adequate way to prevent that, I'll prefer the latter. If for any reason you would like to push the next release before the end of the week, then let me know. Then I'll go for a temporary solution with ghost.

Or if you have other ideas or preferences then of course I'm all ears.

**Comment by rafcolson** [comment]
Okay, I'm still quite busy, so it'll have to wait. Sorry, guys.

**Comment by GoranM** [comment]
No problem.

**Comment by rafcolson** [comment]
Okay. So the issue is that compound parenting currently doesn't work properly when set up in Blender (the Outliner).

The problem is originated at scene initialization where instances of the templates are added to the scene *after* children templates are hooked to their parent templates.

So let's say a ```"DYNAMIC"``` *child* object would be parented to a ```"DYNAMIC"``` *parent* object in the Blender Outliner. Starting BDX will first generate the templates of the *child* and *parent* object, then parent the *child* to the *parent* in [```Scene.hookParentChild()```](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L287) before anything is added to the scene in [```Scene.addInstances()```](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L296).

When adding instances the bodies of the children of compound parents shouldn't be added to the world, as shown in [```GameObject.parent(p, true)```](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/GameObject.java#L139). This to prevent the physics shape of the children from interfering with the compound shape of the parent.

So you would think it should be fixed by just removing those bodies from the scene after they had just added. That solves the interference issue alright, but now there's a total different issue when unparenting afterwards. The "DYNAMIC" *child* object is now floating in the air, as if it would have zero mass (although it actually isn't).

The problem goes away by removing and adding the body of the child after unparenting.

Here's the [file](https://www.dropbox.com/s/73ws6emcvu9z59m/outliner_unparent_compound_bug.blend?dl=0).

**Comment by GoranM** [comment]
> So you would think it should be fixed by just removing those bodies from the scene after they had just added.

That would make sense, but for that to work beyond addInstances, it needs to be in addToWorld:

```java
if (!gobj.currBodyType.equals("NO_COLLISION"))
    world.addRigidBody(gobj.body, ...);

if (parentIsCompound)
    world.removeRigidBody(gobj.body);
```

I'm not sure what's causing the floating problem, but I would guess that it has something to do with collision flags/props being improperly set, when the child object is unparented and restored back to dynamic.

If simply re-adding the body makes the whole thing work, we could just do that - I mean, I don't think it would break anything else.

**Comment by rafcolson** [comment]
>If simply re-adding the body makes the whole thing work, we could just do that - I mean, I don't think it would break anything else.

Yes, we could. But it's just so hacky, that I'm annoyed by it. ;)

**Comment by rafcolson** [comment]
>That would make sense, but for that to work beyond addInstances, it needs to be in addToWorld:

It actually only have to work in addInstances. It's an initialization issue. So, there's no problem with compound parenting in game.

Also, the main reason I didn't put it in ```addToWorld``` is because this would do an unnecessary removal of bodies when adding objects to the scene, even in some cases this would be unwanted. Though some objects may have a compound parent in the Blender Outliner, we would still want to be able to add those to the scene separately (for example adding a train wagon).

I'll look into collision flags/props first.

And thanks, by the way.

**Comment by GoranM** [comment]
> this would do an unnecessary removal of bodies when adding objects to the scene

I'm not sure I understand. Wouldn't the creation process be the same?

In your demo, with your patch applied, if you `scene.add("Parent")`, the newly created instance disappears when it hits the floor.

This doesn't happen if you remove child bodies in addToWorld.

**Comment by rafcolson** [comment]
I must have done something wrong, because apparently, as you are saying, the fix doesn't work. I also made some bad conclusions in my previous post. Sorry about that. Anyway, I'll have a look at the second part of the fix as I already made your suggested changes.

**Comment by rafcolson** [comment]
I found the cause! Such a dumb mistake. I completely forgot that currently also with compound parenting the child is set to STATIC, which is not necessary. So now it works. I think this is ready for a PR so I'll just go ahead.

**Comment by rafcolson** [comment]
PR merged. Thanks for the help.
