### ISSUE TITLE
Bug: Transparency Blending Issues

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#409]
Hey, there. So basically, there appears to be some slight transparency blending issues present at the moment. I'm not sure exactly why it appears, but textures with partial transparency seem to be blended against the clear color at the upper half of the game screen, and blended against the ground color at the lower half of the game screen. You can see this in a screenshot of my game project:

![Example](https://lh3.googleusercontent.com/bo7V1xRVSCIav7QqV89ermlNJ_Vss3OjZgKQG4AzAYk=w1560-h860-no)

The shadows of the gas cans toward the upper half of the screen have slight blue squares where they appear to be blended against the sky?

I'm not sure about the specifics, but that's what appears to be the issue, anyway. Any thoughts?

**Comment by GoranM** [comment]
I don't know how libgdx determines what to "blend against", but if it's based on sort order, then what I said in #70 is probably relevant:

> LibGDX already sorts objects, and (as far as I can tell) does so exclusively to support alpha blending. However, the sorting algorithm is of the simple "distance from camera" variety, so if you have object A placed in front of object B, but the origin of B is closer to the camera than the origin of A, you will get rendering anomalies (when objects with alpha are involved).

To test this, move origin of the float plane closer to the camera; If the anomalies disappear, it's a sort order thing.

**Comment by SolarLune** [comment]
Thanks for the tip; that might have been at least part of the problem (as the entire map from the front to the back is a single mesh). I also stumbled upon a workaround, which is that the alpha blending attribute all materials now have defaults to basically putting everything in a single sorting process (i.e. opaque objects aren't sorted apart from transparent objects). 

A PR for this has been submitted, and just involves setting the [blended](https://github.com/libgdx/libgdx/wiki/Material-and-environment#blendingattribute) field of the BlendingAttribute for opaque materials to false.

We might have to set `blended` to true for opaque objects if we want to use blending from this point (maybe?), but this should work OK for now, I think.

**Comment by GoranM** [comment]
> We might have to set blended to true for opaque objects if we want to use blending from this point (maybe?)

I don't really understand what you mean, but since your patch seems to fix the issue, and doesn't appear to break anything else, I merged it.

**Comment by SolarLune** [comment]
Ah, I meant that for blending modes that turn opaque objects partially transparent (where you can see other objects through them), we'd have to enable `blended` to get them sorted better, I guess? But I'm not sure on that; it's just a speculation. Thanks for the merge!
