### ISSUE TITLE
Worldstep Taking Long Time

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#411]
Hey, there. So, I noticed this in my current WIP game project, but it seems like the physics is running rather slowly - I'm getting 13-14% world step in my game of roughly 52 objects without any complex physics setups (i.e. compound colliison or triangle / convex hull shapes).

The FPS and stats reported in the profiler vary wildly when the objects are colliding or not, which might indicate that there's some settings we're missing that are making the physics engine have a harder time resolving collisions, even for static objects? I'm not sure, it's just something that seems to be the case.

**Comment by rafcolson** [comment]
I'm only guessing here, but static bodies are probably less expensive then kinematic bodies. Right now there are no static bodies in BDX, only kinematic bodies, even for objects that have no kinematic value, such as objects of body type "STATIC" or "SENSOR". Maybe doing some tests in this regard are in place?

**Comment by SolarLune** [comment]
Perhaps that would be wise; it seems like even as a (somewhat outdated and unsupported?) port of Bullet, gBullet should be able to handle more than what any of us are throwing at it, so I'm not sure what the problem could be. I'll make a simple test blend file to show the issue further.

**Comment by SolarLune** [comment]
OK, I think I figured it out. The problem is that children of objects never "turn off" their physics bodies - they just remain "on" indefinitely. Attached is an example; note how the game runs slowly constantly. 

https://copy.com/HmhgcZWMxiQcKqtC

If you uncomment the line ```g.children.get(0).parent(null);```, it speeds up eventually as the static bodies are put to sleep. I imagine they could always be put to sleep if they're static - perhaps that's what makes static bodies static (the fact that they have no motion, and so never need to be treated as live, moving bodies like rigid ones).

@rafcolson - You think you might know where the issue lies?

**Comment by rafcolson** [comment]
No, right now I couldn't think of anything else, but to be honest, I've been a little tired on spending time on BDX, for the moment. There's also the compound parent issue that needs to be addressed. I looked into it and just can't find a solution, other then rewinding a rewind and start from there.

I'll have a look this afternoon.

**Comment by rafcolson** [comment]
Two things this commit does:
- make sure only objects with dynamics are activated
- make sure at scene initialization, when instances are added, those of body type "STATIC" are deactivated

**Comment by GoranM** [comment]
> I looked into it and just can't find a solution

You don't have to find a solution. As I said in #408:

> We need to understand that problem in more detail - What is the core reason for that? Is it documented somewhere?

If you understand the problem well enough to explain it clearly, that will probably enable us to find a solution together.

As for the problem in this thread:

I didn't test rafs patch, so I don't know if it resolves the issue, but in either case, we should make sure that it doesn't break anything else, before we consider it a viable solution; I remember that there were certain issues (like #135) where sleeping caused collision inconsistencies, or some other problems.

**Comment by SolarLune** [comment]
> I didn't test rafs patch, so I don't know if it resolves the issue, but in either case, we should make sure that it doesn't break anything else, before we consider it a viable solution; I remember that there were certain issues (like #135) where sleeping caused collision inconsistencies, or some other problems.

OK, I'll test it out myself as well.

**Comment by SolarLune** [comment]
OK, so I've tested it, but I don't see any difference from how it worked before? The test blend file remains slow unless you unparent the children ground objects.

This particular issue isn't really a pressing one since it's not hard to work around (just make sure static objects aren't parented, basically). A quick and simple alternative (which appears to be in @rafcolson's solution) would be to just add activation and deactivation methods, and allow the developer to decide which objects to activate or deactivate as necessary. Not ideal, but it's workable. As a sidenote, those functions:

```java
    public void activateForced(){
		body.forceActivationState(1);
	}

	public void activate(){
		if (dynamics())
			activateForced();
	}
```
could probably just be combined as

```java
     public void activate(boolean forceActivation){
     if (dynamics() || forceActivation)
          body.forceActivationState(1);
     }
     public void activate(){
     activate(false);
     }
```

The second function doesn't save too much time, so it seems like it'd be okay to just have the first one for simplicity.

And it's cool, @rafcolson - you've done a ton of really great work with BDX that I really appreciate. I understand not wanting to work on the engine, as I've also not wanted to work on the engine before. Using it to make stuff brings me back sometimes, though, haha. That's one good thing about open-source stuff is that other people can improve it as necessary. 

Anyway, thanks a lot for your hard work! If you've gotten burned out, feel free to take a break, as long as you need.

**Comment by rafcolson** [comment]
>OK, so I've tested it, but I don't see any difference from how it worked before? The test blend file remains slow unless you unparent the children ground objects.

I've just tested again. It works on my end, so maybe you forgot about something?

>The second function doesn't save too much time, so it seems like it'd be okay to just have the first one for simplicity.

I personally don't like the boolean approach for forced activation. I find it to be less confusing to have a separate function with a descriptive name. Also, note that this kind of "forced" is not the same as the ```g.body.activate(true)``` kind. The method ```g.activateForced()``` is used to be able to activate bodies of 'all' types, "STATIC" and "SENSOR" included.

>And it's cool, @rafcolson - you've done a ton of really great work with BDX that I really appreciate. I understand not wanting to work on the engine, as I've also not wanted to work on the engine before. Using it to make stuff brings me back sometimes, though, haha. That's one good thing about open-source stuff is that other people can improve it as necessary.
>
>Anyway, thanks a lot for your hard work! If you've gotten burned out, feel free to take a break, as long as you need.

Thanks, @SolarLune. I'm glad if my work eventually payed off, I mean, if it has added some value to BDX. I learned a lot from it also. Only a pity that I don't have a career in programming or game creation. I'm just a worker in a warehouse.

**Comment by SolarLune** [comment]
Ah, I did forget I made a new project and forgot to link the project's libraries to my development copy. On doing it, it works first try. Perfect! The test no longer runs slowly at all at first run (and so, doesn't even need to "settle down"). My personal game project that I noticed the problem on also seems to be working flawlessly. Thanks!

The other bug @GoranM linked to seems to work fine with @rafcolson's changes, so that should be OK.

Maybe it'd be a good idea to eventually create a unit test for these kinds of issues? Perhaps just objects falling onto different kinds of objects (dynamic onto dynamic, rigid onto dynamic, rigid onto rigid, parented onto dynamic, compound onto parented, etc)?

**Comment by rafcolson** [comment]
>The other bug @GoranM linked to seems to work fine with @rafcolson's changes, so that should be OK.
>
>Maybe it'd be a good idea to eventually create a unit test for these kinds of issues? Perhaps just objects falling onto different kinds of objects (dynamic onto dynamic, rigid onto dynamic, rigid onto rigid, parented onto dynamic, compound onto parented, etc)?

Yes, that would be a good idea. But for now I think I'll just make my own customized tests to test the commit more thoroughly.

**Comment by GoranM** [comment]
Ok. I'll be waiting for the PR.

> Maybe it'd be a good idea to eventually create a unit test for these kinds of issues? Perhaps just objects falling onto different kinds of objects (dynamic onto dynamic, rigid onto dynamic, rigid onto rigid, parented onto dynamic, compound onto parented, etc)?

What you're describing sounds more like an integration test ... but yeah, something like that would probably help.

**Comment by SolarLune** [comment]
> What you're describing sounds more like an integration test ... but yeah, something like that would probably help.

Yeah, I didn't know the actual name for it, but that's it, I guess. Something to help test out physics (since it seems like possibly the most fragile or complex part of BDX).

**Comment by rafcolson** [comment]
Here's a [TestScene.blend](https://www.dropbox.com/s/9dq2ag5i3uwrvqq/TestScene.blend?dl=0) with some features that may come in handy (or not). Just put it in the blender folder or your project, and after opening it, change the package name end run the script to update the package name. Then press p and play around. You may have to look at the file a bit to know what's in it.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
On second thought, please ignore my earlier statement:

>when instances are added, those of body type "STATIC" are deactivated (**not "SENSOR" because deactivation also deactivates sensory properties, which would imply that from now on "STATIC" will not register collision unless applying activateForced first**)

The bold part is not true. There's no deactivation of sensory properties when deactivating the body.

For this reason also SENSOR can be deactivated, and there's no use for ```activateForced```. Sorry for being messy earlier.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
@SolarLune 

There are some issues with deactivating the body with ```body.forceActivationState(2);``` or ```body.forceActivationState(5);```, respectively ISLAND_SLEEPING and DISABLE_SIMULATION. See [Constant Field Values (JBullet)](http://jbullet.advel.cz/javadoc/constant-values.html#com.bulletphysics.collision.dispatch.CollisionObject.WANTS_DEACTIVATION).

Using this method has the advantage that STATIC or SENSOR objects will be deactivated immediately after the body is added to the world.

But, this seems to cause problems with other DYNAMIC and RIGID_BODY objects in the scene. Those will not go to sleep anymore.

So my suggestion is to take a bit of both sides. Instead we'll deactivate bodies with ```body.activate(false)```. It just takes a few seconds until STATIC and SENSOR objects will be deactivated. The performance bottleneck could probably best be solved by adding STATIC or SENSOR objects over time.

Hopefully this doesn't put you back in your project. But because this previous fix brakes sleeping, I think we have no choice but to make those changes.

**Comment by rafcolson** [comment]
I really feel bad now. Please forgive me for whatever I was missing before, but you should ignore my previous statement:
>But, this seems to cause problems with other DYNAMIC and RIGID_BODY objects in the scene. Those will not go to sleep anymore.

This was probably caused by something else, because now it works just fine with this [test](https://www.dropbox.com/s/r8ddaok98rf5ew4/physics_sleeping_bug_changed.blend?dl=0) file.

So please, @GoranM, accept my apologies and could you change this back? Especially because of the performance advantage this adds to BDX.

A PR is submitted.

PS: I'm done for a while.

**Comment by SolarLune** [comment]
Hey, so this appears to be solved as of a recent build of BDX, so I'll close this. Thanks for your help, guys.
