### ISSUE TITLE
Suggestion: Mouse wheel support

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#413]
As the title suggests.

**Comment by SolarLune** [comment]
Agreed, mouse wheel support would be great to have as an option. I guess it might be implemented like the joystick axes, in that there's a "deadzone" that you would have to scroll past for it to be a valid input? It'd be nice to add it to InputMaps as well, eventually.

**Comment by GoranM** [comment]
Yes, mouse wheel support would be a nice addition.

> I guess it might be implemented like the joystick axes, in that there's a "deadzone" that you would have to scroll past for it to be a valid input?

The wheel usually has detents to turn in discrete steps, rather than continuously as an analog axis, so I'm not sure if a "deadzone" would have any utility there.

**Comment by rafcolson** [comment]
I tried with ```Gdx.InputProcessor``` but couldn't get it working.

Maybe better use ```java.awt.event.MouseWheelListener```?

**Comment by GoranM** [comment]
What did you try?

**Comment by rafcolson** [comment]
I'm not so familiar with the workings of it. I extended InputProcessor to a custom class IP and added this to gdx.input. Then I accessed IP.scrolled(1) and IP.scrolled(-1) to get the necessary info, but I'm always getting false.

**Comment by GoranM** [comment]
You're not supposed to extend InputProcessor - We already have a [GdxProcessor](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/inputs/GdxProcessor.java) that does that.

You simply need to add the [scrolled](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/InputProcessor.html#scrolled-int-) method, which will set the necessary data on the mouse structure.

**Comment by rafcolson** [comment]
Alright. Thanks a lot.

**Comment by rafcolson** [comment]
It's difficult for me to see how it works. I would appreciate it if you could add the changes, or @SolarLune.

**Comment by GoranM** [comment]
Can you be a bit more specific about what you're finding difficult to understand?

If you actually look through the GdxProcessor code, you can see how we update mouse button state via the implemented touchDown and touchUp methods.

**Comment by rafcolson** [comment]
Okay, I got this far. I assume we don't have to "log" anything, or do we? And if so, what do we log?

**Comment by GoranM** [comment]
> Okay, I got this far.

... ?

You just have a method that always returns true.

> I assume we don't have to "log" anything, or do we? And if so, what do we log?

It depends on how you want to track wheel state.

For mouse buttons, I use a log-like structure that records the tick on which the button was either pressed or released. That information is then used by Mouse.btn* methods, to return the proper boolean.

> Anyway, this won't work unless I understand how the GdxProcessor works in conjunction with InputAdaper (or InputProcessor).

GdxProcessor simply extends InputAdapter (which implements InputProcessor, which is documented [here](https://github.com/libgdx/libgdx/wiki/Event-handling))

**Comment by rafcolson** [comment]
>... ?
>
>You just have a method that always returns true.

Exactly, but as you can see in the docs you referred to (and I also searched before) returning true in some unclear cases doesn't mean that you return anything, but "indicates that the event was handled". This I didn't understand.

>It depends on how you want to track wheel state.

I don't think scrolling should be treated as pushing buttons. So just a method ```Mouse.scrolled(int amount)``` returning a boolean would be great.

What I also had in mind was a convenience function to return an integer instead of a boolean, and so the function would be ```Mouse.scrollAmount()```.

```java
public int scrollAmount(){
	if (scrolled(1))
		return 1;
	else if (scrolled(-1))
		return -1;
	return 0;
}
```

**Comment by GoranM** [comment]
> Exactly, but as you can see in the docs you referred to (and I also searched before) returning true in some unclear cases doesn't mean that you return anything, but "indicates that the event was handled". This I didn't understand.

I was referring to your Mouse method, not GdxProcessor.scrolled. The method on the mouse object should not always return true. Actually, it should not even return a boolean, so I don't know what you were trying to do there ...

As the documentation states, the InputProcessor is a "listener interface". The object that implements that interface (GdxProcessor, in our case) is managed by libgdx, and the methods on that object are called by the underlying libgdx system.

You don't call those methods - They're called by the system.

> I don't think scrolling should be treated as pushing buttons. So just a method Mouse.scrolled(int amount) returning a boolean would be great.

This seems unnecessary.

You just need a method that returns an int: 1 for scrolling up, -1 for scrolling down, and 0 when not scrolling.

Basically: Mouse.wheelMove()

**Comment by rafcolson** [comment]
>This seems unnecessary.

I agree. But I assumed that the only way to get information about scrolling is through ```InputProcessor.scrolling(int amount)``` which will return a boolean.

Thanks for explaining all of this to me, but it's still dark before my eyes. I'm sure it's me.

I'm guessing I don't know the least about listening interfaces. I tried to learn more but to no avail, at least, for now. Maybe later.

**Comment by GoranM** [comment]
> But I assumed that the only way to get information about scrolling is through InputProcessor.scrolling(int amount) which would return a boolean.

Libgdx calls GdxProcessor.scrolling, with the current wheel move direction stored in the amount argument.

Implement GdxProcessor.scrolling like this:

```java
	public boolean scrolling(int amount){
		System.out.println(String.format("Wheel event: %d", amount));
		return true;
	}
```

Then run game and scroll the wheel.

Does that make it clear?

If not, be specific about what you don't understand, and I'll try to explain that, if I can.

**Comment by rafcolson** [comment]
I still don't understand where to put this method, so it works. Because the console doesn't print out anything when scrolling the mouse wheel.

**Comment by GoranM** [comment]
The name of the method should be scrolled, not scrolling - Sorry, that was my mistake.

**Comment by rafcolson** [comment]
Ah okay. That's a bit of a relief. Because I think the concept was clear to me from the point you gave the example. Thanks for helping me on my way. It's much appreciated.

**Comment by rafcolson** [comment]
As you can see in the reference above I had recycled the variables of ```UpDownLog``` (which are ```hit``` and ```up```) for the ```codeToLog``` even though they didn't fit the description. But I thought it would be better to make a separate class for scrolling.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR updated. As you can see ```mouse.wheelMove``` is reset after all scenes are updated.

**Comment by rafcolson** [comment]
PR merged.

@SolarLune: Feel free to re-open this for InputMaps support.
