### ISSUE TITLE
Suggestion: Physics Damping support.

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#418]
We could use the Blender Physics Damping properties to set linear and angular damping.
```java
JsonValue physics = g.json.get("physics");
g.body.setDamping(physics.get("damping"), physics.get("rotation_damping"));
```
Only question is if there's a need to expose this to the GameObject API? (I would think not).

**Comment by GoranM** [comment]
Until someone actually needs this, I don't think it's necessary.

**Comment by rafcolson** [comment]
Okay. Then I'll just add support for Blender Translation and Rotation Damping.

**Comment by GoranM** [comment]
No. I'm talking about the feature as a whole, not just exposing it to the GameObject API.

**Comment by rafcolson** [comment]
Ah okay. Then I'll close this for now.
