### ISSUE TITLE
Suggestion: Don't Export if Scene Doesn't Have Valid Camera

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#421]
Hey, there. 

So basically, if you try to use BDX without a camera set (like in a layer different from the one with the camera), BDX will crash out (logically, of course) on start. It'd be nice if this was replaced with a simple error message on export, like "Please set a valid starting camera object for this scene and layer."

**Comment by GoranM** [comment]
The right way to address this would be to generate default camera data, when necessary, just like the BGE.

**Comment by rafcolson** [comment]
I'm assuming this would mean that BDX should also be able to generate a default object. This could also be the foundation for possibly ```scene.addPrimitive()```, ```scene.addEmpty()```, ```scene.addLight()```, ```scene.addCamera()```. But that's another suggestion. Anyway, it would be great if the code for generating data for such default camera could also be used for these other kind of objects.

I've tried this a couple of months ago, but I was having some trouble with building the the JsonValue ```g.json```.

**Comment by GoranM** [comment]
> I'm assuming this would mean that BDX should also be able to generate a default object.

No, because the exporter can simply generate the camera data, which BDX can load normally.

**Comment by rafcolson** [comment]
How could BDX load a camera if there is no camera? Are you talking about the Custom Camera ?

**Comment by GoranM** [comment]
I'm not sure what you mean by "User Camera".

If you have a scene without a camera, the exporter could be modified to create the data for a default camera, as if it actually existed in the scene. Since BDX only knows what the exporter data encodes, if a .bdx file contains camera data, BDX will simply use it.

**Comment by rafcolson** [comment]
>I'm not sure what you mean by "User Camera".

I'm not sure how it works, but the BGE generates the User Camera, so it should be accessible in the bpy, I think. I think it would be nice if BDX would also import this camera if not in Camera View.

>If you have a scene without a camera, the exporter could be modified to create the data for a default camera, as if it actually existed in the scene. Since BDX only knows what the exporter data encodes, if a .bdx file contains camera data, BDX will simply use it.

I understand. But it would be great if the exporter would also create the data for a default object (which would be a large part of the default camera data anyway), and so it would be possible to use this default object, preferably an empty (which is actually a NO_COLLISION cube with no material), for features such as ```scene.addEmpty()```, ```scene.addPrimitive("CUBE")```, ```scene.addPrimitive("UV_SPHERE")```, ... In conjunction with a method ```GameObject.material()``` this would open up a lot of possibilities.

So the suggestion "on the side" is to set the base for later enhancement of the system by providing a default object.

The reason I tried to do this before (but failed) was to work on ```Scene.addJoined(ArrayList<GameObject> objects, boolean endObjects)```, which would first have to create an instance of some default object (which we don't have right now) and then replace its Model with the merged Model.

**Comment by GoranM** [comment]
> I'm not sure how it works, but the BGE generates the User Camera, so it should be accessible in the bpy, I think. I think it would be nice if BDX would transform the default camera according to the transform of this User Camera.

Yes.

> I understand. But it would be great if the exporter would also create the data for a default object (which would be a large part of the default camera data anyway), and so it would be possible to use this default object, preferably an empty (which is actually a NO_COLLISION cube with no material), for features such as scene.addEmpty(), scene.addPrimitive("CUBE"), scene.addPrimitive("UV_SPHERE"), ... In conjunction with a method GameObject.material() this would open up a lot of possibilities.

I'm not really sure I understand the utility of "addPrimitive". I mean, if you need a cube, or anything else, you can just create it in blender, and then make all the instances you need.

> To make it easy, couldn't we just add a Camera to Blender before exporting all objects?

In theory, that should work.

**Comment by SolarLune** [comment]
> To make it easy, couldn't we just add a Camera to Blender before exporting all objects?

> In theory, that should work.

Adding a camera in the blend file if there isn't one already could work, but it seems like altering blend files is something that should be avoided, since it's not something that's apparent or obvious - it's something the developer would have to look up and study to understand why it's happening. 

I think I like a simple message stating, "Hey, add a camera or switch to a layer with one in it" because it's simple and solves the core problem of BDX crashing if a camera doesn't exist. It also prevents the developer from running the game in a layer not set up for it, which is possible with the alternative solutions. The developer could adjust something in a hidden layer, press P to play, wait, and then find out nothing is visible in-game, or just some parts of their scene are, rather than being told they're not where they want to be, basically. 

Another thing we could do is just default to the layer that has the camera in it, assuming one is there already. 

Lastly, we could create a default camera in code and position it at the position of the Blender camera if it's outside of an existing camera.

I kinda agree with Goran about there not really needing to be an addPrimitive -yet-, as you can, of course, make the primitives yourself, and adding code-based functions for this would require constructing the primitives themselves in code, or silently hiding them in template blend files or something and just calling scene.add() with them as the argument.

> The reason I tried to do this before (but failed) was to work on Scene.addJoined(ArrayList<GameObject> objects, boolean endObjects), which would first have to create an instance of some default object (which we don't have right now) and then replace its Model with the merged Model.

This sounds like a good idea for merging things, which can definitely be useful for larger / block-based / randomly-generated games, so I'm all for it. An `addEmpty()` function (or just the ability to pass `null` to the scene.add() function) to add an empty would allow for this, right?

**Comment by rafcolson** [comment]
>This sounds like a good idea for merging things, which can definitely be useful for larger, block-based (like Minecraft), or randomly-generated games, so I'm all for it. An addEmpty() function (or just the ability to pass null to the scene.add() function for an object name) to add an empty would allow for this, right?

I'm not sure about this yet. There may be some problems with it still, such as how to change the class name in case you want to run a java script on the created empty. This is somewhat different from the suggestion in this issue, so I could better open a separate issue when this issue comes around.

**Comment by SolarLune** [comment]
> I'm not sure about this yet. There may be some problems with it still, such as how to change the class name in case you want to run a java script on the created empty. This is somewhat different from the suggestion in this issue, so I could better open a separate issue when this issue is at hand.

Well, that sounds like a general "switching code class for GameObjects" issue, yeah. 

If you wanted to control the merged thing for now, you could change the function so that it would just use the first game object in the array list, or use a designated "base object" argument that all the other GameObjects would be merged into. That way, the developer can provide the empty, so to speak.

**Comment by rafcolson** [comment]
I don't want to go into this deep right now, because it's another issue altogether, but I can say this. I think I'll go for another approach, dropping the idea of creating an empty in game. If I ever complete the code for merging objects it will require to create a "base" object in Blender itself.

So on the subject, maybe we it's good to have an error message when trying to run BDX on an inactive layer. And only generate the User Camera if not in Camera View.

**Comment by rafcolson** [comment]
This is my first attempt of fixing the problem. But there's a problem with reading the transform. In the default scene remove the camera and print ```scene.camera.json``` during the game. You'll see the transform, but for some reason the new camera is not transformed...

**Comment by rafcolson** [comment]
What's so strange is that even though ```json.get("transform")``` is correct, the transposed ```transform()``` is giving other data for translation, ```(0, 0, 0)```, to be exact. You can test by removing the camera of the default scene and adding this to ```Sacky.java```

```java
    public void init(){
        Matrix4f jsonTransform = new Matrix4f(scene.camera.json.get("transform").asFloatArray());
        jsonTransform.transpose();
        System.out.println(jsonTransform);
        System.out.println(scene.camera.transform());
    }
```
If you test this without removing the camera, the outputs are the same. Why the translation gets lost with the generated camera is a mystery.

Maybe you guys could have a look?

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR updated.

**Comment by SolarLune** [comment]
I think this was merged and my suggestion was eventually dealt with, so I'll close it. Thanks.
