### ISSUE TITLE
Suggestion: GameObject.positionLocal() & GameObject.moveLocal()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#423]
Five additional methods:
- positionLocal() - Vector3f
- positionLocal(Vector3f vec)
- positionLocal(float x, float y, float z)
- moveLocal(Vector3f vec)
- moveLocal(float x, float y, float z)

**Comment by GoranM** [comment]
This doesn't really seem to fit with existing "Local" semantics.

I suppose "moveLocal" would fit, if the implementation were changed to simply act on the orientation transformed vector (like velocityLocal), but anything beyond that seems like a bad idea.

**Comment by rafcolson** [comment]
I would also prefer to lose the scale dependency on all these methods, but still I think ```positionLocal``` getter and setters would be useful. Why wouldn't they fit with existing 'local' semantics? I don't quite understand. I remember making use of 'localPosition' in the BGE once in a while. Don't you think such methods are useful?

**Comment by rafcolson** [comment]
So I've adjusted ```moveLocal```. You were right the semantics here should be as in ```velocityLocal```. But what about ```positionLocal``` still? I know the semantics are a bit different here, but how else could it be interpreted then positioning relative to the parent?

**Comment by GoranM** [comment]
> I know the semantics are a bit different here, but how else could it be interpreted then positioning relative to the parent?

I don't know.

Maybe positionLocal would be ok, but until someone actually has a real need for it, in a real game, I'm not sure if it should be added.

**Comment by rafcolson** [comment]
Okay, I'll make a PR, for ```moveLocal()``` only then.

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR submitted.
