### ISSUE TITLE
Suggestion: ChildrenRecursive

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#426]
Hey, there. A `childrenRecursive` function would be useful to have, since otherwise you have to manually step down each child to check its children. 

The use case I'm currently working with is one of spawning lots of parented objects, and trying to get those children through those parents. In my case, I can just loop through all objects in the scene to find the ones I want as it's not that complex, but it'd still be nice to have a childrenRecursive function. 

I guess a nice way to go would be to add this on to the existing ArrayListGameObject so you can just go:

```java

for (GameObject child : parent.children.recursive()){
     System.out.println(child.name);
}

```

**Comment by GoranM** [comment]
Typically, one writes a recursive function to walk a tree:

```java
public void printChildren(GameObject parent){
    for (GameObject child : parent.children){
        System.out.println(child.name);
        printChildren(child);
    }
}
```

But, I guess children.recursive() would be a reasonable convenience, so I think that would be fine.

**Comment by rafcolson** [comment]
Just curious. But why ```children.recursive()``` and not ```childrenRecursive()```?

**Comment by GoranM** [comment]
> But why children.recursive() and not childrenRecursive()?

Well, it's not a big deal, but I would argue that GameObject.childrenRecursive would be better, because I can't think of a case where calling recursive() on anything other than GameObject.children would have any utility.

**Comment by rafcolson** [comment]
I must agree with that.

**Comment by SolarLune** [comment]
It was a function because if it was a list (GameObject.childrenRecursive), it'd have to be updated with each parent / un-parent. With a function, it can just run and get the children recursively when you "ask" for it by using the function.

It didn't make sense to me to have `children` be a normal ArrayListGameObject and have a childrenRecursive() function - it seems better to simply group the function in with the children list. The only other place the recursive() function shows up would be in collision lists, which seems like a minor problem.

**Comment by rafcolson** [comment]
Well, it would make sense if ```GameObject.children``` were to be private and so use ```GameObject.children()```. I don't see a good reason why this also couldn't be a function, since we already have ```GameObject.parent()```. It's another kind of suggestion, but if you guys are up to it, I'm willing to make these changes throughout the whole code.

**Comment by SolarLune** [comment]
GameObject.children() sounds okay to me, I guess. Then childrenRecursive()
would also make sense.

Here's the recursive function I made that used to sit in
ArrayListGameObject's class:
```java
public ArrayListGameObject recursive(){
ArrayListGameObject children = new ArrayListGameObject();
for (GameObject child : this) {
children.add(child);
children.addAll(child.children.recursive());
}
return children;
}
```

**Comment by GoranM** [comment]
> It didn't make sense to me to have children be a normal ArrayListGameObject and have a childrenRecursive() function

It seems perfectly sensible to me: childrenRecursive() needs to be a method because it has to actually do work to flatten the parent-child hierarchy, and return a new list.

The children() method would do nothing more than return the internal datastructure, and that makes it redundant, in my view.

**Comment by SolarLune** [comment]
^ OK, that's fine. Here's a PR.

**Comment by SolarLune** [comment]
PR merged. Issue closed. Thanks!
