### ISSUE TITLE
Suggestion: GameObject.objectID

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#430]
Hey, there. 

So, the discussion on determinism in the replay suggestion thread got me thinking, and there's no way to uniquely identify game objects in games as of yet. You can go by names, but there can be multiples of objects, and between scene or game starts, the hashCodes themselves will probably be random. 

So, I think some sort of ID numbering scheme would be nice to have, since it would allow you to get objects by their numbers, and identify them uniquely, while keeping that scheme across scene and game starts (i.e. the 9th object spawned will always be the Player object in a project, unless you add or remove objects that change that ordering. Since this is the case, the objectID field would allow you to access and use this information to track certain important GameObjects).

We could also build in getting GameObjects by their IDs from ArrayListGameObject, if we just go with a single ID number (probably a scene-based one). A global ID that rises with each spawned object could also be useful, but I can't think of any real need or use for it, so that's OK.

**Comment by GoranM** [comment]
I don't really understand the utility.

What is the actual problem that you're trying to solve?

**Comment by SolarLune** [comment]
Well, the replay example got me thinking that there's no way to identify objects especially across different instances of the game and scene. This could be critical for networking (sending messages to move specific characters on client machines) or more detailed replays (controlling unique objects according to full state-stored replays) in the future. 

Since we know that games are deterministic unless we add random or player-determined elements, being able to numerically identify objects allows you to sync up locations between code and the game, or between running instances (of course, this is depending upon the online functionality implementation).

**Comment by GoranM** [comment]
In a typical network game, where one is trying to replicate server state across multiple clients, the hash of the object, on the server, seems like it could function as a perfectly valid ID that clients can use to manipulate their visual proxies.

So, I don't see why you would additionally need an objectID in that case.

As for replays: I don't really understand what you mean by "more detailed", and why that would require an objectID.

If you can provide a concrete use case, where an objectID is necessary, that would really help.

**Comment by SolarLune** [comment]
Ah, I thought I responded to this. Nah, I can't think of / don't have time right now to go into a concrete use case. I guess I'll close this unless I can think of something later.
