### ISSUE TITLE
Suggestion: Restructuring Blender Scene and Object BDX Props

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#432]
What bothered my about the Object BDX Panel is that Custom Properties are added when using execution priority or custom java class name. By putting these properties in one PointerProperty, named "bdx", users won't be confused so much, I think.

![bdxobjectpanel_custom_property](https://cloud.githubusercontent.com/assets/10002909/9736376/0f2761e4-5641-11e5-9786-c761246dfa12.png)

Well, then I thought it may also be a bit nicer for ```bpy.types.Scene``` to have one PointerProperty, containing all properties. So I changed that too.

This doesn't change anything really, but if you like this commit to be merged, then I'll submit a PR.

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR merged. Thanks.
