### ISSUE TITLE
Suggestion: modify game.blend and remove redundant line

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#434]
Just some cleanup.

The startup blend file can use some adjustments.
- remove Game Properties area, since those are accessible through the Object panel now (and we probably want to encourage that)
- move BDX to the top of the Object panel (for every screen)
- remove Video Editing screen and show grid in 3d View as was suggested by SolarLune

Removal of redundant line in ```createproj.py```.

Edit: added two other things.

**Comment by GoranM** [comment]
Sounds fine.

You should also re-enable display for parent-child relationship lines, assuming there's no good reason to keep them hidden.

**Comment by rafcolson** [comment]
Okay. Do you like those these relationship lines in all screens? Note that I added some other proposals too. (Sorry about that).

**Comment by rafcolson** [comment]
Also changed Player Resolution to 1024 X 576. Is that okay?

**Comment by rafcolson** [comment]
PR merged. Thanks again.
