### ISSUE TITLE
Suggestion: Ability to Change Text Resolution

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#441]
Hey, there. The resolution of text objects is a bit lacking for my current project - I'd like the text to be sharper and crisper than it is currently. It seems like BDX runs a little program to generate a text picture when you start the game - can we add the ability to change how large the generated file is?

**Comment by GoranM** [comment]
[Hiero](https://github.com/libgdx/libgdx/wiki/Hiero) was designed to be a GUI application, to be used directly. I had to hack [the source](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-tools/src/com/badlogic/gdx/tools/hiero/Hiero.java) a bit (and in some ugly ways), to get it working as a command line utility that could be called by the BDX exporter.

Hiero ships in gdx-tools.jar, so I basically had to download the LibGDX source, modify Hiero.java, and then recompile LibGDX to get a new gdx-tools.jar (containing my custom version of Hiero), which I could then ship with BDX.

Unfortunately, at some point, I removed that LibGDX repository from my system, and the modified Hiero.java went with it, so I can't give you the changes I made already, but perhaps you can extract them from the custom gdx-tools.jar that ships with BDX - I don't know how the LibGDX build system was set up, but I think they include the sources by default.

... And that would be a start to adding the feature you want.

**Comment by SolarLune** [comment]
Dang, that's really unfortunate. I can't seem to decompile JARs anymore under Eclipse for some reason, which makes things a lot harder.

Perhaps there's an alternative that's available to command-line usage that we can utilize now?

**Comment by GoranM** [comment]
Well, following the instructions on the Hiero wiki, you can launch the Hiero GUI app, and use it directly to generate the relevant font texture, and the accompanying font (.fnt) file.

Replace the BDX generated font texture with the higher resolution texture that you crated with Hiero.

You'll also need to replace the BDX generated .fntx file with one that contains correct data for the higher resolution texture. Hiero will provide you with a .fnt file, so you'll need to convert that into .fntx - You should be able to make a small python program that can do that, by just copying [the code that does that in BDX](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L717).

**Comment by rafcolson** [comment]
@GoranM I managed to recover ```gdx-tools.jar``` with the latest [Java Decompiler](http://jd.benow.ca/) . I can copy the java code of ```Hiero.class```. But to replace ```Hiero.class``` I should be able to recompile ```Hiero.java``` back to ```Hiero.class```. But how can I do this? 

7-zip can extract ```gdx-tools.jar``` and I suppose zipping it will return it in a jar file, right?

As for the changes I would like to make. I would add a method ```makeBmFont(String ttf, String out, int size)```, so with the extra field ```size```, and calculate the font size by multiplying the default font size (which is 32) by this size value. I would derive the size value from the ```TextCurve.size``` and multiply it by 1.47, which seems to be the constant factor of difference in font size between Blender and BDX.

I didn't make a separate suggestion because I thought it belongs here.

**Comment by rafcolson** [comment]
>Well, following the instructions on the Hiero wiki, you can launch the Hiero GUI app, and use it directly to generate the relevant font texture, and the accompanying font (.fnt) file.
>
>Replace the BDX generated font texture with the higher resolution texture that you crated with Hiero.
>
>You'll also need to replace the BDX generated .fntx file with one that contains correct data for the higher resolution texture. Hiero will provide you with a .fnt file, so you'll need to convert that into .fntx - You should be able to make a small python program that can do that, by just copying the code that does that in BDX.

Very useful. It's nice that with [Hiero](https://libgdx.badlogicgames.com/tools.html) you can apply effects to the font as well.

Saved the font with Hiero (which saves a ```*.fnt``` and a ```*.png```), added prefix ```__FNT_``` to the ```*.png``` and put it in ```assets/bdx/textures```, put the ```*.fnt``` in ```assets/bdx/textures``` and then ran the following python script in Blender. (Beware that with this script the ```*.fnt``` will be automatically removed).

```python
import bpy
import fnmatch
import json
import os
import re

p = os.path
j = p.join

def project_root():
	root = p.join(bpy.path.abspath('//'), p.pardir)
	return p.abspath(root)

def listdir(path_to_dir, recursive=False, full_path=True, pattern="*", files_only=False, dirs_only=False):
	ret = []

	fds = [1, 2]
	if files_only:
		fds.remove(1)
	elif dirs_only:
		fds.remove(2)

	for root_dirs_files in os.walk(path_to_dir):
		root = root_dirs_files[0]
		for i in fds:
			for fd in root_dirs_files[i]:
				if fnmatch.fnmatch(fd, pattern):
					ret.append(p.join(root, fd) if full_path else fd)

		if not recursive:
			break

	return ret

def angel_code(path_to_fnt):
	"""
	Returns dict with relevant angel code data,
	which is retreived from a .fnt file.

	"""
	def line_to_items(line):
		words = re.findall(r'(?:[^\s,"]|"(?:\\.|[^"])*")+', line)
		items = [w.split('=') if '=' in w else (w, "0") 
				 for w in words]
		return [(k, eval(v)) for k, v in items]

	ac = {"char":{}}
	with open(path_to_fnt, "r") as f:
		for l in f:
			(key, _), *data = line_to_items(l)
			if key == "char":
				(_, char_id), *rest = data
				ac["char"][char_id] = dict(rest)
			else:
				ac[key] = dict(data)
	
	return ac

# convert hiero-generated angel code files (.fnt), to proper json files (.fntx)

bdx_dir = j(project_root(), "android", "assets", "bdx")
fonts_dir = j(bdx_dir, "fonts")
fnts = listdir(fonts_dir, pattern="*.fnt")
for fnt in fnts:
	with open(fnt+'x', 'w') as f:
		json.dump(angel_code(fnt), f)

# remove fnt files
for f in fnts:
	os.remove(f)
```

**Comment by GoranM** [comment]
I don't think you need a "decompiler" to get the sources from our custom version of gdx-tools - jar files are just zip archives, so if you unzip them, the sources files should be extracted.

As for compiling a new version of Hiero: I don't think you can actually do it at that level, because Hiero is part of gdx-tools, so you have to rebuild gdx-tools.jar.

I basically just had a copy of the libgdx source where I had my hiero changes, and then I would use their build system to rebuild gdx-tools.jar.

**Comment by songproducer** [comment]
Using @rafcolson's python script gave me a fntx file that couldn't load into Blender.

**Comment by rafcolson** [comment]
@SolarLune I think this can be closed now too.

**Comment by SolarLune** [comment]
Ah, so it can be. Thanks. 

Issue closed.
