### ISSUE TITLE
Suggestion: 2D Screen Filter Downsampling

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#444]
Hey, there. 

So basically, I think being able to down-sample / "render smaller and then upscale" 2D filters would be a nice feature to add. For some context, I'm working with the Bloom filter in my game, and trying to get it to be smooth and run quickly is just a bit difficult, which reminds me of the same problem with Bloom filters in the BGE, haha. 

So, I'm thinking that it should be easier on the GPU to render the bloom shader small, and then upscale it later - I believe this is simple downsampling.

As a guess, this would require a couple of changes. One would be to make a `size` or `resolutionPercentage` property that would set the size of the FrameBuffer the ShaderProgram uses (i.e. resolutionPercentage = new Vector2f(0.5f, 0.5f) to set it to be half the size of the screen). I'd put it on the ShaderProgram because every ShaderProgram can theoretically have different resolution percentages (i.e. a Bloom filter might be downsampled while a Tint filter would probably be run at full resolution).

The other change would be a simple boolean variable called something like `overlay` on the ShaderProgram. This would indicate whether BDX should draw the outputted framebuffer straight:

`Scene render > Effect > Output`

... or overlay it on the previous, unaltered render output:

`Scene render > Effect > Scene Render + Effect > Output`

This way, the "low quality" bloom filter result would be overlaid on top of the normal, high-fidelity game render for the final output for that ShaderProgram.

This is to present the idea - if it's OK'd, then I'll look into it to see if it'll work / if it actually does improve things GPU workload-wise. I'm not sure if simply changing the size of the frame buffer would work, or if we would actually need to render it small for the downsampling to take effect. I guess I'll see when I test it.

**Comment by SolarLune** [comment]
OK, I think I've made some headway into this.

I've added some changes to the API to facilitate downsampling. Here's an example of the API currently.

```java
ShaderProgram shader = ShaderProgram.load("bdx/shaders/2d/default.vert", "bdx/shaders/2d/bloom.frag");
    
        shader.renderSize.x = 0.25f;  // Downsample to 25% of the size of the screen
        shader.renderSize.y = 0.25f;
        shader.overlay = true;            // Overlay the shader over the original screen capture (so the shader should have an ending alpha color of less than 1 to see the effect over the original).
        
        ShaderProgram.nearestFiltering = false;  // Filter all RenderBuffers linearly rather than with nearest filtering.
            
        scene.filters.add(shader);
```

The overlay boolean value allows you to have a downsampled shader without having a downsampled overall render (it'll draw the shadered result over the original scene). 

Nearest filtering makes the downsampled shader render pixelly, while linear filtering automatically blurs it (which is useful for a Bloom filter).

Here's an example - the bloom shader tweaked to run with more samples was running at around 10 FPS:

![badbloom](https://cloud.githubusercontent.com/assets/4733521/10261978/70d12d86-6969-11e5-83cd-4ca0ef8f8979.png)

while the same shader downsampled to 25% of its size with linear filtering was running at a full 60 FPS:

![goodbloom](https://cloud.githubusercontent.com/assets/4733521/10261979/74968998-6969-11e5-837e-8e90efd18c4b.png)

____

Internal code-wise, I added another RenderBuffer to BDX to render the unprocessed scene to for overlaying to work. This is so that we can downsample the tempBuffer when we render it. If we try to downsample the frameBuffer before we copy it to the tempBuffer, the downsampling speed gain is lost (as it's still running the shader on the entirety of the screen, I guess).

Changing the size of a framebuffer to downsample requires that it be re-made entirely, apparently, as I didn't see any means of simply altering its dimensions. This is checked and done every time a filter is drawn, so the tempBuffer is destroyed and recreated every frame that you have multiple resolutions of filters. Not ideal, I know, but I'm not sure of an alternative, apart from perhaps giving each ShaderProgram its own RenderBuffer?

None of this fixes the alpha transparency problems the filter system has currently, unfortunately. I feel like I got a little clue by enabling blending after the batch.begin() command when RenderBuffers are drawn to, but I wasn't able to fix the core problem.

Anyway, check it out and let me know what you think. I've opened a PR for easy comparison.

**Comment by GoranM** [comment]
Suggestion threads should be used to discuss the merits of the proposed feature. Implementation details should be discussed in the PR, assuming we agreed that the feature in question should be added, and therefore warrants a PR to begin with.

I agree that this feature has merit, so in this case it's fine, but please, in the future, don't make PRs until we actually agree on adding a particular feature.

In cases where you really need to show code ahead of time, in order to support the idea itself, you can just push a commit that references the issue in question, and that will make it available in the issue.

**Comment by SolarLune** [comment]
I agree with you, but:

> Suggestion threads should be used to discuss the merits of the proposed feature. Implementation details should be discussed in the PR, assuming we agreed that the feature in question should be added, and therefore warrants a PR to begin with.

When I opened the issue a few days ago and didn't see any response, I just figured I'd go ahead and write the code to confirm it actually would work first.

> I agree that this feature has merit, so in this case it's fine, but please, in the future, don't make PRs until we actually agree on adding a particular feature.

The PR was made to show the additional code, mainly. Usually I would wait until I got some feedback, but since some time passed, I figured I might as well just press on to show the current result. But OK, I'll keep this in mind for the future.

> In cases where you really need to show code ahead of time, in order to support the idea itself, you can just push a commit that references the issue in question, and that will make it available in the issue.

Without a PR, you can't see the differences in the code on Github, right? I guess if you download the source to test yourself, then you can see the additional changes in the latest commits, though, so I guess it is unnecessary for checking changes.

**Comment by rafcolson** [comment]
>Without a PR, you can't see the differences in the code on Github, right?

If your master is up-to-date and your commit rebased, you could simply compare with Goran's master and see the differences on GitHub.

**Comment by SolarLune** [comment]
> If your master is up-to-date and your commit rebased, you could simply compare with Goran's master and see the differences on GitHub.

Oh, really? I didn't know that. Cool!

> Edit: Neat suggestion by the way!

Thanks!

PR updated with the suggestions from Goran.

**Comment by SolarLune** [comment]
Welp, this was merged in, so I'll close it. Thanks!
