### ISSUE TITLE
Suggestion: GameObject.boundsType() and GameObject.collisionMargin()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#448]
In regard to my ongoing suggestion to join meshes (see #437) I would like to be able to change the bounds type in BDX.

For this to work I don't want to duplicate code from ```Bullet.makeBody()``` into ```GameObject.java```. In my opinion it would be better to simply add arguments (body type, ghost, mass, compound and margin) to the method, since those features are variable in game. There's no downside to this than maybe some extra lines in ```Scene.init()``` to pass in the arguments from the JsonValue.

So what do you say? And would there be other scenarios in which this feature could be useful?

**Comment by GoranM** [comment]
Your title states: `GameObject.physics(String bodyType, String boundsType, float margin)`. But then you mention: `(body type, ghost, mass, compound and margin)`. Which one do you actually want to do?

We already have GameObject methods for bodyType, ghost, and mass, so it would make more sense to add `boundsType`, and `collisionMargin`.

**Comment by rafcolson** [comment]
Okay, I'll change the suggestion.

**Comment by rafcolson** [comment]
It appears that it was quite simple to change the bounds type. I first assumed that it was necessary to replace the body, but replacing the shape was enough. I'm not sure if not updating the inertia will cause issues. If so, then we could always make this adjustment.

Is it okay to submit a PR?

**Comment by GoranM** [comment]
Ok. Feel free to make a PR.

**Comment by rafcolson** [comment]
Thanks. PR submitted.

**Comment by rafcolson** [comment]
Thanks for the merge.
