### ISSUE TITLE
Bug: TRIANGLE_MESH origin supported for insideFrustum

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#457]
So not only Bullet's CONVEX_HULL supports origin with an offset to the body's center, also TRIANGLE_MESH does. I've known this for a while, but I forgot to update ```GameObject.insideFrustum()``` to accommodate this.

**Comment by GoranM** [comment]
In cases where you already have a patch for the bug in question, you can just make a PR - there's no need to make an issue.

**Comment by rafcolson** [comment]
Okay, thanks. I'll keep that in mind for the next one.
