### ISSUE TITLE
Small Shader-based Graphical Improvements

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#460]
Hiya! So since we're looking into making our own shaders, I think we can start things off with some really small-scale additions. I'm thinking of:

- Shadeless-ness - This will solve Bug #390 and allow us to set truly shadeless materials. The existing shadeless implementation can be re-purposed to use the Emit slider from Blender to up the "ambient dark level" of a single material.

- A Shadeless function - This will allow us to turn on or off shadeless-ness for a material at a whim.

- Tint function - This will allow us to tint objects; it's like the current color() function, but instead of multiplying the texture and object by the color, it will add the color to the texture and object. Basically, with the function set as such: `tint(1,1,1)`, the entire texture would turn fully white. If it were `tint(1, 0, 0)`, then what was black on the object's texture becomes red. Compare that with the color function: `color(1,1,1)`, where what was black is still black. If this doesn't make sense, here's a little example info*graphic* (haha).

![infographicbig](https://cloud.githubusercontent.com/assets/4733521/10838101/8dc20cc4-7e7e-11e5-8a15-d929c653c12f.png)

On the left is the unaltered sprite, in grayscale. With the current color() implementation, using the color() function to tint the sprite red would make it darker (the next sprite over).

The tint() implementation's red tinting can be seen next - what was black on the first sprite (the outline) is now red. With a full set of 1's for the colors, the tint() function can turn a sprite bright white (which is impossible with the current color() implementation).

The alternative approach to the tint() function would be to just allow the color() function to serve both purposes. A value of 1 and below multiplies the color for each channel, like it works currently, while a value from 1 to 2 would add the color, effectively tinting the sprite. I believe the BGE's color function worked like this. Above 2, the color() function wouldn't really do anything. This would be the cleanest way, I guess.

Thoughts?

**Comment by SolarLune** [comment]
I think a tint() function might be just easier to comprehend so far after working on this? Otherwise we'd have to subtract 1 from each channel and clamp the values, I think?

Also, what do you guys think about cutting out some of the extra color functions? We've got three for color and colorNoChildren - we really could get by with two fine, I think (so we'd probably cut out the ones that auto-set the alpha).

**Comment by GoranM** [comment]
Is there a case in which multiplying color (as we're doing currently) would be desirable? If not, then perhaps it would be better to just make the color function add, instead of creating an additional tint function.

If you think convenience methods for color are unnecessary, feel free to remove them.

**Comment by SolarLune** [comment]
Well yeah, I think you'd want both options. The above example graphic isn't "in-engine", but I think it's correct - I think you'd want both tinting and multiply coloring. Otherwise, you'd never be able to darken or lighten a sprite, and rather be tied to just one option.

I think I'll remove at least one convenience color() method.

I don't think I'll have a shadeless function, as shadelessness is tied to the material, so you can't just enable or disable it for a singular object. Anyway, I'll finish this up soon.

**Comment by SolarLune** [comment]
OK, PR submitted.

**Comment by SolarLune** [comment]
OK, so shadelessness should be able to be altered on a per-object basis, just like any other dynamic property. I'll add a function for it. Otherwise, I should basically be done for this small set of improvements?

**Comment by SolarLune** [comment]
OK, made some fixes and improvements.

- The Shadeless attribute now defaults to shaded, and you set it to be shadeless manually. Of course, the value in Blender writes this when BDX creates the material.
- The attribute dictates by its value whether to make the model render as shadeless or not, rather than its presence as before.
- Every material now gets a shadeless attribute, just like the tint color attribute.
- I removed some print statements I forgot I had in there in Scene.java.

**Comment by SolarLune** [comment]
This was merged in, so I'll close this now. Thanks!
