### ISSUE TITLE
Suggestion: Known Issues Page

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#462]
It might be a good idea to start a Known Issues page to gather known bugs, problems, and limitations in one place. That way one doesn't have to go looking all through the Wiki to find out if there's a problem with something somewhere that's documented.

Thoughts?

**Comment by GoranM** [comment]
This issue tracker is effectively a "known issues page".

**Comment by SolarLune** [comment]
Well yeah, but issues can be closed, even if they're never actually resolved. 

But yeah, I guess this kinda does work in a similar fashion. Never mind, then.
