### ISSUE TITLE
Suggestion: provide latest build once in a while

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#467]
Not everyone will be familiar with building BDX. Since BDX versions are not updated frequently, I'm willing to provide builds after significant changes. Thoughts?

**Comment by Ohmnivore** [comment]
Yeah "nightly" builds would be awesome!

**Comment by SolarLune** [comment]
I'd like more frequent builds too. Not even every new feature needs a new build, but considering how easy it is to build the engine, I think making a build every week (or other time period), or for every major fix (like the last one that fixed ambient lighting) might be easy enough and be a good idea. Please feel free to start this, @rafcolson. Having a dedicated build-bot would be sweet, but not really necessary given how small and infrequently updated the engine is (it's not like, say, Blender itself, where every day a ton of commits are added).

P.S. @Ohmnivore - Hello! Good to see someone else interested in the engine so far.

**Comment by Ohmnivore** [comment]
@SolarLune Hi! I love bdx and how well it's integrated with Blender. It's beautifully light-weight, cross-platform, and provides an editor. Makes me happy :) I'm working on my own engine most of the time though, but I still plan to make at least one game with bdx eventually.

**Comment by rafcolson** [comment]
Hi guys. The easiest way for me to provide this is to "Draft a new release" on my GitHub's repository.

If Goran is okay with this we could add a link in the Wiki to this page:

https://github.com/rafcolson/bdx/releases

Would that be sufficient?

**Comment by GoranM** [comment]
I don't think it makes sense to draft official releases on a fork; They should be drafted here, in the upstream repository to which we all contribute.

It's no trouble for me to create a new release, it's just a question of when that's actually necessary.

Considering the state of this project, I don't think it makes sense to draft frequent releases, but we can certainly discuss that further.

**Comment by rafcolson** [comment]
>I don't think it makes sense to draft official releases on a fork; They should be drafted here, in the upstream repository to which we all contribute.

I agree. Is there a place on this repo to which builds could be uploaded by third parties? I'm sure noone wants to burden you with this.

Or we could drop the whole thing and make suggestions for drafting new releases.

**Comment by SolarLune** [comment]
I think a single suggestion thread asking for a new release would be a simple path to take. I personally get updates whenever any new PR or issue is created or updated (I think?) for BDX's repo. I'd imagine Goran has his account set up the same way, so if anyone thinks a new build would be nice to have, we could just post on that one issue.

**Comment by Ohmnivore** [comment]
^ sounds like a good idea

**Comment by GoranM** [comment]
Since there is a bug, I guess a new release now would be justified: https://github.com/GoranM/bdx/releases/tag/v0.2.1.

I'm not sure if we need suggestion threads for this - I know you want a new release as soon as your PR is merged, but that tends to bump version numbers a little too fast, and there are cases where certain PRs introduce bugs, and then we need to make an additional release to fix that - It's better to let some time pass.

How about drafting a new release every other week, or maybe even monthly, depending on our commit volume?

**Comment by rafcolson** [comment]
Sounds good to me, even monthly. If anyone needs a new release urgently (which may almost never occur) that person could always ask, couldn't he?

Thanks for willing to draft new releases more frequently.

**Comment by GoranM** [comment]
> If anyone needs a new release urgently (which may almost never occur) that person could always ask, couldn't he?

Yes, of course.

**Comment by rafcolson** [comment]
If anyone wants to talk about this more, you could by reopening this issue. Closing.
