### ISSUE TITLE
Suggestion: API - updates for ArrayListGameObject

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#471]
Hi guys.

Currently the API is not up-to-date with ```ArrayListGameObject```, for example ```GameObject.children``` is said to be an instance of ```ArrayListNamed<GameObject>```.

I suppose I could check the code myself, but feel free to beat me to it.

Have a good weekend.

**Comment by GoranM** [comment]
Yes, it's probably a good idea to update that.

**Comment by rafcolson** [comment]
So I updated the API. Added [[ArrayListGameObject|API-ArrayListGameObject]].

Modified description (removed the examples) of [[touchingObjects|API-GameObject#touchingObjects]].

Closing now.
