### ISSUE TITLE
Suggestion: MeshAnim Component

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#472]
Hey, there.

So, given that there's no armature animation yet, there's no method to animate a 3D mesh. Until we manage to get that up and running, I was wondering about suggesting an alternative?

I actually had an old solution for animating 3D objects, and that was my [MeshAnim](https://github.com/SolarLune/SolHelp/blob/master/BDX/bdxhelper/src/com/solarlune/bdxhelper/components/MeshAnim.java) component; I was wondering if there was any interest in adding it in? It's basically functionally the same as a SpriteAnim component, but replaces the entire mesh of the GameObject instead of animating its UV values, but only when it needs to.

The animation format would be:

```java
ma = new MeshAnim(this);
ma.add("walk", "PlayerWalk0", "PlayerWalk1", "PlayerWalk2", "PlayerWalk1");
```

With those "PlayerWalk" meshes existing in Blender for the MeshAnim function to use.

Thoughts?

**Comment by rafcolson** [comment]
I like it for sure. Even if in future releases armature mesh deformations are supported, this could still be a useful component (in my opinion).

**Comment by GoranM** [comment]
I'm not sure if it's wise to give the impression that "mesh frames" are the way we generally intend to support 3D animation in the system.

If there's really a pressing need for armature support, then getting that to work should be the focus.

**Comment by SolarLune** [comment]
@rafcolson - Thanks, I agree. Even once armature animation is up and running, this could fill a need for a different style of 3D animation.

@GoranM - Well, I wouldn't really say adding this gives the impression that this is how 3D animation should go in the future, but rather that it's something for intermediate animation before (or even after) armature support's up and running. I mean, obviously the FAnim component, for example, isn't all we plan to do for 3D animation, so I'd think people wouldn't get too tripped up on the "wishlist".

The usefulness of the concept is pretty solid, I think, as it would allow you to make more severe changes more quickly than armature animation could allow for (like completely removing faces, or adding faces, or changing face colors, for example, during an animation).

**Comment by GoranM** [comment]
> The usefulness of the concept is pretty solid, I think, as it would allow you to make more severe changes more quickly than armature animation could allow for (like completely removing faces, or adding faces, or changing face colors, for example, during an animation).

Ok, that makes sense.

**Comment by SolarLune** [comment]
OK, I've got it working. I ended up working with the current incarnation of the SpriteAnim component as a base. It has all of the stuff that you'd expect it to have from SpriteAnim (i.e. frame() functions) with none of the stuff that doesn't apply (i.e. UV Scale functions).

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!

**Comment by SolarLune** [comment]
I've updated the API; not sure how I feel about the Animation page containing information for both SpriteAnim.Animation and MeshAnim.Animation, but they're so similar that it might not be too much of a problem. If necessary, we could make the Animation class generic, I guess? Well, it's working for now, so I guess it's no big deal.
