### ISSUE TITLE
Suggestion: Alpha Function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#474]
Hey, there! I was wondering what you guys thought of convenience alpha() function. It would just set the alpha of the object by calling the color function, but with the object's color on all parameters except for the alpha. For example this:

```java
Vector4f c = color();
c.a = c.a + 0.1f;
color(c);
```

could become this:

```java
alpha(alpha() + 0.1f);
```

Thoughts?

**Comment by rafcolson** [comment]
Close to redundant, but I would say yes.

**Comment by SolarLune** [comment]
You know, I don't really like the redundancy either, but I do like the alpha function. What if the color function didn't allow you to set the alpha component, and it just altered the color of the object? They are two separate concepts (the color of an object, and the transparency of an object); they just happen to be stored together in a single value (the diffuse color attribute). Maybe the color() function could just take and return Vector3fs?

I mean, when you think about it, you can't, for example, fade an object's color to black by doing this:

```java
color(color().mul(0.1f));
```

... Because it will also alter the object's alpha component. Maybe we should also adjust the color functions to just deal with the diffuse color, and not the alpha value?

**Comment by rafcolson** [comment]
That makes sense to me. I personally would prefer these functions:
```color()``` - Vector3f rgb
```color(Vector3f rgb)```
```color(float r, float g, float b)```
```color(Vector4f rgba)```
```color(float r, float g, float b, float a)```
```alfa() - float a```
```alfa(float a)```

**Comment by SolarLune** [comment]
Eh, I dunno. I already removed a couple of the convenience color functions in favor of just having a few; I think I'd rather not have additional functions if possible.

**Comment by GoranM** [comment]
Sounds fine.

**Comment by SolarLune** [comment]
OK, so what do you think, @rafcolson? Do you think there can be too many convenience functions?

**Comment by rafcolson** [comment]
Well, I think we could have as many, as long as there are use cases.

I would prefer to also have the current (Vector4f) Color method. I don't mind if we don't have those with the rgb(a) arguments.

**Comment by SolarLune** [comment]
> I would prefer to also have the current (Vector4f) Color method. I don't mind if we don't have those with the rgb(a) arguments.

I'm not sure if I understand - can you clarify?

**Comment by rafcolson** [comment]
Sorry.

I meant that this is okay for me:

color() - Vector3f rgb
color(Vector3f rgb)
color(Vector4f rgba)
alpha() - float a
alpha(float a)

**Comment by SolarLune** [comment]
OK, I got it. I'm not sure what use case we could have for needing to set all R, G, B, and A components at the same time through a vector, though? Except for maybe "initializing" the color and opacity of the object at one time (like if a character or object dies and gets respawned)?

**Comment by rafcolson** [comment]
Preserving this method allows a little more freedom in my opinion. But I
don't mind if you would remove it from the api. Just make sure to update
the codebase.

**Comment by SolarLune** [comment]
Eh, I've been thinking about this for awhile, and I never really liked any of the solutions. I think I'm just gonna drop it for now; it's not a big enough deal to worry about, haha. I would add the alpha() function, but that would make the color setting function a bit redundant, and I think it best not to have that. We can leave it alone, for now, at least.

**Comment by SolarLune** [comment]
Reopening because I'm doing alpha stuff again and it's a bit ugly without an alpha function.

**Comment by SolarLune** [comment]
I was going to submit a PR, but I keep thinking of adding a Color class of our own. Something that would allow us to set Hue, Saturation, and Value, and that would allow us to easily set alpha, too. That might be the best of both worlds?

**Comment by GoranM** [comment]
I'm not sure that we need a custom "Color" class.

I'm ok with having an alpha function.

**Comment by SolarLune** [comment]
I think it'd be useful just for HSV, but it's up to you. PR submitted.

**Comment by rafcolson** [comment]
Is it really necessary to remove the ```color(rgba)``` methods?

**Comment by SolarLune** [comment]
We can keep that in, but do we really need to set the color at the same time as setting the alpha? Also, should we add colorNoChildren(rgba)?

This also influences Light.java, as the color functions need to essentially ignore alpha, as there's no materials to set color or alpha on.

**Comment by rafcolson** [comment]
>We can keep that in, but do we really need to set the color at the same time as setting the alpha?

I think in some cases we do. Even the color class of LibGdx holds the alpha component.

>Also, should we add colorNoChildren(rgba)?

I don't think we should mind about the quantity of methods spent on 'color'. I do think a method ```colorNoChildren(rgba)``` is logical.

>This also influences Light.java, as the color functions need to essentially ignore alpha, as there's no materials to set color or alpha on.

I see your point.

Maybe we could have just tree methods: ```color() - Color rgba```, ```color(Color rgba)``` and ```colorNoChildren(Color rgba)```, instead of ```color(float r, foat g, float b, float a)```, ```color(Vector4f r, g, b, a)```, ```colorNoChildren(float r, foat g, float b, float a)``` and ```colorNoChildren(Vector4f r, g, b, a)```.

This way it's possible to set rgba values at the same time and we have the benefit of being able to use valuable [methods of LibGdx's Color class](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/Color.html).

Well, that's what I would do. I'm sorry to bring this up one more time, but do whatever you and Goran decide.

**Comment by SolarLune** [comment]
Hmm, that does make sense. LibGDX's Color class adds some useful stuff, for sure, like lerping.

See, if we had our own Color class that extended LibGDX's, we could make a couple of changes / additions:

1) We could overload the alpha() function to return the color instance, allowing you to oneline stuff:

```java
color(color().alpha(0.25f));
```

2) We could add alphaAdd() and alphaSub() functions to allow you to easily add and subtract alpha values:

```java
color(color().alphaSub(0.05f));  // Fade-out alpha
```

3) We could add add() and sub() functions to add or subtract a single amount from all RGB components, rather than having to type all of them out.

```java
color(color().sub(0.1f));  // Fade-out color, rather than this:

color(color().sub(0.1f, 0.1f, 0.1f, 0));
```

The mul() function kinda works like this already in that you can provide a single value, but multiplication is, of course, different from subtraction, and it multiplies all components, rather than just the color components.

We could also just have it subtract all RGBA components, and rely on the user to set the alpha again manually later.

4) We could have HSV alteration, which is really useful when randomly generating color and you want a selection of colors of a specified brightness, saturation, or hue. Like, say, for randomly generated equipment that are all "cold"-element, we could restrict the hue to a specific range.

Example:

```java
Color c = color();
c.hue(Random.random(0.1f, 0.2f));
c.saturation(0.5f);
c.value(0.75f);
color(c);  // Sets the HSV
```

Of course, these can also return the instance for easy one-lining, as well.

**Comment by rafcolson** [comment]
I think I would like an extension of the Color class also. It's pretty convenient.

**Comment by GoranM** [comment]
Ok, that sounds reasonable.

**Comment by SolarLune** [comment]
Hmm, I was able to get the functions up and running and HSV stuff, but the built-in LibGDX color functions won't work because they're not generic (i.e. most return an instance of the LIbGDX color class, not the new BDX one). 

Ideas?

**Comment by Fr0sk** [comment]
If you extend the LibGDX color class, you might want to create a function that accepts the gdx color and returns a bdx one and override the methods to return the bdx color one making use of that function

**Comment by SolarLune** [comment]
Yeah, that's what I had to end up doing. Thanks for the tip!

PR submitted.

I added convenience functions for fading the color component, the alpha component, and HSV support.
I also added Random.color(); lemme know if that's undesirable, @GoranM.

**Comment by SolarLune** [comment]
PR merged, so I'll close this now. Thanks!
