### ISSUE TITLE
JBullet Vs LibGDX's Bullet?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#480]
Hey, there!

I know the current physics engine we have running under BDX is jBullet, and I was wondering what the thoughts were that went into choosing jBullet vs LibGDX's Bullet wrapper. 

After some Googling, it looks like jBullet is a somewhat outdated, unmaintained port of Bullet, but a full Java port, which means we can use it in GWT (HTML5)?

On the other hand, LibGDX's Bullet wrapper wraps Bullet's C++ library, which means it's maintained and fast (according to @Xoppa in [this older thread](http://www.badlogicgames.com/forum/viewtopic.php?p=76592&sid=0b30173738a90aa4f9003be569bb2417#p76592)), but [can't be used on GWT](https://github.com/libgdx/libgdx/wiki/Bullet%20Wrapper%20-%20Setup).

Is that about right?

**Comment by GoranM** [comment]
Yes.

In addition to GWT compatibility, the jBullet API is also much nicer/easier to use; The native wrapper is very slim, and more efficient, but it requires the user to manually manage bullet memory, and to worry about some additional "C++ interface" details.

**Comment by SolarLune** [comment]
Hm, I see. Okay, I guess it's no big deal as long as jBullet works fine, which it has, for the most part.

Issue closed.
