### ISSUE TITLE
Speeding Up Export and Run

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#483]
Hey, there. So, it seems like the Export and Run process could be streamlined and made more efficient; it can take 10, 20 seconds to do this for a scene with even a moderate number of faces (say, 30000). This isn't that outrageous, either, as I'd imagine it would be worse, or at least the same, for a large number of scenes with less faces in those scenes (i.e. 10 3000-face scenes). 

I'll do some more tests later on, but if anyone has any ideas about speeding up the exporting process, I'd like to hear 'em! 

You can test this yourself by just subdividing an object in the default test scene until there's a pretty good number of faces, and then trying export and run.

**Comment by SolarLune** [comment]
Just to make sure I'm not crazy, I tested the lighting demo blend with the ground plane subdivided multiple times - the scene contains 22,380 triangles. It took around 1:45 to export everything before the "---BDX START---" message was printed to the console. After that, it didn't take long to actually start the game, but it crashed with an "OutOfMemoryError: Java heap space". It looks like it crashed on building the MeshBuilder, probably when building the ground plane.

So, there's two issues here. Firstly, it takes too long to export and run a game, and secondly, we get an out of memory error under some conditions. To actually solve the latter problem effectively, we should probably look into actually solving the prior one so that we can do multiple tests with larger swaths of data. So, here are some ideas:

1) Optimize the exporting and running process. I imagine the exporting process hasn't been optimized, so it might be possible to squeeze out some more performance by just optimizing the process in the add-on.

2) Add a "Run" button that just runs the game without exporting it. This way, unless you make alterations to the .blend file, you can just run the game again without exporting any data. If there's no data exported, then this can just act like the "Export and Run" button.

3) Just export things if the blend file has actually been altered since the last export. This way, we don't waste time exporting scenes that already have been created.

4) Split the exported process up to export more files, and **smaller** files. For example, rather than having one BDX file for an entire scene, we could have one BDX file for a material, one for a scene (placement of objects), one for the object with its model / mesh, parameters, and so forth for each kind of resource we have contained in our current BDX format. 

The add-on would then only export the items that don't have an exported file already, or that have been altered since the last export. This would probably one of the better options, as we would see an improvement in speed over repeated exports as the data mostly remains unchanged. So, even with huge games with tons of high-poly assets and scenes, the export process would only slow down the less you playtest your game, in a sense. 

Also, by splitting up the files, we wouldn't have to deal with a single huge scene file, but rather, a number of smaller, more contained files that we can open, read, and close in succession, thereby lessening the memory that Java would need to consume at once. This, however, wouldn't help just straight-up huge meshes that the exporter needs to deal with; I guess we'll have to just improve the process (method 1, above) to deal with this effectively.

As a side-note, I'm just guessing that the "OutOfMemory" error might just be the way we're executing Java or something; just something we need to tweak elsewhere.

Thoughts?

**Comment by rafcolson** [comment]
>Just to make sure I'm not crazy, I tested the lighting demo blend with the ground plane subdivided multiple times - the scene contains 22,380 triangles. It took around 1:45 to export everything before the "---BDX START---" message was printed to the console. After that, it didn't take long to actually start the game, but it crashed with an "OutOfMemoryError: Java heap space". It looks like it crashed on building the MeshBuilder, probably when building the ground plane.
>
>So, there's two issues here. [...]

One issue really. This ```OutOfMemoryError``` in Java can't be avoided since the array of indices is a short array, and Java's maximum short value is 32,767. See for more info: https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX#maximum-vertices

**Comment by SolarLune** [comment]
Ah, well that makes sense. At least that should be easy to fix, then. So then just speeding up the export process is the only missing part.

**Comment by rafcolson** [comment]
About optimization. I like the idea of updating while exporting instead of exporting everything once over again. But I wonder if using different extensions would become necessary. For example an object could be named "Cat", resulting in: "Cat.bdx", but so could be a material named "Cat".

**Comment by SolarLune** [comment]
Well, we could have a folder for each kind of resource:
`/bdx/materials/Cat.bdx`, `bdx/scenes/Cat.bdx`, `bdx/objects/Cat.bdx`, etc.

Or we could have different extensions for different resources, like you mentioned (`Cat.bdxs` is the scene named "Cat", `Cat.bdxo` is for the "Cat" object, `Cat.bdxm` is for the cat's material, etc).

**Comment by GoranM** [comment]
As I said in #264:

> A few things that would be helpful there:
>
> * A .blend example where export time is too long.
> * Measured execution times for "srl_" functions, relative to the execution time of the export function.

Exporting all the scenes, even when they didn't change, would probably have significant benefits.

As for everything else: Concrete profile data is required to properly orient optimization efforts.

In addition to timing "srl_" functions, I would recommend timing the json.dump call. If the time for that is a significant portion of the total scene export time, I would recommend splitting json.dump into a json.dumps call, and a file write for the resultant json string. With that, you can measure json parsing time separate from the time it takes to actually write all that data to disk.

**Comment by rafcolson** [comment]
>1) Optimize the exporting and running process. I imagine the exporting process hasn't been optimized, so it might be possible to squeeze out some more performance by just optimizing the process in the add-on.

Let's time the ```json.dump``` call and split things up if necessary. The issue seems to immerge above a certain vertex count. So it could be a reading or writing problem. For example I remember when importing image data with LibGdx, anything higher than 1024 X 1024 would 'freeze' the process.

>2) Add a "Run" button that just runs the game without exporting it. This way, unless you make alterations to the .blend file, you can just run the game again without exporting any data. If there's no data exported, then this can just act like the "Export and Run" button.

I'm all for this one. I think this is a good idea, and shouldn't be to hard to implement. Most of the time we would be coding and previewing, while just once in a while we would be changing things in blender. This would save a lot of time indeed. @GoranM what do you think?

>3) Just export things if the blend file has actually been altered since the last export. This way, we don't waste time exporting scenes that already have been created.

This would be the alternative approach, but I think a "Run" button would give more clarity. Else we would have to expressively give a warning in the API that you should save the blend file first in order to see changes in BDX.

>The add-on would then only export the items that don't have an exported file already, or that have been altered since the last export.

I'm curious. How would you be able to check such alterations without using a lot of computation? You couldn't just check for file size as some changes would have no effect on file size (I assume).

**Comment by SolarLune** [comment]
> I'm curious. How would you be able to check such alterations without using a lot of computation? You couldn't just check for file size as some changes would have no effect on file size (I assume).

I dunno. Blender might expose a "object altered" flag that basically states if an object's data has been changed. Alternatively, we might be able to browse the undo history for anything related to materials, object vertices, positions, etc., and just export data for those objects since the last Export and Run. 

Anyway, I agree with Goran that we should probably hold off on that and profile the export and run process so we can figure out where the process could be optimized. We already have a good guess where to start, which is where exporting the vertex and mesh data starts. After that, we can (hopefully) optimize and get things running smoother. 

As an alternative, we might be able to make use of [Java .Blend](http://homac.cakelab.org/projects/JavaBlend/spec.html) so we don't have to export the data ourselves anymore at all, and could just directly use and read the blend file. 

I think we should focus on optimizing, though, as this alternative would be fairly invasive and involve a lot of changes to the export process. It's something to consider for the future, I guess.

**Comment by SolarLune** [comment]
Oops, didn't mean to close this.

**Comment by rafcolson** [comment]
Here are some timing results of ```json.dump``` with planes of 4096 faces each, in a hidden layer:

| number of 64X64 planes |   1 |  4 | 8 |
| :---- | ----: | ----: | ----: |
| dump in seconds | 1 | 4 | 8 |
| dump in percentage | 15 | 15 | 15 |

So I think I can assume that the dumping process doesn't "freeze" the overal process. Exporting 32,768 faces takes about 54 seconds on my laptop, only 8 of those seconds is spent on ```json.dump```.

I'll investigate further if there's a bottleneck somewhere.

**Comment by GoranM** [comment]
You can already run `gradlew desktop:run` from the command line, which will recompile and run the game without exporting anything, but if you guys really want a "Run" button, I would be fine with that.

When python code is slow, it's usually allocation related. The code segment referenced by raf is allocating a lot of new lists. I also suspect that additional allocations are being made in the sum process.

It would probably be faster if we could replace the sum call with a traditional for loop, that just appends data to a single list.

That's something to try.

**Comment by aliasaila** [comment]
A potential replacement for line 121 of exporter.py.

`m_verts[m] = numpy.concatenate([verts[i * tfs : i * tfs + tfs] for i in tris]).tolist()`

For a 7,938 vertex UV sphere, the current version takes ~40 seconds, the numpy version takes ~0.8 seconds.

**Comment by SolarLune** [comment]
Whoa, I didn't know Blender included numpy. This helps IMMENSELY. My test scene contains:

Roughly 20,736 faces / 41,472 triangles.
9 objects (just planes, each subdivided, with 2304 faces / 4608 triangles).
2 materials.
Each plane has its own mesh.

My results are timed with just a couple of system.time() calls.

Original `exporter.py` | Numpy `exporter.py`
----------------------------|----------------------------
37.17 seconds | 2.18 seconds.
38.92 seconds | 2.10 seconds.
37.12 seconds | 2.02 seconds.

Wow. This is, like, the entirety of the slowdown that made me ask to speed this up. This is excellent.

Thanks a ton, @aliasaila!

Making a PR with this change as we speak!

**Comment by rafcolson** [comment]
Wow! Super!!!

**Comment by Fr0sk** [comment]
That's amazing! Great work @aliasaila and @SolarLune

**Comment by SolarLune** [comment]
Haha, I literally just made the PR. Thanks, though.

**Comment by aliasaila** [comment]
Using the package **ujson** instead of **json** saves an additional 1 second for the UV sphere test.

**Comment by Fr0sk** [comment]
@aliasaila Ultra JSON is more limited on what it can serialize, can't that eventually limit blender data exporter in someway?

**Comment by aliasaila** [comment]
@Fr0sk Not sure. The only potential issue I could find is in relation to unicode, which we might need for fonts?

**Comment by aliasaila** [comment]
@SolarLune It seems that simplifying that line even further, to just:

`m_verts[m] = verts`

produces identical results numerically, and is slightly faster.

**Comment by Fr0sk** [comment]
@aliasaila Well, can't test that right now, but even if that's the case, we can use it for everything that isn't text, and for text type meshes just use the normal JSON I guess.

**Comment by GoranM** [comment]
> I didn't know Blender included numpy.

Me neither.

Anyway, this is a really nice win, for the small change made.

PS: Quick PR is appreciated, but in the future, it would probably be better to ask people if they're willing to make the PR themselves, so they are logged as the actual contributor (especially in cases like this, where a really short/sweet solution is handed to us on a silver platter).

>It seems that simplifying that line even further, to just:
>
>m_verts[m] = verts
>
>produces identical results numerically, and is slightly faster.

`verts` contains the vertices of the whole mesh. `m_verts[m]` must reference only the vertices that belong to the given material.

It may be the same when you just have a single material, but with multiple materials, scattered across arbitrary triangles, it should be different.

Relating to other optimizations: I'm sure there many other things that we can think of (including what I mentioned previously) but unless there's actually a need to optimize beyond what we have now, I think it would be best to stop.

**Comment by SolarLune** [comment]
> PS: Quick PR is appreciated, but in the future, it would probably be better to ask people if they're willing to make the PR themselves, so they are logged as the actual contributor (especially in cases like this, where a really short/sweet solution is handed to us on a silver platter).

Ah, shoot, you're right, haha. Next time, I guess, unless you want to undo the PR and ask @aliasaila to submit it? I'd be fine with that, of course.

> Relating to other optimizations: I'm sure there many other things that we can think of (including what I mentioned previously) but unless there's actually a need to optimize beyond what we have now, I think it would be best to stop.

Agreed. I wasn't expecting roughly a 1900% speed increase outta this, haha, and not this easily.

I'm fine with stopping here.

**Comment by aliasaila** [comment]
@SolarLune No need to undo the PR. 

I consider it a small token contribution relative to the effort that @GoranM and yourself have put in!

**Comment by SolarLune** [comment]
Hah, thanks!

Well, I guess this is solved, then. Thanks a ton, everyone!

Issue closed.
