### ISSUE TITLE
Suggestion: Another bdx.scenes.remove()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#486]
Hey, there. 

I think it'd be nice to add another remove() function to the scenes list, as there's no way to remove an instance of a Scene from the list (i.e. you'd have to use something like `bdx.scenes.remove(bdx.scenes.get(scene));`). This isn't a huge deal, but there could be multiple versions of a scene in a single list, so it might be best to add a function to do this for us.

**Comment by GoranM** [comment]
I'm not sure I really understand the problem.

ArrayListScenes extends ArrayListNamed, which extends ArrayList, which has a remove(T) method (T being Scene in this case).

So, `bdx.scenes.remove(scene_instance)` should work.

**Comment by SolarLune** [comment]
Hm, that's odd; guess I was just mistaken! Thanks, I'll close this.
