### ISSUE TITLE
Suggestion: Scene.end()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#487]
Hey, there. 

It might be a good idea to add an end() function to the Scene class to properly end all game objects and lights, in particular, and then remove itself from the scenes list. If there's no more scenes after this, the function can call Bdx.end().

Scene.remove() could be modified for this purpose, but the scene still exists in memory and is still available for use later, so it's not safe to clean up stuff there.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!
