### ISSUE TITLE
Suggestion: Better Scene toString() function.

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#490]
Hey, there. 

When you go to print, for example, the list of scenes in Bdx.scenes, the scenes aren't identified by name, so it's hard to know which scenes are which. I propose to improve the toString() function like the GameObject's was, so that you can see which scenes, by name, are referred to when they're printed out.

**Comment by SolarLune** [comment]
Also, do we need the fully qualified names for these toString functions? `Pillar <GameObject> @123456` is descriptive enough, right? Like, we don't really need `Pillar <com.nilunder.bdx.GameObject> @123456`, right? Making it easier to read these would be nice, in my opinion.

**Comment by GoranM** [comment]
Adding some additional info to that which the default toString method already provides is fine, but I'm not sure about cutting any of it out:

Package information could be important for debugging purposes (ie: Someone creates a class in their package that shares the same name with a class in the bdx package, and they need to figure out which is being used at runtime).

**Comment by SolarLune** [comment]
I disagree, I think the payoff's worth it. I think, as a user, I'd rather take the small chance of a slight inconvenience in discerning the package of a class of a GameObject I've overloaded over having a lot of information that is duplicated and annoying to sift through constantly. It's up to you, anyway. I believe I've mentioned this before, and the general consensus was to leave things like they are, so I'll leave it alone for now.

PR submitted.

**Comment by SolarLune** [comment]
PR merged, so I'll close this. Thanks!
