### ISSUE TITLE
Suggestion: Bdx.restart()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#491]
Hey, there. 

So, there's a function to restart the current scene, but not something to restart the entire game, which could be useful to have.

**Comment by SolarLune** [comment]
Huh, so there's no Gdx.app.restart() (even if there was one, I'm not too sure if that'd be what we needed), so we'd have to make our own solution for this, I guess. Should be as simple as just removing all scenes and adding a new instance of the first scene, right? Also, resetting Bdx's instance values (like Bdx.time). I guess just calling Bdx.init() could work, but we'd have to do some extra cleaning up before that.

**Comment by GoranM** [comment]
Ok.

> Should be as simple as just removing all scenes and adding a new instance of the first scene, right? Also, resetting Bdx's instance values (like Bdx.time).

I believe so.

**Comment by SolarLune** [comment]
OK, PR submitted. I think I've got this right.

**Comment by SolarLune** [comment]
This was merged, so I'll close this. Thanks.
