### ISSUE TITLE
Bug: Setting Camera doesn't change Near / Far settings

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#493]
Hey. So, setting the active camera with scene.camera doesn't actually change the camera's near and far settings. I'm not too clear on camera math, so am I right that this just needs us to update scene.cam's projection using the current camera's projection as a float array, like the cam field is first set? It should be in the updateCamera() function, right?

**Comment by GoranM** [comment]
The "current camera's projection" is derived from scene.cam, so you would be setting and resetting the same data.

We need to either store the projection matrix on Camera, or given each Camera it's own libgdx cam - The latter would probably be easier for you.

**Comment by SolarLune** [comment]
OK, I think I got everything "scene.cam"-related pushed over into the Camera class. Everything seems to be working as expected.

PR submitted.

**Comment by SolarLune** [comment]
This was merged, so I'll close it, now. Thanks.
