### ISSUE TITLE
Bug: Build failed - failed to find target android-20

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#497]
After updating BDX I created a new project, but a strange error appears. I only have android-22 installed, and I checked if ```exporter.py``` is failing, but it isn't. (It identifies android-22). So I'm wondering why it's looking for android-20?

```
Read new prefs: C:\Users\Acer\AppData\Roaming\Blender Foundation\Blender\2.76\co
nfig\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.76\python
read blend: D:\BLENDER\BDX\projects\Test_creator.blend
Executing 'D:\BLENDER\BDX\projects\Test/gradlew.bat clean'
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> failed to find target android-20 : C:\Users\Acer\AppData\Local\Android\sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 10.56 secs
read blend: D:\BLENDER\BDX\projects\Test\blender\game.blend
```

**Comment by SolarLune** [comment]
I imagine this is only a problem if you specify an Android SDK? It's OK otherwise?

**Comment by rafcolson** [comment]
Not specifying an Android SDK is also ```A problem occurred configuring project ':android'.```, but only because the SDK directory is not found. As far as I know this is normal.

Maybe it would help if you could check if you are getting the same error message when building a new project. To test you should not have android-20 installed, of course. Else, I assume the error will not occur.

**Comment by SolarLune** [comment]
> Not specifying an Android SDK is also A problem occurred configuring project ':android'., but only because the SDK directory is not found. As far as I know this is normal.

Yeah, that's normal.

> Maybe it would help if you could check if you are getting the same error message when building a new project. To test you should not have android-20 installed, of course. Else, I assume the error will not occur.

OK, so I downloaded API 22 and used the latest build tools (23.0.2).

It did give me the same issue that you got, as well. Weird.

Building the android project past that with `gradlew android:assembleRelease` seemed to worked, though... Why not check to see if that works for you? I didn't check the APK to confirm it actually runs, but it apparently compiles fine, and the android/build.gradle file seems to have the correct specs in it... 

Maybe the latest LibGDX update changed something, such that you need API-20 to be installed to build projects, regardless of which API is actually being targeted?

Anyway, after also installing API 20 and build tools 23.0.1, making a new BDX project works, so ???

It might be nice for us to consider a way to "apply" Android into an existing project, rather than it being an option just from the beginning. Not sure how hard that is, or what that entails, but it'd make debugging Android issues easier, I think.

**Comment by rafcolson** [comment]
Thanks @SolarLune. Yes, I checked and building an APK works fine. The error message is caused after the LibGDX update, as you suspected. It sure is weird.

@GoranM:

This could be confusing to the user so maybe we could add a note about this somewhere in the docs?  Since this is a LibGDX issue I'm pretty sure that we can't do anything about it.

**Comment by GoranM** [comment]
> This could be confusing to the user so maybe we could add a note about this somewhere in the docs?

That the "SDK directory not found" error is normal, when the sdk is not specified? Yes, that should be documented.

However, the new bug needs to be addressed. You mention exporter.py, but, as far as I know, there's nothing in there that sets the android sdk version. The code that actually creates the project is in createproj.py, in the set_android_sdk_version method (that's your code, if I remember correctly).

That method sets the buildToolsVersion, and the compileSdkVersion - You're saying that they're both set correctly?

Are you sure that your android sdk actually has a proper version of build-tools installed - I think that's something that you have to install/update yourself, after the core sdk is installed.

**Comment by rafcolson** [comment]
>That method sets the buildToolsVersion, and the compileSdkVersion - You're saying that they're both set correctly?

Yes, they are. I'm sorry, I didn't remember correctly. I shouldn't have said ```exporter.py``` but ```createproj.py```. Anyway, the ```android/build.gradle``` file seems to have the correct specs in it.

>Are you sure that your android sdk actually has a proper version of build-tools installed - I think that's something that you have to install/update yourself, after the core sdk is installed.

Yes, I'm sure that everything is installed correctly. I know this because the error only occurs after the LibGDX update.

**Comment by GoranM** [comment]
> But I have no idea how to do that. Where to change gradlew.bat clean into gradlew.bat clean --debug?

The code that runs the gradlew command is in exprun.py

Searching the codebase for relevant words will probably help you find info like that in the future. If you don't have local tools to do that, you can just use [github search](https://github.com/GoranM/bdx/search?utf8=%E2%9C%93&q=gradlew).

**Comment by rafcolson** [comment]
Thanks for the tip. Well, it seems that the gradlew command is run also in ```createproj.py``` while creating the LibGDX project through [```subprocess.check_call(cmd)```](https://github.com/GoranM/bdx/blob/bc1e434b3a84fc77d5f1e7d77d4579cfc65923a9/blender/bdx/ops/createproj.py#L43). So the error is definitely within that LibGDX process, and so there's not much we can do about, except for reporting this, if it's a bug. Maybe this part of the application requires ```android-20``` after 1.6.5? I have no idea really. I'll try to search the forums.

**Comment by GoranM** [comment]
If you comment out `self.set_android_sdk_version()`, and then create the project, the default android/build.gradle file will have:

```
    buildToolsVersion "23.0.1"
    compileSdkVersion 20
```

I'm guessing there's something in the new LibGDX version that expects (and therefore looks for) sdk 20, but it seems like you can build a working APK with 23, so maybe it's not something that we need to worry about.

**Comment by rafcolson** [comment]
Yes, everything works just fine and that's a relief. But do you think we should add this info to the documentation? Or at least note that this building error can be ignored?

**Comment by GoranM** [comment]
Yes, I think that would be a good idea.

**Comment by rafcolson** [comment]
Adjusted the [API](https://github.com/GoranM/bdx/wiki/Installation). Closing.
