### ISSUE TITLE
Bug: Successfully build *.apk crashes on Android with new advanced lighting.

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#503]
Just build an apk of the default blend file. This will give no problems. Also installing the apk will give no problems. But when starting the apk it will stop immediately. Here's a [test.apk](https://www.dropbox.com/s/gol10m3d3rhg4ag/test.apk?dl=0), which you can test for yourself.

**Comment by GoranM** [comment]
What's the actual crash exception?

**Comment by rafcolson** [comment]
I can't say. And I don't know if it's possible on Android to get such information. The app just stops with a message, like: "The app has stoppped".

**Comment by GoranM** [comment]
Android should put everything into the system log, which can be accessed via [`adb logcat`](http://developer.android.com/tools/help/logcat.html).

**Comment by rafcolson** [comment]
Can't reproduce any errors on ```Nexus 5 API23 x86 (Android 6.0)```. Everything seems to work fine.

**Comment by GoranM** [comment]
You're not supposed to use CatLog, or any other "app" - As the article you linked to explains, apps are restricted in what system data they can actually access.

You should use the adb utility that comes with the android sdk (it's in platform-tools). You can use that to establish a connection between your PC and your android device, and then run the logcat command (the details should be on the page I linked in my previous post).

**Comment by rafcolson** [comment]
Silly me. Didn't try to connect my phone to the PC yet, but I'll will do that first thing.

>One thing is sure. Initializing Sacky with ```Bdx.display.advancedLighting(false)``` will prevent this crash.

However, this is not true anymore, since Issue #504 was fixed. Probably it's because now both modes use customized shaders. So the bug's definitely in those.

**Comment by rafcolson** [comment]
So here's what logcat logged:
```java
01-24 16:23:47.345 13424-13438/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 934
 Process: com.raco.test.android, PID: 13424
 com.badlogic.gdx.utils.GdxRuntimeException: Fragment shader compilation failed.
 ERROR: 0:179: 'max' : no matching overloaded function found 
 ERROR: 0:180: '<=' :wrong operand typesno operation '<=' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
 ERROR: 0:181: 'assign' :cannot convert from 'const int' to 'float'
 ERROR: 0:195: 'max' : no matching overloaded function found 
 ERROR: 0:196: '<=' :wrong operand typesno operation '<=' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
 ERROR: 0:197: 'assign' :cannot convert from 'const int' to 'float'
 ERROR: 0:209: 'max' : no matching overloaded function found 
 ERROR: 0:211: '/' :wrong operand typesno operation '/' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
 ERROR: 0:220: 'max' : no matching overloaded function found 
 ERROR: 9 compilation erro
 at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:167)
 at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:586)
 at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:35)
 at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:269)
 at com.nilunder.bdx.Bdx.main(Bdx.java:225)
 at com.raco.test.BdxApp.render(BdxApp.java:29)
 at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:424)
 at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
 at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)
01-24 16:23:49.898 13424-13438/com.raco.test.android I/Process: Sending signal. PID: 13424 SIG: 9
```
Hope this helps. It's probably the same error as described in Issue #511, but I'm not sure.

**Comment by rafcolson** [comment]
PR submitted and ready to merge.

**Comment by GoranM** [comment]
Good work hunting this down.

**Comment by SolarLune** [comment]
Ah, yeah, that's what I was thinking. Seems like replacing the integers with floats would be the necessary solution. Thanks for looking into it!

**Comment by rafcolson** [comment]
Once I got my usb driver installed and set my phone to developer mode, ```logcat``` did all the work really. However, the numbers in the log didn't quite represent line numbers, but with an offset. I don't know what's that about. Anyway, this should be helpful in the future. So thank you.

PR merged.

**Comment by SolarLune** [comment]
As a guess, I believe the line offset is because the #define and #ifdef (and related) GLSL keywords can influence the final shader created. So basically, the areas between #ifdef and #endif s are only "there" and compiled into the shader if the statement is true. Otherwise, they are "removed", and so the shader can be shorter. This idea of compiling shaders using different values is what allows us to make an "Ubershader", but disengage areas depending on the circumstances (i.e. no specularity, don't do specular lighting). 

I don't *think* we're doing it correctly, though, as we're creating attributes regardless of whether they're needed or not (i.e. creating specular attributes for a material regardless of if specularity is "on" or not).

We can look into it and optimize later, though.

**Comment by rafcolson** [comment]
Good to know. Thanks.
