### ISSUE TITLE
Bug: Black screen after Bdx.display.advancedLighting(false).

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#504]
As title.

**Comment by GoranM** [comment]
Confirmed.

It's not exactly black (on my system, at least), just really, really dark.

**Comment by rafcolson** [comment]
>It's not exactly black (on my system, at least), just really, really dark.

Oh, okay. I didn't notice this. That's some good news. It's probably a value issue then.

**Comment by SolarLune** [comment]
'Sup! 

Ah, I had to revert [the energy * 10 multiplier I did some time ago](https://github.com/SolarLune/bdx/commit/2d5bbd6bf8709a3c6fba488df5e3b15f02f53da7) when I first implemented lighting, as that was throwing off the new, more accurate per-pixel lighting system. Any ideas to fix it? An idea might be to have a low-quality shader that's used when not using advancedLighting, and to adjust for the low energy there?

**Comment by rafcolson** [comment]
I think that would be straightforward. But if we're at it, I have another suggestion too. See Issue #505.

**Comment by SolarLune** [comment]
OK, that should do it. PR submitted.

**Comment by rafcolson** [comment]
Thanks!
