### ISSUE TITLE
Suggestion: move Light.setMaxCount() to Bdx.display.setLightsMaxCount()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#505]
As title.

Edit: As there's no obvious reason why this should be a method of Light? The description could be something shorter maybe, but I think it would be more straightforward to have this on Bdx.display instead.

**Comment by SolarLune** [comment]
Well, I figure it makes sense because it's setting the maximum number of lights, so it's on the Light class itself. Having everything in one place makes sense, though.

**Comment by rafcolson** [comment]
It's a more general function, I think. Maybe a more proper place would be ```Bdx.display.lighting.setMaxCount()```, next to ```Bdx.display.lighting.fragmentShading(fs=true)```. But I don't mind really, so it's up to you. Unless, @GoranM would prefer differently, of course.

**Comment by SolarLune** [comment]
So also have a static Lighting class on Bdx.Display for these shader-related functions? And change advancedLighting() to fragmentShading()? What's "fs=true" about?

**Comment by rafcolson** [comment]
I'm sorry I wasn't clear. I meant also replacing ```Bdx.display.advancedLighting()``` to ```Bdx.display.lighting.advanced()``` or ```Bdx.display.lighting.setFragmentShading()```.

**Comment by GoranM** [comment]
For the most part, I would expect static properties on a given class to represent data that all instances of that class would need to share. Setting the max number of possible lights sounds like a general render system configuration detail that should be on Bdx.display (in my opinion).

**Comment by SolarLune** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Thanks, man.
