### ISSUE TITLE
Suggestion: Profiler changes/enhancements

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#506]
There are a couple of things I'd like to change in order to expose variables ```Bdx.profiler.avgTickRate``` and ```Bdx.profiler.avgTickTime```, and to add an option to display variables of ```com.badlogic.gdx.graphics.profiling.GLProfiler```.

- splitting up the initialization process (by using class initialization ```{//initialization}```)
- updating ```avgTickRate``` and ```avgTickTime``` regardless if the profiler is visible or not
- additional methods to enable/disable display for "tick info", "processes" and "gl"
- additional method to scale the profiler (useful with small screens, eg. on mobile)

**Comment by SolarLune** [comment]
This sounds OK to me, but I don't quite get what you mean by "splitting up the initialization process".

I'm going to probably cut the code that scales the profiler in accordance with the screen size (not your proposal to scale it using a method) when I get back to viewports, as I believe it was problematic. Just letting you know.

I like the idea of allowing the user to scale the profiler to size it up or down, though.

**Comment by rafcolson** [comment]
> I don't quite get what you mean by "splitting up the initialization process".

It will be clear once I've finished the update.

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by SolarLune** [comment]
Looks OK, I suppose, though if there's nothing in the new classes that are publicly accessible, we could just go with glVisible() and subsystemsVisible() functions, right?

**Comment by rafcolson** [comment]
I'm not sure. We do want ```gl``` to be public to have access to gl specifics. Maybe we could put ```start()```, ```stop()``` and ```remove()``` in ```subsystems``` instead?

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR merged. Thanks a lot guys, for your comments and suggestions. As always, this made the result much better.

**Comment by SolarLune** [comment]
Great to hear, and great work on finishing this. Thanks for updating the API, as well; it'd be nice if you could explain what each function does in the GL module (i.e. what does "calls()" return).

**Comment by rafcolson** [comment]
>it'd be nice if you could explain what each function does in the GL module (i.e. what does "calls()" return).

Updated.

**Comment by SolarLune** [comment]
Cool. Thanks!
