### ISSUE TITLE
BUG:Android demo can't run

### ISSUE THREAD

**Issue by xirtam-ch** [GoranM/bdx#511]
01-21 17:01:59.482    2440-2471/com.xirtam.test11.android E/AndroidRuntime﹕ FATAL EXCEPTION: GLThread 2375
    Process: com.xirtam.test11.android, PID: 2440
    com.badlogic.gdx.utils.GdxRuntimeException: --From Vertex Shader:
    Error: uniform variables in vertex shader do not fit in 256 vectors.
    --From Fragment Shader:
    Error: uniform variables in vertex shader do not fit in 256 vectors.
            at com.badlogic.gdx.graphics.g3d.shaders.BaseShader.init(BaseShader.java:167)
            at com.badlogic.gdx.graphics.g3d.shaders.DefaultShader.init(DefaultShader.java:586)
            at com.badlogic.gdx.graphics.g3d.utils.BaseShaderProvider.getShader(BaseShaderProvider.java:35)
            at com.badlogic.gdx.graphics.g3d.ModelBatch.render(ModelBatch.java:269)
            at com.nilunder.bdx.Bdx.main(Bdx.java:191)
            at com.xirtam.test11.BdxApp.render(BdxApp.java:28)
            at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:424)
            at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1535)
            at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

My device is Nexus 5,System version android  6.0

**Comment by rafcolson** [comment]
@SolarLune: Any ideas about what this means: ```Error: uniform variables in vertex shader do not fit in 256 vectors.```?

**Comment by GoranM** [comment]
@rafcolson 

This might be the same exception that you get for #503. Can you confirm that?

**Comment by rafcolson** [comment]
Can't confirm (yet). I'll have to admit that this week I tested for the first time with an Android Studio virtual device. But I couldn't reproduce any errors on ```Nexus 5 API23 x86 (Android 6.0)```. Everything seems to work fine.

**Comment by SolarLune** [comment]
OK, so a few questions.

1) What version of BDX are you using?
2) Does the project run fine on your desktop PC, and just not run on the Android device?
3) If so, what OS are you using on your computer?
4) Is this an actual, or emulated Nexus 5?
5) Is this the default BDX demo (with Sacky and the square of grassy blocks), or something else?

____________

According to my little bit of Googling research, [it looks like we might be sending too much information through uniforms](https://bocoup.com/weblog/counting-uniforms-in-webgl). If that's the case, then we can reduce the uniforms in the vertex and fragment shaders to just what we need. 

To confirm this, though, we can test with a couple of ways.

1) Try reducing the light count using the `Bdx.Display.setMaxLightCount()` functions to set them to 1 for each kind of light. Does this work?

2) Next, try a couple of *really* basic shaders. Replace the `default.vert` and `default.frag` shaders in your `android\assets\bdx\shaders\3d` folder with these.

default.vert
```cpp
attribute vec3 a_position;
uniform mat4 u_projViewTrans;
uniform mat4 u_viewWorldTrans;
uniform mat4 u_viewTrans;
uniform mat4 u_worldTrans;

void main() {
	vec4 pos = u_worldTrans * vec4(a_position, 1.0);
	gl_Position = u_projViewTrans * pos;
}
```

default.frag
```cpp
#ifdef GL_ES 
#define LOWP lowp
#define MED mediump
#define HIGH highp
precision mediump float;
#else
#define MED
#define LOWP
#define HIGH
#endif

void main() {
	gl_FragColor = vec4(1, 0, 0, 1);
}
```

They just are made to basically put something (completely red shapes) on screen. Does this work? 

It might be that we need to overwrite our BdxDefaultShader class and send less uniform data ourselves if too much is being sent, even by default through LibGDX.

An aside:

These OpenGL functions and attributes do influence shader speed and efficiency (and obviously can also crash the game under some circumstances). So, it might be a good idea to have them be available in the profiler also at some point in the near future, alongside number of shader changes, number of textures, number of faces / triangles, etc.

**Comment by xirtam-ch** [comment]
@SolarLune 
1.BDX version 0.22
2.PC can't run  I got #11 
3.OS X 10.10.3
4.Actual
5.Yeah,Sacky Demo.

I'll try it later.thanks.

**Comment by rafcolson** [comment]
@xirtam-ch

Maybe after #514 is merged you could check if this also fixes this issue? You could also pull from my repo, it's up to you.

**Comment by rafcolson** [comment]
@xirtam-ch I think we're close to a new release now. Would you be able to check if this issue is fixed? Thanks.

**Comment by ridvandongelci** [comment]
I think this issue might not be fixed. I am having a probably same issue with change files as well but when I set test shaders it seem to be ok.

**Comment by SolarLune** [comment]
Huh? I'm pretty sure I saw someone else post a comment on this thread that said that they were still having issues with this issue...?

**Comment by rafcolson** [comment]
>Huh? I'm pretty sure I saw someone else post a comment on this thread that said that they were still having issues with this issue...?

This issue may be the same as #514, which is fixed. But in order to test it the newest BDX build should be used, of course.

**Comment by SolarLune** [comment]
Ah, I got an e-mail from that person, and he said that he was having the problem, but updating to the latest version of BDX fixed it for him.

**Comment by rafcolson** [comment]
@xirtam-ch Could this be closed?

**Comment by xirtam-ch** [comment]
Thanks
