### ISSUE TITLE
Suggestion: Profiler scene - reducing gl calls by joining or Instanced Rendering

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#513]
Performance is still low due to the many objects in the profiler (causing many draw calls). Without gl statistics there are 22 and with there are as many as 28 draw calls with 3624 vertices in total. I think it would be a possible to reduce these to just 3 draw calls by adding and joining objects every logic tic. It'll cost some more processing, but I think it would be worth it.

I'll have to check if it's possible to optimize by adding another joining method. This method would create an object out of meshes directly, without having to add all objects individually first. But I hope it won't come to that.

I'll have to search deeper into reducing gl draw calls as I've found a good tutorial about [Instanced Rendering](https://www.youtube.com/watch?v=Rm-By2NJsrc&index=36&list=PLRIWtICgwaX0u7Rf9zkZhLoLuZVfUksDP) with ```glDrawArraysInstanced()``` in a shader program.

Anyway, is it okay to do this next optimization?

**Comment by GoranM** [comment]
I'm not sure if it's worth the additional complexity.

As long as the profiler accounts for its own time, it doesn't have to be extremely fast in order to provide the user with relevant information.

**Comment by SolarLune** [comment]
I think I agree. Is the performance of the rendering that low with the profiler enabled? If so, I suppose updating the profiler every frame, setting it to be invisible onscreen, and then the user just printing out the statistics would be a valid way to profile more quickly.

I think the point is to give you an idea of how the game's performing, so it doesn't really need to run quickly; it's like a debugging feature. It wouldn't exist or wouldn't be enabled in the release-version of a game, so I think it's OK if it slows things down a bit.

**Comment by rafcolson** [comment]
>If so, I suppose updating the profiler every frame, setting it to be invisible onscreen, and then the user just printing out the statistics would be a valid way to profile more quickly.

Yes, this would probably be a better solution. Made those changes too. See [#506](https://github.com/GoranM/bdx/pull/512#issuecomment-174456258).
