### ISSUE TITLE
Suggestion: Profiler properties

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#515]
For example, if you want to display ```Sacky.health``` in the BDX Profiler, you'd be doing this by adding and setting a property. There would also be a method to remove properties: ```Bdx.profiler.removeProp(String propName);```
```java
import com.nilunder.bdx.*;

public class Sacky extends GameObject{
	
	private int health;
	
	public void init(){
		health = 10;
		Bdx.profiler.addProp("health", Integer.toString(health));
	}
	
	public void main(){
		if (Bdx.keyboard.keyHit("space")){
			health -= 0;
		}
		Bdx.profiler.setProp("health", Integer.toString(health));
	}
	
}
```
Edit: Methods could also be in ```Bdx.profiler.props```, ```props``` being an extended HashMap.

**Comment by SolarLune** [comment]
This sounds like a pretty interesting idea... 

I think having just a HashMap called `props` would fill the purpose fine, right? Like, you have the built-in `set()` function to add or set values, and you can remove them with `remove()`.

**Comment by rafcolson** [comment]
On the other hand, why not use reflection for this. Then setting wouldn't be required:

```java
import com.nilunder.bdx.*;

public class Sacky extends GameObject{
	
	private int health;
	
	public void init(){
		health = 10;
		Bdx.profiler.add(this, "health");
	}
	
	public void main(){
		if (Bdx.keyboard.keyHit("space")){
			health -= 0;
		}
	}
	
}
```

**Comment by SolarLune** [comment]
That sounds and looks nice and slick, yeah. Does reflection work well on all targeted platforms?

**Comment by rafcolson** [comment]
I suppose it does. But because you're mentioning this, do you think it's possible that it doesn't? Would ```java.lang.reflect.Field``` not be accessible on some platforms?

**Comment by SolarLune** [comment]
Nah, I guess it should work on all platforms. I don't see anything that says it wouldn't, so go ahead with it.

**Comment by rafcolson** [comment]
First I'll wait for Goran to approve of this.

**Comment by GoranM** [comment]
The GWT transpiler doesn't support reflection, so it wouldn't work for the HTML5 build.

I think a `HashMap<String, String>` would make sense for `Bdx.profiler.props`.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Oh it seems that the outside subsystem is giving wrong results. So better put this on hold.

**Comment by rafcolson** [comment]
PR merged. Thanks.
