### ISSUE TITLE
Gamepad.hit(), down(), and up()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#516]
Hey, there. I was wondering, should we rename the input checking functions in Gamepad to remove the `btn` prefix, as they're not all buttons?

**Comment by rafcolson** [comment]
Those which are no buttons are "buttonized", not? So it seems correct to me. The btn prefix implies the value is either true or false.

**Comment by GoranM** [comment]
What raf said.

**Comment by SolarLune** [comment]
I mean, they are in the sense that it's turned into a boolean, on or off value, but they obviously aren't buttons. 

For people who are just learning the engine, it seems easier to understand that a function checks for one of several kinds of inputs ( hit() ), than that a function checks for only buttons, but will treat other kinds of inputs as buttons ( btnHit() ) . 

Then you could actually omit the "BDX will "buttonize" these input types", and just say hats, axes, and buttons can be checked with the hit(), down(), and up() functions.

**Comment by rafcolson** [comment]
I see your point. Gamepad.hit(), down(), and up() also imply that the value
will be either true or false. So I don't mind if you change this.

**Comment by GoranM** [comment]
Gamepad.axes contains Axis objects that provide the analog values from the actual hardware. We also have Gamepad.sticks, containing Stick objects that serve as a more convenient abstraction for axis pairs that represent stick controls.

As you said, they're obviously not buttons, so if there is any utility in transforming their data into discreet button-like inputs, I think the button abstraction makes perfect sense.

From that perspective, I don't see how removing the "btn" prefix would make anything easier to understand.

**Comment by SolarLune** [comment]
Eh, I guess it doesn't matter too much. Nobody's complained about it so far, haha.

Issue closed.
