### ISSUE TITLE
Question: Name() function and name field

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#517]
Hey, there. 

So on a lot of the objects that implement Named, there is a name field that can be read (and written to), and a name() function that returns the name of the object, whatever it might be. Do we need both? Should one be hidden? I'd imagine we would want some ability to name Named objects, as that can help the developer to distinguish them later. Components, for example, can be re-named as something other than their class name so you can distinguish between two instances of the same component.

I bring this up because I added a name property to Gamepads so you can get them by name awhile back, but the name function just returns the system's provided name for the gamepad (so our class doesn't hold onto the name itself).

**Comment by GoranM** [comment]
The Named interface requires a `name()` method.

**Comment by SolarLune** [comment]
Ah, OK. So should we hide the name field for objects that shouldn't be renamed, or is it fine the way it is?

**Comment by GoranM** [comment]
I think it's fine the way it is.

As stated on our [API page](https://github.com/GoranM/bdx/wiki/API): "Unless otherwise labeled, all fields should be considered read-only."

So, based on that, GameObject.name should not be changed.

**Comment by SolarLune** [comment]
OK. 

I wonder, is there any reason why names shouldn't be changed?

**Comment by rafcolson** [comment]
I think it's pretty beneficial that we can change the name of objects.

**Comment by SolarLune** [comment]
Yeah, that's what I'm thinking. 

I could see it being useful in some circumstances. As an example, say we made a game with a primarily component-based design, and did so in such a way that a Player object and an Enemy object are fundamentally the same object (say, "Biped"), just with different components. By being able to change the name of the GameObject, we could identify this Player object separately from Enemies in collections, even though they're both Bipeds.

Is there a fundamental reason that users shouldn't change GameObject names?

**Comment by GoranM** [comment]
The name is basically there to make a clear reference to what blender object is actually being represented. It is also used by collision functions, to determine if you are colliding with an object of a given name.

It wasn't intended to be used for anything else (even though it could be, technically).

> As an example, say we made a game with a primarily component-based design, and did so in such a way that a Player object and an Enemy object are fundamentally the same object (say, "Biped"), just with different components.

The fact that they have different components, and therefore behave differently, is what makes them different objects. It's a clear conceptual difference, so it seems far cleaner to simply have two objects, instead of some overstuffed "uber object" with a bunch of if statements that dispatch based on the implicit type.

**Comment by SolarLune** [comment]
OK. I don't really mind too much either way; I've never changed the name of GameObjects, but I do change names of components, so being able to do so is beneficial. I was just wondering if we needed both the field and the function, really.

Anyway, thanks!

Issue closed.
