### ISSUE TITLE
Gamepad stops responding when fullscreen mode changes

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#518]
Hey. So it looks like gamepads stop responding when fullscreen mode changes. This seems like it might be a bug in LibGDX; not sure if we can work around it or not. [Here's ](http://www.java-gaming.org/index.php?topic=29376.0)a post on the matter. I also posted about it on the [LibGDX forums](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=21667) to confirm that this is an issue that's still ongoing.

It's weird; I feel like I've gone full-screen mode and had the gamepad work before, but maybe not?

**Comment by GoranM** [comment]
Seems like a LibGDX bug.

You can try reporting it in their github tracker. 

I'm not sure what the workaround would be, but reading the java-gaming thread, I get the sense that re-initializing the gamepads would probably do the trick.

**Comment by rafcolson** [comment]
Maybe also check if resizing the window also causes problems then.

**Comment by SolarLune** [comment]
Nah, resizing the window's no problem, and just creating new gamepads doesn't seem to fix the problem, either... Basically, from my tests, it seems like the Input Processor no longer checks joystick events after full-screen-ing. I'll have to look into it some more, I guess. 

I'm delaying on creating an issue in LibGDX's Github because I don't actually have LibGDX set up on my computer to create a new project and stuff, so I can't really provide an easy test case, which is something that they require to create a new issue...

**Comment by GoranM** [comment]
> just creating new gamepads doesn't seem to fix the problem, either

Note that Gamepad initialization consists of not only creating the Gamepad object, but also adding an event listener to its controller. The latter is done in [GdxProcessor](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/inputs/GdxProcessor.java#L164).

**Comment by SolarLune** [comment]
Turns out that it is possible to fix by creating new gamepads (possibly also creating a new processor), but it needs to be done after the display is fully re-initialized. Not quite sure how to check to make sure the fullscreen setting process is completed before re-initializing the gamepads.

**Comment by SolarLune** [comment]
I created an issue for it over on the LibGDX repo [here](https://github.com/libgdx/libgdx/issues/3798), but in the meantime, I managed a fix. PR submitted.

Basically, I recreate the gamepads a short time after either a fullscreen change or a window size change. 

The timer's necessary because this should only be done once the display is completely finished changing; if it's too early, the newly created gamepads won't be recognized. This creates a 1-second delay between changing the window's size or fullscreen status, and the gamepad responding to input. If the delay's shorter, the gamepads don't always get picked up - 1 second seems long enough for the gamepads to be successfully recreated and picked up 100% of the time (in my tests, anyway).

**Comment by SolarLune** [comment]
PR merged, so this issue can be closed for now. Hopefully LibGDX will get a fix to actually fix this instead of this workaround. I'll make a note in the Wiki about this, in the meantime.

**Comment by SolarLune** [comment]
Oh, and @rafcolson - yeah, resizing the window using the size() function also causes the issue. Sorry - maybe I thought you were talking about manually changing the window size. Anyway, thanks for the tip.

**Comment by SolarLune** [comment]
Hey, it seems like the latest LibGDX update might've fixed this so we don't need to refresh the gamepads after window size changes. Can someone confirm on Windows (I tested on Linux)?

**Comment by SolarLune** [comment]
Ah, [here's](https://github.com/SolarLune/bdx/tree/MinorFixes) a branch that has the gamepad refreshing reverted, and I've submitted a PR as well.

**Comment by SolarLune** [comment]
Well, this was merged, so I guess I'll re-close this (for now, anyway). Thanks.

**Comment by SolarLune** [comment]
Seems like this came back (or just never left, on Windows, at least), so I'm opening a PR with a fix for it.

**Comment by rafcolson** [comment]
Seems like a commit, fixing this issue, is merged, right?

**Comment by SolarLune** [comment]
Ah, it was, thanks.
