### ISSUE TITLE
Question about scene.java: cloneNoChildren()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#52]
Lines 266-267:
```java
		g.body = Bullet.cloneBody(gobj.body);
		g.body.setUserPointer(g);
```
What if the object being added to the scene has no collision, then would it be necessary to give it a body for Bullet? I'm just figuring out why objects with no collision are costing performance so much if there are plenty of them.

Probably I'm just catching air here, but you never know.

https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java

**Comment by GoranM** [comment]
A bullet body is just a data structure, which should have no performance impact unless it's actually added to a bullet world (as far as I understand).

All objects in BDX have a bullet body (makes for a more elegant implementation), but only bodies of collision enabled objects are actually added to the bullet world (as you can see [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L320)).

So, as far as bullet is concerned, objects set to `NO_COLLISION` don't exist. To confirm that, you can time [world.stepSimulation](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L554): the number of no collision objects in the scene should not affect the execution time of that call.

I gather you're having performance problems on mobile hardware?

Mobile hardware is generally under-powered (especially older/cheaper android phones, which don't have fast floating point, or use a very old version of Dalvik JIT compiler). Your performance profile will depend on various factors, but, needless to say, you shouldn't expect to get anything close to the kind of performance you get on the desktop.

**Comment by rafcolson** [comment]
Thanks for that info. Yes, I'm having performance issues on mobile hardware, but not with older phones. I believe it's about average of what you could buy in the stores today. I never had guessed that a lot of object with no collision would be so expensive.

I'm making a game of the same genre as Sega Genesis platform games, much like Monster World, if you know that. To create the environment I'm using PixMap to generate all blocks from a region of an 1024x1024 image. I'm storing the blocks per section of 16x16. An lod system updates 4x4 sections once in ten frames. It checks which ones have to be loaded and which have to be freed. On average I count 800 blocks of which maybe a 100 blocks are detecting collision. So you see I don't know where to look. A 100 cubes and 700 planes isn't too many is it? I'll yet have to check what it gives if not textured...

**Comment by GoranM** [comment]
> On average I count 800 blocks of which maybe a 100 blocks are detecting collision. So you see I don't know where to look. A 100 cubes and 700 planes isn't too many is it?

I think that's too many for BDX on mobile ... at least for now (I didn't try optimizing anything yet).

I don't know the specifics of the game you're trying to make, but you can probably do it with a few big objects for your environment, instead of the "grid of blocks" approach, which requires hundreds of different objects.
