### ISSUE TITLE
Suggestion?: Combo Component

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#520]
Hey, there!

So, I've been thinking about this for awhile now, and I think a Combo component could be useful in BDX. The general idea is that you can provide a Combo component with a set of inputs for it to watch for, and it would check the inputs pressed to see if those inputs are pressed in sequence for the specified combo. 

You could check to see if each input in the string were completed (for a standard combo in action games, or combo-based fighting games) or if the string were completed (for, say, ultras and specials in fighting games). Here's a basic idea of what I was thinking:

```java

Combos combo;
String hdkn;

void init(){

    combo = new Combos();
    combo.alias("p", "Player1Punch");  // Set an alias for letters to entire input names
    combo.alias("k", "Player1Kick");
    combo.alias("d", "Player1Down");
    combo.alias("f", "Player1Forward");
    combo.alias("b", "Player1Back");
    combo.aliasFlipped("f", "b");  // Signifies that back now is forward if combo.flipped is set to true

    combo.add("p,p,k");  // Add some basic combos
    combo.add("p,k,k");
    combo.add("b,b");  // Backstep
    hdkn = "d, d+f, f, p";
    combo.add(hdkn);

    combo.endOnWrongInput = false; // Whether to end the combo on wrong inputs or not
    combo.endOnSuccessfulCombo = true;  // Whether to end a combo if another one is completed successfully or not.
    combo.minTime = 0.2f;  //  Window of time to press an input and have it be recognized
    combo.maxTime = 1.0f;  //  If too much time passes, the string is dropped.

    components.add(combo);

}

void main(){

    if (combo.status("p,p,k") == Combos.Status.IN_PROGRESS)
        System.out.println("Working on a standard PPK");

    if (combo.status("p,p,k")  == Combos.Status.FINISHED)
        System.out.println("Completed a PPK");

    if (combo.status(hdkn) == Combos.Status.FINISHED)
        System.out.println("Launch Hadoken.");

    if (combo.status(hdkn) == Combos.Status.FAILED)
        System.out.println("Failed to complete!");

    System.out.println(combo.lastCompleted());  // The last combo sequence successfully completed

    if (facingLeft)
        combo.flipped = true;    // You're facing left, so now forward needs to be backward, and vice-versa

}
```

This component would be useful for 2D and 3D action, fighting, and possibly rhythm games (with some alterations), I think. I'd also like to add special keywords, like "hold" or "wait" to signify holding an input for a specified amount of time, or not pressing anything for some time, but that can wait.

What do you guys think? Not sure if it falls into "core" BDX, but components by their nature would generally be focused on stuff that people wouldn't want to make for themselves, I think?

**Comment by GoranM** [comment]
> Not sure if it falls into "core" BDX, but components by their nature would generally be focused on stuff that people wouldn't want to make for themselves, I think?

I think components included with BDX should be focused on features that are generally useful across a very wide spectrum of game types.

I'm not sure that this component falls into that category, and I'm also not sure that the outlined API is the best thing we could do.

For now, it would probably be best to keep this in your helper lib.

**Comment by SolarLune** [comment]
Yeah, that makes sense. Thanks. 

Issue closed.
