### ISSUE TITLE
BDX Build Failed

### ISSUE THREAD

**Issue by colepram** [GoranM/bdx#521]
I'm still new to BDX, but it looks REALLY promising. I stumbled on to BDX while having issues loading a Blender Model that uses transparent textures into a LibGDX project.

I downloaded BDX and got it installed without issue, but when I went to run the sample application I just get BDX BUILD FAILED, nothing else is reported. I'm still looking for log files.

Any debug suggestions?

**Comment by rafcolson** [comment]
Did you also get a BDX BUILD FAILED with running the default game.blend (Sacky on the green platform)?

**Comment by colepram** [comment]
I didn't do that yet, but I did get it working. I don't know what the difference is, but if I start blender from a command prompt it works fine. If I start Blender from the quick launch icon I get the BDX BUILD FAILED.

Probably worth noting I'm using Ubuntu 15.10.

I think the issue has something to do with the environment variable settings.

**Comment by rafcolson** [comment]
I'm a little confused. You are getting BDX BUILD FAILED after starting Blender? Or after starting BDX?

**Comment by colepram** [comment]
I start blender using the quick launch icon
![image](https://cloud.githubusercontent.com/assets/16956852/12678256/4941c498-c674-11e5-8041-068fb64f89aa.png)

Mouse over the 3D view window

![image](https://cloud.githubusercontent.com/assets/16956852/12678123/9d7f8df2-c673-11e5-9079-cfe510eaba9b.png)

press 'P'
and get "BDX BUILD FAILED"

![image](https://cloud.githubusercontent.com/assets/16956852/12678150/d6b40e9a-c673-11e5-895f-6e3235f94698.png)

However, launching blender from a terminal
![image](https://cloud.githubusercontent.com/assets/16956852/12678293/7357a9d2-c674-11e5-9520-d4ab1ce50c5d.png)

Mouse over the 3D view
![image](https://cloud.githubusercontent.com/assets/16956852/12678334/94696804-c674-11e5-8dec-3ff45ef6238a.png)

press 'P'
and compiles fine 
![image](https://cloud.githubusercontent.com/assets/16956852/12678358/aa27d05e-c674-11e5-94ff-432da26cc962.png)

So I'm not sure what the issue is, maybe it's a profile setting that points to the wrong JDK?

**Comment by colepram** [comment]
Sorry I just realized I misunderstood your question earlier

"Did you also get a BDX BUILD FAILED with running the default game.blend (Sacky on the green platform)?"

Yes, it failed when running the default game.blend.

**Comment by rafcolson** [comment]
Thanks. What happens if you press "Export and Run" in the BDX render tab panel? Also, could you open the System Console (under the Window tab on top of the screen) and copy paste the error here? Thanks.

**Comment by colepram** [comment]
I don't see the BDX render panel and no System Console either

![image](https://cloud.githubusercontent.com/assets/16956852/12679230/61df100a-c679-11e5-86eb-3688b6a12d8b.png)

Are they add-ons I don't have?

**Comment by colepram** [comment]
I found the export and run, I was looking for a "BDX Render" view, found it in the under the "render options"

![image](https://cloud.githubusercontent.com/assets/16956852/12679722/0fba5d68-c67c-11e5-9829-09beb0a7ca4e.png)

**Comment by SolarLune** [comment]
Hey, there! What does the console say the error is? For Linux, you have to run Blender from a console to get it to be visible.

**Comment by colepram** [comment]
LOL, that's the funny part. When I run blender from the console, it works fine, there is no error.

When I started this ticket I was starting blender from a quick launch icon, which doesn't start a terminal window. I read that when you start from a launch icon the output goes to ~/.xsessionerrors, but there's no output there on my machine.

**Comment by colepram** [comment]
Just for clarity if anyone else stumbles on this issue

**SOLUTION: RUN BLENDER FROM TERMINAL

I did muck around with changing my /etc/enviornment and /etc/profile files to set the JAVA_HOME to the JDK, and restarted a bunch of times. It didn't help.

Running from a console is acceptable for me.

**Comment by SolarLune** [comment]
Yeah, I dunno, haha. A side-note might be to ensure that the gradle app in the project directory is marked as executable. Maybe running BDX successfully also requires running Blender with `sudo`, and your prompt does that by default? Not sure.

Anyway, I'll make a note about making sure gradle is executable in the API, as it's something that could trip people up if they slide Linux files around in Windows.

Hope you enjoy using the engine!

**Comment by rafcolson** [comment]
Just a quick question. What is the error in the System Console? You can open the System Console by cliking on "Window" in the info bar on top of the Blender screen, and then clicking: "Toggle System Console".

**Comment by colepram** [comment]
There is not "Toggle System Console" that I can see. I might not be looking in the right spot, but I think it's a difference between Linux and Windows.

I've been known to be wrong though.

**Comment by rafcolson** [comment]
Well, if it's not there then I assume it's because of Linux, couldn't think of another reason. The Blender docs mention something about this:

>[When you start Blender using a Desktop icon or menu entry rather than a Terminal window, the Blender Console Window text will most likely be hidden on the Terminal that your XWindows server was started from.](http://wiki.blender.org/index.php/User:Fade/Doc:2.6/Manual/Interface/Window_system/Console_window#Linux)

**Comment by SolarLune** [comment]
> There is not "Toggle System Console" that I can see. I might not be looking in the right spot, but I think it's a difference between Linux and Windows.

You're correct - there's no such option on Linux. I'm not sure - maybe Linux doesn't support showing and hiding windows? But yeah, that option's not there on Linux and Mac, and is there on Windows.

**Comment by colepram** [comment]
Yeah, seems to be the case. It's an inconvenience, but nothing "game breaking" HA, I made a funny.

Might be worth adding this to an FAQ somewhere though
