### ISSUE TITLE
Suggestion: Draw Line Function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#528]
Hey, there. An ability to easily draw a line in code from point to point would be nice for debugging purposes (I'm currently working on a multi-raycast function, so the ability to see which casts go from place to place would be nice). As far as I can see, drawing lines in OpenGL ES alone seems to be a huge pain, so I thought it might be a good idea to allow for this or something similar in BDX.

Thoughts?

**Comment by GoranM** [comment]
Yeah. I guess it could be Scene.drawLine, or something like that.

I used the libgdx ShapeRenderer to draw lines for the bullet debug drawer, so it might be possible/convenient to leverage that.

**Comment by SolarLune** [comment]
Hey, thanks for the tip - it was really as simple as using the ShapeRenderer. I thought it was just for 2D drawing, but it has 3D functions, too.

I added a drawLine() function and a drawPoint() function (I could imagine the latter being useful for things like, say, debugging a grid of points in 3D space). Lemme know if you don't want drawPoint, though.

**Comment by SolarLune** [comment]
This was merged, so I'll close it now. Thanks!
