### ISSUE TITLE
Suggestion: Minor Text Improvements.

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#533]
Hey, there. I think we could make a few improvements to Text objects.

1) As is documented, you need to fix the scaling on text manually as the size of text objects in BDX is smaller than the size of text objects in Blender. Is this always a certain amount? If so, we could make BDX just automatically fix this, right?

2) We could stand to change the `text` attribute and `set()` function to just a couple of `text()` functions - one to set the text, and one to get the text.

3) We could export the string that text objects are displaying in Blender to display them in BDX. This is an issue because if you get the `text` property of Text objects before setting them in BDX, it'll crash BDX because `text` is null.

4) We could add a `capacity` integer value that indicates how many characters the text object can display.

**Comment by SolarLune** [comment]
Updated the issue with more suggestions.

**Comment by GoranM** [comment]
> As is documented, you need to fix the scaling on text manually as the size of text objects in BDX is smaller than the size of text objects in Blender. Is this always a certain amount?

As far as I remember, no - It seemed to vary based on some characteristic of the given font, and how it's interpreted by the whole Hiero system.

> 2) We could stand to change the text attribute and set() function to just a couple of text() functions - one to set the text, and one to get the text.

That would be fine.

> 3) We could export the string that text objects are displaying in Blender to display them in BDX.

We already export the relevant data, so you should be able to just use it.

> 4) We could add a capacity integer value that indicates how many characters the text object can display.

Ok.

**Comment by SolarLune** [comment]
> As far as I remember, no - It seemed to vary based on some characteristic of the given font, and how it's interpreted by the whole Hiero system.

Oh, really. Dang, that's unfortunate. I thought it was always the same number (0.72).

> We already export the relevant data, so you should be able to just use it.

Not sure what you mean - I mean that the `text` field is blank on Text objects until you use set() to set the text manually. Right?

**Comment by GoranM** [comment]
> Do you mean that the string that the Text object is displaying in Blender is exported?

Yes.

**Comment by SolarLune** [comment]
If we export the string, and we can set the text object to the string from Blender, do we need to export the text mesh's vertices from Blender? Could we just cut out the entire `vertices_text()` function?

**Comment by GoranM** [comment]
Setting the vertices to specific data is redundant (provided we set the text at initialization), but that doesn't remove the need for vertices themselves.

The only reason I initially set the data in the exporter is because I wasn't really sure about the performance implications of changing vertex buffer data after it's already on the GPU; OpenGL has these different usage hints:

>STREAM
>The data store contents will be modified once and used at most a few times.
>
>STATIC
>The data store contents will be modified once and used many times.
>
>DYNAMIC
>The data store contents will be modified repeatedly and used many times.

I'm not sure if libgdx does something that drops down to a slower mode if I change mesh content, so just in case, I didn't want to actually do that for any visible text unless explicitly required by gamecode.

It's probably not an issue.

**Comment by SolarLune** [comment]
Well, I'mma leave that up to you - not too sure about how the process should go. Simply removing the vertices_text() function and setting the model to null didn't work, so you can remove it if you feel like it (which I'd recommend, if the functionality stays the same).

Anyway, PR submitted.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!
