### ISSUE TITLE
Suggestion: Print stages of Export and Run

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#536]
Hey, there. I think it'd be nice if the console printed out some information while it's exporting and running. For example:

```
Exporting Models... 4.2 seconds
Exporting Materials.... 0.2 seconds
Exporting Actions... 0.04 seconds
Running BDX...
------- BDX START --------
```

And so on.

**Comment by Fr0sk** [comment]
That would be awesome. Also, if possible, adding the compiling code would be nice

**Comment by SolarLune** [comment]
What do you mean by "adding the compiling code"? Do you mean printing out when it's compiling the source code? If so, LibGDX does that when we launch it (the `:core:compileJava`, `:core:classes` part shows it).

**Comment by GoranM** [comment]
I'm not sure if it's wise to bombard users with debug information that they typically don't need/want to see.

**Comment by Fr0sk** [comment]
> What do you mean by "adding the compiling code"? Do you mean printing out when it's compiling the source code? If so, LibGDX does that when we launch it (the :core:compileJava, :core:classes, etc. part shows it).

Yep, that was what I meant. Where do you get those messages? In the Blender console?


> I'm not sure if it's wise to bombard users with debug information that they typically don't need/want to see.

Maybe give the option to enable debug messages, then. Well, they are not normal computer users if they are interested in gamedev and want an engine like BDX, so it might not be completely inappropriate.

**Comment by SolarLune** [comment]
Or maybe just print out the fact that the export process has started? Otherwise, Blender'll just seem to hang for a few seconds between pressing P and LibGDX being run.

> Yep, that was what I meant. Where do you get those messages? In the Blender console?

Yeah, that's where'd it be. Same thing if we printed out information about BDX exporting - it'd be printed out to the console.

**Comment by Fr0sk** [comment]
Don't know why, but I don't think it appears to me... Well, probably I just missed it

**Comment by GoranM** [comment]
> Or maybe just print out the fact that the export process has started?

When you export, Blender changes the mouse cursor to a timer, which signifies "wait for the operation that you just initiated to complete".

Given that, it seems kinda redundant to print "export started" in the console.

**Comment by SolarLune** [comment]
Well, I think it's necessary, as Blender just freezing when you press P doesn't really tell you why it's happenning. Unless you're familiar with BDX, the user wouldn't know why this happens.

However, given that the export process was optimized, this phase should only last a few seconds now in most use cases, so it's OK, I suppose.

Issue closed.
