### ISSUE TITLE
Suggestion: OnRender()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#547]
Hey, there. So, basically, the issue that I'm seeing is that drawLine() functions don't work because they execute before the game world is drawn. So, to rectify this, I suggest an `onRender()` function that runs in GameObjects and Components after the scene is rendered. This way, any drawing logic can run afterwards.

An alternative solution would be to drop the `scene.update()` call to after the rendering process, but that would mean that changes take effect one frame after the game renders. I'm not a fan of this solution.

Anyway, thoughts?

**Comment by GoranM** [comment]
You could have drawLine() buffer commands, and then execute them later.

**Comment by SolarLune** [comment]
Hmm, that might be a better idea, yeah. I'll give it a shot.

**Comment by SolarLune** [comment]
Seems to work fine. PR submitted!

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!

**Comment by rafcolson** [comment]
I don't think it's merged yet, is it?

**Comment by SolarLune** [comment]
Ah, it's not - whoops! Oh well; guess I'll re-open this until it is?

**Comment by SolarLune** [comment]
OK, now it was merged, so I'll close this, haha.
