### ISSUE TITLE
Suggestion: initialize uv position in SpriteAnim.Animation

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#548]
Currently, when adding an animation to ```SpriteAnim```, the ```sequence``` entry in ```SpriteAnim.add()``` will also not update the uv position until the animation is played.

I'm using this workaround:

```java
package com.raco.test;

import com.nilunder.bdx.Bdx;
import com.nilunder.bdx.GameObject;
import com.nilunder.bdx.components.SpriteAnim;

public class Button extends GameObject{
	
	public SpriteAnim sa;
	
	public void initialize(boolean rowBased, int sequence){
		sa = new SpriteAnim(this, 64, 64, rowBased, true);
		sa.add("in", sequence, new int[]{2, 4, 5}, 60, false);
		sa.add("out", sequence, new int[]{3, 1, 0}, 60, false);
		sa.active = sa.animations.get("out");
		components.add(sa);
	}
	
}
```
But obviously this is not always a good solution. In the case of the ```Button.java``` class "out" will end with zero so it will return to the initial uv position. This wouldn't work with "in".

My suggestion would be to initialize the uv position when adding the animation so it corresponds to the row or column first uv position, without initializing ```active``` at all.

Can I give it a try?

**Comment by GoranM** [comment]
> In the case of the Button.java class "out" will end with zero so it will return to the initial uv position. This wouldn't work with "in".

I don't really understand the problem.

The add method is used to define sequences, not to actually set current frame - we have a method to do the latter, and that should be used to initialize as desired.

**Comment by rafcolson** [comment]
>The add method is used to define sequences, not to actually set current frame - we have a method to do the latter, and that should be used to initialize as desired.

I'm sorry I wasn't clear. When no animation is played yet, also the ```active``` field will be ```null```. And so the problems arises when using the ```frame(int frame)``` method, when it calls ```playHead``` on ```active```, as you can see [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/components/SpriteAnim.java#L170). This will cause an error. I wasn't sure to call this a bug because it could be a design flaw.

**Comment by GoranM** [comment]
The system assumes that an active animation is set before animation methods are called, so the user is expected to specify that as part of initialization.

I don't really see the benefit in having `add` set an active animation by default, because the user typically wants to set that explicitly, regardless of the order in which the sequences were added.

**Comment by rafcolson** [comment]
I see your point. You see, I have an animation sheet with rows containing animation sequences of several types of buttons. I'm adding all buttons from only one template and add the SpriteAnim component to them with the option to make the models unique. So for example, to initialize the button in the second row, I should set the uv position to the first position on the second row. I suppose I could just add an "init" animation and play this once at initialization. That would make sense indeed.
```java
sa.add("init", sequence, new int[]{0}, 60, false);
```
