### ISSUE TITLE
Suggestion: Change Default Clear Color

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#555]
Hey, there. 

I think a lighter, more neutral default clear color would be nice, rather than defaulting to pure black. Either blue or dark gray, perhaps? With black, it's easy to lose darker objects / colors in the background.

EDIT: Or maybe something more "BDX-themed"? What about orange-ish?

**Comment by GoranM** [comment]
It would probably be best to just get the starting color from blender's world properties, which seems to be set to a dark gray by default.

**Comment by SolarLune** [comment]
Good idea. PR submitted. 

If there's not a world in Blender for the scene, it defaults to the dark gray that new Blender Worlds are created with (not gamma corrected, though). Also, the clear color default is only set once, by the first scene. Otherwise, adding scenes would change the background clear color.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!
