### ISSUE TITLE
Profiler Clean-up

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#559]
Hey, there. I think we could do a bit to kinda clean up the profiler's headings - there's a few things that we don't really need to profile, like updating the camera or input logic. There's just not enough time spent on it to profile it, I think. "Visuals" and "Render" or "Worldstep" and "Collisions" could be compressed, as well, into a single profiler listing - simple stuff like that. "Children", for example, could be compressed with "Render" or "Logic".

We also need might need to move some code around to be properly profiled, like moving the BDX components list after the call to stop the profiler for input checking (which isn't really necessary, as it doesn't profile all of it, just for presses).

Finally, we need to document what each category in the profiler does.

**Comment by rafcolson** [comment]
Sounds good. I would personally be interested to see these categories:

- **logic** (no change)
- **scene** (input, visuals, camera, children)
- **physics** (worldstep, collisions)
- **graphics** (graphics, render)
- **outside** (no change)

**Comment by SolarLune** [comment]
PR Submitted.

**Comment by rafcolson** [comment]
This should fix for #576.

**Comment by SolarLune** [comment]
So I should rebase my changes over that commit and remove the extra start() calls?

**Comment by rafcolson** [comment]
If you want to you can just copy paste, that would be easiest. But you don't have to. I can submit a PR after this PR (like it is now) is submitted.

**Comment by SolarLune** [comment]
OK, you can submit the PR, then; I'll submit the PR was the clean-up as it is.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now.
