### ISSUE TITLE
Suggestions: Vector2f to Vector3f (and visa versa) convenience methods

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#561]
API Vector3f:

<a name="to2f" href="#to2f">#</a> **to2f**() - Vector2f

API Vector2f:

<a name="to3f" href="#to3f">#</a> **to3f**() - Vector3f

**Comment by GoranM** [comment]
It doesn't really seem like something that you would need to do frequently, and when you do, `new Vector2f(v.x, v.y)` is already fairly terse.

**Comment by rafcolson** [comment]
Yeah, you're right.
