### ISSUE TITLE
Suggestion: Index Arguments for Color(), Tint(), Shadeless(), blendMode()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#566]
Hey, there. So currently, the color() setters work on all materials on the GameObject. This can be undesirable, so I propose an index argument that would specify which material to work on.

Here's the proposed API:

```java

- Getters -

color(int index) - Color
color() - Color - (shorthand for color(0))

- Setters -

color(Color color) - Sets the color for all materials on it and its children
colorNoChildren(Color color, int index) - Sets the color for just the object for the material in the specified slot
colorNoChildren(Color color) - Would color all materials for just the object

```

Note that color() can't be specified to use an index because it would do that for its children, too, which may not make sense.

EDIT: Oh, and pretty much the same thing for tint(), too.

EDIT 2: Might as well extend it to the shadeless functions, as well.

EDIT 3: BlendMode, too, I guess.

**Comment by GoranM** [comment]
It sounds like a method that should be on the Material, not on a GameObject. Might be time to create our own subclass of libgdx material, with all the relevant methods.

**Comment by SolarLune** [comment]
OK, I think I got this working, then. PR submitted. Here's a quick list of the changes.

- We have a Material class now. It extends the LibGDX Material.

- The color, tint, blendMode, and shadeless functions are now on the Material.

- I added two functions (`copyToMaterials` and `copyToGameObjects`) to allow the user to easily set the color / tint / alpha / whatever across multiple objects / materials.

- The GameObject material functions now take and return our Materials.

- The materials returned from the GameObject are stored on the GameObject itself (because each GameObject can have its own set of materials, of course).

- By default, the materials in use on the part and on the GameObject are references to the scene materials. This means that changing the values of one material changes them for all objects using them in the scene. This can be easily worked around by duplicating the Material and assigning it, using one of the GameObject's material functions.

**Comment by rafcolson** [comment]
Nice. But why put ```Material``` in ```gl```? Couldn't it be in ```bdx```?

**Comment by SolarLune** [comment]
> Also be sure to change line 306 in Profiler.java to background.materials.get(0).color(BG_COLOR);.

Thanks! Fixed. Now it should be more friendly to objects with "no material" (it assigns them the default material).

> Nice. But why put Material in gl? Couldn't it be in bdx?

Because it's a display related class. It's not on the same "level" as GameObjects, Lights, Cameras, etc. It's more akin to Textures, Sounds, Music, etc. An asset, and a supporting class. That's my thought, anyway.

> By setting the material on the model it will not be unique anymore. And so, changing colors will affect all objects with the same materials.

I don't set them on the model, I set them on the NodeParts of the modelInstance after it's created. Effectively, it's the same in that all meshes of objects that use a material use that very same material, but I just wanted to clarify that point.

As I mentioned, the materials available on GameObjects are just references to the scene's materials. That makes sense, as if you have, say, a grass material on a platform object in-game, it should basically be the same grass material as on the other platform objects throughout the game. That way, if you wanted to change the color of all materials in the game, you can.

If you want to have a material be "local" for a GameObject, just duplicate it and assign it to the GameObject. If this is undesirable, we could alter this to be reversed - that materials default to being unique to each model (so basically, the materials in `scene.materials` are basically just used to clone from), and you could have them shared between GameObjects as you wish. We could also add a `useUniqueMaterials()` function that just duplicates and reassigns the materials currently used on the modelInstance.

Using a unique model, however, should not break links to the materials - they should link to the same materials that the modelInstance used (whether unique or shared).

> But maybe there's an other gain with having our own Material class, I don't see?

I'd agree that simply adding the slot argument would be easiest, but I think the class might be best in the long run. I think the goal of having it is that it should be its own thing - the GameObject shouldn't really have coloring, tinting, etc. functions, as we're not altering the GameObject - we're altering its material. We could also extend the material to provide other features, like having an easy to access function to slide UVs around, or things like that. 

I mean, everything to do with materials can't be on GameObject forever - it'd get bloated eventually.

**Comment by rafcolson** [comment]
>Because it's a display related class. It's not on the same "level" as GameObjects, Lights, Cameras, etc. It's more akin to Textures, Sounds, Music, etc. An asset, and a supporting class. That's my thought, anyway.

I understand. But I think we should have a separate folder then. I don't think ```gl``` would be a proper destination because it implies a specific part of display related stuff (rendering). LibGdx has ```graphics```. I think we should change ```gl``` to ```graphics``` instead then.

>I don't set them on the model, I set them on the NodeParts of the modelInstance after it's created. Effectively, it's the same in that all meshes of objects that use a material use that very same material, but I just wanted to clarify that point.

That's only true for initialization. But not for altering the material afterwards, because you're not editing the material on the ```ModelInstance``` itself. Did you test this? Because my tests show that replacing the material with a copy has no effect. It just gives the model a unique material, so all objects sharing that model have that unique material.

As you mentioned:
>As I mentioned, the materials available on GameObjects are just references to the scene's materials.

And so, when you change a material on the GameObject, you'll in fact change the scene material, changing all objects referencing to that material.

>That makes sense, as if you have, say, a grass material on a platform object in-game, it should basically be the same grass material as on the other platform objects throughout the game. That way, if you wanted to change the color of all materials in the game, you can.

I agree we should be able to easily change the color of objects with the same material. But I think there could be alternative ways to do that.

>If you want to have a material be "local" for a GameObject, just duplicate it and assign it to the GameObject.

Doesn't work. I'm using this method:
```java
    private void useUniqueMaterials(){
        for (Material mat : materials){
            mat = new Material(mat);
        }
    }
```
>Using a unique model, I suppose, should create new materials for the modelInstance.

Doesn't work either, as my tests show.

>the GameObject shouldn't really have coloring, tinting, etc. functions, as we're not altering the GameObject - we're altering its material.

You're right, but LibGdx offers two ways to do that. You can change the material on the ```ModelInstance```, which is a local operation, or you can change the material on the ```Model```, which is a global operation, since multiple ```ModelInstance```'s can share the same ```Model```. It really think we should not lose this advantage by ruling out one of those options.

That's why I would suggest to keep the old methods on ```GameObject```.

>We could also extend the material to provide other features, like having an easy to access function to slide UVs around, or things like that.

>I mean, everything to do with materials can't be on GameObject forever - it'd get bloated eventually.

That's fine.

**Comment by SolarLune** [comment]
Before we go on with this discussion:

> It just gives the model a unique material, so all objects sharing that model will have that unique material.

That code snippet doesn't do anything other than just create a new material. You've got to assign the new material to the GameObject with a `GameObject.material()` function. Just making a duplicated material doesn't do anything.

**Comment by rafcolson** [comment]
I was wrong. The ```modelInstance.materials``` array is the same as the one in ```modelInstance.nodes```. I'm sorry about that. So doing this:
```java
                ColorAttribute ca = (ColorAttribute) modelInstance.nodes.first().parts.first().material.get(ColorAttribute.Diffuse);
                ca.color.a = 0.5f;
```
Will also be a local operation.

**Comment by rafcolson** [comment]
>That code snippet doesn't do anything other than just create a new material.

Stupid me. It works:
```java
    private void useUniqueMaterials(){
        ArrayList<Material> l = new ArrayList<Material>();
        for (Material mat : materials){
            l.add(new Material(mat));
        }
        for (int i=0; i < l.size(); i++){
            material(l.get(i), i);
        }
    }
```

**Comment by SolarLune** [comment]
The PR for this was merged, so I'll close this now.
