### ISSUE TITLE
Using move() on a GameObject with a Vector of length 0 Makes the Object Disappear

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#57]
Hey, there. So if you use move() on a game object with a vector that has a length of 0, the object will disappear.

**Comment by GoranM** [comment]
I can't seem to reproduce.

If you could follow [these instructions](https://github.com/GoranM/bdx/wiki/Reporting-Bugs), and provide a small example, that would be very helpful.

**Comment by SolarLune** [comment]
Hm, I can't either, though it was happening earlier today. I'll close this until it comes up again.
