### ISSUE TITLE
Suggestion: VirtualController

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#570]
# API VirtualController

Extends [ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<String>. A collection of names of GameObject's that act as onscreen buttons. Tells if a button is hit, touched or just touched by a mouse or fingers on a touchscreen. Overrides methods of [ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html) for adding and removing names of buttons. Buttons should not have body type ```"NO_COLLISION"```.

When created it will be added to ```Bdx.vControllers``` and available for mapping with ```Bdx.imaps```.
___

### Constructors

<a name="VirtualController" href="#VirtualController">#</a> **VirtualController**(String prefix="")

Constructor with optionally a prefix.

<a name="VirtualControllerGameObject" href="#VirtualControllerGameObject">#</a> **VirtualController**([ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<GameObject> btns, String prefix="")

Constructor with a list of buttons and optionally a prefix.

<a name="VirtualControllerString" href="#VirtualControllerString">#</a> **VirtualController**([ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<String> btnNames, String prefix="")

Constructor with a list of button names and optionally a prefix.
___

### Fields

<a name="name" href="#name">#</a> **name** - String

Customizable name for use with multiple virtual controllers. For example:
```java
if (Bdx.vControllers.get("vGamepad").hit("a")){
	// do stuff
}
if (Bdx.vControllers.get("vMenu").hit("options")){
	// do stuff
}
```
<a name="prefix" href="#prefix">#</a> **prefix** - String

The prefix field determines which part of the button name should be ignored in the getters. For example if buttons are named *"Btn_A", "Btn_B", "Btn_C", ...*:
```java
public class InputController extends GameObject{
	
	public VirtualController vc;
	
	public void init(){
		String prefix = "Btn_";
		vc = new VirtualController(prefix);
		for (GameObject g : scene.objects){
			if (g.name.startsWith(prefix)){
				vc.add(g);
			}
		}
	}
	
	public void main(){
		vc.update();
		
		if (vc.hit("A")){
			// do stuff
		}
		if (vc.hit("B")){
			// do stuff
		}
		...
	}
	
}
```
<a name="hitList" href="#hitList">#</a> **hit** - [ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<String>

List of the names of buttons that are hit.

<a name="downList" href="#down">#</a> **down** - [ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<String>

List of the names of buttons that are touched.

<a name="upList" href="#upList">#</a> **up** - [ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<String>

List of the names of buttons that are just touched.

Access to these fields becomes useful when animating the buttons. For example:
```java
	public void main(){
		vc.update();
		
		if (vc.hit()){
			for (String s : vc.hit){
				((SpriteAnim)scene.objects.get(s).components.get(0)).play("hit");
			}
			
			if (vc.hit("A")){
				// do stuff
			}
			...
		}
		
		for (String s : vc.up){
			((SpriteAnim)scene.objects.get(s).components.get(0)).play("up");
		}
	}
```
___

### Methods

<a name="add" href="#add">#</a> **add**(GameObject btn)

Convenience function for adding the name of this button.

<a name="remove" href="#remove">#</a> **remove**(GameObject btn)

Convenience function for removing the name of this button.

<a name="addAll" href="#addAll">#</a> **addAll**([ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<GameObject> btns)

Convenience function for adding the names of these buttons.

<a name="removeAll" href="#removeAll">#</a> **removeAll**([ArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html)\<GameObject> btns)

Convenience function for removing the names of these buttons.

<a name="hitAny" href="#hitAny">#</a> **hit**() - boolean

Returns whether any of the buttons is hit or not.

<a name="downAny" href="#downAny">#</a> **down**() - boolean

Returns whether any of the buttons is touched or not.

<a name="upAny" href="#upAny">#</a> **up**() - boolean

Returns whether any of the buttons is just touched or not.

<a name="hit" href="#hit">#</a> **hit**(String s) - boolean

Returns whether a button with this name is hit or not.

<a name="down" href="#down">#</a> **down**(String s) - boolean

Returns whether a button with this name is touched or not.

<a name="up" href="#up">#</a> **up**(String s) - boolean

Returns whether a button with this name is just touched or not.

<a name="iHit" href="#iHit">#</a> **iHit**(String s) - int

Same as ```hit(s)```, but returns an integer: 1 if true, and 0 if false.

<a name="iDown" href="#iDown">#</a> **iDown**(String s) - int

Same as ```down(s)```, but returns an integer: 1 if true, and 0 if false.

<a name="iUp" href="#up">#</a> **iUp**(String s) - int

Same as ```up(s)```, but returns an integer: 1 if true, and 0 if false.

<a name="update" href="#up">#</a> **update**()

Update function that should be called before calling the functions above. For best results it's recommended to call it on a GameObject which uses execution priority (It seems that execution priority is not yet documented in the API, so I'll do this also and reference to it).

<a name="dispose" href="#up">#</a> **dispose**()

Removes this virtual controller from ```Bdx.vControllers```.
___

# API Bdx
...
<a name="vControllers" href="#vControllers">#</a> **vControllers** - [ArrayListNamed](https://github.com/GoranM/bdx/wiki/API-ArrayListNamed)\<VirtualController>

A named list of added virtual controllers. 
...
___

# API InputMaps
...
* VirtualController - "v:button" (button -> valid string arg for VirtualController.\* methods); specifying indices works the same as with gamepads.

...

**Comment by SolarLune** [comment]
Sounds like it could be useful for mobile games, or possibly having GUI options that also have keyboard shortcuts (i.e. click a map icon, or press M to open the map). Here's my thoughts:

1) I'd imagine we wouldn't need the update() function to be publicly available, as we could call it from inside BDX.

2) Your example API lists GameObject as the types where I'm guessing it should be Strings (i.e. the add function)?

3) While I know you don't like everything going through InputMaps, being that this is a method of controlling game actions, it should at least be able to work with InputMaps as well. There's no sense in having disparate and separated control mechanisms in a single engine (i.e. "Use code to check InputMaps for desktop controls, but you'll have to use more code to check the VirtualController for inputs").

**Comment by rafcolson** [comment]
>Sounds like it could be really useful for mobile games, or having GUI options that also have keyboard shortcuts (i.e. click a map icon (a virtual button), or press the M-key to open the map). Cool!

Yes, it could be used for menus, virtual gamepads or even objects.

>1) I'd imagine we wouldn't need the update() function to be publicly available, as we could call it from inside BDX.

This would be desirable but not so much necessary, I think. And then there's the question if multiple instances of the VirtualController are used at once or not. Because that too, would be an option. For example, one for the Hud, one for a Menu, one for the Game. Another approach could be to make this a Component. But then the super object wouldn't be very useful, missing the purpose of being a Component... But that would have the advantage to put everything in a State update, which will run when ```c.state.main()``` is called in the game loop.

>2) Your example API lists GameObject as the types where I'm guessing it should be Strings (i.e. the add function)?

These are convenience functions. One could have a bunch of buttons parent to an object on a hidden layer. Adding the object to the scene and next creating the VirtualController with the children saves some extra code. The same for adding and removing.

>3) While I know you don't like everything going through InputMaps, being that this is a method of controlling game actions, it should at least be able to work with InputMaps as well. There's no sense in having disparate and separated control mechanisms in a single engine (i.e. "Use code to check InputMaps for desktop controls, but you'll have to use more code to check the VirtualController for inputs").

I agree that this should work with InputMaps as well. The VirtualController acts similarly as the Keyboard. So implementation should be simple. I don't understand what you mean by "using more code to check the VirtualController for inputs"?

**Comment by rafcolson** [comment]
>1) I'd imagine we wouldn't need the update() function to be publicly available, as we could call it from inside BDX.

I looked into this. Because button detection (with Finger) needs the scene it's not possible to call ```update()``` in ```Bdx```. I think the ```update()``` function is best managed manually.

Or, as being suggested, we could make it a component. But then I'm not sure if that would be a too unconventional use of ```Component```.

**Comment by SolarLune** [comment]
> I looked into this. Because button detection (with Finger) needs the scene it's not possible to call update() in Bdx. I think the update() function is best managed manually.

Why not just put it in the Bdx main loop where it updates the scene?

**Comment by rafcolson** [comment]
>Why not just put it in the Bdx main loop where it updates the scene?

It should be put in ```runObjectLogic()``` after the scene is assigned to ```Bdx.fingers``` and before the objects of the scene run ```main()``` ([line 779](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L779)). But for some reason this causes a flicker. It's as if every once in a frame the buttons are not detected. I could try it again. I'll let you know what happens.

**Comment by GoranM** [comment]
> There's no sense in having disparate and separated control mechanisms in a single engine

From that perspective, the best solution would be to actually create a Gamepad object with input triggers that correspond to user defined events.

With that, you wouldn't need a special path for a "virtual controller" in imaps - It would all work as if you actually had a real gamepad.

**Comment by SolarLune** [comment]
Could you explain a bit? Not sure I get it. Would it be like a Gamepad object that we would manually define buttons or axes for or something like that?

**Comment by rafcolson** [comment]
>With that, you wouldn't need a special path for a "virtual controller" in imaps - It would all work as if you actually had a real gamepad.

Interesting idea. But wouldn't that be unnecessarily complicated. All a virtual gamepad would have is buttons really, in contrary to a real Gamepad. I think the Gamepad classes with their specifics wouldn't be the best environment to implement a virtual gamepad.

Another reason why I think it's probably not worth it, is that VirtualController actually could be used for a variety of input types. It's not so much limited to a virtual gamepad. You could easily create a GUI with menus for a touchscreen device but also for pc using the mouse.

In any case, if you are worried about the extra if-clause in imaps, that's nothing compared to all the extra conditions we'll have to set while implementing virtual ```Bdx.gamepads```. But I could be missing something of course.

**Comment by GoranM** [comment]
> Would it be like a Gamepad object that we would manually define buttons or axes for or something like that?

It would be a Gamepad object, where gamecode would call the methods of its GamepadAdapter directly, instead of libgdx calling them (as it would for a real gamepad).

> Interesting idea. But wouldn't that be unnecessarily complicated.

Not unnecessarily, because it integrates a "virtual gamepad" as an actual gamepad object within the system. That's far more elegant than having a special purpose "vControllers" thing, with a completely separate code-path in imaps.

> You could easily create a GUI with menus for a touchscreen device but also for pc using the mouse.

I don't really see the utility from a GUI perspective. I mean, the whole point of having a "virtual gamepad" is to be able to use it as if it was an actual gamepad in the system.

**Comment by rafcolson** [comment]
>Not unnecessarily, because it integrates a "virtual gamepad" as an actual gamepad object within the system.

Maybe @SolarLune could tell us if such an integration would be overly complicated. I suspect there comes more to it then we might think.

>That's far more elegant than having a special purpose "vControllers" thing, with a completely separate code-path in imaps.

I would agree with you if all we want is a "virtual gamepad", but that has not been my suggestion.

>I don't really see the utility from a GUI perspective. I mean, the whole point of having a "virtual gamepad" is to be able to use it as if it was an actual gamepad in the system.

I never suggested to implement a "virtual gamepad", but rather a "virtual controller". A "controller" has more than one variant, which can go from gamepads, joysticks and steering wheels to keyboard, mouse and touchpad, even to motion sensors or a fishing rod, ... see [Wikipedia](https://en.wikipedia.org/wiki/Game_controller).

A "virtual" controller would be, as the word implies, an emulated version of the existing variants, and more. So when I'm saying GUI, I mean a graphical interface which is performed through direct manipulation of the graphical elements by a touchscreen device or mouse.

And so this could also be a "virtual keyboard", a "virtual mouse", a "virtual piano", a "virtual gun", a "virtual steering wheel", ..., even menu and window interfaces. It could even be used as a puzzle game controller.

Then there's another important aspect to consider. As you can see the "VirtualController" class offers more than a "Gamepad" class would, when it comes to adding and removing buttons, specifying a prefix and accessing hit, down and up lists. Without those methods a "virtual" gamepad would lose a lot of its dynamic potential: modification of the buttons itself. Well, it could be preserved, but you'd have to take a lot of sidetracks to get there.

The reason I started this issue was mainly because I would like to use InputMaps for all input, virtual controllers included. @SolarLune also liked me to share this so it could be considered to become part of BDX. So it's up to you what you like to do with it. Everything's fine with me. I'll just have to use my own version of something that resembles to InputMaps.

**Comment by GoranM** [comment]
Well, in that case, It sounds like all you really need here is a mechanism to define a custom imaps descriptor, with corresponding "hdu" methods that call relevant virtual device functions.

**Comment by rafcolson** [comment]
>Well, in that case, It sounds like all you really need here is a mechanism to define a custom imaps descriptor, with corresponding "hdu" methods that call relevant virtual device functions.

I don't see how this would be possible without adding fields and an extra if-clause to the ```InputMaps.Input``` constructor. Could you maybe give me some pointers?

**Comment by GoranM** [comment]
I'm not sure about extra fields, but you'll probably need an additional clause to handle a custom descriptor:

```java
...
} else if (customDescriptor(d[0])) {
    ...
}
...
```

Is that what you mean?

**Comment by rafcolson** [comment]
>Is that what you mean?

I don't understand what ```customDescriptor(d[0])``` is supposed to represent. And I don't see how such a mechanism would work.

**Comment by GoranM** [comment]
> I don't understand what customDescriptor(d[0]) is supposed to represent.

It represents a function that returns true if d[0] is a custom descriptor name.

> I don't see how such a mechanism would work.

There would be a mapping from a custom descriptor name, to an object with a method that takes d[1], and returns a fully populated hdu array.

**Comment by rafcolson** [comment]
This is what I came up with. A ```CustomInput``` class with methods ```hit(s)```, ```down(s)``` and ```up(s)``` returning false by default. And a ```Bdx.customInputs``` list, which will be iterated in ```InputMaps.Input(d)```. For use, extend ```CustomInput``` and override constructor (if necessary), override ```hit(s)```, ```down(s)``` and ```up(s)``` methods and add other methods (for updating eg.). Use ```dispose()```if not needed anymore.

I don't see another way then to create a built-in object with relevant methods for hit, down and up events, because internally such methods should exist in order map with ```InputMaps```. But if there is another way to make it work with ```InputMaps```, I would appreciate it if you could give a short example @GoranM, because I could be misunderstanding your explanation about your suggested mechanism.

**Comment by GoranM** [comment]
Given something like:

```java
class FnHDU {
    public FnBool[] eval(String d1){
    }
}
```

I think you could do:

```java
FnHDU vc_hdu = new FnHDU(){
    public FnBool[] eval(String d1){
        FnBool hdu = new FnBool[3];
        hdu[0] = new FnBool(){
            public boolean eval(){
                 return virtual_controller.btnHit(d1);
            }
        }
        ...
    }
}

Bdx.imaps.customDescriptorHUD.put("vc", vc_hdu);
```

And then in the Input constructor:

```java
...
} else if (customDescriptorHDU.contains(d[0])) {
    hdu = customDescriptorHDU.get().eval(d[1]);
}
...
```

**Comment by rafcolson** [comment]
Thanks.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Merged. Thanks for the help. API will be updated soon.
