### ISSUE TITLE
Set Scaling to -1

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#572]
Hey, there. I'm trying to flip a mesh to face the opposite direction. As far as I know, apart from making duplicate meshes that are mirrored, the only possible way to do this is to reverse the scaling on the X axis. However, BDX doesn't support negative values for scaling, right? Why / is it possible to fix / is there another, alternative solution for this?

**Comment by GoranM** [comment]
If I remember correctly, the getLocalScaling method on the bullet collision shape will always provide a vector with positive elements, regardless of what is provided via setLocalScaling.

If you store the scale on the game object itself, that should allow for negative scale (for the visual part - the physics should just ignore it, as it does now).

**Comment by SolarLune** [comment]
Hmm, I tried replacing that line in scale() with a stored scale vector, but it doesn't work for collision shapes that aren't Triangle Mesh or Convex Hull. It looks like the other shapes might call ConvexInternalShape.setLocalScaling, which sets the local scaling absolutely...

Would it be possible to, say, alter the modelInstance's transform for these cases where the object has an internal collision shape (though I don't know how to do it)?

**Comment by GoranM** [comment]
It should be more than just a one line change; Search for all uses of getLocalScaling, and make sure those vectors are replaced with the new scale stored on GameObject.

**Comment by SolarLune** [comment]
OK, I think I've got it now. Testing seems fine on my end; lemme know if there's anything wrong.

**Comment by GoranM** [comment]
Once the PR is up, the discussion should continue there.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!
