### ISSUE TITLE
Issue: Profiler background.color

### ISSUE THREAD

**Issue by EdwardAngeles** [GoranM/bdx#579]
I'm compiling the lastest pull and it throws me this error:

`build:
    [javac] Compiling 1 source file to /home/edward/Documents/bdx/bdx-source/build
    [javac] /home/edward/Documents/bdx/bdx-source/src/com/nilunder/bdx/utils/Profiler.java:304: error: cannot find symbol
    [javac] 				background.color(BG_COLOR);
    [javac] 				          ^
    [javac]   symbol:   method color(Color)
    [javac]   location: variable background of type GameObject
    [javac] 1 error

BUILD FAILED
`

**Comment by rafcolson** [comment]
Seems that the new color method is not yet updated in the Profile.java. I'll submit a fix soon (with also another fix).

**Comment by SolarLune** [comment]
After we get this fixed, can we get a new build of BDX?

**Comment by GoranM** [comment]
> After we get this and the prefix bug (#581) fixed, can we get a new build of BDX?

Yes.

**Comment by rafcolson** [comment]
Fixed with #578, so can be closed.
