### ISSUE TITLE
Issue: Can't Extend Custom Material Shaders From Lighting Shaders

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#581]
Hey, there. 

So basically, the issue is that we can't use custom shaders that extend from the lighting shaders. The problem comes in because when creating the default lighting shaders, we allow LibGDX to create its own ShaderProgram, which adds on a prefix to the beginning depending on the attributes of the renderable it's created for. However, when we pass in our custom ShaderProgram, this prefix isn't added on. Since we can't edit the shaderprogram's fragment and vertex source later, we can't add in the prefix later, and since the lighting shaders reference things in the prefix, it crashes. So, we can't base custom shaders off of the existing lighting shaders. 

Basically, BDX will crash if you try to use a custom material shader with the built in default.frag and default.vert shaders.

A solution could be to create our prefix for ShaderPrograms using a fixed prefix no matter what (since we know what our renderables require).

Another solution could be for our ShaderProgram to contain the actual LibGDX shader program data, which would be recreated as necessary when LibGDX feels like it. Our ShaderProgram will then overload the setUniform functions, so the users would generally create a Program and then call setUniform on it. The function calls will only go through if the program data has been initialized.

I'll try the first solution, well, first.

**Comment by SolarLune** [comment]
Tried the first solution; I thought it best that I didn't do that (since it'd be fixed across all renderables).

I ended up going with an alternative solution.

Basically, I'm adding a new kind of ShaderProgram, the MaterialShader, and renaming the old ShaderProgram to ScreenShader. Why?

- Because 3D material shader programs don't need any of the fields on the ScreenShader, like renderScale or overlay.
- Because 3D material shader programs should NOT be compiled immediately like the ScreenShader can be, but rather should only be compiled when the renderer goes to append the prefix to the beginning of the shader source and actually create the shader.
- Since the 3D material shader program can be recompiled through the above point, the user shouldn't be able to store a reference to it (since it would be broken when the shader program is recompiled). To facilitate this, the MaterialShader is a shell around which the program data exists (in the `programData` field). For the difference, see:

```java

screenShader = ScreenShader.load("bdx/shaders/2d/default.vert", "bdx/shaders/2d/bloom.frag");
screenShader.begin();
screenShader.setUniformf("strength", 1.0f);
screenShader.end();

materialShader = MaterialShader.load("bdx/shaders/3d/default.vert", "bdx/shaders/3d/static.frag");

// And then later

if (materialShader.compiled()) {
    materialShader.programData.begin();
    materialShader.programData.setUniformf("strength", 1.0f);
    materialShader.programData.end();
}
```
- Also (kinda unrelated), calling GameObject.materials.unique() now renames the cloned materials to at least attempt to make them unique. This was done in accordance with the matShaders hash map, which links material names to shaders. It might be best to link actual materials to shaders, but it might also be wise to keep this HashMap on the Scene, as the Materials are local to GameObjects / the Scene.

PR submitted. Lemme know what you guys think.

**Comment by rafcolson** [comment]
How about renaming ```Scene.filters``` to ```Scene.screenShaders```? And renaming "2d" to "material" and "3d" to "screen" in ```assets\bdx\shaders\```

**Comment by SolarLune** [comment]
Sure! Done.

**Comment by SolarLune** [comment]
PR merged, so I'mma close this. Thanks!
