### ISSUE TITLE
Issue with numpy on ubuntu / linux

### ISSUE THREAD

**Issue by EdwardAngeles** [GoranM/bdx#583]
Hey. So, adding the bdx.zip 0.2.3 to blender works perfectly, but with the lastest versions, blender throws me this error:

File "/usr/share/blender/2.77/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/edward/.config/blender/2.77/scripts/addons/bdx/__init__.py", line 2, in <module>
    from . import (
  File "/home/edward/.config/blender/2.77/scripts/addons/bdx/exporter.py", line 10, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

multiarray is in the package numpy which is not being imported in bdx 0.2.3, but it is in the lastest version. Trying to troubleshoot it, I tried reinstalling the package, which is the solution in some forums, and it didn't worked.

Any idea?

(ubuntu 14.04 LTS)

EDIT:

By the way, running python on the terminal and importing numpy work perfectly.

**Comment by aliasaila** [comment]
What's the output of:

`echo $PYTHONPATH`

and 

`python3 -c 'import sys; print(sys.path)'`

I suspect that Blender is using it's own copy of the python binary with the numpy package from your local python installation, and that's where the mismatch is happening. 

(Somewhat related: [ImportError: cannot import name multiarray](http://blenderartists.org/forum/showthread.php?233753-adding-3rd-party-modules&p=1966918&viewfull=1#post1966918)).

It appears you are using Blender 2.77. Would that be rc2? 

I've just tried it and it works, so I'm not exactly sure what's going on.

**Comment by EdwardAngeles** [comment]
Thanks for the answer. This is what I got:

- echo $PYTHONPATH: nothing shows up. Do I need to configure?

- python3 -c 'import sys; print(sys.path)':
`['', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages']`

- I'm using Blender 2.77 Release Candidate. That's what the splash screen says, I guess it's rc1.

**Comment by aliasaila** [comment]
As a test you could try setting PYTHONPATH to the full path of the python3.5 directory in the Blender 2.77 directory.

(e.g:
`export PYTHONPATH=/home/edward/blender-2.77-rc2-linux-glibc211-x86_64/2.77/python/lib/python3.5`)

Then when you run blender from that terminal python *should* find the correct packages.

The new Blender comes with python 3.5.1, so it needs to use those packages.

**Comment by EdwardAngeles** [comment]
Oh yeah! It worked, thanks!

But! The build failed, it said this:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> failed to find Build Tools revision 23.0.1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.546 secs
read blend: /home/edward/Documents/bdx/projects/Test/blender/game.blend`

Of course, it has nothing to do with the python issue, right?. Oh! And I can run the project normally. Is it something I should worry about?

**Comment by aliasaila** [comment]
Nothing to worry about, it does that when it can't find the Android SDK.

**Comment by EdwardAngeles** [comment]
Ok!, problem solve, thanks.

By the way, are you using ubuntu? I wanted to asking if you are able to turn off mipmaps in blender, I toggle the button but nothing happes :/. I also tried toggling GPU mipmap generationm, it didn't work either. It used to work on windows. Any idea?

**Comment by aliasaila** [comment]
@EdwardAngeles I honestly don't know. I've never used that feature.

**Comment by SolarLune** [comment]
@EdwardAngeles Just to make sure, you're talking about the mipmaps button in the User Preferences? Because that works for me.

_____
If your original issue's solved, please feel free to close it.

**Comment by EdwardAngeles** [comment]
Yes, that one. I guees it's something with my blender.

Anyways, issue solved.
