### ISSUE TITLE
Suggestion: Material Unique By Default

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#584]
Hey. 

I was just thinking about this some more, and the more I think about it, the more awkward it seems for objects to share materials. That means that anytime you want to color or tint an object's material, you have to remember to make its material unique. 

If you want an enemy to flash, if you want a particle to change color over time - for anything that you want to uniquely change color, you'll need to make the material unique. It feels like it comes up often enough in game development to be a pain.

It might be better to approach this from the other direction; make the materials unique by default, and just allow the player to assign the shared material to objects as necessary.

**Comment by rafcolson** [comment]
I remember you were saying:
>I mean, everything to do with materials can't be on GameObject forever - it'd get bloated eventually.

I guess on second thought it feels awkward to treat color and tint as things that have to do with materials.

For the reason that most of the time color and tint are not so much material related as they are object related, their methods should also exist on ```GameObject```. We should follow LibGdx's design on this. Changing the color (or tint) through the ```modelInstance``` didn't affect other objects and didn't require keeping lists of unique materials either.

I suggest we add Blender's "Object Color" to the equation. We then could manage two sets of color, one for the ```GameObject```, and one for the ```Material```. Much as it is in the BGE right now. ```Scene.materials``` then aren't affected by setting ```GameObject.color```.

I'm not fond of the idea to make all materials unique by default. With hundreds of objects the ```Scene.materials``` map would contain at least as many and for what? It seems better to me to reflect how Blender works. By default materials are shared. And by default every object has its unique color.

**Comment by SolarLune** [comment]
> I guess on second thought it feels awkward to treat color and tint as things that have to do with materials.

Kinda, yeah. I think a middle ground would be nice. I dunno if I agree with adding an object color property / field, as that just feels kinda unnecessary.

I was just thinking of making each GameObject have its own copy of the material from the scene.materials HashMap (so the materials there would be the originals, but the copies aren't stored anywhere but on the GameObject). You can color each object as you wish through the normal `object.materials.color()` method, but if you needed to, you can have the objects share materials by assigning the reference to the original material to the object.

But I guess I could see the utility of a local object color property...

**Comment by GoranM** [comment]
> most of the time color and tint are not so much material related as they are object related

I don't see how they're "object related". I mean, if I can have an object with multiple materials, each with their own color, tint, texture, etc ... Clearly, the material is the defining unit of how a given piece of geometry is rendered.

I think it's probably fine to make materials unique by default.

**Comment by SolarLune** [comment]
If so, then we wouldn't really need the MaterialArrayList.unique() function, as that would be unnecessary. If it's OK with @rafcolson, I'll submit a PR to take that out next. Can we include this fix in the next release, as well?

**Comment by rafcolson** [comment]
It's up to you guys. I don't like it. But I suppose I could be wrong.
Blender proves with the concept of object color that color can be
considered to be a property of the game object and not of the material. But
don't let me stop you doing what you think is best.

**Comment by SolarLune** [comment]
Well, just because the BGE had something doesn't mean that BDX should as well. We're free to forge our own path here for BDX.

I think color is something inherent to materials, as even objects with no material in Blender need a material (the default one) to be rendered properly under LibGDX. This being the case, coloring materials to color objects seems easy enough to deal with; I don't think we really need an object coloring mechanic if materials are per-object anyway.

PR submitted.

**Comment by rafcolson** [comment]
>Well, just because the BGE had something doesn't mean that BDX should as well. We're free to forge our own path here for BDX.

That's beside the point. The fact that the BGE took that path proves with "Object color" that color can be considered to be a property of the game object and not of the material. I'm not saying that the BGE does something and that's why we should do the same. I'm saying that we should do something because of a reason and that the BGE proves that reason to be true.

**Comment by SolarLune** [comment]
I guess we just disagree. It doesn't really seem that big of a deal, though I do see some utility in having a color that influences the final color of all of a ModelInstance's materials. If an issue comes up where you need object coloring, make an issue and let us know; we can discuss it some more.

The PR was merged, so I'll close this now. Thanks, guys.
