### ISSUE TITLE
Suggestion: Automatic "To String Conversion" for Bdx.profiler.props

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#588]
Hey, there. 

I think it might be nice to add convenience functions to convert some of the common data types to strings in Bdx.profiler.props. That way, you don't have to type `Bdx.profiler.props.put("name", String.valueOf(value))` every time. You can just type `Bdx.profiler.props.put("name", value);`.

**Comment by rafcolson** [comment]
Seems like a good idea.

**Comment by GoranM** [comment]
I guess that would be fine.

**Comment by SolarLune** [comment]
PR Submitted. 
________
Hey, @rafcolson, I noticed that the profiler doesn't seem to display all the characters for the value of user property. It gets cut off at around 6 characters. Do you know anything about that?

**Comment by rafcolson** [comment]
>Hey, @rafcolson, I noticed that the profiler doesn't seem to display all the characters for the value of user property. It gets cut off at around 6 characters. Do you know anything about that?

Sorry, just noticed that you asked me a question. Could it be that @User is not notifying if a comment is edited?

Anyway, yes, there's a character limit. I didn't realize it was that limited though. Also, I don't know why I outlined the values to the right. So I've changed that. Now it's outlined to the left and limited to 17 characters.

**Comment by rafcolson** [comment]
@SolarLune Is 17 characters sufficient?

**Comment by SolarLune** [comment]
Hey, sorry, yeah, 17 characters is probably OK. I was just thinking about, say, displaying a Vector onscreen on the Profiler, so more is better, to me. Is there a reason the limit has to be relatively low?

**Comment by rafcolson** [comment]
>Is there a reason the limit has to be relatively low?

Not really. But to be able to display a Vector onscreen sounds like a good reason to extend the limit even more.

I'll just have to make sure that the background of the profiler scales accordingly. @GoranM I'll let you know when the PR is updated.

**Comment by rafcolson** [comment]
@SolarLune 25 is the maximum number without scaling the background. The number could be increased infinitely. The background could be scaled with increments of ```0.575 * SPACING * size``` per character (approximately). Let me know if this would be desirable.

If it's not that urgent, I'll suggest to leave this for another commit though. I noticed that fonts get quite distorted when converted, so I'm also looking into fonts and a way to make those pixel perfect. There is absolutely no way to make those pixel perfect right now. There is also no exact way to get the width and height of a converted text object. The ```*.fntx``` should produce the exact figures, but for some reason the converted text objects don't match.

**Comment by rafcolson** [comment]
@GoranM @SolarLune I've increased the number of characters to 150. I assume that's more than sufficient, so this can be merged.

**Comment by SolarLune** [comment]
Ah, 150 is great, yeah. Thanks!

**Comment by SolarLune** [comment]
I just tried it out - that's a lot better, though the profiler background changing size is a bit odd. It might be better to either have the background get bigger as necessary, but only get smaller after a short period of time, or to just have the background stretch to the edge of the window.

Anyway, it's fine as it is now, as I can see the result of printing out an object (a Vector3f, in this case).

**Comment by rafcolson** [comment]
>though the profiler background changing size is a bit odd. It might be better to either have the background get bigger as necessary, but only get smaller after a short period of time, or to just have the background stretch to the edge of the window.

It's probably better to remove the background altogether and use a custom bitmap font (white with black shadow and border). This would also allow us to double the font resolution and aim for a pixel perfect display. Right now the font is readable, but somewhat distorted. I'll start a new issue for that.

**Comment by SolarLune** [comment]
Cool! Everything was wrapped up, so I'll go ahead and close this now. Thanks!
