### ISSUE TITLE
Do We Need ScreenShader.overlay?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#589]
I'm just thinking that if you don't want to overlay the filtered result on the normal / previous render, you can do it yourself in the shader....?

The point of the overlay field was to indicate if the framebuffer should be cleared prior to drawing the filtered result, but if it simply never is cleared, then you can just write your shader to use the previous scene render as the base for the effect.

Anyway, it seems like we could do away with the overlay field altogether and just not clear the framebuffer. Then we could alter the blur and bloom filters to be ready for downsampling (it works fine with them now, but it doesn't work with overlay because it was built to be visible with overlay off).

I'll look into it, I think.

**Comment by SolarLune** [comment]
OK, it seems like we can remove it and the shaders that don't use overlay will work the same (and those that can take advantage of overlay, like the bloom shader, can benefit).

I'd also like to propose an `active` field that allows you to easily disable ScreenShaders without sacrificing their position in the filter stack.

**Comment by SolarLune** [comment]
OK, never mind about the overlay field - we do need it in case a filter alters the shape of the objects rendered onscreen (and so the original render can be seen behind it). We can keep it in.

_______

I'd still like to propose the `active` field, and also move the depthExtract shaders to the 3D folder.

**Comment by GoranM** [comment]
If you want to make a new suggestion, you should make a new issue for it.

This one should be closed.

**Comment by SolarLune** [comment]
OK.
