### ISSUE TITLE
Bug: Can't Fullscreen

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#591]
Hey, there. Looks like fullscreening is... Buggy at the moment? On my current project, triggering fullscreen causes a crash; BDX says it's because there's no OpenGL context found in the current thread, with the crash happening on the glClear() function call before rendering the game scene. Here's the error:

```
Exception in thread "LWJGL Application" java.lang.RuntimeException: No OpenGL context found in the current thread.
        at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
        at org.lwjgl.opengl.GL11.glClear(GL11.java:585)
        at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glClear(LwjglGL20.java:151)
        at com.nilunder.bdx.Bdx.main(Bdx.java:260)
        at com.solarlune.gearend.BdxApp.render(BdxApp.java:30)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:218)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:123)
```

Not sure quite how to go about this - I'm guessing it's because we're continuing rendering even though the context hasn't been re-established yet. I guess the right way to do it is to perform the fullscreen call at the end of the frame? That way, it won't be in the middle of changing the display when the graphics are drawing.

**Comment by aliasaila** [comment]
There are a couple of issues with full screen toggling mentioned here: [Finish LWJGL 3 backend and request for testing](https://github.com/libgdx/libgdx/issues/3673)

Maybe the latest libgdx build fixes it?

**Comment by GoranM** [comment]
> I'm guessing it's because we're continuing rendering even though the context hasn't been re-established yet.

You'll have to run some tests to make sure.

**Comment by SolarLune** [comment]
Hm, my tests didn't work - I got a different error about the display not being created.

[I saw that back in January, LibGDX got some changes to the fullscreen and window API](http://www.gamefromscratch.com/post/2016/01/05/LibGDX-18-Released.aspx) - maybe that solved it. Could we get BDX updated to the latest LibGDX version?

**Comment by GoranM** [comment]
A PR for issue #523 would include a LibGDX update, and I think @Fr0sk is working on that.

In the meantime, you could try to figure out when this actually stopped working (after which commit), because it did function properly at some point in time.

I think [`git bisect`](https://git-scm.com/docs/git-bisect) could probably help you with that.

**Comment by SolarLune** [comment]
Hey, updating the LibGDX version did indeed fix this bug, so I'll close this now. Thanks!
