### ISSUE TITLE
Screenshader.active and DepthExtract move

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#594]
I'd like to propose an active field for ScreenShaders, allowing you to turn them on and off easily without removing them from their stack and render order, and also move the depthExtract shaders to the 3D folder (they were never supposed to be in the 2D folder; I messed that up).

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
OK, PR submitted.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks!
