### ISSUE TITLE
Suggestion: SpriteAnim.isPlaying(String animName)

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#599]
Hey, there. 

An `isPlaying(String animName)` function to let you know if a SpriteAnim is playing a specified animation would be nice. If nothing's provided, it would just be if it's playing anything at all (active != null).

**Comment by GoranM** [comment]
Since active is a public field, couldn't you just test that?:

```java
if (sa.active.name == animName){
    ...
}

**Comment by SolarLune** [comment]
Yeah, but active might be null, so I'd have to do:

```java
if (sa.active != null && sa.active.name.equals("Whatever"))
```

Which is a tad wordy.

**Comment by GoranM** [comment]
As long as you initialize the SpriteAnim component to a specific animation (which is what you would typically want to do anyway), active should never be null, so I'm not sure that you'll ever actually need to make that check in practice.

**Comment by SolarLune** [comment]
Hm, I suppose so. Issue closed.
