### ISSUE TITLE
Suggestion: Text optimization / remove profiler background and use customized bitmap font

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#600]
It's probably better to remove the background and use a custom bitmap font (white with black shadow and border). Doubling the font resolution would also improve readability. See picture beneath.

To achieve this, on export, the profiler should copy the ```__FNT_BDXFontMono.png``` and ```BDXFontMono.fntx``` from the ```gen``` folder. I would also suggest to remove those when BDX ends.

For pixel perfect results we'd have to optimize the way text objects are created. So in a way this commit would be killing two birds with one stone.

![__fnt_bdxfontmono](https://cloud.githubusercontent.com/assets/10002909/13974549/0c415fc8-f0ad-11e5-9c2f-24f91f8c38f3.png)

**Comment by GoranM** [comment]
I don't know. I think the profiler looks fine with the existing setup.

Assuming that this suggested change would make it look even better, I'm not sure if the overall benefit would be worth the additional complexity.

**Comment by rafcolson** [comment]
Okay. Maybe I'll come back to this after text objects are optimized.
