### ISSUE TITLE
Suggestion: GameObject.lifeTime

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#601]
Hey, there. 

I'm doing some basic stuff with limited life particle effects, and it'd mean one less class I need to create if each GameObject had a lifeTime property that indicated how long the GameObject was going to love for when it was created.

**Comment by GoranM** [comment]
One of the core benefits of a Component oriented design is in being able to avoid stuffing GameObject with virtually every feature that anyone could ever find convenient for their specific purposes.

Unless there's some special reason as to why you can't, I think it would be best if you just write a component:

```java
GameObject g = scene.add("Whatever");
g.components.add(new TimedEnd(g, seconds));
```

**Comment by SolarLune** [comment]
Ah, that does make a lot of sense! Thanks. I'll close this now.
