### ISSUE TITLE
Suggestion: Camera.zoom() Relative to View Size

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#603]
Hey, there. 

I think rather than returning a somewhat obtuse number, the Camera.zoom() functions could set and return the value relative to the width of the camera. Basically, rather than zoom() returning, say, 0.0374999998, it could return 30, for 30 Blender Units across (like how it works in Blender).

**Comment by GoranM** [comment]
Sounds good.

**Comment by SolarLune** [comment]
OK. PR submitted.

**Comment by SolarLune** [comment]
PR merged, so I'll close this now. Thanks!
