### ISSUE TITLE
Suggestion: Better explanation of the API color

### ISSUE THREAD

**Issue by brennced** [GoranM/bdx#604]
Hi! I don't quite understand how to create colors in BDX.

**Comment by rafcolson** [comment]
Hi. It says:
>The Color class is an extension of the LibGDX [Color](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/Color.html) class, but with some additional functionality and convenience methods.

So you should look at the constructor of the LibGDX [Color](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/Color.html) class.

Example:
```java
import com.nilunder.bdx.utils.Color;

Color color = new Color(1, 1, 1, 1);
color = new Color(Color.GRAY);
...
```

**Comment by brennced** [comment]
Also, would it be possible to mention what you have to import in all the API references? This would help a lot!

**Comment by rafcolson** [comment]
I agree that this would be convenient. Especially when a hyperlink to the API of a specific class is opened.

**Comment by GoranM** [comment]
Yeah, I guess that would be fine.

**Comment by rafcolson** [comment]
Before I start updating the API, is this okay visually? For example:

`com.nilunder.bdx.GameObject`

**Comment by GoranM** [comment]
Well, you just need the package, not the fully qualified class name, so I think it would be fine to just have a link at the beginning of the page:

[com.nilunder.bdx](https://github.com/GoranM/bdx/wiki/API#comnilunderbdx)

**Comment by rafcolson** [comment]
Okay.

**Comment by rafcolson** [comment]
@GoranM API updated. @brennced if this solves the issue, you can close it.

**Comment by SolarLune** [comment]
@brennced We've added the package name to all of the current pages, I believe, and we're adding it to new pages as well. Can you close this?

**Comment by SolarLune** [comment]
Hey, I dunno if @brennced is still around, but I think this was solved. Is it OK to close it, @GoranM?

**Comment by GoranM** [comment]
Yes, we can probably close this.

**Comment by SolarLune** [comment]
Thanks, @brennced!
