### ISSUE TITLE
Suggestion: GameObject.updateJoinedMesh(boolean)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#605]
A typical use case is to end all objects in ```GameObject.joinedMeshObjects``` once ``` GameObject.updateJoinedMesh()``` is called. A house, for example, could have dozens of individual parts. Those parts could then be recycled to build other houses in Blender. Once added to the scene and joined, it doesn't make sense to keep all the individual parts.

So I'd like to add one extra method to automatically end all joined mesh objects after the joined mesh is updated. This saves the trouble doing this each time:
```java
for (GameObject jmo : g.joinedMeshObjects){
	jmo.end();
}
g.joinedMeshObjects.clear();
```
The commit also includes a fix. @SolarLune It seems that there was no use for a ```updateMaterials()``` call in ```updateJoinedMesh()```.

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks!
