### ISSUE TITLE
Suggestion: hitObjects

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#606]
Hey, there. A `hitObjects` list of objects that the object just came into contact with would be nice to have. The alternative is deriving it yourself using the touchingObjects and touchingObjectsLast lists.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
Hey, so I made this a function, as maintaining another list is unnecessary. Cool?

**Comment by SolarLune** [comment]
This was merged, so I'll close it now. Thanks!
