### ISSUE TITLE
Suggestion: UV Scrolling Component

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#608]
Hey, there. A component to allow you to scroll the UV values of the mesh, or set the values (relatively or absolute) would be really helpful.

**Comment by GoranM** [comment]
At this point, I think we should have a class that extends libgdx Model, with some basic methods to manipulate vertex properties like UV coordinates.

For components in general: It's probably best to wait until the codebase is a bit more mature/stable before we start adding them to BDX.

**Comment by SolarLune** [comment]
Hmm, I see. I guess I'll make an issue for it, because I'm not 100% on how we should go about it.

As a side-note, I agree about the model class, but I don't really see the point of waiting to add components. As far as you told me earlier, the point of components is to add things that aren't "completely necessary", like sprite animation, into the engine. 

I think if you want to hold off on adding features outright and just focus on bugfixes and usability changes for now, that's one way to go. But I wouldn't stop adding components specifically (it's not like there's a ton of components that we're suggesting, anyway).

Anyway, what kind of components did you have in mind?

**Comment by GoranM** [comment]
> As far as you told me earlier, the point of components is to add things that aren't "completely necessary", like sprite animation, into the engine.

The components that ship with BDX would need to have fairly general utility.

It would have to be something that's actually worth the cost of adding it in, because once it's part of the engine, we're basically responsible for maintaining that code.

> Anyway, what kind of components did you have in mind?

I didn't suggest any.

If we ever get to a point where we have some good candidates (components with strong general utility), and the engine is in a more stable state, I think that would be the time to think about it.

**Comment by SolarLune** [comment]
> I didn't suggest any.

Hah, that's why I asked!

> If we ever get to a point where we have some good candidates (components with strong general utility), and the engine is in a more stable state, I think that would be the time to think about it.

Hmm, well, OK. I thought UV animation is general purpose enough that it'd be useful in a lot of different game types. We'll see how it goes with the Model class, anyway.

OK, I'll close this now.
