### ISSUE TITLE
BDX Project Creation Fails

### ISSUE THREAD

**Issue by TX256** [GoranM/bdx#616]
I've been wanting to start using BDX for around a year. I've tested several versions, and not a single one has successfully created the project. I now decided to create a Github account to hopefully resolve what's wrong...

Blender version: 2.77
BDX version: 0.2.4

I've tried to create a new project twice today. On the first try BDX actually managed to create the project directory, but created corrupted Java files - there was a missing } - for example... I don't have logs for that anymore, unfortunately.

But now I tried again, and this time it doesn't even create the project directory, but fails before that, here's the console log:

```
Read new prefs: C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.77\python
Executing 'C:\Users\Me\Documents\Blender Projects\Test/gradlew.bat clean'
Configuration on demand is an incubating feature.
:android:clean UP-TO-DATE
:core:clean UP-TO-DATE
:desktop:clean UP-TO-DATE
:html:clean UP-TO-DATE
:ios:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 27.95 secs
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 239, in execute
    self.set_android_sdk_version()
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 123, in set_android_sdk_version
    build_tools_version = get_version_dir_name(build_tools_dir, build_tools_sort_key, "20.0.0")
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 105, in get_version_dir_name
    return sorted(os.listdir(path), key=sort_key)[-1]
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 115, in build_tools_sort_key
    return int(h) * 100 + int(t) * 10 + int(o)
ValueError: invalid literal for int() with base 10: 'build-tools-22'

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by SolarLune** [comment]
Hey, there! This is a bit strange; the step to set the android SDK version comes after the project directory should be created... 

I don't know much about Android as I personally haven't messed around with it too much, but everything works fine for me on testing Android project creation, so let's troubleshoot your configuration.

_______

1) What desktop OS are you using?

2) Are you trying to create a project using the Android SDK? If so, does it work otherwise (without the SDK)?

3) Do you have the necessary Android build tools installed on your computer?

4) When you create your project from Blender, ensure that you direct BDX to the root Android SDK folder itself. On my computer, it's `C:/Program Files (x86)/Android/android-sdk`. BDX uses the folders inside of the build-tools folder (e.g. `23.0.1`) to pass info along to gradle.

4.5) Did you rename any folders inside of the build-tools folder? Inside of the Android SDK folder, the build tools folder should be called simply `build-tools`. Each folder inside of there should be named using just numbers, with the numbers indicating the version that the build tools are for.

Here's a quick example showing how the Android SDK folder I have is laid out:

```
                                          V Your Android SDK Folder
                                          |
C:/ Program Files (x86) / Android / android-sdk / build-tools / 23.0.1
                                                              / 23.0.2
```

**Comment by TX256** [comment]
1) Windows 10 (Latest Insider Preview)
2) I am trying to create a project with the Android SDK.. I assumed it was actually necessary. However, I just tried without it, and I'm getting the same (new) errors as with it (see below)
3) Yes, most certainly. I have updated everything in the SDK manager.
4) I did use the android-sdk directory.
5) I didn't rename anything myself, BUT for some reason I actually did have "build-tools-22.0.1" in the folder, in addition to the number folders. I renamed it and the old error is gone, however a new set of errors appeared:

```
Read new prefs: C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.77\python
Executing 'C:\Users\Me\Documents\Blender Projects\Test/gradlew.bat clean'
Configuration on demand is an incubating feature.
:android:clean UP-TO-DATE
:core:clean UP-TO-DATE
:desktop:clean UP-TO-DATE
:html:clean UP-TO-DATE
:ios:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 6.998 secs
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 236, in execute
    self.create_android_assets_bdx()
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 51, in create_android_assets_bdx
    os.mkdir(bdx)
FileExistsError: [WinError 183] Tiedostoa ei voi luoda. Tiedosto on jo olemassa: 'C:\\Users\\Me\\Documents\\Blender Projects\\Test\\android\\assets\\bdx'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ui.py", line 41, in draw
    r().label(text="In BDX project: " + ut.project_name())
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\utils.py", line 26, in project_name
    _, name, *_ = line.split("'")
ValueError: not enough values to unpack (expected at least 2, got 1)

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ui.py", line 41, in draw
    r().label(text="In BDX project: " + ut.project_name())
  File "C:\Users\Me\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\utils.py", line 26, in project_name
    _, name, *_ = line.split("'")
ValueError: not enough values to unpack (expected at least 2, got 1)

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by SolarLune** [comment]
What was the project name you used when you tried to create a project?

**Comment by TX256** [comment]
The name was simply "Test"... but now I feel stupid :) I had actually TWO BlenderProjects folders, another in My Documents, and another in C:\Users\Me\. And of course I was looking at the wrong folder in Explorer all the time (which was empty at the time). The project building works now, and Sacky is there! So the only problem was the "build-tools-22.0.1". Thank you!

**Comment by SolarLune** [comment]
OK, great! Glad it all worked out. 

If everything works OK, feel free to close this issue.

**Comment by rafcolson** [comment]
For some unknown reason android sdk build tools sometimes comes with unexpected names. This is the second time I hear about this problem. `ValueError: invalid literal for int() with base 10: 'build-tools-22'` could be avoided by removing `"build-tools-"` if present first. Hopefully there won't be other variants to the name.

@ TX256 I'm sorry you had to go through all this trouble. We had this issue before but then for some reason the sdk manager didn't distribute under that (incorrect) name anymore. I assumed it had to be a one-time glitch on the part of the distributor as the name only popped up for a couple of days..
