### ISSUE TITLE
Suggestion: SpriteAnim.justChanged()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#618]
Hey, there. 

I think it might be a good idea to add a justChanged() function to SpriteAnim, allowing you to check to see when a sprite's frame just got finished changing.

For clarity, I think this'd be useful because I'm doing things that rely on using animation for timing (i.e. on the 6th frame of a shooting animation, spawn a bullet).

**Comment by GoranM** [comment]
frameChanged() seems like a more fitting name.

**Comment by SolarLune** [comment]
That's fine. PR submitted.

**Comment by SolarLune** [comment]
PR merged, so I'll close this. Thanks.
