### ISSUE TITLE
Need some help with commit: import properties

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#62]
Hi, Goran or SolarLune.

I'm trying to write a commit for exporting and importing properties to GameObject. I'm exporting like this in exporter.py:
```python
	name_object[obj.name] = {
		"properties": {n: p.value for n, p in obj.game.properties.items()},
		...
	}
```
But I'm not sure how to import a Python dictionary. Does it have to be converted? I noticed that "physics" is a library too and isn't converted, so I guess this should work in Scene.java?
```java
	for (JsonValue gobj: json.get("objects")){
		...
		GameObject g = instantiator.newObject(gobj);
		...
		g.properties = gobj._json.get("properties");
	}
```
Of course GameObject also has a new HashMap:
```java
import java.util.HashMap;
...
public class GameObject implements Named{
	public HashMap<String, JsonValue> properties;
	...
```
Any help is appreciated. If it's not clear enough you could always check the commits in my repository.

Edit:

I think methods addProperty() and removeProperty() would be unnecessary because I think HashMap is pretty clear:
```Java
properties.put(k, v); // for adding a property
properties.remove(k); // for removing a property
```
Other useful methods are:
```Java
properties.containsKey(k); // for checking if a property exists
properties.containsValue(k); // for checking if a value exists
properties.get(k); // for getting the value of a key
properties.keySet() // for getting a set of the names of the properties
properties.values() // for getting a collection of the values of the properties
for (Set.Entry<String, JsonValue> e: properties.entrySet()) {
	String k = e.getKey();
	JsonValue v = e.getValue();
} // for looping through the properties
```

**Comment by SolarLune** [comment]
Sounds pretty good so far. I haven't looked into the exporter too much; Goran might be able to help you out if you're stuck, but it sounds like you've got it pretty solid already. Having automatic property export will be nice, indeed.

**Comment by rafcolson** [comment]
It won't work. I tried a lot of things, but I can't seem to export BDX because I can't manage to convert the dictionary to a HashMap.

**Comment by GoranM** [comment]
[JsonValue](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/utils/JsonValue.html) is not a HashMap, so you can't simply set a HashMap reference equal to a JsonValue.

You could do this:

```java
// on GameObject:
public JsonValue props;

// in Scene.init:
gobj.props = json.get("properties");

// then you can get:
int ammo = gobj.props.get("ammo").asInt();
```

However, that only sets properties for initial templates, from which all other objects are spawned, so you would also need to write code in cloneNoChildren, to make a complete copy of the those properties for newly spawned objects.

You would also need to modify cloneInstance, to incorporate properties from the instance (blender link group), and have them override those on the base object.

**Comment by rafcolson** [comment]
I ll give it a try.

**Comment by rafcolson** [comment]
Okay, everything is working. You can check it out on my GitHub: https://github.com/rafcolson/bdx/releases

@GoranM : Let me know if I can pull a request.

**Comment by GoranM** [comment]
As stated on the [contributing page](https://github.com/GoranM/bdx/wiki/Contributing): the issue thread is a place to discuss what and/or why; the PR thread is a place to discuss how, and to refine the solution.

So, if you're ready, then go ahead and make the PR; I'll review the code there.

> Should we add the possibility to add properties in game?

I don't think it would be a good idea to rely on properties for anything more than simply providing object-specific data from blender.

If you need something that can be set, make a regular variable, and use that.

> There are cases where adding properties could be useful. For example, when spawning instances, you could add id's to them, to get track of them later on. There is no other way to do this unless instances would be extended objects.

I don't really understand what you mean.

You can just store the references themselves, in any regular data structure: The reference itself is unique, so id's would be completely redundant.

**Comment by rafcolson** [comment]
> So, if you're ready, then go ahead and make the PR; I'll review the code there.

Maybe, let's first talk a bit further about the application itself, of what and why properties.

>I don't think it would be a good idea to rely on properties for anything more than simply providing object-specific data from blender.
>
>If you need something that can be set, make a regular variable, and use that.

I see your point. I have to examine further if there are any cases where adding properties would be needed.

But what about checking if an object has a specific property. How would you do this then? Because, as far as I know this won't work with JsonValue:
```java
if (g.props.containsKey("ammo"))
```

**Comment by GoranM** [comment]
If I recall correctly, JsonValue.get will return null if the given name is not found.

So I think this should work:

```java
if (g.props.get("ammo") != null);
```

**Comment by rafcolson** [comment]
That's correct. I'm sorry I didn't check this myself first.

I thought about it a bit further. It's hard to imagine cases where a HashMap would be more practical, so I'm closing this. If I can in the future, I'll make a new suggestion.

Thanks for all the answers. I'll pull the request right now.
