### ISSUE TITLE
Bug: Meshes Can't Be Colored After Replacement

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#620]
Hey, there. 

So if you replace a GameObject's modelInstance, you can't modify the color of the new mesh's materials. Guess we need to override the materials in the GameObject's materials list with the ones from the new modelInstance, at that point.

**Comment by rafcolson** [comment]
I can have a look this weekend.

**Comment by rafcolson** [comment]
That should do it.

**Comment by SolarLune** [comment]
Looks like you might have done what I did earlier, which is try to set the materials on the mesh according to what's in the GameObject. However, shouldn't it be the opposite? That when you replace a mesh, you also replace the materials? I think that would be expected.

Secondarily, this should probably be the case because the replaced mesh might not have the same number of mesh slots. So, just assigning the model instance's materials to be the equivalently numbered material in the GameObjects.materials list might cause an OutOfBounds error (a mesh has 5 parts, but the GameObject only has two materials).

**Comment by rafcolson** [comment]
I'll leave it up to you, SolarLune, as I don't have a clue how to copy materials through the modelInstance. I tried this, but that won't work of course:
```java
			materials.clear();
			for (int i = 0; i < modelInstance.nodes.get(0).parts.size; i++){
				materials.add(i, (Material)modelInstance.nodes.get(0).parts.get(i).material);
			}

```
I'll close the PR.

**Comment by SolarLune** [comment]
Casting the materials like that would be ideal, and it seems like it should work, but I guess downcasting can be an issue sometimes. I guess an alternative would be to use the scene's materials Hashmap to grab a material with the same ID, but the materials present on the swapped model could be unique. 

Anyway, I'll have to see about it, I suppose.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
This PR was merged, so I'll close this now. Thanks.
