### ISSUE TITLE
GameObject.props shared between instances

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#622]
Hey. 

So it seems like changes to a GameObject's props in-game are shared between instances of GameObjects. Each GameObject should have its own HashMap, of course.

**Comment by SolarLune** [comment]
I believe that should do it. PR submitted.

**Comment by rafcolson** [comment]
I'm all for it of course but as I recall @GoranM didn't think it would be
beneficial. Maybe it's good to give an example of the benefits.

**Comment by SolarLune** [comment]
That's weird; if it's left the way it is, then you can't use props to identify instances of a common class. Like, I have the player object and an enemy both shooting bullets, but I use props to distinguish which they are (because they're fundamentally the same; it's just what they can damage that changes).

**Comment by rafcolson** [comment]
Exactly.

**Comment by rafcolson** [comment]
Maybe lines 534-535 could also be:
```java
g.props = new HashMap<String, JsonValue>(gobj.props);
```

**Comment by SolarLune** [comment]
I think the goal with that section is to write the instance's props over the GameObject's established ones. Is there anything wrong with the proposed PR, or what behavior would your addition change?

**Comment by rafcolson** [comment]
Oh right. Forgot about that. Sorry. Of course we don't want to lose the group instance props!

**Comment by GoranM** [comment]
The api docs state:

> Unless otherwise labeled, all fields should be considered read-only.

So, you're not supposed to change props at runtime; The system assumes that you're just going to use them to set your own local data, which you can then modify however you wish.

**Comment by SolarLune** [comment]
Is there a reason why the system can't be adjusted to have props be unique to each instance?

**Comment by rafcolson** [comment]
>The system assumes that you're just going to use them to set your own local data, which you can then modify however you wish.

I see you point but it's not really a matter of modifying data. I think customizable props can be useful in two cases:
- With adding instances of a GameObject which has no use for a class except for one or more fields to differentiate between those instances. Example: Coins could look the same but have different values. No class needed for every coin as a component could do the animation. No class needed for any other reason too, as all the coin does is do the animation and return its value (for the bank).

- With adding instances of a GameObject which uses a class, but can't be identified through a field so easily. For example: Hero wanders and encounters one type of enemy after the other. In this case it could be argued that a 'common' field as an identifier would do. But this would also require every type of enemy to have a class, just for the sake of providing a field. But not every enemy would require a class. A component for the animation, and when Hero hits this type of enemy, he gets hurt, but can't destroy it. For example a cactus.

I think these are the best practical examples I can think of.

**Comment by GoranM** [comment]
> Is there a reason why the system can't be adjusted to have props be unique to each instance?

Not technically, but it seemed sensible not to do that, so that we could avoid potentially excessive allocation and copying.

@rafcolson 

You have a different type either way, it's just the difference between making that explicit via the class, or encoding it with a bunch of tightly coupled properties and components.

That said, I can see how it could be convenient in certain cases.

**Comment by rafcolson** [comment]
>You have a different type either way, it's just the difference between making that explicit via the class, or encoding it with a bunch of tightly coupled properties and components.

With "one type of enemy after the other" I meant different types.

Anyway, I agree that having unique props for every instance opens the door for potentially misuse of props. But if anyone read the [General Overview](https://github.com/GoranM/bdx/wiki/General-Overview#properties) it should be clear that props are not intended to be used as fields would be used in a GameObject class.

**Comment by SolarLune** [comment]
PR submitted and updated.

**Comment by SolarLune** [comment]
PR merged, so I'll close this. Thanks.
