### ISSUE TITLE
Suggestion: export scene resolution

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#627]
For example, the Profiler scene's resolution determines the scaling of the display object so that it doesn't size or stretch. For perfect pixel results also the camera's width and height have to be adjusted according to the `Bdx.display.size()` sometimes. And so it would be nice if the resolution is exported.

I would suggest a field on Scene: `bdx["resolution"] -> Scene.resolution`

Edit:

As far as I know, in the BGE the overlay scene's is stretched so the width of the overlay scene's camera matches the width of the background scene's camera width. In BDX however, there is no stretching: the overlay scene's resolution will be the same as the background scene's resolution. In short, the overlay scene's resolution is useless right now.

I think it would make more sense to set the camera's viewport width and height to the resolution of the scene in which the camera exists, instead of the first scene.

**Comment by SolarLune** [comment]
If I understand you correctly, I'm not sure if you need to export the resolution for each scene. One option would be to hard code the resolution into the Profiler class. Another would be to just hard code the aspect ratio (it's 1 because the profiler scene's a square), and then just use that in combination with the display size, I think.

**Comment by rafcolson** [comment]
>If I understand you correctly, I'm not sure if you need to export the resolution for each scene. One option would be to hard code the resolution into the Profiler class.

With the Profiler class I've done that already with a final float `SCREEN_SIZE=512`. But this request is not just for the Profiler. For example, with a Virtual Gamepad (which I'm currently working on) in most cases we don't want the buttons and axis change in size, much like a real gamepad. And so to keep that fixed size you should know the resolution. But I guess you're right. I could probably have the screen size of the Gamepad scene hard-coded also.
