### ISSUE TITLE
Subimage Setting Mechanism for SpriteAnim Component

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#63]
Hey, there. So I think it'd be nice to have an ability to set the subimage (frame) of an animation on demand, so you could, for example, stop a walking animation to show a character standing.

**Comment by GoranM** [comment]
Wouldn't simply switching from walking to standing do that?

I mean: If you're playing a walking animation, and then you play standing, walking stops, and the character is shown standing, right?

**Comment by SolarLune** [comment]
Yeah, but that'd require a standing animation, of course. This way, you wouldn't have to have additional animations if you don't need them.

There are other situations as well in which you'd want to set a frame of an animation directly over playing an animation.

**Comment by GoranM** [comment]
> Yeah, but that'd require a standing animation, of course. This way, you wouldn't have to have additional animations if you don't need them.

Technically, you "don't need" more than one animation: You could just cram the frames for all logical animations into a single sequence, but that wouldn't be better, clearly.

> There are other situations as well in which you'd want to set a frame of an animation directly over playing an animation.

That's true, so I think it would be valuable to add this in.

**Comment by SolarLune** [comment]
Hey, if you haven't started on this, I guess I can take a crack at it. Let me know and I'll assign myself.

**Comment by GoranM** [comment]
Oh, sorry - I assumed that you were working on it.

Sure, give it a go.

**Comment by SolarLune** [comment]
OK. PR done here: https://github.com/GoranM/bdx/pull/74
