### ISSUE TITLE
Suggestion: Vertex Groups Export

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#631]
Hey, there. Since we have mesh editing capability now, I think it'd be nice to also export the vertex group information from the Blender mesh. This way, we can easily identify and modify specific vertex sets (i.e. move just the surface of a water mesh up and down). 

I'm thinking that the groups could just be a simple HashMap with the name of the group as the keys and an ArrayList of vertex indices as the values.

**Comment by GoranM** [comment]
If you have a "surface of a water mesh", why the need to distinguish further? I mean, all the vertices in that mesh are "surface of a water" ... I guess I don't fully understand the use case you're trying to describe.

**Comment by kellpossible** [comment]
Vertex groups in blender seem to also include the concept of vertex weight too right? You're talking about only dealing with vertices being a binary in or out of the group?  I can see a feature like this being quite useful if it included the vertex weight. Would have to think of some solid use cases to justify the extra complexity though I guess, that wouldn't already be covered by using vertex colors to store the information...

**Comment by SolarLune** [comment]
> If you have a "surface of a water mesh", why the need to distinguish further? I mean, all the vertices in that mesh are "surface of a water" ... I guess I don't fully understand the use case you're trying to describe.

Imagine a cube of water. How would you distinguish the surface of the water? You could loop through and grab the vertex indices that have the highest Z value, but it'd be simpler to be able to define a "surface" group in Blender (especially if the water's not a simple cube, but is shaped to fit different containers).

Another use case would be spawning objects in an area if vertices are in a specific zone. For example, only spawning treasure chests, NPCs, pathfinding nodes, or whatever on surfaces that are a part of the "ground" group, for a randomly generated rogue-like.

Basically, anywhere you want to identify a part of a mesh, vertex groups would be useful.

> Vertex groups in blender seem to also include the concept of vertex weight too right? You're talking about only dealing with vertices being a binary in or out of the group? I can see a feature like this being quite useful if it included the vertex weight. Would have to think of some solid use cases to justify the extra complexity though I guess, that wouldn't already be covered by using vertex colors to store the information...

Yeah, vertex groups also contain the weight value. I was just talking about defining groups for vertices in a binary set-up, where they're in a group or out of it. I'm not sure how vertex weights would be especially useful apart from armature animation, though. I mean, I could imagine some random generation taking advantage of it, but yeah, I think vertex colors would give you a more visual approach to this that would serve the purpose better.

**Comment by GoranM** [comment]
> Imagine a cube of water. How would you distinguish the surface of the water?

By a specific material: You can access vertex data by material slot.

**Comment by SolarLune** [comment]
That would only work if the surface of the water has a different material than the rest of the mesh (which it may or may not have, if it doesn't have a texture or the textures are on the same image file). 

Even if it did, all of the vertices wouldn't move correctly, as only the vertices that are a part of the surface material would be "grabbable" using the surface material. The other vertices that share position, but have a different material wouldn't.

And what about the other use cases?

**Comment by GoranM** [comment]
Wouldn't the surface of the water typically have a different material? It sounds like a lot of use cases break down into something that should logically be a different mesh, or at least a different material.

> Even if it did, all of the vertices wouldn't move correctly, as only the vertices that are a part of the surface material would be "grabbable" using the surface material. The other vertices that share position, but have a different material wouldn't.

But isn't the goal to just move the vertices that represent the surface? I mean, if you have a lake, surrounded by land, you don't want to move the land vertices.

> And what about the other use cases?

Well, I think what I said covers those, but I would add:

It seems cleaner to just have a completely separate mesh, and use that to designate nav points, walkable terrain, and other things that have logic related utility.

**Comment by SolarLune** [comment]
Hm, well, OK. I suppose between material slots and different meshes, it should be possible to identify groups of vertices as necessary and work with them. Issue closed.
