### ISSUE TITLE
Suggestion: Render-To-Texture

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#635]
Hey, there. I think I'm going to require render-to-texture capabilities to create a pause screen (just blurring the game view), so I was thinking I'd implement it. The general idea is two-fold.

1) Make easy functions to get and set textures available on a Material. An additional function to load up a texture from a file and set it on a Material would be nice to have, as well.

2) Add the ability to turn on render-to-texture for a camera. When you don't need it on, it wouldn't render to a framebuffer.

**Comment by GoranM** [comment]
It sounds like you could just use a 2d shader ... but, if you really want/need RTT, and you want to implement it, feel free.

**Comment by SolarLune** [comment]
Ah, I'd forgotten about that possibility. I don't actually need RTT, just something to blur the game scene, basically, so that would work fine. Thanks for the tip!

I'll leave this open for now, though, and work on it at some point soon (I think).

**Comment by SolarLune** [comment]
PR submitted. Should be good to go, I think. Let me know how you feel about the specifics.

**Comment by SolarLune** [comment]
Well, this was merged, so I'll update the wiki and close this now. Thanks!
