### ISSUE TITLE
Android-SDK stops BDX project creation in blender

### ISSUE THREAD

**Issue by JBird62** [GoranM/bdx#639]
HI!
I am using blender 2.77 along with bdx 0.2.3
When I create a project, Everything works unless I point to my "android-sdk" directory. I get the following error and blender stays with my start-up file.

BUILD SUCCESSFUL

Total time: 11.91 secs
Traceback (most recent call last):
  File "/home/john/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 239, in execute
    self.set_android_sdk_version()
  File "/home/john/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 123, in set_android_sdk_version
    build_tools_version = get_version_dir_name(build_tools_dir, build_tools_sort_key, "20.0.0")
  File "/home/john/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 105, in get_version_dir_name
    return sorted(os.listdir(path), key=sort_key)[-1]
  File "/home/john/.config/blender/2.77/scripts/addons/bdx/ops/createproj.py", line 115, in build_tools_sort_key
    return int(h) * 100 + int(t) * 10 + int(o)  
ValueError: invalid literal for int() with base 10: '0-preview'

location: <unknown location>:-1

location: <unknown location>:-1

So, I took a look at createproj.py to see if I could find anything that would throw this error, and with searching other issues, I came to no conclusion on what it could be. I came across a thread from last year where Goran stated

"It seems that the android sdk changed a bit, and that the way in which we parse the build tools version is no longer correct - instead of a number that we can feed to int, we get the "build-tools-21" string, and that raises an exception, which in turn prevents the project creation process from properly finishing."

I did just update to the latest android sdk. Could this be the issue?
Is there an alteration I can make to the .py file?

Thank you all in advance!

P.S. 
I am not using 0.2.4 version because I could not get it to deploy. I just rolled back one version. Thanks again!

**Comment by GoranM** [comment]
> I did just update to the latest android sdk. Could this be the issue?

Possibly. Make sure that you actually downloaded the build tools with you SDK, and not just the API libraries.

> Is there an alteration I can make to the .py file?

Well, assuming this is a bug, it would be best to fix it properly, but you could just edit the build.gradle file directly, and set the correct build tools version for android.

@rafcolson had some experience with this in the past, so maybe he could help.

**Comment by JBird62** [comment]
OK! Thank you @GoranM .
  I have all of the required SDK directories and files listed in the scripts and build files, I also made sure there were no more updates for the SDK, I am 99% sure I updated and have the SDK and not just the API. Thank you for the reference. I am beginning to learn to write my own build scripts with gradle. I'll have a look at rafcolson's page. Thank you!

Also, I have a lot of respect for what you've done with this. I have used netbeans, eclipse, JME3.1, android studios, along with libgdx, env3d, bluej, and what you've done is my favorite. I enjoyed using BDX over all the others, so thank you!

**Comment by rafcolson** [comment]
I'll have a look tomorrow.

**Comment by JBird62** [comment]
Thank you! @rafcolson

**Comment by rafcolson** [comment]
I got a fix, so here it is.

**Comment by rafcolson** [comment]
PR merged.

@JBird62 Does this solve the issue?

**Comment by JBird62** [comment]
@rafcolson Thank you for this! so blender now has issues when I changed the code. The BDX properties section disappeared when I changed the code. I'm going to check to see which part.

**Comment by JBird62** [comment]
@rafcolson So I am going to restart my computer, I'll be away for a few hours. when I come back, I'll attempt this again after the restart. I'll write back soon. Thank you for the help!

**Comment by JBird62** [comment]
Ok, so after an update and restart, I still don't have the BDX options anymore. Is there anything else I should do?

**Comment by rafcolson** [comment]
Strange, it should work. There's probably something wrong with your build. Try my build of current master: [bdx.zip](https://www.dropbox.com/s/gahqqcq5r7700ra/bdx.zip?dl=0).

**Comment by SolarLune** [comment]
What does the console say when you load up Blender?

**Comment by JBird62** [comment]
@SolarLune  This is what I get when I begin blender from the linux terminal.

connect failed: No such file or directory
Read new prefs: /home/john/.config/blender/2.77/config/userpref.blend
Loading MakeWalk v 0.943
MakeWalk loaded
Loading maketarget v 1.32
MakeTarget loaded
Loading makeclothes v 0.949
MakeClothes loaded
addon not found: 'bone_selection_sets'
WARNING: "io_export_rogremesh" is missing
Rpython module is not cached, you must exit Blender to compile the module:
cd io_export_rogremesh; python rogremesh.py
Starting blender2ogre 0.5.9
[WARNING]: Invalid my-shaders path
Traceback (most recent call last):
  File "/usr/share/blender/2.77/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/home/john/.config/blender/2.77/scripts/addons/bdx/__init__.py", line 2, in <module>
    from . import (
  File "/home/john/.config/blender/2.77/scripts/addons/bdx/exporter.py", line 10, in <module>
    import numpy
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python3/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python3/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python3/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

What do you think?

@rafcolson 

It seems I may have a path, python, add-ons, and configuration issue. I used your build, and got the same thing. I'm starting to think it's a python issue, and does not reflect with your script. Thank you for the files and help. Would you agree it's a python issue on my computer?

**Comment by aliasaila** [comment]
Maybe the same issue as https://github.com/GoranM/bdx/issues/583. See the bit about setting PYTHONPATH.

**Comment by JBird62** [comment]
@aliasaila 
Thank you!
I set the PYTHONPATH like you said, but I still get the errors. But, I was messing with the path changing yesterday and couldn't get much info on other sites. I was able to set the path to the python 3.5. So thank you for that!

**Comment by SolarLune** [comment]
Hey, what OS do you have, and where did you install Blender? 

On Linux, I would get numpy issues if I used a version of Blender from the packaging manager (Ubuntu Software Center) because it would use the system's Python distribution, which didn't have numpy support. It seems like numpy does exist in your log, so that might not be the problem, but just to be sure, perhaps you could try the Blender version from the homepage?

**Comment by JBird62** [comment]
@SolarLune 

Yeah actually I'm using ubuntu 14.04. I installed blender from a zip file on the blender homepage. I try to avoid using the software center as much as possible because of outdated software and issues like you just described. I haven't looked into numpy though. That's a good idea! Thanks!

**Comment by GoranM** [comment]
Your errors indicate that blender is trying to load python modules from the system libraries (/usr/lib/python3). Only the repo version of blender would try to do that; The binary from the official archive would try to load from where the archive was extracted.

This leads me to believe that you're still using the repo version.

How are you launching blender? If it's by typing `blender` in terminal, and the repo version of blender is higher up on your path than the official version, it's going to launch the repo version.

Run `which blender`, so you can see what binary you're actually launching.

**Comment by JBird62** [comment]
@GoranM 

OK, so I ran which blender, and it is running from user/bin/blender

I do launch blender from the terminal, user/bin/blender is the only path however. I will look at fixing the python path issue. I'm also going to a clean up of my OS and computer today. I will see if that helps. 

Thank you all for the help. I really appreciate the time!

**Comment by JBird62** [comment]
OK! So, I found something. I did not use the zip from the homepage of blender! I have a blender zip, but I don't remember where I got it from. I just downloaded the blender homepage file, I'm going to install it, and see what happens! Thank you!

**Comment by JBird62** [comment]
UPDATE!
So, I reinstalled blender 2.77 from the homepage. I still have issues but I'm going to configure the gradle scripts using android studios gradle.build as a reference bc I was able to deploy an app on my android using android studios. I will be spending time on some of the scripts too. I'll see if I can help by any means. 
Thank you!

**Comment by GoranM** [comment]
If you're using official blender, and the latest bdx master, you should be able to create a new bdx project that just works, and where you can deploy to android in the same way as you would for libgdx: https://github.com/libgdx/libgdx/wiki/Gradle-on-the-Commandline#running-the-android-project

**Comment by JBird62** [comment]
@GoranM 
  
   Thank you! I got a bdx game deployed on my android! I changed two variables in the build.gradle file in the android directory, ran through the terminal "gradle build" while in the directory, and I got three .apk files and the one signed "android-debug.apk" deployed on my phone with no issues. Thank you! I appreciate all your help!

**Comment by SolarLune** [comment]
What was the two variables you changed, by chance, @JBird62?

**Comment by JBird62** [comment]
@SolarLune 
I changed the compile SdkVersion to 23
and the buildToolsVersion to "23.0.2"
otherwise, I would get only an unsigned-release, which, without a playstore signature, my phone kept saying error parsing the package. When I changed those versions, I got the unsigned-release along with a debug. the debug worked perfect on my phone. I just changed the versions.

**Comment by SolarLune** [comment]
Hey, thanks for that info!
