### ISSUE TITLE
Question: coding conventions

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#642]
I was thinking to ask this for a while now. What coding conventions should we use? For example, I noticed @SolarLune often removes tabs for empty lines. I'm not sure if this is deliberate or if the IDE is responsible. I want to adjust if necessary.
```java
	private GameObject cloneNoChildren(GameObject gobj){
		GameObject g = instantiator.newObject(gobj.json);
// like this?
		g.json = gobj.json;
		// or like this?
		g.name = gobj.name;
		...
```
And what about space in front of brackets?
```java
	private void initGameObject(GameObject gobj){ // like this?
		if (!gobj.initialized) { // or like this?
			gobj.init();
			gobj.initialized = true;
		}
	}
```

**Comment by SolarLune** [comment]
I think comments should be at least on the same tab column as the lines before or after it (or at the end, on the same line), so they match up. And I personally add a space before the bracket to help improve readability, but that's just how I personally do things.

**Comment by rafcolson** [comment]
>I think comments should be at least on the same tab column as the lines before or after it (or at the end, on the same line)

And what about empty lines? (the comments where just to illustrate the existence of tabs)

**Comment by GoranM** [comment]
Unlike in Python, whitespace is not significant in Java, so as long as it's not something completely crazy, I think it's ok to have small inconsistencies, based on developer preference.

**Comment by rafcolson** [comment]
Okay, thanks guys. It's something I shouldn't be worried about then.
