### ISSUE TITLE
Dev: building problems after LibGdx update 1.7.3-SNAPSHOT

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#646]
Hey guys, I'm trying to check @SolarLune's [revert](https://github.com/GoranM/bdx/issues/518#issuecomment-215865914) but it seems, even after making a new fork of current master, that I can't build master. I ran `ant clean`. So I wonder if you might know what's going on.

**Comment by GoranM** [comment]
With an up to date master, create a new project *before* trying to build BDX - gradle needs to download the new libgdx dependencies first, so that the BDX build process can find them.

**Comment by rafcolson** [comment]
I'm trying this over and over again, but it doesn't work. Sounds like the same issue I was having before. Ironically I just started a fresh repository (deleted my fork and created a new one). That didn't work, so I downloaded and installed the latest official build instead and created a new project. But even after that I can't build current master. Did I do something irreparable or is there yet another way to update dependencies? If not, I'm afraid I'll have to request for drafting a new official release (again).

**Comment by GoranM** [comment]
When you say "but it doesn't work", what do you mean? Are you getting an error?

Using the latest official won't work, because that uses a previous version of libgdx, so creating a new project with that is not going to download the required dependencies for the latest libgdx version, which is used in latest master.

You need to create a new BDX project with the latest master. That should download the new dependencies, and then you can actually build BDX.

**Comment by SolarLune** [comment]
> If not, I'm afraid I'll have to request for drafting a new official release (again).

Which would be fine with me, as we've made quite a bit of progress with bugfixes. We could use another release.

**Comment by rafcolson** [comment]
I'll give it another try later this evening. Feel free to draft a new release. But I should try this issue for myself first as it will repeat with future LibGdx updates.

**Comment by rafcolson** [comment]
>You need to create a new BDX project with the latest master.

How can I create a new BDX project with the latest master?

So I forked the latest master. Then I cloned it to my desktop with GitHub. Then I would normally build bdx and zip it, and install it in Blender. But how can I produce the add-on otherwise?

**Comment by SolarLune** [comment]
You can't build the add-on until you download the prerequisites (the new LibGDX version, among other things, which happens automatically). Assuming you previously had the add-on symlinked up as directed [here](https://github.com/GoranM/bdx/wiki/Building-BDX#streamlining), then after grabbing the files from Github, you'll be able to create a new BDX project. When you try to run the project, it'll download the necessary files (as your new project will be asking for the latest LibGDX version), and then you'll be able to actually build BDX, as you'll have the prerequisites.

**Comment by rafcolson** [comment]
Thanks @GoranM and @SolarLune. I still have to figure out how to make a symlink and which symlink to make. But I could solve the issue by manually applying the changes of the [Update LibGDX to 1.9.2](https://github.com/GoranM/bdx/commit/c9166309fef09346494c74f5f42150a252427192) in the bdx add-on directory.
