### ISSUE TITLE
Suggestion: onCreate() / Init() change

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#648]
Hey, there. 

So basically, I'm running into a situation where I can't really initialize objects as I would like. The use case is that I have an enemy spawner creating an enemy object, and before I can position the enemy object where I want, BDX runs the enemy's "init" function. 

This is undesirable for my purposes. Would it be possible to add another function that runs one frame later? Maybe add an `onCreate()` function that runs when the object is instantiated like the `init()` function now, and change `init()` to run before `main()` on the first frame afterwards?

At least change it to have `init()` run later?

P.S. We could also alter the function names to be more consistent. For example:

- onCreate()  - Called once when object is created.
- onInit() - Called once on the next frame after the object is created.
- onUpdate() - Called on every frame the object is valid.
- onEnd() - Called once when end() is called on the object.

**Comment by GoranM** [comment]
I think it's a common expectation for the GameObject to be fully initialized as soon as you actually have a reference to it; Having a reference to an object with a bunch of null fields can be really awkward, and really confusing, especially for beginners.

People who need/want to initialize an object at some later time can create a different initialization function, and run that whenever they want.

**Comment by SolarLune** [comment]
> I think it's a common expectation for the GameObject to be fully initialized as soon as you actually have a reference to it; Having a reference to an object with a bunch of null fields can be really awkward, and really confusing, especially for beginners.

OK, so then the second function would be the way to go. That way you have one function that is triggered when an object is created, and one when the object has a chance to actually be initialized properly. I believe I've had this issue before with a similar situation, where I needed to, essentially, have my object's init() function run after I position it after creation. This second function would aid in this quite well, I think.

I appreciate trying to think of how beginners might approach things, but I think a small amount of documentation would be enough to inform them of the difference between `onCreate()` and `onInit()`.

> People who need/want to initialize an object at some later time can create a different initialization function, and run that whenever they want.

Eh, it's not really a "later time". It's one frame later, and would be run on just that one frame.

**Comment by GoranM** [comment]
> Eh, it's not really a "later time". It's one frame later, and would be run on just that one frame.

One frame later falls under "later time", relative to creation time ... The point I'm trying to make here is that initialization requirements can vary, so it seems more reasonable for users to write whatever support they need for that, than for us to write additional engine code to support one specific case.

For your case, it seems like you could just have the spawner call a custom initialization method on the object, after it's properly placed in the world.

**Comment by SolarLune** [comment]
> One frame later falls under "later time", relative to creation time ... The point I'm trying to make here is that initialization requirements can vary, so it seems more reasonable for users to write whatever support they need for that, than for us to write additional engine code to support one specific case.

But that's the thing; it's not "one specific case" - it's a pretty basic situation. If you have anything that checks an object's properties, position, rotation, whatever, at initialization, and you also want to change that property when the object is created, this will arise. 

And I dunno about initialization requirements varying that much; it seems like most people would be OK with the init() function as it is, and for the few who need it, the new function would step in to fill the void.

> For your case, it seems like you could just have the spawner call a custom initialization method on the object, after it's properly placed in the world.

Yeah, that's basically what I'm doing, and that's what I'm trying to avoid. 

I mean, if you want to avoid adding code, we don't even "need" an init() function at all, as people can just use a variable to check for the first frame an object is "alive" (like in the BGE). But it's awkward to do, so we support it at engine base-level.

**Comment by GoranM** [comment]
> But that's the thing; it's not "one specific case" - it's a pretty basic situation. If you have anything that checks an object's properties, position, rotation, whatever, at initialization, and you also want to change that property when the object is created, this will arise.

I'm not sure if that's generally common enough to justify explicit engine support. It may be common in a setup that uses properties (instead of the java type system) to differentiate between objects, and then follow different initialization branches, but that setup itself is fairly uncommon.

> if you want to avoid adding code, we don't even "need" an init() function at all

It's not the same: Virtually every object, in every game type, needs to initialize in some way, which justifies system support for that process. You can't really say the same about the circumstances you describe.

Also, for those circumstances, the actual need is to initialize after your "pre-initialization" code executes, not on "the next frame". So, calling the custom initialization method explicitly (as I suggested, and as you're currently doing) is a very straightforward, and very easy solution that corresponds more directly to the actual problem at hand.

If this was something extremely messy, which could be made much cleaner by an additional engine feature, I think that would be worth considering, but, as far as I can tell, that doesn't seem to be the case.

**Comment by SolarLune** [comment]
> I'm not sure if that's generally common enough to justify explicit engine support. It may be common in a setup that uses properties (instead of the java type system) to differentiate between objects, and then follow different initialization branches, but that setup itself is fairly uncommon.

It's common in a setup that stores any kind of property at a basic level. As an example:

```java
Vector3f startingPosition;

void init() {
     startingPosition = position();
}
```

This init function already doesn't work if you need to position this object after creation, as the startingPosition was stored as soon as the object was created, not after it was positioned. Now the options are to make the variable public and have the spawner correct the startingPosition, or run the init function (or another initialization function) later; neither are desirable, to me.

Now, I see the usefulness of having init() run right after object creation, but I also see the usefulness of having a deferred initialization function; something that runs a bit later, after the object is created.

> Also, for those circumstances, the actual need is to initialize after your "pre-initialization" code executes, not on "the next frame". So, calling the custom initialization method explicitly (as I suggested, and as you're currently doing) is a very straightforward, and very easy solution that corresponds more directly to the actual problem at hand.

Not quite. I need the object to initialize any amount of time after being created (not right when its created) and before the main function runs. The beginning of the next frame would work.

> If this was something extremely messy, which could be made much cleaner by an additional engine feature, I think that would be worth considering, but, as far as I can tell, that doesn't seem to be the case.

I don't consider adding an extra function / if statement in multiple objects' main functions straightforward; I consider it messy.

**Comment by GoranM** [comment]
> It's common in a setup that stores any kind of property at a basic level.

There's usually no fundamental requirement to actually run that kind of code in "init".

Those seem like constraints you placed on yourself, rather than being inherent to the actual requirements:

> Now the options are to make the variable public and have the spawner correct the startingPosition, or run the init function (or another initialization function) later; neither are desirable, to me.

Why are they not desirable?

You already have a part of your initialization (what I previously referred to as "pre-initialization") running in the spawner, so an additional function call is basically negligible.

**Comment by SolarLune** [comment]
I guess there's no sense in discussing this further; we fundamentally disagree on this point. I'll let it go. Issue closed.
