### ISSUE TITLE
Altkey activated after BDX END

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#65]
On Windows 7 x64 I always have to refresh the Blender window (minimize and then maximize for example) in order to disable the Altkey from being activated after BDX ended.

I noticed it by pressing "p" after closing BDX and getting the Blender Remove Parent dialog.

This bug is present since the beginning.

**Comment by GoranM** [comment]
I can't seem to reproduce this issue.

Which version of Blender are you using?

**Comment by rafcolson** [comment]
I will update to 2.73 shortly.

**Comment by GoranM** [comment]
I'm still using 2.72 ... This may be an issue with your system specifically, or maybe even with your keyboard (sounds unlikely, I know, but I guess it's something to check).

**Comment by rafcolson** [comment]
It seems that it comes and goes. Closing this. If I have figured out what the source of the problem is I'll let you know.
