### ISSUE TITLE
Suggestion: Update Timer for Profiler

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#650]
Hey, there. 

A (customizeable, I suppose) Timer for updating the Profiler would probably be a good idea at this point; it's a little difficult to see the numbers and bar graphs.

**Comment by GoranM** [comment]
> it's a little difficult to see the numbers and bar graphs.

In which circumstances?

They seem fairly clear to me.

Anyway: @rafcolson should be a part of this discussion.

**Comment by SolarLune** [comment]
When you're trying to see the numbers and you have 1/60th of a second to make them out, haha. I mean, sure, you can get a general idea with the way it is now, but you can't really make any accurate readings with the numbers and graphs changing so quickly.

**Comment by rafcolson** [comment]
So, what you suggest is to update the timers not as frequent as 1/60? Which frequency do you suggest?

I suppose we could use a lower frequency for the texts, but keep 1/60 for the bars, so spikes still are noticeable. Let's say the text is updated every 5th of a second, this wouldn't show every irregularity as clearly, as it's the average value of 12 sequential values. Then it's a good thing that the bars will be updated as before.

I'm on it. (if that's okay).

**Comment by rafcolson** [comment]
@GoranM I have a request for a new release. My pc crashed last week and for some unknown reason running BDX fails. Didn't open a new issue, since the problem is probably related to the crash.

**Comment by GoranM** [comment]
> When you're trying to see the numbers and you have 1/60th of a second to make them out, haha. I mean, sure, you can get a general idea with the way it is now, but you can't really make any accurate readings with the numbers and graphs changing so quickly.

The entire purpose of a profiler display is to get a general sense of overall system performance. I guess we could do what raf suggested (assuming that's what you want), but as he pointed out, it's not going to give you accurate numbers.

If you really want/need accuracy, it would be better to log the relevant data, and analyze it later.

Another potential option is to throttle the framerate, in moments where you really need to inspect the frame-to-frame differences in detail.

> I have a request for a new release. My pc crashed last week and for some unknown reason running BDX fails. Didn't open a new issue, since the problem is probably related to the crash.

I have some technical issues myself, so I can't really do that at the moment. In the meantime, you can try to create a plain LibGDX project, using the gdx-setup.jar (currently in master) directly. That should get all the relevant dependencies, and then you should be able to build BDX as before.

**Comment by SolarLune** [comment]
> So, what you suggest is to update the timers not as frequent as 1/60? Which frequency do you suggest?

We could make it so that the frequency of the bar and text updating is customizeable. Leave it up to the user to tweak.

> Another potential option is to throttle the framerate, in moments where you really need to inspect the frame-to-frame differences in detail.

I thought we couldn't alter the framerate?

**Comment by rafcolson** [comment]
>We could make it so that the frequency of the bar and text updating is customizeable. Leave it up to the user to tweak.

So a function such as `Profiler.interval(float seconds)` with `seconds=0f` as the default. Sounds good to me.

>If you really want/need accuracy, it would be better to log the relevant data, and analyze it later.

I'm thinking of a `Profiler.get(String subsystemName) - JsonValue` method and a `Profiler.print(String subsystemName)`, as well as a `Profiler.props.print(String subsystemName)`. I think that would enable the user to log relevant data to analyze.

**Comment by GoranM** [comment]
> I thought we couldn't alter the framerate?

With a bit of effort, it could be done cleanly, but it might not be worth the trouble: Just logging when required is less complicated engine-wise, and easy enough for the user.

**Comment by Lucrecious** [comment]
You should use a profiler if you want to analyze your project. Then, for specific spikes (or even longer period of lag), you can look at a stack trace to see what function was running at the time of the spike. I use a free profiler called VisualVM.

**Comment by rafcolson** [comment]
@GoranM If those technical difficulties are resolved, could you please draft a new release?

**Comment by GoranM** [comment]
Not resolved yet.

**Comment by rafcolson** [comment]
>Not resolved yet.

Okay. Thanks.

**Comment by SolarLune** [comment]
Hey, I would also like a new release, if possible. If it helps, I can build BDX fine, so I could send you the latest version built to upload to the releases section. Otherwise, I'm fine with waiting.

@Lucrecious Hey, thanks for the tip! VisualVM is super useful for seeing the memory usage of the application and stuff. Great tool; I have to look into examining the most expensive functions / areas of the game.

**Comment by rafcolson** [comment]
>Hey, I would also like a new release, if possible. If it helps, I can
build BDX fine, so I could send you the latest version built to upload to
the releases section. Otherwise, I'm fine with waiting.

It would be nice if I could use your build, @SolarLune. Although I think
it's a long shot. Didn't restore my pc yet but I'm curious if it would
work. Could you send it to colsonraf@gmail.com?

**Comment by SolarLune** [comment]
Sent!

**Comment by GoranM** [comment]
I'll be able to make a new release sometime this week.

@rafcolson 

I would recommend trying to resolve your build issues without relying on a new release, because this is probably not the last time that we're going to update libgdx.

**Comment by rafcolson** [comment]
>I would recommend trying to resolve your build issues without relying on a new release, because this is probably not the last time that we're going to update libgdx.

I was planning to. Unfortunately I've been very busy the last couple of weeks. But you're right. I shouldn't rely on new drafts. I should mention though, that I was able to solve the issue before the crash of my pc. I'm not sure what happened. But I guess I lost some files. After the crash I suddenly had to install Microsoft Framework 3.0, as my Git only found 2.0, which is curious, because I assumed even later versions were installed. I'll probably first restore my pc in a day or two and then try to fix this issue again, using the pointers you gave.

**Comment by rafcolson** [comment]
@SolarLune Would these two commits solve this issue?

**Comment by SolarLune** [comment]
Oh, by making the percents and times public, you can grab them every so often (like every second). Yeah, that should be fine, I think.

**Comment by rafcolson** [comment]
Okay, thanks. I'll submit a PR after the current PR with profiler changes is merged.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by SolarLune** [comment]
The PR was merged, so I'll close this. Thanks, @rafcolson!

**Comment by rafcolson** [comment]
No problem.

**Comment by rafcolson** [comment]
@SolarLune Think you forgot to close this.

**Comment by SolarLune** [comment]
Ah, whoops. Thanks!
