### ISSUE TITLE
Memory Leak: Framebuffers Being Created Too Often

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#654]
Hey, there. 

So basically, there's a massive memory leak if you use two (or more) ScreenShaders with differing downsample sizes. When rendering the game, BDX will create a new Framebuffer every time the current ScreenShader's downsample size is different from the temporary render buffer's render percentage. This causes astronomical bloat and hogging of 100% CPU / RAM over a few seconds, resulting in a system freeze. The fix is simply to create RenderBuffers only when necessary.

PR submitted.

**Comment by GoranM** [comment]
If you find a bug, and manage to resolve it yourself, you can just make the PR - there's no need for an issue in that case.

**Comment by SolarLune** [comment]
Oh, OK. Thanks for the info! I thought it would look kinda weird to just propose somewhat major code changes out of the blue.

**Comment by SolarLune** [comment]
The PRs were merged, so I'll close this now. Thanks!
