### ISSUE TITLE
Camera lookAt

### ISSUE THREAD

**Issue by felipetavares** [GoranM/bdx#660]
I searched the docs and the issues here but found no reference on how one would do a `lookAt` with the camera.

I am currently trying to do it this way, with no luck (in the main() of a object to which the camera is parented and both share the same initial position):

```
        Vector3f eye = ;//Some code to get the cam position

        Vector3f dir = Bdx.scenes.get(0).objects.get("ObjectToLookAt").position();
        Vector3f up = new Vector3f(0, 1, 0);
        Vector3f right = new Vector3f();
        
        dir.sub(eye);
        dir.normalize();
        right.cross(dir, up);
        right.normalize();
        up.cross(right, dir);
        up.normalize();
                
        Matrix4f mat = new Matrix4f();
        mat.setIdentity();
        mat.setColumn(0, right.x, right.y, right.z, right.dot(eye));
        mat.setColumn(1, up.x, up.y, up.z, up.dot(eye));
        mat.setColumn(2, dir.x, dir.y, dir.z, dir.dot(eye));
        
       transform(mat);
```

Maybe there should be/is a function to do that (or docs explaining) as it is a pretty common use case?

**Comment by SolarLune** [comment]
There's a function that aligns an axis of an object to a direction called [alignAxisToVect](https://github.com/GoranM/bdx/wiki/API-GameObject#alignAxisToVec). There's also a component, [Track](https://github.com/GoranM/bdx/wiki/API-Track), that tracks an object to face a specific other object.
