### ISSUE TITLE
Scene.valid()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#661]
Hey, there. It might be nice to add a `valid()` function to the Scene class to indicate when it's being cleaned up. So when you call scene.end(), it sets the validity to false, and so GameObjects in the scene can know it's being destroyed.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR Created.

**Comment by SolarLune** [comment]
This was merged, so I'll close it now. Thanks!
