### ISSUE TITLE
Android Controller

### ISSUE THREAD

**Issue by stamoksa** [GoranM/bdx#663]
Hello,
On pc we use Bdx.keyboard.key(hit , down , up) and mouse to move and control objects what codes should i use to control android game when touching screen and titling the phone (can u give me example code please )
Thanks alot.

**Comment by SolarLune** [comment]
There's no method to check for phone rotation with BDX; you should be able to do this through whatever method LibGDX exposes. I suppose we should probably add this, actually; it's a pretty major tool for developers.

Anyway, for touching the screen, checking for [Fingers](https://github.com/GoranM/bdx/wiki/API-Bdx#fingers) should work.

**Comment by stamoksa** [comment]
Thanks alot

**Comment by rafcolson** [comment]
> I suppose we should probably add this, actually; it's a pretty major tool for developers.

I agree.

**Comment by SolarLune** [comment]
Hmm, well, it looks like [it's pretty simple to use in Gdx.input](http://www.gamefromscratch.com/post/2013/10/30/LibGDX-Tutorial-6-Motion-controls.aspx); it's just a matter of making some alterations to a couple of Android files to take advantage of it. I dunno if it'd be worth the added code just to expose it under BDX's package space. 

Maybe we could add a couple of additional useful helper functions to justify it, like `flicked()` and `bumped()`, to tell when the device has been quickly rotated or jolted?

**Comment by rafcolson** [comment]
>titling the phone (can u give me example code please )

@stamoksa Would this tutorial in the [Wiki's Installation page - Android Development](https://github.com/GoranM/bdx/wiki/Installation#android-development) solve this issue for you? If so, could you close this?

**Comment by stamoksa** [comment]
thanks alot for helping and i am sorry for taking long time to close it i was busy and didn't open the forums long ago.
