### ISSUE TITLE
Axis() function drifting

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#664]
Hey, there. If you rotate a GameObject using its local axis (using the axis() function) and a non-cardinal rotation (i.e. its local axes aren't facing the global axes), it'll start drifting pretty quickly. For example, this:

```java
rotate(axis(1).mul(0.25f));
```
Causes the object to spin around its local Y-axis, but quickly start drifting.

**Comment by SolarLune** [comment]
Here's an [example blend file.](https://www.dropbox.com/s/sioez7o3w5vf36i/DriftError.blend?dl=0)

**Comment by rafcolson** [comment]
Could we use the euler instead of column as we do in rotateLocal? Just a guess.

I think a better practice would be to just use rotateLocal though.
```java
rotateLocal(0, 0.25f, 0);
```

**Comment by GoranM** [comment]
Note the definition of the method you're using:

```java
public void rotate(Vector3f rot){
    rotate(rot.x, rot.y, rot.z);
}
```

It simply uses the vector components as rotation values for each global axis. It doesn't rotate the object around the given vector.

If you want to rotate around a specific axis, you can use rotateLocal, as raf demonstrated.

**Comment by SolarLune** [comment]
Yeah, it doesn't look like rotateLocal suffers from this "drifting", so I guess it's just a matter of using the correct tool for the job. Thanks!

Issue closed.
