### ISSUE TITLE
Suggestion: Property Visualization in Blender

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#665]
Hey, there. 

I was thinking that a nice addition to upgrade usability might be to add the ability to see properties of objects in Blender's 3D view. It would list the name and value of each property of each selected object, probably in different sections (green for Group Instances, gray for object properties). I think it should be possible, since there are add-ons that visualize things in the 3D view (like the Measure add-on).

**Comment by GoranM** [comment]
I think the ability to select objects by specified property would probably be more effective than just dumping all the property names into the 3D view.

Something like this would work fine:

```python
for o in C.scene.objects:
    if "prop_name" in o.game.properties:
        bpy.ops.object.select_pattern(pattern=o.name)
```

That said:

I'm not sure if the BDX plug-in is the right place for those kinds of helpers.

If people have useful blender operators that they want to share, they can do that independently.

**Comment by SolarLune** [comment]
> I think the ability to select objects by specified property would probably be more effective than just dumping all the property names into the 3D view.

That does nothing to visualize game objects' properties; it's a completely different thing.

> I'm not sure if the BDX plug-in is the right place for those kinds of helpers.
If people have useful blender operators that they want to share, they can do that independently.

I'm not sure what's the delineation between "Optional Blender helper" and "useful core BDX helper".

**Comment by rafcolson** [comment]
>I'm not sure if the BDX plug-in is the right place for those kinds of helpers.

I think so too.

**Comment by GoranM** [comment]
> That does nothing to visualize game objects' properties; it's a completely different thing.

But we already have a clear listing in the object properties panel, so I don't really see the utility of repeating that information in the 3D view.

What is the actual problem that you're trying to solve?

> I'm not sure what's the delineation between "Optional Blender helper" and "useful core BDX helper".

The purpose of the BDX plug-in is to support the export process, so it seems sensible to only include code that's helpful in that context.

**Comment by SolarLune** [comment]
> But we already have a clear listing in the object properties panel, so I don't really see the utility of repeating that information in the 3D view.

> What is the actual problem that you're trying to solve?

Seeing at a glance what properties my objects have and are set to. For example, seeing what objects have a property (are solid) without having to check object instance source objects, or click on each individual one.

> The purpose of the BDX plug-in is to support the export process, so it seems sensible to only include code that's helpful in that context.

OK, but the purpose of BDX as a whole is to serve as a game engine. Anything that supports this should be considered for addition.

**Comment by GoranM** [comment]
> Seeing at a glance what properties my objects have and are set to. For example, seeing what objects have a property (are solid) without having to check object instance source objects, or click on each individual one.

But isn't that just search by property? I mean, you're looking for objects that have the "solid" property, so it would make sense to have an operator that would select all objects that have it, instead of polluting the 3D view with a bunch of lists that the user would then have to search manually, by visual scanning.

> OK, but the purpose of BDX as a whole is to serve as a game engine. Anything that supports this should be considered for addition.

Yes, but for something that can be provided independently, I think it would be prudent to introduce it that way.

People can give it a try, if they want, and if they find the feature to be as essential as you think it is, we can then ship it with the plug-in.

Until then, I'd rather not complicate the relatively pure exporter.

**Comment by SolarLune** [comment]
Hmm, yeah, I suppose so. 

Issue closed, then.
