### ISSUE TITLE
Suggestion: Sensor Collision Checking With All Types

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#667]
Hey, there.

So the Sensor physics type is implemented under BDX (which I wasn't aware of until today, haha), but it still only detects dynamic or rigid body objects. Would it be possible to enable static objects and other sensors to also be detected by sensors?

**Comment by rafcolson** [comment]
Blender's Physics Type *Sensor* doesn't detect static objects, does it? If not, then maybe a fourth `bodyType` "SENSOR_STATIC" would be in place, or something like that.

**Comment by SolarLune** [comment]
I'm not sure if the BGE's sensor detects everything; I hadn't checked before I made this. It seems like Sensor should be able to detect everything; otherwise, there's a lot of overlap between a Sensor-type object and a Static Ghost object.

**Comment by rafcolson** [comment]
>otherwise, there's a lot of overlap between a Sensor-type object and a Static Ghost object.

I don't think this would justify deviating from the definition of Blender's Physics Type *Sensor*. Users would usually expect *Sensor* (a.k.a. Bdx's "SENSOR") not to be detecting "STATIC" bodies. That's why I would prefer the "SENSOR_ALL" solution. But it's up to you and @GoranM. I wouldn't be opposed to it that much.

**Comment by SolarLune** [comment]
I'd be happy with just being able to detect static and dynamic objects.

**Comment by rafcolson** [comment]
>I'd be happy with just being able to detect static and dynamic objects.

Me too. Anyway how to approach this? I'm not sure if jbullet's kinematic (or static) bodies could even detect bodies of the same kind.

**Comment by GoranM** [comment]
> Blender's Physics Type Sensor doesn't detect static objects, does it?

The tooltip in blender states: "Collision Sensor, detects static and dynamic objects but not the other collision sensor objects".

Right now sensor is no different than a static ghost object. 

If anyone wants to implement that properly, according to the blender definition, feel free to do so.

**Comment by rafcolson** [comment]
>The tooltip in blender states: "Collision Sensor, detects static and dynamic objects but not the other collision sensor objects".

Oh, my bad! Sorry guys.

**Comment by SolarLune** [comment]
> Me too. Anyway how to approach this? 

Nope! I'll have to look into it, I guess.

> Oh, my bad! Sorry guys.

No problem!

**Comment by rafcolson** [comment]
If I'm not mistaken, this issue was solved with #906, right?

**Comment by SolarLune** [comment]
Ah, yeah, this is solved. Thanks!
