### ISSUE TITLE
Suggestion: GameObject.ignoreCameras

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#668]
Hey, there. 

I think an ArrayList of cameras, present on the GameObject, to ignore rendering might be a cool thing to add. This would allow people to do things like create glass, water, and other "see-through" effects.

The basic idea and use-case I have is to hide water objects when rendered through a specific camera, and then take the camera's texture and substitute that texture on the water object. 

For this to work, I think I'd apply the texture using window-based UV coordinates, which I could easily create a new custom shader for. I guess I could add that into BDX proper, though, whichever.

**Comment by GoranM** [comment]
Camera.ignoreObjects seems better, as it makes more sense for cameras to host data that affects the rendering process, instead of having a camera list on every game object.

**Comment by SolarLune** [comment]
OK, PR submitted. Not sure if @rafcolson'll need to tweak his Viewports branch.

**Comment by rafcolson** [comment]
>Not sure if @rafcolson'll need to tweak his Viewports branch.

No problem.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks.
