### ISSUE TITLE
Suggestion: ArrayListNamed & LinkedListNamed: indexOf(String) & remove(String)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#670]
Extra methods that will eventually be accessible in both ArrayListNamed and LinkedListNamed:

- reverse()
- shiftTo(index i, T x)
- shiftToFirst(T x)
- shiftToLast(T x)
- shiftTo(index i, String name)
- shiftToFirst(String name)
- shiftToLast(String name)
- toNames() - String
- **indexOf(String name)**
- **remove(String name) - T x**

API changes:
___

# API ArrayListNamed
...
<a name="indexByName" href="#indexByName">#</a> **indexOf**(String name) - int

Returns the index of the first E where E.name().equals(name), or -1 if this list does not contain the element.

<a name="removeByName" href="#removeByName">#</a> **remove**(String name) - E

Removes and returns the first E where E.name().equals(name).
___

# API LinkedListNamed
...
<a name="indexByName" href="#indexByName">#</a> **indexOf**(String name) - int

Returns the index of the first E where E.name().equals(name), or -1 if this list does not contain the element.

<a name="removeByName" href="#removeByName">#</a> **remove**(String name) - E

Removes and returns the first E where E.name().equals(name).

**Edit: removed all but *indexOf(String)* and *remove(String)*.**

**Comment by SolarLune** [comment]
I like the improvements to the Named variants of the ArrayLists (.indexOf(name) is great).

I'm not sure if we need `shiftToFirst`, since that could just be covered with `shiftTo(0, "blah")`. The `shiftToLast` function could be useful enough, though (since the alternative would be `whateverList.shiftToLast(whateverList.size() - 1, "blah");`).

**Comment by rafcolson** [comment]
>I'm not sure if we need shiftToFirst, since that could just be covered with shiftTo(0, "blah").

I think it's a matter of convention. If there is a `last`, one would normally expect there's a `first` too. Especially with extensions of classes such as [LinkedList](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedList.html), I think we should continue in the same fashion. Compare with `getFirst`, `addFirst` and `removeFirst`. Don't know if that's a good enough reason.

**Comment by GoranM** [comment]
Is there a justification for this suggestion?

IE: Why do we need this? What kind of problem is this supposed to solve?

**Comment by rafcolson** [comment]
>Why do we need this? What kind of problem is this supposed to solve?

Not don't suppose we absolutely need these methods, but it would be convenient to have those, if someone would like to utilize `ArrayListNamed` or `LinkedListNamed`. That said, I think some of these functions would add some improvements to Bdx too.

- *toNames() - String* -> to be able to print the names of named lists in Bdx easily
- *indexOf(String name)* -> convenience method, maybe @SolarLune could tell why this would be great?
- *remove(String name) - T x* -> in case of `scene.viewports` this would be a common operation, e.g. for toggling between split and single screens
- *reverse()* -> fairly common operation. This addition would personally encourage me to use `Bdx.utils` lists instead of those of `Java.util`.
- *shiftTo*-methods -> not as common, and maybe not as justified, since *set(index i, Tx)* is probably all we need in order to 'arrange' items. So I'll drop these. If I really want to arrange items after they're added, I could always do this:
```java
T x = myList.remove("Bicycle");
myList.set(myList.indexOf("Car"), x);
```

**Comment by SolarLune** [comment]
Well, there's slightly longer ways around all of these options; I guess it's probably best not to include them, though, as I can't really come up with situations where you'd really be using these options all that often (if at all).

`reverse()` is nice, but the Collections package has functions for reversing lists.

`remove(name)` sounds useful, but I don't think it's something that you'd use that often in practice. If you want to remove a GameObject from play, you'd `end()` it, so you wouldn't have to manually alter any built-in lists (though you could use it  for manually kept lists).

For toggling split-screens, you might want to have a `Viewport.active` property that determines if the Viewport is on or not. Then you could just create a single-player fullscreen Viewport, and then two split-screen Viewports, and turn them on and off as necessary. That way you don't have to destroy and recreate Viewports whenever you switch to split-screen mode.

I guess I'd be OK without them.

**Comment by rafcolson** [comment]
>That way you don't have to destroy and recreate Viewports whenever you switch to split-screen mode; you could just do:

You wouldn't have to destroy and recreate in order to switch. You can store the viewport and add or remove it from the Scene.viewports list. I don't think it's necessary to let Bdx store inactive viewports.

**Comment by SolarLune** [comment]
Ah, that's true. The difference is pretty slight; it's up to you which way you go.

**Comment by rafcolson** [comment]
Okay. So could I change my suggestion? How about only these additions to ArrayListNamed:
- *toNames() - String* -> to be able to print the names of named lists in Bdx easily
- *indexOf(String name)* -> convenience method
- *remove(String name) - T x* -> in case of `scene.viewports` this would be a common operation, e.g. for toggling between split and single screens

**Comment by rafcolson** [comment]
I'll drop *`toNames() - String*, as the item itself could change *.toString()* in order for it to be more distinguishable when printing to the console.

@GoranM

So how about `indexOf(String name)` and `remove(String name)` or only `remove(String name)`? The latter seems to be more important to me, since this would be a common operation with `scene.viewports`.

**Comment by GoranM** [comment]
The whole use case for those methods seems to tied to the viewports list. Is there's actually a circumstance in which you would want to have two different viewports with the same name?

If not, maybe scene.viewports should be a HashMap, and maybe we don't really need these additions.

**Comment by rafcolson** [comment]
>The whole use case for those methods seems tied to the viewports list.

For now it is. But previously I mentioned also that I would be encouraged to use `Bdx.utils`'s list classes instead of those of `java.util`. I think these two extra methods would complete those classes. I couldn't think of other related methods to be added. About the other methods, I now see these would be redundant.

>Is there's actually a circumstance in which you would want to have two different viewports with the same name?

>If not, maybe scene.viewports should be a HashMap, and maybe we don't really need these additions.

I see your point. The order by which viewports are rendered and detected by Pointers matters of course. So should I use a LinkedHashMap instead?

That said, I'm feeling a bit uncomfortable with having to provide the name twice:
```java
scene.viewports.put("ViewportA", new Viewport("ViewportA", camera, type));
```

**Comment by GoranM** [comment]
Ok.

> So how about indexOf(String name) and remove(String name) or only remove(String name)?

Sounds good.

**Comment by rafcolson** [comment]
Thanks. I'll wait with adding this after viewports are in.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks a lot.
