### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by jrdzha** [GoranM/bdx#673]
Hi So I'm just reporting a bug that I found

I just got started on BDX and I was following this guide:
https://github.com/GoranM/bdx/wiki/Basic-Tutorial-3%3A-Creating-A-New-Project

So I got to the step where it asked me go create the new project. The issue I found was that if the project directory already existed and you try to input that directory into BDX, the project will not be created correctly. 

Thanks, BDX looks very promising and I hope to have a good experience with it! (I'm switching from intelliJ + libGDX to BDX :D)

Jared

**Comment by GoranM** [comment]
This is actually noted on the wiki page you referenced:

> To be sure it goes off without a hitch, the directory shouldn't exist, as BDX will make it for you.

Although, I guess it would be a good idea to have some code that would detect that error condition, and notify the user.

**Comment by SolarLune** [comment]
Thanks, I added a note to that  that says the directory shouldn't exist before creation.

**Comment by rafcolson** [comment]
This now can be closed.

**Comment by GoranM** [comment]
Ok.
