### ISSUE TITLE
Velocity problem

### ISSUE THREAD

**Issue by stamoksa** [GoranM/bdx#674]
Hello,
GameObject Player = scene.objects.get("player")
if(Bdx.keyboard.keyDown("space")){
Player.applyForce(0,0,100);
}
it works without any problem and he jumps up but when i set velocity it doesnt jump
GameObject Player = scene.objects.get("player")
Player.velocity(20,0,0);
if(Bdx.keyboard.keyDown("space")){
Player.applyForce(0,0,100);
}
it moves without stopping and when i press space it doesnt jump i want the object yo move ahead without stopping but i want it to jump when i press space what should i do?
Thanks.

**Comment by SolarLune** [comment]
Hello!

1) To better format the code on GitHub, use three tildes (`) with the word java, and then put the code after that, starting with a new line. After it all, put three tildes again to form a code block. Here's your code formatted:

```java
GameObject Player = scene.objects.get("player")
if(Bdx.keyboard.keyDown("space")){
Player.applyForce(0,0,100);
}
```

```java
GameObject Player = scene.objects.get("player")
Player.velocity(20,0,0);
if(Bdx.keyboard.keyDown("space")){
Player.applyForce(0,0,100);
}
```

2) Where's the semicolons after the Player line?
3) You're manually setting the object's velocity with the call to Player.velocity(). The third argument is the Z axis, which you're setting to 0, stopping any upward momentum. Try modifying the player's speed and writing back to it, like so:

```java
Vector3f vel = Player.velocity();
vel.x = 20;
Player.velocity(v);
```
or
```java
Player.velocity(20, 0, Player.velocity().z);
```
4) This issue tracker is mainly for bugs and suggestions related to the engine itself; if you have questions about using the engine, refer to the subreddit [here](https://www.reddit.com/r/bdx).

**Comment by stamoksa** [comment]
Thanks alot it worked

**Comment by SolarLune** [comment]
Glad to hear! Could you close this issue, then?

**Comment by rafcolson** [comment]
@stamoksa This can be closed, right?

**Comment by SolarLune** [comment]
Hey, I believe this can be closed, @GoranM. It looks like @stamoksa got his answer.
