### ISSUE TITLE
Joining Objects Doesn't Work With Materials

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#676]
Hey, there. 

So joining objects doesn't quite work correctly with materials; it looks like it just grabs the first material in the last joined object to use. It would be nice if this used the actual materials from the joined objects. 

All of the `updateJoinedMesh()` function could also be easier to use with the new Mesh class, though if it's easier to just modify the existing code instead of refactoring it to use the class, that's fine.

**Comment by rafcolson** [comment]
Yes. Right now it's not possible to join objects with more than one material. I'll work on a fix for this. It shouldn't be difficult, as for every material a mesh part can be created.

**Comment by SolarLune** [comment]
Thanks!

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR updated. I should be okay now.

**Comment by rafcolson** [comment]
PR updated.

**Comment by SolarLune** [comment]
Cool, this was merged. I'll close this now. Thanks for your help, @rafcolson!
