### ISSUE TITLE
Suggestion: GameObject.id() and ArrayListGameObject.getByID()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#679]
Hey, there. 

I think It'd be nice to be able to grab a GameObject out of a list based on its ID - something that's not a reference to the GameObject itself, but that still uniquely identifies the GameObject (unlike name, property, or component). This could be useful when trying to keep track of objects, but without keeping references in case the GameObject gets end()-ed, or if you're unable to send the reference directly (like in the propose Notifications system).

When the GameObject prints out itself as a string, it gives:

```java
return name + " <" + getClass().getName() + "> @" + Integer.toHexString(hashCode());
```

so I guess the ID for the GameObject is `Integer.toHexString(hashCode())`. Adding that as a function (`id()`) and adding `ArrayListGameObject.getByID(String)` would be useful, I think.

**Comment by rafcolson** [comment]
Sounds like a useful addition to be able to identify instances of the same object, as these would all have the same name. This would discourage changing names to do the same thing, for which the "name" field isn't intended to be used for.

**Comment by SolarLune** [comment]
Yeah, that was my original thought. 

PR submitted.

Anyway, it seems like hashCode() [might return a colliding ID after there's a certain number of memory entries](http://eclipsesource.com/blogs/2012/09/04/the-3-things-you-should-know-about-hashcode/) (see point number 2 in that link), so each GameObject now has a unique ID number. The toString() value also uses this number.

As a side-note, I thought scene.objects was ArrayListGameObject, but it's not, so no built-in method to search for objects by ID. Oh well.

**Comment by GoranM** [comment]
> This could be useful when trying to keep track of objects, but without keeping references in case the GameObject gets end()-ed

Why would an "id" be more useful then a reference at that point?

> or if you're unable to send the reference directly (like in the propose Notifications system).

Why are you unable to send the reference directly?

> Sounds like a useful addition to be able to identify instances of the same object, as these would all have the same name.

Can you provide a concrete use-case that clearly illustrates the utility of unique identifiers for spawned instances?

I can only think of a few, and I don't think any of them would justify engine support.

**Comment by SolarLune** [comment]
Hmm, yeah, I was mainly thinking of this for the Notification system, but I can't really imagine a situation where we'd need to send the ID and not just be able to create a custom Note that has a reference to the direct GameObject, as necessary. 

The original idea was that by sending the ID, the objects that receive the Note could check to find the object with the ID, but since the Note should be able to just hold the data, that's not a valid use case.

I can't think of a use case that requires an ID that the reference itself wouldn't serve the purpose of, so I guess that's it! PR closed. Thanks.
