### ISSUE TITLE
Exception in build.gradle while building for android

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#68]
This bug was present from the beginning. I had to work around it by editing **build.gradle** in the android folder, line 3:
```java
compileSdkVersion 19
```
(When installing the add-on?) *buildToolsVersion* is being updated to my current Android SDK Build-tools version (see Android SDK Manager), but *compileSdkVersion* is not. I should have:
```java
android {
    buildToolsVersion "21.1.2"
    compileSdkVersion 21
    ...
```
Then it works.

Maybe this is an issue with gradle itself, but I felt it should be reported anyway.

For anyone who wants to build their BDX project into an Android *.apk, it should be helpful to inform about this issue. I could make a tutorial of all necessary steps to build for Android, but who knows, maybe it could be fixed..

**Comment by GoranM** [comment]
This is one of those things that's not managed by the libgdx project generator, or gradle, so we need code that can find out, and subsequently set the proper version in the gradle file.

I already [do this](https://github.com/GoranM/bdx/blob/master/blender/bdx/ops/createproj.py#L210) for the build tools version, so we should probably do it for the sdk version as well.

You want to give that a try?

I think you can just search the platform directory in the android sdk, which should contain directories like android-\<version\>, so if you can just get the highest there, and set that in the build file, I think that should do it.

**Comment by rafcolson** [comment]
> You want to give that a try?

I will. Thanks for the tips.

**Comment by rafcolson** [comment]
Pulled request #77

**Comment by GoranM** [comment]
You made a pull request, it's up to me to pull it.

Also, in commits that address issues, you should reference the issue in the commit message - don't reference the pull request from the issue.

**Comment by rafcolson** [comment]
I'll keep in mind what you said.

**Comment by rafcolson** [comment]
Well, it finally got in. Thanks.
