### ISSUE TITLE
Suggestion: Rename init() / main()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#683]
Hey, there. 

I think it might be good to rename these `onInit()` and `onUpdate()`, because they're callbacks, not functions that are supposed to be run directly.

Thanks.

**Comment by GoranM** [comment]
They're just methods. They're called by the system, but they could also be called by the user (ie: they want to reinitialize the object, or something along those lines).

From that perspective, the existing names seem fine.

**Comment by SolarLune** [comment]
onEnd() already exists, so they all probably should share the "on" part for consistency. And yes, regardless of the name, the function can be called by hand, so to speak.

**Comment by GoranM** [comment]
As I remember, we named "onEnd" to avoid colliding with the existing "end" method, not to signify that it's a callback.

It might be more "consistent" to rename "onEnd" to "deinit", but I'm not sure if it's worth changing at this point.

**Comment by SolarLune** [comment]
> As I remember, we named "onEnd" to avoid colliding with the existing "end" method, not to signify that it's a callback.

But it is a callback. It makes sense to name it "onEnd", because it runs on `end()`. Naming it `deinit()` doesn't really make sense, because it doesn't describe what the function's there for. Like, you don't have to look up what `onInit()` does, but you do have to look up what `deInit()` does. People might think it resets or de-initializes the GameObject.

**Comment by rafcolson** [comment]
I think I have to agree that "onInit" and "onUpdate" would be more correct and also more descriptive. The "on" would describe that there is a distinction to be made.

But I'm okay with "init" and "main" too. I don't think someone would have to think that anything's reset as these methods are well documented.

**Comment by GoranM** [comment]
> People might think it resets or de-initializes the GameObject.

Well, it is a counterpart to "init", so in that sense, it should "de-initialize" the GameObject.

I personally don't think it's worth breaking existing code (and some video tutorials) for this, but if you guys really want it, I'm ok with it.

**Comment by SolarLune** [comment]
Well, I mean, I'd rather not break existing functionality either, but it's better to do it early rather than later. The engine still is in beta, so it's to be expected that major or otherwise fundamental code changes would happen earlier in the engine's lifecycle, when compared to later. I'll submit a PR for it later.

**Comment by GoranM** [comment]
Well, the fact that we have so few users is more relevant in than respect, but still, it doesn't seem like it's worth it.

The existing documentation (and videos) clearly explain these methods, and they're the first thing that the user is introduced to anyway, so I don't think the scant semantic benefit of the "on" prefix is actually worth the trouble.

But, as I said, it's up to you guys.

**Comment by rafcolson** [comment]
I gave it some thought. And I came to the conclusion that it would be better not to break the existing documentation over this seemingly semantic benefit. It's not like `main()` or `init()` are confusing, are they?

That said, I think that I've found a valid argument against it. As @GoranM mentioned earlier, the names shouldn't actually indicate that they are callbacks, as they are just (empty) methods (to be overridden). And than there's this problem. Renaming "init" to "onInit" would imply that "end" would also have to be renamed to "onEnd", because "end" is also a callback. However the already existing "onEnd" indicates it to be a call back on method "end". In order to be consistent, we then would have to rename this callback on the "end" callback to "onOnEnd", which sounds ridiculous.

So let's stick with names "init" and "main" and "end" and "onEnd".

**Comment by SolarLune** [comment]
Nah, end() isn't a callback; it's just a normal function, like `rotate()` or `move()`. It ends the GameObject. `onEnd()` is the "callback" function for `end()`. (And I know, there's not really any "callbacks" in BDX (or Java at all?); I was just using that as a term to refer to the fact that usually, BDX calls these functions, not you, manually).

But yeah, I was kinda waffling on this, too. It'd be a shame to break tutorials over a fairly slight and minor change, although the change isn't really that huge.

Anyway, it's OK; we can stay with everything the way it is. Issue closed.
