### ISSUE TITLE
Suggestion: GameObject.logicActive / GameObject.logicFrequency

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#684]
Hey, there. 

So, it might be a good idea for users to be able to optimize their project by delaying or deactivating main() logic execution (i.e. allows the user to turn off triggering main() if a GameObject goes off-screen). 
Something like the tic rate in the BGE, but also with the ability to just shut off main() altogether. The same might be a good idea for Components, as well.

**Comment by GoranM** [comment]
How often they want to run their code, if at all, is something that the user can already control, in a fairly simple/straightforward manner:

```java
public void main(){
    if (offScreen())
        return;
    ...
}
```

**Comment by SolarLune** [comment]
It's not particularly straightforward to add logic execution frequency, as that would be something that needs to be added in a base classes extending GameObject and Component that all other classes extend.

It's also more efficient to turn off main() altogether and have a manager object turn main() on for these objects when necessary, rather than having each object check every frame to see if it should run.

**Comment by GoranM** [comment]
> It's not particularly straightforward to add logic execution frequency, as that would be something that needs to be added in a base classes extending GameObject and Component that all other classes extend.

That's true.

Although, having game logic as the performance bottleneck kinda makes it a special case to begin with.

> It's also more efficient to turn off main() altogether and have a manager object turn main() on for these objects when necessary, rather than having each object check every frame to see if it should run.

Well, when you say "turn off main()", what do you actually mean by that? If you mean having a boolean value on GameObject that will be checked in the Scene.update loop, then the overhead of the check is still there.

That said, there is a slight overhead in actually calling a function, so not calling main (even if it did nothing but return) would be faster, but I'm not sure if the savings in execution time would ever amount to anything of significance ... But then again, it's the JVM, so it's hard to be sure ...

Ok.

I assume 60 would be the default value of logicFrequency, specifying that it runs on every frame, and 0 would indicate that it's essentially deactivated?

If you want to add that to GameObject and Component, I think that would probably be fine.

**Comment by SolarLune** [comment]
> Well, when you say "turn off main()", what do you actually mean by that? If you mean having a boolean value on GameObject that will be checked in the Scene.update loop, then the overhead of the check is still there.

Well, yeah, I meant a boolean. It'd be easy to turn of "main()" for, say, all enemy spawning objects and then turn them on for only the area near the Player, rather than having them check constantly. Even just having them check periodically would be good.

But this:

> I assume 60 would be the default value of logicFrequency, specifying that it runs on every frame, and 0 would indicate that it's essentially deactivated?

Might be better than a boolean. I was thinking that the frequency would be how often it triggers, so 0 is every frame, 1 is every other frame, and so on. The advantage of your approach is that you can turn off triggering by setting the value to 0, so there's no need for an extra boolean value. However, it's hard-coded to work at 60, which means something that can't really work in case the logic tick rate ever changes. 

I guess it'd be OK? Do we ever think BDX will support > 60 FPS logic execution?

**Comment by GoranM** [comment]
I don't think we'll ever need to change the tick rate, but if the default value of logicFrequency is Bdx.TICK_RATE, it should work fine regardless.

**Comment by rafcolson** [comment]
@SolarLune In your code I find: `g.logicCounter += g.logicFrequency * Bdx.TICK_TIME;` (the same for components). But I don't get this. If `logicFrequency` is always `Bdx.TICK_RATE` and `Bdx.TICK_TIME` is always `1f / Bdx.TICK_RATE` than isn't this actually the same as doing:
```java
g.logicCounter += 1;
```

**Comment by SolarLune** [comment]
Yeah, it is, which is correct. Leaving it alone has execution work the same as it does now; the user can lower the `logicFrequency` to make it execute less often.

**Comment by rafcolson** [comment]
Great addition.

**Comment by SolarLune** [comment]
Thanks!

This was merged, so I'll close it out now. Thanks, you guys.
