### ISSUE TITLE
Installing latest bdx got error on blender 2.77a

### ISSUE THREAD

**Issue by gerardogc2378** [GoranM/bdx#685]
![screenshot from 2016-06-12 22-51-27](https://cloud.githubusercontent.com/assets/24534/15996733/d0d4630c-30f0-11e6-884a-35a1a33b1d70.png)

**Comment by SolarLune** [comment]
Looks like you're on Linux. There's a page about this particular issue on the [Installation page of the Wiki](https://github.com/GoranM/bdx/wiki/Installation#linux).

**Comment by gerardogc2378** [comment]
Yes, I'm using Arch Linux, I just installed python-numpy and bdx works again

```bash
# pacman -S extra/python-numpy
```

Thanks @SolarLune for your support.

**Comment by SolarLune** [comment]
No problem! Glad to hear that also works as a solution. I hadn't actually tested installing numpy in the Python installation. I'll update the Wiki to list this as a valid approach as well.
