### ISSUE TITLE
Camera Render Precision Issues

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#69]
Hey, there. So basically, it looks like there's some precision issues with the camera in BDX. if objects are parallel to each other and close in position, they can get under and over drawn between themselves, even if they're separated by a nice distance and the camera's got a pretty small clip distance. In the attached screenshot, you can see the black circles (they're opaque versions of a shadow sprite) not drawing correctly under the bushes. The camera's got a 0.1 - 50 clipping value, and the shadow planes are 0.1 Blender units above the ground plane.

![drawingissues](https://cloud.githubusercontent.com/assets/4733521/5794448/3eb2184a-9f22-11e4-8488-5937f52077aa.png)

Any ideas of why this might arise? Is this something you've already noticed in using BDX (this isn't the only time I've seen this happen)?

Here's a test blend file that shows the issue. Notice that the blue planes are "interlacing" with the green ground plane under BDX, and notice how far away they are from the ground plane in Blender.

https://app.box.com/s/6q8woot598rys7r4jzi5atntst6dl55c

**Comment by GoranM** [comment]
Did you forget to pack textures? I can't see any in the .blend.

I suspect your troubles are related to the sorting algorithm used in LibGDX, as I noted in #70.

**Comment by SolarLune** [comment]
No, I didn't feel the need to pack the textures since they don't do anything to illustrate the problem. Just the base colors show the issue.
