### ISSUE TITLE
Suggestion: GameObject.onRender(Viewport)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#690]
When viewports are in, the Halo component will not work properly anymore, when there's more than one viewport. The "Halo" GameObject should change its orientation to face each viewport, before each viewport is rendered. So, when there are two viewports for example, it should change its orientation twice.

A method `GameObject.halo(boolean halo)` to add/remove to a list `Scene.halos`. A function inside `Bdx.main()` to orient all `Scene.halos` to face each viewport.

Edit: A better solution was suggested: `onRender()`

**Comment by SolarLune** [comment]
An alternative might be to add an `onRender()` function to GameObjects and/or Components, which are called when the GameObject is rendered. 

That way, we could keep the Halo component as a Component, and add functionality for other such rendering-related components (though I can't come up with any use cases for this right now).

**Comment by rafcolson** [comment]
>Just an idea.

Much better than mine. I'm changing the suggestion.

**Comment by rafcolson** [comment]
I don't think I could think of any other use cases. The "halo" feature seems like a general feature anyway, so I don't think it's that bad to add it to the general code base. @GoranM What do you think?

**Comment by rafcolson** [comment]
>On one player's viewport, the object could appear normal, while it could appear "highlighted" for other players' viewports (if they're looking to pick it up).

Nice example. I think this would justify it.

>You don't really need both GameObject.halo and Scene.halos, though, right?

Not that it really matters right now (because I'll be changing the suggestion again, haha), but `Scene.halos` would be an unexposed public field to/from which GameObjects are added/removed with the method `GameObject.halo(boolean)`. This to prevent from iterating over *all* objects for every viewport for every scene in `Bdx.main()`. Then it would be iterating over just the objects in the `Scene.halos` list. That would be significant for performance, I think.

I think we should do something similar with `GameObject.onRender()`, since it's outside `Scene.runObjectLogic()`. We could do this in [Bdx.main()](https://github.com/GoranM/bdx/pull/647/files#diff-ce8d289cfdf75ba8036d025405a05057R279)
```java
			...
			for (Viewport viewport : scene.viewports){
				// run object logic for onRender() here
				for (GameObject g : scene.onRenderObjects){
					g.onRender();
				}
			...
```
Which would probably require `GameObject.onRenderActive(boolean)` method to first add/remove to/from that `Scene.onRenderObjects` list. Otherwise, wouldn't it be too expensive?

**Comment by SolarLune** [comment]
> Which would probably require GameObject.onRenderActive(boolean) method to first add/remove to/from that Scene.onRenderObjects list. Otherwise, wouldn't it be too expensive?

It probably wouldn't be too bad, but this kinda stuff can add up (running `main()` on _every_ GameObject, running `onRender()` on _every_ GameObject and each Component, and so on). In any case, you could probably get away with just having a list in Scene that GameObjects can add themselves to. You probably would never really want to remove it from that list, and BDX can remove invalid GameObjects from the list before it runs their `onRender()` functions.

**Comment by rafcolson** [comment]
Okay, I'll first wait on what @GoranM has to say about this.

**Comment by SolarLune** [comment]
> Edit: Removing could become necessary when switching from a two-player-screen to a single-player-screen.

It's still not that big of a deal; of the previous use case, how many interactable objects might be in a game scene? Maybe 20 or 30, max? I don't think it'd really weigh down the CPU much. You'd be able to remove a GameObject just by removing it from the `Scene.onRender()` list.

**Comment by rafcolson** [comment]
>of the previous use case, how many interactable objects might be in a game scene? Maybe 20 or 30, max?

With about 30 objects per viewport, that would give about 30 X 4, with 3 overlay scenes, and just one of those with 2 viewports.

>You'd be able to remove a GameObject just by removing it from the Scene.onRender() list.

Maybe I don't understand what you are trying to say. If you mean to add all objects to a `Scene.onRenderObjects` beforehand, so you could remove any of those which doesn't need it, than I see your point.

However, thinking about this, we wouldn't be able to specify the viewport (or camera) within that `onRender()` method. We could only do:
```java
g.orientation(viewports.get("myViewport").camera().orientation());
```
So I'm not changing the title yet...

**Comment by rafcolson** [comment]
I think it can work without having to remove from a `Scene.onRenderObjects` list.

If in `GameObject` we would have `onRender()` by default changing the "active" variable:
```java
...
public boolean onRenderActive = true; // allows this object to be added to Scene.onRenderObjects
...
	public void onRender(){
		onRenderActive = false; // disallows this object to be added to Scene.onRenderObjects
	}
...
```
Then in `Scene` we could this:
```java
	...
	public Viewport onRenderViewport;
	public ArrayList<GameObject> onRenderObjects =  new ArrayList<GameObject>();
	...
	public void update(){
			...
			onRenderViewport = viewports.get(0); // allows running onRender for 1st viewport
			runObjectLogic();
			...
```
`Scene.runObjectLogic()`:
```java
			...
			g.main();
			g.onRender();
			if (g.onRenderActive){
				onRenderObjects.add(g);
			}
			...
```
`Bdx.main()`
```java
			...
			for (Viewport viewport : scene.viewports){
				if (!scene.onRenderObjects.isEmpty()){
					if (onRenderViewport != viewport){ // disallows running onRender for 1st vp
						onRenderViewport = viewport;
						for (GameObject g : scene.onRenderObjects){
							g.onRender();
						}
					}
				}
				...
```

**Comment by SolarLune** [comment]
> But how would you know which are interacting and which not?

I was only counting the objects that are in the onRender list. So only the "interactable" objects (in the previous example) would be in that list, basically. There could be others, too, but it wouldn't be that many objects.

> Maybe I don't understand what you are trying to say. If you mean to add all objects to a Scene.onRenderObjects beforehand, so you could remove any of those which doesn't need it, than I see your point.

Yeah, that's what I meant.

> However, thinking about this, we wouldn't be able to specify the viewport (or camera) within that onRender() method. We could only do:

Just have the `onRender()` method take the Viewport the object is being rendered in and pass it when you call the function for each GameObject.

> I think it can work without having to remove from a Scene.onRenderObjects list.

I thought of something like this, but it wouldn't work effectively because accidentally calling `super.onRender()` in `onRender()` will cause it to not work.

**Comment by rafcolson** [comment]
>Just have the `onRender()` method take the Viewport the object is being rendered in and pass it when you call the function for each GameObject.

I'm not following. How would you be able to pass that specific Viewport if you can only specify by name or index?

>I thought of something like this, but it wouldn't work effectively because accidentally calling super.onRender() in onRender() will cause it to not work.

With `init()`, `main()` and `onEnd()` are supposed to be overridden without any `super` calls. The API doesn't mention these methods are actually "blank slates to fill in", but if it would for those three methods along with `onRender()` I don't think this should be a problem. But if you guys think otherwise I then would prefer the first approach, of keeping an empty `Scene.onRenderObjects` list, and add to it. However the mistake could be made to add objects to it in `GameObject.main()`, which would probably crash BDX. For which in this case a method `GameObjects.onRenderActive(boolean)` would be necessary to avoid this.

**Comment by SolarLune** [comment]
> I'm not following. How would you be able to pass that specific Viewport if you can only specify by name or index?

Just pass the viewport when you call the method.

```java

for (Viewport viewport : scene.viewports) {
    for (GameObject g : scene.onRenderObjects) {
        g.onRender(viewport);
    }
}

```

> However the mistake could be made to add objects to it in GameObject.main(), which would probably crash BDX. 

Nah, that shouldn't happen, to my knowledge. Only if you're looping through that list when you modify it (which wouldn't happen; the list is modified in the logic loop, and then that list is checked to call the `onRender()` methods later, right before the objects are drawn).

**Comment by rafcolson** [comment]
>the list is modified in the logic loop

Yes, that's right. That would be a point to check if an object has already been added. And if so we don't add it.

>```java
for (Viewport viewport : scene.viewports) {
    for (GameObject g : scene.onRenderObjects) {
        g.onRender(viewport);
    }
}
```

I'm sorry but I still don't understand. Let's say I would like to orient an object to face the camera, how would the `onRender()` method look like?
```java
@Override
public void onRender(){
	orientation(howToSpecifyThisViewport.orientation()); //?
}
```

**Comment by SolarLune** [comment]
> Yes, that's right. That would be a point to check if an object has already been added. And if so we don't add it.

I don't think there's a real need for that; the developer can make sure they only add it once.

> I'm sorry but I still don't understand. Let's say I would like to orient an object to face the camera, how would the onRender() method look like?

Like this:

```java
-- GameObject.java --

public void onRender(Viewport viewport) {}

-- Crate.java --

public void onRender(Viewport viewport) {

    System.out.println("I'm being rendered by viewport " + viewport);

}
```

**Comment by rafcolson** [comment]
Oh okay. Didn't think about that possibility. Much better, of course.

**Comment by SolarLune** [comment]
Yeah, I mean, there's not really a clean way to implement this, unfortunately. It'd be nice if there was a way to do this without an additional list, but I don't think there is. I think it'd be useful to have as a feature, though.

Either we have this list and loop through it, or we have a list specifically for Halo and loop through that, so we might as well get the most bang for our buck, I think.

Guess we'll see what @GoranM's input is.

**Comment by GoranM** [comment]
> Yeah, I mean, there's not really a clean way to implement this, unfortunately.

If we didn't have viewports, we wouldn't have to bother with any of this.

I don't remember if I said it at some point, when the idea of implementing viewports was suggested initially, but "split-screen" seems like the only legitimate use case, and I don't know anyone who actually wants/needs to play in that mode.

It was a feature that had utility on early consoles, before they had decent online networks, but today, multiplayer games are played almost exclusively over the network, where each player has their own machine, and where this is preferred.

... I know you and raf both put significant time and effort into it, but at this point, and considering all the additional complexity (some of which I failed to predict, under the assumption that we could simply wrap the LibGDX viewport system in a straightforward way), I think it's time to re-evaluate whether or not viewports are actually worth the total complexity cost.

It's probably best if we have that discussion in the viewports PR, so if you want to respond to this, please do it there.

Back on topic:

SolarLune's approach seems reasonable to me.

**Comment by rafcolson** [comment]
This could be reopened or revisited if/when multiple viewports are in the picture again.
