### ISSUE TITLE
Sort Transparent Objects Back-To-Front

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#70]
Hey, there. Transparent objects usually render incorrectly next to other transparent objects, and I think part of the problem might be that they're being rendered as opaque objects would be (front to back) to take advantage of depth culling (if LibGDX handles depth culling). I think this could be improved by sorting transparent objects back-to-front instead. I'm not sure if I already brought this up on the BlenderArtists discussion thread or not, but I figure a formal suggestion thread would be useful.

So, looking at the normal render process makes it seem like sorting transparent objects separately should be relatively easy. For now, an easy way to do this would be to add objects to a "transparentObjects" list on "conversion" from Blender mesh and material data to BDX data. So basically, this would happen just once; BDX would add the object to a "transparentObjects" list when it converts the materials, and check this list when it comes to rendering the bojects. The good thing about this is that it's automatic. The bad thing is that it wouldn't cover changes to materials (though that would be easy to add in if we add a function to change the material's transparency in some way).

Another easy (probably better) method would be to have a "transparentSorting" or "renderBackToFront" variable / getter and setter in the objects themselves. You can use these to instruct BDX to sort that object in the reverse order. Using this function would swap the object between a normal "opaqueObjects" list and an additional "transparentObjects" list. BDX would sort and render the opaque objects list normally, and would reverse the transparent one and draw that one afterward. The up-side would be that this would be easiest to implement, I think, and it'd allow for the most control. The user would just turn on transparent sorting on the object that needs this mechanic, regardless of if it's actually transparent, additive blended, or whatever. The downside is that it wouldn't be automatic.

So, any thoughts?

**Comment by GoranM** [comment]
LibGDX already sorts objects, and (as far as I can tell) does so exclusively to support alpha blending. However, the sorting algorithm is of the simple "distance from camera" variety, so if you have object A placed in front of object B, but the origin of B is closer to the camera than the origin of A, you will get rendering anomalies (when objects with alpha are involved).

This is something that would need to be fixed in LibGDX - it's not a BDX issue.

**Comment by SolarLune** [comment]
I looked around online and it seems that while you used to have to sort objects yourself, it was deprecated in favor of just adding an alpha test attribute to the materials of objects that you want to test for alpha transparency. This makes things a lot simpler; it looks like just using:

```
sprite.modelInstance.materials.first().set(FloatAttribute.createAlphaTest(0));
```

is enough to have correct transparency, both for "Clip Alpha" like textures, with all-or-nothing transparency, as well as for partially transparent objects. Hurrah! Pictured is the results of the alpha test attribute existing on the material and not. As you can see on the left, the character sprite cuts into the tree's sprite. On the right, the alpha test has been enabled, and it's shown correctly. I think that whatever the value in the alpha test creation function, the alpha value below that is set to completely invisible.

![cutandnot](https://cloud.githubusercontent.com/assets/4733521/5796517/211c5eda-9f5e-11e4-8f55-7e3e0c0d87e0.png)

So perhaps this could be added on transparent materials to ensure the objects are sorted correctly?

**Comment by rafcolson** [comment]
I'm all for it.

**Comment by SolarLune** [comment]
No, this isn't a camera issue; it's because of the lack of an alpha test attribute that the transparent (fully or partially) sprites can "clip into" each other.

**Comment by rafcolson** [comment]
> Perhaps a toggle-able option would be best to ensure that transparent objects that you don't care much about (like particles) don't suck up GPU time.

I agree. It could be added to the Material tab.

Edit: Oops. I mistakenly edited your comment. Thank God for Ctrl+Z.

**Comment by SolarLune** [comment]
If it's added to the actual Blender material tab, then I guess that would mean that we'd need to add a BDX render engine mode (like Blender Game)? I think that would be a good idea and something we'd end up doing anyway at some point, since not every feature of the BGE would be necessary for BDX (i.e. no need for Clip Alpha, Alpha Blend, Alpha Sort, and Additive alpha blend modes; it could just be Alpha and Alpha Sort). Otherwise, I suppose we would be using the Alpha blend mode drop-down, which has those options we'd just mentioned, and have Alpha Sort add the alpha test float attribute.

As a side-note, it's kinda surprising how little information on 3D for LibGDX there is; I can't really find a straight answer of exactly what Float Attributes do for materials, haha.

**Comment by GoranM** [comment]
Well, looking in the [shader](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/g3d/shaders/default.fragment.glsl#L181), it's an additional compare, which is not that expensive on its own, but the "if" implies a branch (between two code paths), and that may have costs that are less than trivial.

That said, I don't think we should prioritize performance at this point; if adding this attribute ([to relevant materials](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L138)) produces desired behavior, I think we should include it.

I take it you wouldn't mind adding that line yourself, SolarLune?

If you make a PR, I will merge it.

> As a side-note, it's kinda surprising how little information on 3D for LibGDX there is

The 3D API is a fairly recent addition, but even so, it seems pretty clear that they prioritized features over documentation.

We should learn from their mistakes.

Relating to "BDX render engine mode", various panels, etc: The Blender API is not as convenient as it appears, and a lot of things that should be easy are actually quite complicated, or even impossible.

In general, I think it's far easier to just use what already exists in Blender (for the most part), then to develop an entire "BDX mode".

PS:

In that last issue, you mentioned that changing near clip values was required to make things render properly - Could you elaborate on that, or give us some examples that show the differences (if it's not too bothersome)?

I don't know why default near clip of 0.1 would cause problems, so I'd like to study those cases a bit.

**Comment by SolarLune** [comment]
No, I don't mind. I'll make a PR for this issue's alpha material change.
_____

I'll be happy to elaborate on the other issue as best as I can.

Changing the end clip value of the camera pretty much never lends to inaccuracies, no matter what, even with ridiculously high values (5 million or something like that).

Values of 0.1 and below lend to inaccuracies and disappearing polygons quickly (showing z-fighting, I guess). Interestingly, it looks like the AlphaSort Float Attribute helps this problem for transparent objects, so the problem "only" manifests on objects that are opaque and close together. Changing the locations of the centers of the objects doesn't seem to help; it seems to depend on the polygon's positioning and the near frustum for some reason. Maybe it doesn't have enough precision or something? I dunno.

Attached is an image showing the issue on 3D objects this time. Not sure if it'll show up as a GIF animation, but in the animation is different values for the starting clip value of the camera. Note that a clip value of 0.2 looked pretty good, but still a bit "under cutting" when it comes to the bottom polygons of the button's mesh. 0.5 is more than necessary, but illustrates the "correct" look. Blender never shows any problem (though it can get inaccurate a bit), no matter the clip rate (I dunno, it's probably running in software or something).

![clippingbuttons](https://cloud.githubusercontent.com/assets/4733521/5807459/6eedd15a-9fd8-11e4-861a-ed344a810fa0.gif)

The blend file in issue #69 (while lacking textures and other things) illustrates the same issue as well.

**Comment by GoranM** [comment]
> The blend file in issue #69 (while lacking textures and other things) illustrates the same issue as well.

This is what I see in blender:

![b.png](http://i.imgur.com/mWj3Axe.png)

This is what I see in BDX:

![bdx.png](http://i.imgur.com/8iz5G0h.png)

If you're sure the .blend is proper, then I guess it's an OS specific bug in libgdx.

**Comment by SolarLune** [comment]
Yeah, the blend file does show the issue, and it is clearly visible; texturing doesn't matter, as it's about the opaque objects themselves. Anyway, I'm fine with it being, apparently, an OS or graphics card specific bug and appending that information to the correct closed issue.

I'll close this issue as well.
