### ISSUE TITLE
Discussion: Viewport -> utilize LibGDX viewports or not?

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#701]
[LibGDX Issue 4175: Suggestion: don't ignore screenX and screenY while updating Viewports](https://github.com/libgdx/libgdx/issues/4175)

[badlogicgames forum topic: Viewport.update() ignores screenX and screenY](http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=22932)

Continued from #469.

There are issues that come with utilizing LibGDX viewports for implementing a single viewport (per scene) in BDX. This would also apply for implementing multiple viewports.

With [ExtendViewport](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/ExtendViewport.java#L87), [FitViewport](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/ScalingViewport.java#L59) (Letterboxed) and [ScreenViewport](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/ScreenViewport.java#L40) the `update()` function sets the position of the viewport at the center or at the left bottom corner of the display screen. This happens while calling [`setScreenBounds()`](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java#L206), which sets `screenX`, `screenY`, `screenWidth` and `screenHeight`.

But, this will not take into account the actual position of the viewport relative to the display size. This can be solved by setting the position again after calling `update()`, but `update()` is also calling `apply()` (which sets the gl viewport). So we also have to call `apply()` again, after setting the position with `screenX()` and `screenY()`. This was to be expected as it is mentioned that `screenX()` and `screenY()` are typically set by the `update()` function, which you can read [here](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java#L162) and [here](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/viewport/Viewport.java#L171). This also forces us to store the `screenX` and `screenY` positions before calling `update()` in order to return to these values again.

With LETTERBOX the viewport won't update correctly, so we have to update `screenX`, `screenY`, `screenWidth` and `screenHeight`. With SCREEN we have to tweak with `setUnitsPerPixel()` so it updates correctly.

We're also forced to store the normalized position and size for updating filters (`Bdx.main()`) and for updating the `x`, `y`, `w` and `h` values in the `update()` function itself.

For all of these reasons I would like to suggest not to utilize LibGDX viewports. If you compare the commit utilizing LibGDX with the commit without utilizing LibGDX, you'll find that there's virtually nothing LibGDX viewport have to offer, except for causing these issues.

For your comparison I'll be committing referencing to this issue, the following steps:
- Viewports without utilizing LibGDX viewports
- Viewports with utilizing LibGDX viewports, presenting the issues
- Viewports with utilizing LibGDX viewports, fixing those issues
- Viewports without utilizing LibGDX viewports (for comparison)

Edit: Please ignore line `import com.badlogic.gdx.graphics.glutils.ShapeRenderer;` in LibGDX commits. I forgot to remove this line.

Edit: Also notice that with EXTEND the viewport will behave differently (as LETTERBOX) when utilizing LibGDX; the view will be cropped horizontally with PERSPECTIVE camera. Without utilizing LibGDX, the viewport will not be cropped but extend horizontally or vertically.

**Comment by rafcolson** [comment]
So, please let me know what you think.

**Comment by GoranM** [comment]
> With ExtendViewport, FitViewport (Letterboxed) and ScreenViewport the update() function sets the position of the viewport at the center or at the left bottom corner of the display screen. This happens while calling setScreenBounds(), which sets screenX, screenY, screenWidth and screenHeight.
>
> But, this will not take into account the actual position of the viewport relative to the display size.
> ...
> With LETTERBOX the viewport won't update correctly

So these are bugs, right? Or you think they're bugs?

If so, I think it would be best to make an issue in the libgdx tracker.

**Comment by rafcolson** [comment]
>So these are bugs, right? Or you think they're bugs?

I wouldn't describe these as bugs, because technically they are not, for the reason that the LibGDX API mentions that `screenX` and `screenY` are typically set by the `update()` function. Maybe there is a reason why it was designed that way, so I think we only could ask some questions about it, and maybe make the suggestion to alter the design so it would fit our purposes better.

**Comment by rafcolson** [comment]
@GoranM Until LibGDX viewports are altered, if granted, could we go with not utilizing LibGDX viewports for this this single viewport commit, for now? We could always implement it later.

**Comment by SolarLune** [comment]
Yeah, I kinda think the same. The "bugs" may not be fixed at all, or might be fixed some time in the future. Even then, we'd have to wait for a new release of LibGDX. We could always modify the viewports to utilize LibGDX's if/when they're available, anyway, assuming we keep the same API for our Viewport class.

**Comment by GoranM** [comment]
> Maybe there is a reason why it was designed that way

That's what I was thinking, because it's hard to believe that viewports could be so broken, for so long, without anyone noticing.

> could we go with not utilizing LibGDX viewports for this this single viewport commit, for now?

I would like to hear back from someone in the libgdx community before doing anything else.

To speed that up, it might be a good idea to actually create an issue, as I advised before, instead of making a post in an old issue. They also have a support forum on their website, so posting there could also be helpful.

Irrespective of what we ultimately choose to do, the PR will need to be simpler: For a single viewport, I don't think there's a need to break the API, in any way.

**Comment by rafcolson** [comment]
> I don't think there's a need to break the API, in any way.

Okay, but I'm assuming that you aren't talking about methods or fields that are being added to the API (such as `Pointer.insideArea()`, `Bdx.display.changed`, `Bdx.display.width()`, ...). I was planning to return to `Pointer.raySource()` and `Pointer.rayDirection()`, but there's no need for `Pointer.clipCoords()`, is there?

**Comment by rafcolson** [comment]
API changes:

# API Viewport

A viewport represents a window for the scene's camera. Its size and position are relative to the display screen.
___

<a name="type-enum" href="#type-enum">#</a> **Type : enum**

The Type enum establishes the kind of viewport the Viewport object is, either `LETTERBOX`, `EXTEND`, `SCALE` or `SCREEN`. You can access it publicly anywhere you import the Viewport class.

`SCALE` will stretch the view to fill the display screen without preserving the aspect ratio. `LETTERBOX` will stretch the view while preserving the aspect ratio by adding bars to fill the display screen. And `EXTEND` will stretch the view while preserving the aspect ratio by extending the width or height to fill the display screen. `SCREEN` will only stretch when manually changing the resolution or size. 
___

<a name="type-getter" href="#type-getter">#</a> **type**() - Type

Returns the type of this viewport.

<a name="type-setter" href="#type-setter">#</a> **type**(Type type)

Sets the type of this viewport.

<a name="scene-getter" href="#scene-getter">#</a> **scene**() - Scene

Returns the scene to which the viewport belongs.

<a name="camera-getter" href="#camera-getter">#</a> **camera**() - Camera

Returns the camera for this viewport. Calls `scene().camera()`.

<a name="orientation-getter" href="#orientation-getter">#</a> **orientation**() - Matrix3f

Returns the orientation of this viewport directly. Calls `camera().orientation()`.

<a name="resolution-getter" href="#resolution-getter">#</a> **resolution**() - Vector2f

Returns the resolution for this viewport. Calls `camera().resolution()`.

<a name="resolution-setter-Vector2f" href="#resolution-setter-Vector2f">#</a> **resolution**(Vector2f resolution)

<a name="resolution-setter-floats" href="#resolution-setter-floats">#</a> **resolution**(float width, float height)

Sets the resolution for this viewport. Calls `camera().resolution(float width, float height)`. Changing this vector may also change the aspect ratio. With viewports of type `SCREEN`, this value can be altered to get 'pixel-perfect' results. [Link to Wiki here].

<a name="size-getter" href="#size-getter">#</a> **size**() - Vector2f

Returns the size of this viewport.

<a name="size-setter-Vector2f" href="#size-setter-Vector2f">#</a> **size**(Vector2f size)

<a name="size-setter-floats" href="#size-setter-floats">#</a> **size**(float width, float height)

Sets the size of this viewport.

<a name="sizeNormalized-getter" href="#sizeNormalized-getter">#</a> **sizeNormalized**() - Vector2f

Returns the normalized size of this viewport.

<a name="sizeNormalized-setter-Vector2f" href="#sizeNormalized-setter-Vector2f">#</a> **sizeNormalized**(Vector2f sizeNormalized)

<a name="sizeNormalized-setter-floats" href="#sizeNormalized-setter-floats">#</a> **sizeNormalized**(float width, float height)

Sets the normalized size of this viewport.

<a name="position-getter" href="#position-getter">#</a> **position**() - Vector2f

Returns the position of this viewport.

<a name="position-setter-Vector2f" href="#position-setter-Vector2f">#</a> **position**(Vector2f position)

<a name="position-setter-floats" href="#position-setter-floats">#</a> **position**(float x, float y)

Sets the position of this viewport.

<a name="positionNormalized-getter" href="#positionNormalized-getter">#</a> **positionNormalized**() - Vector2f

Returns the normalized position of this viewport.

<a name="positionNormalized-setter-Vector2f" href="#positionNormalized-setter-Vector2f">#</a> **positionNormalized**(Vector2f position)

<a name="positionNormalized-setter-floats" href="#positionNormalized-setter-floats">#</a> **positionNormalized**(float x, float y)

Sets the normalized position of this viewport.

<a name="screenPosition" href="#screenPosition">#</a> **screenPosition**(Vector3f worldPosition) - Vector2f

Returns the screen position of the specified world position.

<a name="screenPositionNormalized" href="#screenPositionNormalized">#</a> **screenPositionNormalized**(Vector3f worldPosition) - Vector2f

Returns the normalized screen position of the specified world position.

<a name="rayData" href="#rayData">#</a> **rayData**(Vector2f screenPosition) - Vector3f[]

Returns the source and direction of a ray at the specified screen position.

<a name="rayDataNormalized" href="#rayDataNormalized">#</a> **rayDataNormalized**(Vector2f screenPosition) - Vector3f[]

Returns the world coordinates of the specified normalized screen position.

___

# API Display

<a name="changed" href="#changed">#</a> **changed** - boolean

Returns whether the display changed since the last logic tick.
___

<a name="width-getter" href="#width-getter">#</a> **width**() - int

Returns the width of the game window.

<a name="height-getter" href="#height-getter">#</a> **height**() - int

Returns the height of the game window.

<a name="width-setter" href="#width-setter">#</a> **width**(float width)

Sets the width of the game window.

<a name="height-setter" href="#height-setter">#</a> **height**(float height)

Sets the height of the game window.
...
<a name="size-floats" href="#size-floats">#</a> **size**(float width, float height)
...
___

# API Scene
...
<a name="viewport" href="#viewport">#</a> **viewport** - Viewport

Returns the scene's viewport.
...
___

# API Camera
...
<a name="resolution-getter" href="#resolution-getter">#</a> **resolution**() - Vector2f

Returns the resolution of this camera. Equivalent to the Blender resolution (in the Render tab).

<a name="resolution-setter-Vector2f" href="#resolution-setter-Vector2f">#</a> **resolution**(Vector2f resolution)

<a name="resolution-setter-floats" href="#resolution-setter-floats">#</a> **resolution**(float width, float height)

Sets the resolution of this camera. This is also the actual size of the texture rendered when rendering the camera's output to a texture. Changing this value may also change the aspect ratio.

<a name="width" href="#width">#</a> **width**() - float

Returns the width. Typically set by `Viewport.update()` when the camera is also the scene's camera.

<a name="height" href="#height">#</a> **height**() - float

Returns the height. Typically set by `Viewport.update()` when the camera is also the scene's camera.
...

*`screenPosition()` moved to `Viewport` because the screen position is relative to the `x`, `y`, `w` and `h` of the viewport.*
___

# API Pointer
...
<a name="id" href="#id">#</a> **id**() - int

Returns the id.

<a name="insideScreenArea" href="#insideScreenArea">#</a> **insideScreenArea**(Vector2f min, Vector2f max) - boolean

Returns whether the position of the pointer is inside the specified area of the display screen.

<a name="rayData" href="#rayData">#</a> **rayData**() - Vector3f[]

Returns the source and direction of a ray at the pointer's screen position.
...

*to be removed: `clipCoords()`*

**Comment by GoranM** [comment]
It would be helpful if you could provide a link to the issue you made in the libgdx tracker, so I (and anyone else who is interested) can keep track.

Also, please try to edit your old posts as little as possible (ideally, not at all) ... I mean, it's ok to make small changes, but anything more significant (like removing links) has a very strong potential to be confusing.

> As mentioned in the LibGDX Issue Tracker (as well as indirectly in the LibGDX API) the current behavior is intended.

But, based on your experience, the current behavior is incorrect, so how can they use a system that doesn't actually work?

It all just seems so unlikely, but I hope someone who knows will help us clear it up soon.

> but there's no need for Pointer.clipCoords(), is there?

It's part of the public API, and, as far as I can tell, there's no need to break that. Same with `Camera.screenPosition()`.

We can discuss whether or not it should be removed at some later time, but for now, the goal is to not break the API.

Also, for the stuff that you're adding, make sure that it's really necessary: The new methods on Pointer don't seem to be, and I didn't completely review everything else (because I'm not sure if we're even going to use it), but it's something that should be considered carefully.

**Comment by rafcolson** [comment]
>It would be helpful if you could provide a link to the issue you made in the libgdx tracker, so I (and anyone else who is interested) can keep track.

Can't anyone see that I referenced this LibGDX Issue?

>anything more significant (like removing links) has a very strong potential to be confusing.

Did I remove a link?

>But, based on your experience, the current behavior is incorrect, so how can they use a system that doesn't actually work?

I see your point.

>We can discuss whether or not it should be removed at some later time, but for now, the goal is to not break the API.

Okay.

>Also, for the stuff that you're adding, make sure that it's really necessary: The new methods on Pointer don't seem to be

Okay.

**Comment by rafcolson** [comment]
We did get some response on the forum. In conclusion, the `setScreenX()` and `setScreenY()` setters may as well be `protected` methods, if it weren't for all the people who have been using these methods to position LibGDX Viewports in the aforementioned rather hacky way. We could wrap all LibGDX Viewports (as I have been doing in the example commit of this issue) or go ahead without utilizing those. It's still my opinion that wrapping LibGDX Viewports would be more complicated than simply having our own class, which would gain the necessary clarity and oversight of viewport mechanics.

**Comment by GoranM** [comment]
> Can't anyone see that I referenced this LibGDX Issue?

Yeah, but it can be easy to miss, especially when it's in-line with your own commits.

> Did I remove a link?

I can't really remember if I clicked on the github generated reference, or a link in your post ... You would know for sure, but you can see how it could be confusing for someone else.

> We did get some response on the forum.

Ok. Let's give a bit more time to see if someone else chimes in.

In the meantime, can you explain why resolution has to be in floats? I mean, resolution implies a pixel measurement, doesn't it?

**Comment by rafcolson** [comment]
>Yeah, but it can be easy to miss, especially when it's in-line with your own commits.

I agree. I was planning on making a link in the first post, but at the time it didn't seem as easy to miss.

>In the meantime, can you explain why resolution has to be in floats? I mean, resolution implies a pixel measurement, doesn't it?

I'll change the setter to `resolution(int width, int height)`, but I guess we can keep it as a Vector2f. Or would you prefer two int fields `resolutionX` and `resolutionY`?

**Comment by GoranM** [comment]
> I guess we can keep it as a Vector2f

Are talking about the getter?

It's not really a question of what we can do, but more of what makes sense. I don't think that using floats for pixel-based measurements makes a lot of sense, does it?

At the moment, I think it would be best to just return an `int[]`.

**Comment by rafcolson** [comment]
But then we should also make Bdx.display and camera and viewport sizes an int array?

**Comment by GoranM** [comment]
I'm actually ok with functions that return floats. What really bothers me are functions that take pixel-based measurements as floats, because that brings up translation questions: Internally, does it just do a pure int conversion that truncates the decimals, or does it round generally, or would it always round up?

In addition to being more sensible, integers avoid those questions.

Generally, I don't like breaking the API, and I don't want to do that for the initial viewport PR, but eventually ... I think it might be worth it.

> It seems to me that it would be easier to just stick with Vector2f, especially because we could utilize its mul(), div() and plus() methods for easy calculating.

Ideally, the gwt-vecmath library would have a Vector2i that we could use in these cases. Maybe we can still make that, based on the existing implementation of Vector2f?

Anyway, if you want to use floats, I guess it's fine for now, because it's not a big deal to change later.

It's up to you.

**Comment by rafcolson** [comment]
>Ideally, the gwt-vecmath library would have a Vector2i that we could use in these cases. Maybe we can still make that, based on the existing implementation of Vector2f?

Sounds like a good idea.

**Comment by rafcolson** [comment]
@GoranM 

>Ok. Let's give a bit more time to see if someone else chimes in.

Even so, I don't expect anyone to come up with something new on the horizon. The matter is pretty clear, at least from my perspective.

In any case, it's been a week now. So could I proceed with a PR?

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR merged. Thanks for all you help, guys!
