### ISSUE TITLE
Rename base .game blend file to Project Name

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#71]
Hey, there. I think it'd be a nice usability feature to rename the default "game.blend" file to the project name you enter in the project creation dialog. If for nothing else, it'd be better when it comes to browsing your recent project file list in Blender since every BDX project uses "game.blend" as its file name.

An alternative would be to just convert all scenes from all blend files in the Blender directory for use, so that we could rename "game.blend" to whatever we wanted. Of course, you'd have to think about what should happen in the case of name conflicts from similarly named scenes in two different blend files. 

You could also just use the current blend file as the "global project blend file"; any other scenes would be deleted or overwritten as necessary.

**Comment by rafcolson** [comment]
I think that would be a good idea, for the reason mentioned.

**Comment by GoranM** [comment]
After the project is created, you can rename game.blend to whatever you wish.

I don't think there's anything in the system that requires that particular name.

**Comment by rafcolson** [comment]
> I don't think there's anything in the system that requires that particular name.

Oh, I didn't realize. Sounds like it wouldn't be necessary then.

**Comment by SolarLune** [comment]
Perfect. I thought that it had to be named "game.blend", haha. 

Thanks for the blend, @rafcolson. A BDX template blend file might be nice to have, and those additional panels and editors would be nice, indeed.

Anyway, issue's closed!
