### ISSUE TITLE
Suggestion: Random.choice(int[])

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#710]
Hey, there. 

It might be a nice thing to add an int[] version of Random.choice so that you don't have to construct a new ArrayList just to choose from a set of integers. That'd turn this kinda long and unnecessary:

```java
ArrayList<Integer> choices = new ArrayList<Integer>();
choices.add(0);
choices.add(1);
choices.add(2);
choices.add(3);
spriteAnim.frame(Random.choice(choices));
```

into this simpler:

```java
spriteAnim.frame(Random.choice(new int[]{0, 1, 2, 3}));
```

EDIT: Added better solution below.

**Comment by rafcolson** [comment]
Yes, that's even better.

**Comment by SolarLune** [comment]
Never mind, we could just have a version that has a variable amount of arguments with the generic type using the "..." notation. Then we can provide the objects to choose from directly:

```java
spriteAnim.frame(Random.choice(0, 1, 2, 3));
```

This works with arrays of types as well, but not with primitive data types, unfortunately:

```java
int[] frames = new int[]{0, 1, 0, 0, 0, 1, 2, 1}; // Won't work
Integer[] frames = new Integer[]{0, 1, 0, 0, 0, 1, 2, 1};  // Will work

spriteAnim.frame(Random.choice(frames));
```

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
Cool, PR submitted.

**Comment by SolarLune** [comment]
Thanks, this got merged in. Works pretty well; nice and efficient.

PR closed!
