### ISSUE TITLE
Suggestion: SpriteAnim.active Shorthand Function

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#714]
Hey, there. 

I think an `active()` function that takes the name of an animation would be nice shorthand to turn this: `if (spriteAnim.active.name.equals("Blah"))` into this: `if (spriteAnim.active("Blah"))`.

**Comment by rafcolson** [comment]
```java
if (spriteAnim.active("Blah"))
```
I'm not sure. It seems a bit that the method implies that it's a setter. I don't think that the current method is too long. But that's my opinion.

**Comment by SolarLune** [comment]
> I'm not sure. It seems a bit that the method implies that it's a setter.

What about `SpriteAnim.isActive()`? I don't think I really like it because I don't think many other boolean functions in BDX's codebase have `if` in front, but it's an option.

> I don't think that the current method is too long. But that's my opinion.

Eh, it kinda feels long to me because I'm checking for "which sprite is currently playing" multiple times in a short span of time. It'd be fine to not have, though; it's not that much stuff to type out.

**Comment by SolarLune** [comment]
Ah, I already made an issue for this, #599, haha. Guess that solves that, then. I'll close this.

**Comment by rafcolson** [comment]
>I'm checking for "which sprite is currently playing" multiple times

I understand. I guess it's a matter of preferences.

>What about `SpriteAnim.isActive()` ?

The name is better, but still I would just choose a shorter alias for "SpriteAnim".
```java
sa.active.name.equals("Blah");
// or
spriteAnim.isActive("Blah");
```
Edit: Oh, I see you closed this.
