### ISSUE TITLE
Suggestion: GameObject.distance() Shorthand Function.

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#715]
Hey, there. Similar to the last suggestion, I think a nice shorthand function for getting the distance between objects could be `GameObject.distance()`. 

It'd turn this:
```java
if (position().minus(other.position()).length() < 4) {
}
```
into this:
```java
if (distance(other) < 4) {
}
```

**Comment by rafcolson** [comment]
Great! I would personally like `distance(Vector3f)` more. Or maybe we could have both?

**Comment by SolarLune** [comment]
Yeah, actually, I think both would be good.

**Comment by GoranM** [comment]
I think having a `vecTo()` would shorten the expression to a reasonable length, while being more versatile.

**Comment by SolarLune** [comment]
Good idea. PR submitted.

**Comment by SolarLune** [comment]
PR Merged. I'll close this now. Thanks!
