### ISSUE TITLE
API: ambientLight(float r, float g, float b)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#722]
Should `ambientLight(float r, float g, float b)` be removed from the API or should this function be added to `Scene`? Currently it doesn't exist.

**Comment by SolarLune** [comment]
All of the other color-handling functions require a Color object currently, so I guess it'd make sense to remove it from the API. 

Perhaps we should reconsider adding an RGBA version of each color function back to BDX. I kind of like having the RGBA versions for their ease of use, but the ability to tweak each color using the Color class like we have currently is also really useful.

**Comment by rafcolson** [comment]
>Perhaps we should reconsider adding an RGBA version of each color function back to BDX. I kind of like having the RGBA versions for their ease of use, but the ability to tweak each color using the Color class like we have currently is also really useful.

Okay. I suppose that's a suggestion for a new issue. I'll keep this open until it's decided whether or not to add RGB(A) versions for each color function. (as a reminder).

**Comment by GoranM** [comment]
I'm fine with whatever you guys decide.

**Comment by rafcolson** [comment]
>I'm fine with whatever you guys decide.

@SolarLune I'm fine with whatever you decide, so feel free to add RGB(A) versions for each color function.  I suppose this issue can be closed then.
