### ISSUE TITLE
Blender Memory Slowdown

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#723]
Hey, there. 

So I'm experiencing a slow-down in Blender as I run my BDX project; the time it takes to do memory-related operations like closing the blend file or undoing rises with time, until it starts taking quite a few seconds. 

I'm guessing it's due to the rise in memory allocation. Notice that when you run a BDX project, the memory readout in the header in Blender rises a little bit. For a small project, it's basically nothing, but for a moderately sized one, the usage rises by several megabytes at a time and can fairly quickly become a problem. 

I believe we might be copying some resources in the blend file when we export a run a project, which might be part of (or all of?) the issue.

Anybody got any ideas of where to look regarding this?

**Comment by GoranM** [comment]
We're not creating any additional blender data, other than the profiler scene, which is removed soon after it's created.

The export process does create a lot of temporary python objects (like any other python function that does significant data transformation/manipulation work), but those objects should be garbage collected soon after the export function returns.

I would recommend using the built-in [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) module to narrow it down.

**Comment by SolarLune** [comment]
> I would recommend using the built-in tracemalloc module to narrow it down.

I'll keep that in mind, but first, I might have stumbled upon the core issue. It looks like whenever BDX exports and runs, for whatever reason, a copy of each mesh in the scene is created. You can see this odd behavior here, in this basic example blend file, or in your own project.

https://www.dropbox.com/s/518k1kcqfmk03bi/basicTest.blend?dl=0

Look to the left, at the Outliner. There's 4 meshes, one for each GameObject in the scene. After pressing P to run the game and exiting, note that there's now 8 meshes; 1 "original" version of each mesh, and 1 generically named copy for each GameObject in the scene. In my Gearend project, what was 258 meshes becomes almost 1000 after running the game once (probably because it's running across each game scene in my project file).

It might be due to creating a new mesh [here](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L106), in line 106 of exporter.py, and never cleaning that mesh up. [Maybe we need to manually remove it somehow afterwards?](https://www.blender.org/api/blender_python_api_2_76_2/bpy.types.Object.html#bpy.types.Object.to_mesh) (Note "remove if only used for export" at the bottom of that function description.)

**Comment by GoranM** [comment]
Ah, now I remember.

The to_mesh addition was part of PR #554, by @jsbr, made to automatically apply modifiers like subsurf.

I was under the impression that this would simply create a new mesh object in the python environment, which would be garbage collected after export runs (like everything else), but it seems like it actually creates a new blender data block.

For objects without modifiers, we should just be able to use the existing mesh. For objects with modifiers, the newly created mesh should be removed after it's no longer needed.

**Comment by SolarLune** [comment]
OK, I think I got it. PR submitted.

**Comment by SolarLune** [comment]
The PR was committed, so I'll close this now. Thanks. I'll re-open if I see any further issues.
