### ISSUE TITLE
Suggestion: Animation.reverse() / SpriteAnim.clone()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#726]
Hey, there. 

It might be good to add an `Animation.reverse()` function that allows you to reverse an Animation? Also a means to clone an existing Animation? For example:

```java

SpriteAnim sa;

sa.add("open", 0, new int[]{0, 1, 2, 3}, 30, false);
Animation close = sa.clone("open", "close");  // Effectively like "sa.add("close", 0, new int[]{0, 1, 2, 3}, 30, false);"
close.reverse();  // So it'd be {3, 2, 1, 0}; alternatively, "sa.animations.get("close").reverse();"
```

The basic idea is to make it easier to create another animation based off of an initial one, and to allow for easy reversal. I know that you can reverse ArrayLists by using Collections.reverse(), but SpriteAnims don't take ArrayLists, and it's not very easy to add individual hand-coded values to ArrayLists. I guess we could add a `reverse()` function to

**Comment by GoranM** [comment]
Couldn't you just play the existing animation in reverse?

**Comment by SolarLune** [comment]
> Couldn't you just play the existing animation in reverse?

Yes, I suppose that is a valid solution. I think it still feels kinda awkward to reverse the speed; I guess it's because of the issue I raised earlier, #727, so we'll see how that plays out.

I'll close this issue, I suppose.
