### ISSUE TITLE
Suggestion: Reset Animation on Changing Active Animation on SpriteAnim

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#727]
Hey, there. 

So if the current animation changes, I think the playhead on the new animation should be reset; it doesn't really make sense to me that the playhead stays at what it was the last time that animation was run. 

At the very least, it should be set to the playhead value on the previous animation. For example, if you have "running" and "runningAndShooting" animations, then playing "runningAndShooting" would allow you to "pick up" the shooting animation on the same frame as the "running" one. 

Though either of these behaviors can be enforced by simply setting the frame oneself, so it's OK if it was just reset by default, perhaps?

**Comment by rafcolson** [comment]
>Though either of these behaviors can be enforced by simply setting the frame oneself, so it's OK if it was just reset by default, perhaps?

Yes, that would make sense to me.

**Comment by GoranM** [comment]
A reset sounds fine.

If people want to continue from some specific frame, they can save and later set the frame themselves.

**Comment by SolarLune** [comment]
PR submitted.

**Comment by SolarLune** [comment]
PR was merged, so I'll close this. Thanks!
