### ISSUE TITLE
Suggestion: scene.xray() String... props

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#729]
Hey, there. 

I think it'd be useful to have a means of filtering raycasts to only hit certain objects, by checking for properties present in hit obejcts. This should be able to be done without breaking the API by tacking on a variable amount of String args at the end of `xray()` functions. That way you can specify which props to filter (rather than just one).

**Comment by rafcolson** [comment]
Sounds good to me.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
OK, PR submitted. Note that the properties are all AND, not OR (so objects have to have *all* of the properties you pass to the functions to be recognized).

**Comment by SolarLune** [comment]
The PR was merged, so I'll close this now. Thanks!
