### ISSUE TITLE
Suggestion: Pointer.insideScreenArea(Vector2f min, Vector2f max)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#730]
```java
public boolean insideScreenArea(Vector2f min, Vector2f max){
	return min.x <= position.x && max.x >= position.x && min.y <= position.y && max.y >= position.y;
```
I think this would be a nice addition. It returns whether the Pointer is located inside a specific area. It can be argued that collision detection could serve the same purpose, but in some cases that would be less convenient because you would have to create and manage multiple static planes.

If I just want the camera to turn to the left/right when the Pointer is inside the left/right half of the display screen, that can be easy done by:
```java
for (Finger f : Bdx.fingers){
	if (f.insideScreenArea(new Vector2f(), new Vector2f(Bdx.display.width() / 2, Bdx.display.height()))){
		scene.camera.rotate(0, -0.1f, 0);
	}else if (f.insideScreenArea(new Vector2f(Bdx.display.width() / 2, 0), Bdx.display.size())){
		scene.camera.rotate(0, 0.1f, 0);
	}
}
```

**Comment by GoranM** [comment]
> If I just want the camera to turn to the left/right when the Pointer is inside the left/right half of the display screen

I don't think we need a new function to do that easily:

```java
float ry = f.positionNormalized().x < 0.5f ? -0.1f : 0.1f;
scene.camera.rotate(0, ry, 0);
```

**Comment by rafcolson** [comment]
Yeah, that was a bad example indeed. I'm also not sure if it would actually be useful to determine whether a finger is in a smaller area. I thought it might be useful with dozens of buttons (e.g. a virtual keyboard) due to the physics strain on mobile devices, but I guess it's not common enough.

Thanks. And closing.
