### ISSUE TITLE
Suggestion: Convenience Vector3f.plus / sub functions

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#734]
Hey, there. It might be nice to add convenience functions to Vector3f and Vector2f to be able to directly add and subtract values without making a new Vector. Something like this:

```java
Vector3f result = vecTo(player).plus(0, 0, 2);  // Good

Vector3f result = vecTo(player).plus(new Vector3f(0, 0, 2));  // Not so good
```

**Comment by GoranM** [comment]
It's just two words, so it doesn't really seem like such a big inconvenience.

Also, I'm not sure if adding by some hard-coded vector, in more than just a few places, would be a common requirement (at least not to the point where most people would feel the "overhead" of typing out "new Vector3f").

**Comment by SolarLune** [comment]
Well, whenever you want to add a vector to another vector (i.e. spawn a bullet, place it at a GameObject's position and offset by a bit), it's a bit awkward to utilize, but I suppose you're right.
