### ISSUE TITLE
Request for new release thread

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#736]
@GoranM 

With the last BDX version (0.2.4) being released more than 4 months ago, and a lot of commits since, maybe a good time to draft a new one?

**Comment by GoranM** [comment]
Yes, it should be up now: https://github.com/GoranM/bdx/releases/tag/v0.2.5

**Comment by rafcolson** [comment]
Thanks.

**Comment by dualjack** [comment]
Thanks!

**Comment by SolarLune** [comment]
Yo, can we get another release?

**Comment by GoranM** [comment]
Yes, it's up (0.2.7).

**Comment by SolarLune** [comment]
Cool. Thanks!

**Comment by rafcolson** [comment]
Hi. It might be a good time to draft another release?

**Comment by GoranM** [comment]
It's up -> https://github.com/GoranM/bdx/releases/tag/v0.2.8

**Comment by rafcolson** [comment]
Thanks.
