### ISSUE TITLE
Analog Sticks Reversed on Linux

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#739]
Hey, there. 

So the axis numbers for analog sticks on X-input controllers on Linux seem to be reversed? Up is left and down is right; could someone confirm on Linux and possibly Mac (might be Unix, might just be Linux)? It might also just be my distro (Linux Mint 17.3, I think), though that doesn't seem quite as likely.

I _believe_ the axes were being read correctly on Windows.

EDIT: So to clarify, in jstest-gtk for multiple different X-Input controllers (a steam controller configured through SC Controller to be a standard XBOX Controller layout, and a Logitech Gamepad F310):
- Axis 0 is left horizontal, and axis 1 is left vertical. 
- Axis 3 is right horizontal, and 4 is right vertical. 
- Axes 2 and 5 are the left and right triggers, respectively (which is strange - I guess Linux might just be seeing the controller as a DirectInput controller?).

However, in our Gamepad.java, the axis orders seem to be incorrect for the XBOX360 profile...?

**Comment by rafcolson** [comment]
I did some testing with my Logitech Wireless Gamepad F710 using this `Sacky.java`:
```java
import com.nilunder.bdx.Bdx;
import com.nilunder.bdx.GameObject;
import com.nilunder.bdx.inputs.Gamepad;

public class Sacky extends GameObject{

	private Gamepad gp;
	
	public void init(){
		Bdx.profiler.tickInfoVisible(false);
		Bdx.profiler.subsystemsVisible(false);
		Bdx.profiler.scale(1.5f);
		gp = Bdx.gamepads.get(0);
		Bdx.profiler.props.put("Gamepad:", gp.name());
	}

	public void main(){
		if (Bdx.profiler.props.containsKey("axis")){
			Bdx.profiler.props.remove("axis");
		}
		for (Gamepad.Axis axis : gp.axes.values()){
			if (axis.value != 0){
				Bdx.profiler.props.put("axis", axis.code);
			}
		}
	}
	
}
```
- Axis **1** is left horizontal, and axis **0** is left vertical.
- Axis **3** is right horizontal, and **2** is right vertical.
- Axes **4** and **5** are the left and right triggers

PS: The right trigger seems to malfunction, which may be the same issue as been reported before with Xbox 360 in #323; it gets stuck, so to speak.

**Comment by GoranM** [comment]
Reading the [libgdx controller documentation](https://github.com/libgdx/libgdx/wiki/Controllers#mappings-and-codes):

> Note that those codes can be different for the same type of controller depending on the operating system.

It seems that they actually have a [cross platform mapping for xbox360](https://github.com/libgdx/libgdx/blob/master/extensions/gdx-controllers/gdx-controllers/src/com/badlogic/gdx/controllers/mappings/Xbox.java), so if we just use that, it should work irrespective of the underlying platform.

**Comment by SolarLune** [comment]
> PS: The right trigger seems to malfunction, which may be the same issue as been reported before with Xbox 360 in #323; it gets stuck, so to speak.

Yeah, I never came back to that; as far as I know, that particular bug should still be in BDX. Perhaps we can get that out of the way too when we deal with this.

What OS did you test on?

____

> Note that those codes can be different for the same type of controller depending on the operating system.

Yeah, I figured it's due to OS differences.

> It seems that they actually have a cross platform mapping for xbox360, so if we just use that, it should work irrespective of the underlying platform.

It looks like only the Mac platform is defined there?

**Comment by rafcolson** [comment]
>What OS did you test on?

Windows 10

>It seems that they actually have a cross platform mapping for xbox360, so if we just use that, it should work irrespective of the underlying platform.

It would be nice if we could have at least one manageable controller for BDX. Additionally, in my opinion, we should provide of an easier way to define gamepad profiles as was mentioned earlier in #564. The alternative would be to do research on various gamepads (for every operating system).

**Comment by SolarLune** [comment]
> Windows 10

OK, that's what I thought - it seemed like it works fine on Windows.

> It would be nice if we could have at least one manageable controller for BDX. Additionally, in my opinion, we should provide of an easier way to define gamepad profiles as was mentioned earlier in #564. The alternative would be to do research on various gamepads (for every operating system).

I agree that we should at least have a manageable controller, though we wouldn't have to do research on various gamepads for every system. We could just implement a generic profile with a large number of buttons and axes, and generic terms for the inputs in the profile (i.e. "0" instead of "x", "axis0+" and "axis0-" instead of "ls-left" and "ls-right", etc). 

I'll post in the other issue to follow up.

**Comment by GoranM** [comment]
> It looks like only the Mac platform is defined there?

There should also be a Linux clause.

You can find it by searching the page for "Linux" (Ctrl-F will bring up the search dialog in most browsers).

**Comment by SolarLune** [comment]
No, I mean I see it there on the page, but every button constant is -1 except for the Mac platform.

**Comment by GoranM** [comment]
Ah, I see.

**Comment by SolarLune** [comment]
A PR was merged to fix this, so I'll close this issue. That PR does nothing for OSX, so I'm guessing that it will also prove problematic - a new issue can be opened / PR can be created when it arises, haha.

Thanks!
