### ISSUE TITLE
Dev: JDK8 compatibility issues with assembling apk

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#740]
The issue started after switching to JDK8. No problems with the 0.2.5 release, but with builds of my repo I get this error when assembling apk for android. So I guess it's a gradle 'dependencies' issue again?
```java
PARSE ERROR:
unsupported class file version 52.0
...while parsing javax/vecmath/AxisAngle4d.class
1 error; aborting

:android:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:transformClassesWithDexForDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_102\bin\java.exe'' finished with non-zero exit value 1
```
Do note that the error sometimes states:
```java
PARSE ERROR:
unsupported class file version 52.0
...while parsing com/nilunder/bdx/Bdx.class
1 error; aborting
```
I found [this](http://stackoverflow.com/questions/37902840/got-unsupported-class-file-version-52-0-after-including-a-module-to-a-project) about the error:

>**Java Class Files**
>The Java class file format has been updated for the Java SE 8 release.

>The class file version for Java SE 8 is 52.0 as per the JVM Specification. Version 52.0 class files produced by a Java SE 8 compiler cannot be used in earlier releases of Java SE.

>The following document has information on changes to the Java Language Specification (JLS) and the Java VM Specification (JVMS).

>- [JSR 337: Java SE 8 Release Contents](http://cr.openjdk.java.net/~mr/se/8/java-se-8-fr-spec-01/)

So the problem must be that _Version 52.0 class files produced by a Java SE 8 compiler cannot be used in earlier releases of Java SE_, but what does that mean exactly?

@SolarLune
You once said that you are using JDK8. Maybe you know more?

**Comment by GoranM** [comment]
JDK8 should work fine if developing for desktop, but I don't think it's fully supported by android.

**Comment by rafcolson** [comment]
>JDK8 should work fine if developing for desktop, but I don't think it's fully supported by android.

Ah okay, thanks. I'll wait for @SolarLune just to be sure, before I'll switch back to JDK7 again.

**Comment by rafcolson** [comment]
I've switched back to JDK7, but had to reinstall Android Studio too (as expected). Everything works fine now. I'm still not sure if JDK actually isn't fully supported by Android, so @SolarLune, could you confirm this? If so, it might be good to mention this in the [Wiki - Installation - Prerequisites](https://github.com/GoranM/bdx/wiki/Installation#prerequisites). Especially when newcomers probably will download the latest JDK (which is 8 currently). The link in the Prerequisites also points to this version.

**Comment by SolarLune** [comment]
Sorry, I don't know, I don't do Android development. If you found that JDK8 didn't work, we'll just go with that and adjust the Wiki accordingly. Thanks.

**Comment by rafcolson** [comment]
No, thank you! I see you've already updated the API. Is no point in having this issue around so closing..
