### ISSUE TITLE
Possible Bug: Ending Objects Destroys "Unparented" Object

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#741]
Hey, there. So basically, if you unparent a child in a GameObject's `onEnd()` call, it'll still end the child. Perhaps this is intentional, but it might be better to call `endNoChildren()` at the beginning of `end()`? 

That way, you can de-parent a child when `onEnd()` is called, preventing the child from being removed unnecessarily.

**Comment by GoranM** [comment]
Yeah, calling endNoChildren first should be fine.

**Comment by rafcolson** [comment]
>if you unparent a child in a GameObject's `onEnd()` call, it'll still end the child.

There's a couple of thoughts with this. First, if you end an object, there's no need to remove the parent of the children in `onEnd()`, because `endNoChildren()` already does that.

Secondly, since `end()` is supposed to end all children too, `onEnd()` would logically not be a means to revert that. You've now ended the parent with its children, and so it will happen, regardless if you detach the children when that happens.

Could I ask what kind of case you're dealing with?

That said, as Goran said, it should be fine to do change the order.

**Comment by SolarLune** [comment]
> Could I ask what kind of case you're dealing with?

Well basically, I have entities that can carry things, and I want them to drop the item when they're ended. I guess I could override `end()` to unparent the child before calling `super.end()`, rather than doing it in `onEnd()`, so it's up to you guys. 

_______

As a bit of a side-poll, should we even have `onEnd()`? I originally wanted it because I thought it a pain to override `end()` for everything that you would want to do something before / after ending, but that is what overriding functions is for, and it's not often enough to be a hassle (even if it was, it's only a few lines, and to remember to add `super.end()`). It's been awhile since I proposed it, so I figure it's worth taking a look at again for "inclusion". Has everyone been using it, or do people think it's kind of unnecessary?

**Comment by rafcolson** [comment]
>Well basically, I have entities that can carry things, and I want them to drop the item when they're ended. I guess I could override `end()` to unparent the child before calling `super.end()`, rather than doing it in `onEnd()`, so it's up to you guys.

I think I see. I was having in mind just to call `endNoChildren()` but that would also require all entities to end children manually.

Doing as you suggested would avoid adding such complexity, although it's a bit of a hack too. But I'm all for it. Probably will be needing it too.

**Comment by rafcolson** [comment]
>As a bit of a side-poll, should we even have `onEnd()`?

Almost forgot to respond to this.

It's still convenient to have this method, so I would vote for keeping it. Most of the time you wouldn't be dealing with complex issues which would require to override a function. Any method which would prevent a function from being overridden, would be a good addition to the API, I think.

**Comment by SolarLune** [comment]
Hm, OK. I've submitted a PR, then.

**Comment by SolarLune** [comment]
PR was merged, so I'll close this now. Thanks.
