### ISSUE TITLE
Suggestion: Call Component.exit() when Owning GameObjects are ended

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#743]
Hey, there. 

So I'm trying to get into using a component-based design some more, and I think it'd be nice to be able to know when a Component's GameObject is destroyed. A simple way to do this seems to be to call Component.state.exit() after the GameObject has been turned invalid.

The general idea is that I'm making a component that identifies the "faction" or "team" of a GameObject / entity. The GameObject should be added to that team when the component is created, and removed from that team when the component is removed / when the GameObject is destroyed.

**Comment by GoranM** [comment]
It's expected that State.exit will be called when a component changes state, not when a GameObject is removed from the scene.

A Component.onGobjEnd seems like it would be more descriptive.

**Comment by SolarLune** [comment]
OK. PR submitted. I went with "Component.onGameObjectEnd()"; hope that's OK.

**Comment by SolarLune** [comment]
This was merged, so I'll close it. Thanks.
