### ISSUE TITLE
Suggestion: Vector Additions

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#744]
Hey, there. Here's some suggestions for Vector additions.

______

So it's a bit awkward to have to use Vector3f.cross() to set the cross product of two vectors to a third vector. I think it'd be easier to comprehend and use an alternative version that returns the cross product of another vector and itself. So instead of this:

```java
Vector3f forward = new Vector3f();
forward.cross(right, up);
```

We'd have this:

```java
Vector3f forward = right.cross(up);
```

_____

Another thing that would be nice is the ability to rotate a Vector around on an axis easily. We can do that with Matrix3f.rotation(), but it'd be nice to add a convenience function to the Vector3f class like so:

```java

// Instead of:

facing = Matrix3f.rotation(new Vector3f(0, 1, 0), 0.1f).mult(facing);

// We'd have:

facing = facing.rotate(new Vector3f(0, 1, 0), 0.1f);
```

The issue with just using the Matrix function is that I often forget it exists, because it doesn't reside in the same namespace as the Vector. So I'm looking through the Vector's options looking for a way to rotate, then I realize that I asked this before, and then I remember that I need to use Matrix3f.

For Vector2fs, we should be able to have it work without passing a reference axis by simply rotating around the Z-axis like so:

```java
facing2D = facing2D.rotate(0.1f);
```

We could also add an `angle()` function for Vector2fs that takes no arguments that assumes a provided vector of 1, 0.
_____

Also, there's no `Vector3f.normalized()` or `Vector2f.normalized()`, which would be nice.

**Comment by GoranM** [comment]
Ok.

It would make sense for Vector*.rotate to modify the calling vector, and for Vector*.rotated to return a new copy.

**Comment by SolarLune** [comment]
Cool, thanks for that; I'd kinda forgotten about that naming convention. PR submitted.

Now, a point of interest is that Vector2f.angle() returns the angle from the vector supplied to the target vector, but ignores the sign of that angle. So this is the case:

```java

Vector2f up = Vector2f(0, 1);
Vector2f down = Vector2f(0, -1);

up.angle();  // Returns 1.5707 (half Pi)
down.angle();  // Also returns 1.5707

```

Now, with Vector3f, I kind of understand - what's the reference point for the sign of an angle in the third dimension? I guess it depends on what vectors you're measuring the angles of and against; it's OK to leave that for the developer to figure out. 

However, for Vector2f, I think BDX should be able to help you further differentiate a bit further. I think ideally, rotate() and angle() could kind of be "opposites", in that you could do `rotate(-angle());` to rotate a vector back in its closest direction to have an angle of 0 (or whatever angle you wanted by just providing another value to the `angle()` function, or do it slowly by dividing the angle by a value. or whatever). It could return the sign of the angle:

```java
up.angle() // 1.5707
down.angle() // -1.5707
```

Or loop around:

```java
up.angle() // 1.5707
down.angle() // 4.7122
```

Or whatever, but I think it could do this to help identify the actual direction in radians that a Vector is directed toward, and not just the number of radians between that Vector and another one.

**Comment by SolarLune** [comment]
Also, I'd like to add functions to convert from Vector3f to Vector2f and back. The ones I came up with also can take a String value to swizzle the components around, like so:

```java
Vector2f angle = new Vector2f(1, 0.5f);
Vector3f threed = angle.to3D("x0z"); New Vector3f has the component (1, 0, 0.5f).
```

It might even be better to allow for minuses to invert individual components of the Vector, though that might be too much work.

**Comment by GoranM** [comment]
> what's the reference point for the sign of an angle in the third dimension?

If the angle between two 3D vectors is not 0 or pi, those vectors effectively define a 2D plane, so there is a transform which, when applied to both vectors, can fit them into 2D space, such that one vector is effectively <1, 0>, while the other is a 2D vector with the same relative angle.

So, given two 3D vectors A and B, you should be able to compute that transform like this:

```java
Matrix3f t = new Matrix3f();
t.setColumn(0, B.normalized());
Vector3f BxA = B.crossed(A);
t.setColumn(1, B.crossed(BxA).normalized());
t.setColumn(2, BxA.normalized());
t.invert();
```

With that, you can make a 3D problem into a 2D problem, which you already know how to solve.

> just the number of radians between that Vector and another one

But that's actually the correct definition of an angle between two vectors, so you shouldn't change the implementation of the existing angle method.

If you really need signed angles, make a signedAngle method.

As for the "to3D" and "swizzle": Typing out `new Vector3f(v.x, 0, v.y)` doesn't really strike me as being particularly troublesome, so I don't think it's worth the additional code.

**Comment by SolarLune** [comment]
> If the angle between two 3D vectors is not 0 or pi, those vectors effectively define a 2D plane...

Thanks for that, though I'm still not sure how quite to apply it to an `angleSigned()` function for Vector3fs. I tried multiplying both vectors by the ending transform, but then A's y-axis value is always negative.

**Comment by GoranM** [comment]
Oh, I forgot that the cross products were codependent, so you'll have to actually provide a view plane normal vector that can be used to differentiate (not unlike having to provide the "axis" vector when using Matrix3f.rotation).

Imagine a clock on some arbitrarily oriented wall, and that you want to get a signed angle between the clock hands; the wall normal would serve as the view plane normal.

```java
...
Vector3f BxA = B.crossed(A);
if (BxA.dot(view_plane_normal) > 0)
    BxA = A.crossed(B);
...
```

Actually, since that conditional is the sole determining factor, you can just use it to set the sign directly:

```java
...
if (BxA.dot(view_plane_normal) > 0)
    return A.angle(B);
return -A.angle(B);

**Comment by SolarLune** [comment]
I looked it over, and I still couldn't quite get it to work. That's OK, though; I think the utility of Vector3f.angleSigned() kinda breaks down. It's not often that you'd need to get the signed angle of a 3D vector, so I think it's fine to leave it out for now, at least. I or someone else can come back to it later if necessary.

The PR should be good to go, I think.

**Comment by SolarLune** [comment]
This was merged, so I'll close it now. Thanks!
