### ISSUE TITLE
Suggestion: Gyroscope and Accelerometer

### ISSUE THREAD

**Issue by benkaranja** [GoranM/bdx#747]
Hey there,

is there a way to access the gyro and accelerometer provided via libgdx? Thanks in advance

**Comment by SolarLune** [comment]
See issue #663 - it's not available in BDX, but it should be relatively easy to do in LibGDX. The problem I see is that MainActivity.java doesn't seem to exist - not sure where is should be, as it doesn't seem to be in the BDX project directory. Maybe @rafcolson or @GoranM could weigh in on this - I don't do Android much. It might be worth it to add to BDX if it proves a bit complicated or time consuming to implement on a per-user basis, though, if only just to make it easier to get stuff like this kick-started quicker.

**Comment by rafcolson** [comment]
>I'm planning to add it this month

I think I'm almost done with support for Accelerometer, Gyroscope, Compass and Screen Orientation. But @GoranM is it okay with you? I've added a boolProperty "Create Android Project" which will show a box when enabled. Posting a picture tomorrow.

**Comment by GoranM** [comment]
Generally, I think that support for those inputs would be useful. However, I don't understand how a new bool property for "Create Android Project" is related to any of this; That sounds like a separate suggestion, which should be outlined in its own issue.

**Comment by rafcolson** [comment]
>That sounds like a separate suggestion

I understand. But I think it might be related to some degree as it is a means of implementing the changes. 

This is what I had in mind.

![create android project](https://cloud.githubusercontent.com/assets/10002909/17835733/0ba1e616-677a-11e6-8d5c-7b7db16b32b6.png)

**Comment by SolarLune** [comment]
I suppose that should be a separate suggestion, but I think it's a good idea, especially since each of those options needs its own permission under Android, as I recall. So it's best to provide the option to not require those features if possible.

**Comment by GoranM** [comment]
Unless configuring an android project to ask for required permissions is incredibly convoluted (doesn't appear to be, and it might even be possible to do at runtime), I don't see the need for an additional section in the BDX project panel.

Also, I don't think you can have an option for "Create Android Project" - You have to create it either way, because that's where all the libgdx projects expect to find the relevant resources.

**Comment by rafcolson** [comment]
>Also, I don't think you can have an option for "Create Android Project" - You have to create it either way, because that's where all the libgdx projects expect to find the relevant resources.

Yes. I agree. Was thinking of changing this to "Android Project settings" or something like that.

>Unless configuring an android project to ask for required permissions is incredibly convoluted (doesn't appear to be, and it might even be possible to do at runtime), I don't see the need for an additional section in the BDX project panel.

Is it possible to do this at runtime? I'm not sure if `AndroidManifest.xml` is dynamically loaded by the system. I'm pretty sure that `AndroidLauncher.java` is loaded at launch time, so editing it during runtime wouldn't take effect until you restart the game, right?

I think at the most these Android Settings options could be part of the `BDX Panel` (after project creation).

**Comment by GoranM** [comment]
> Is it possible to do this at runtime?

A quick google search brought me to this page: https://developer.android.com/training/permissions/requesting.html

So, apparently, it should be possible, but I'm not sure on the details, so it's something that you would need to research further.

-

I'm not sure if it's a good idea to take on the responsibility of managing configuration for any of the generated libgdx projects.

The users can do that already, via well documented methods, and without too much trouble.

I think we should just focus on creating a straightforward API.

**Comment by rafcolson** [comment]
>So, apparently, it should be possible, but I'm not sure on the details, so it's something that you would need to research further.

Thanks. So it should be possible to enable the vibrator during runtime. I suppose it then should be possible to change the screen orientation too. Changes to the `AndroidManifest.xml`:
```xml
    <uses-permission android:name="android.permission.VIBRATE" />

    <application
        ...
        <activity
            ...
            android:screenOrientation="fullSensor"
            ...
```
However the accelerometer, gyroscope and compass would require of these lines to be added to the `AndroidLaucher.java` before exporting the project.
```java
		config.useAccelerometer = false;
		config.useGyroscope = false;
		config.useCompass = false;
```
>I'm not sure if it's a good idea to take on the responsibility of managing configuration for any of the generated libgdx projects.

Okay, I think I see your point.

>The users can do that already, via well documented methods, and without too much trouble.

It probably will. I just thought it would be more convenient (and faster) to just check a couple of properties in the BDX project panel.

In conclusion, these are the methods that are not functioning unless some manual changes are made:
```java
Gdx.input.cancelVibrate();
Gdx.input.vibrate(int milliseconds);
Gdx.input.vibrate(long[] pattern, int repeat);

// solution: add permission to VIBRATE in AndroidManifest.xml (during runtime)

Gdx.input.getRotation();
Gdx.input.getRotationMatrix(float[] matrix);

// solution: replace activity screenOrientation in AndroidManifest.xml (during runtime ?)

Gdx.input.getAccelerometerX();
Gdx.input.getAccelerometerY();
Gdx.input.getAccelerometerZ();
Gdx.input.getAzimuth();
Gdx.input.getGyroscopeX();
Gdx.input.getGyroscopeY();
Gdx.input.getGyroscopeZ();
Gdx.input.getPitch();
Gdx.input.getRoll();

// solution: add config.useAccelerometer = false; config.useGyroscope = false; config.useCompass = false; to AndroidLauncher.java
```
Would it be okay to add this information to the [Wiki's Installation page](https://github.com/GoranM/bdx/wiki/Installation#android-development)? Maybe a reference to a written tutorial, which would summarize the steps users can make in order to manually add support for the `Gdx.input` methods?

**Comment by rafcolson** [comment]
>is there a way to access the gyro and accelerometer provided via libgdx? Thanks in advance

@benkaranja Would this tutorial in the [Wiki's Installation page - Android Development](https://github.com/GoranM/bdx/wiki/Installation#android-development) solve this issue for you?

**Comment by SolarLune** [comment]
> Edit: I was pretty sure that this wouldn't be a problem, so I've already added a link to a tutorial in the Wiki's Installation page - Android Development.

Cool! Thanks for the extra documentation! The only gripe I have here is that "Special Inputs" doesn't really describe that it's additional means of control specifically for Android / Mobile. Perhaps you could rename it to something like "Mobile Sensors"?

**Comment by rafcolson** [comment]
>Perhaps you could rename it to something like "Mobile Sensors"?

Good idea.

**Comment by GoranM** [comment]
Shouldn't those android configuration options be set to "true" instead of "false"?

**Comment by rafcolson** [comment]
>Shouldn't those android configuration options be set to "true" instead of "false"?

That's right. Changed it.

**Comment by benkaranja** [comment]
Thanks guys! Ave been abit busy but I will try  and implement the new solution and revert. Cool!

**Comment by rafcolson** [comment]
>Thanks guys! Ave been abit busy but I will try and implement the new solution and revert. Cool!

I thought I could save us some time by creating a Android Project Manager tool, independent of this branch. It's part of a Blender add-on [BDX-Tools](https://github.com/rafcolson/bdx-tools), which can be downloaded [here](https://github.com/rafcolson/bdx-tools/releases).

Feel free to test it out. If there are any issues, I'm glad to hear.

Also added a link to this Android Project Manager tool in the [tutorial](https://github.com/GoranM/bdx/wiki/Advanced-Tutorials:-Mobile-Sensors#android).

**Comment by rafcolson** [comment]
@benkaranja

Did the tutorial solve your issue? If so, and you don't have any other questions, you can close this. Thanks.

**Comment by benkaranja** [comment]
Solved my issue, but haven't had time to thoroughly trouble shoot it. 
We can close this for now. Thanks.
