### ISSUE TITLE
Suggestion: Implement music looping

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#756]
I noticed libgdx has [setLooping](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/audio/Music.html#setLooping-boolean-), can we port these functions to BDX?

**Comment by songproducer** [comment]
Just found the timer function. If we could get the length of the audio file it would be easy enough to make a looping function.

Would be great to have some audio library functions to set level, fade in/out too!

**Comment by SolarLune** [comment]
Bdx's music and sound fields are just extensions of LibGDX's AudioStores of LibGDX sounds and music instances. So you can loop music just like so:

```java
Music m = Bdx.music.get(fileName);
m.setLooping(true);
m.setVolume(startingVolume);
m.play();
```

**Comment by songproducer** [comment]
Thanks! Needed to import com.badlogic.gdx.audio.*;
