### ISSUE TITLE
Bug: Sounds method doesn't play on device first touch.

### ISSUE THREAD

**Issue by songproducer** [GoranM/bdx#758]
Tested on Sony Xperia Z3+

**Comment by songproducer** [comment]
Here was the code I tested:

`

    if (Bdx.mouse.btnHit("left")){

      Bdx.music.get("Space3").play();

      applyForce(0,1000,1000);
    }
`

**Comment by SolarLune** [comment]
OK, does this run at all, regardless of platform? 

Because `Bdx.music` is for triggering songs, audio files put into the music directory, while `Bdx.sounds` is for triggering sounds, audio files placed in the sounds directory. So are you trying to play a sound, or a song?

Also, until any unintended behavior has been confirmed as a bug, it might be best to post questions on the [/r/bdx](https://www.reddit.com/r/bdx/) subreddit.

**Comment by songproducer** [comment]
>OK, does this run at all, regardless of platform?

Yes, the code runs without error, just no sound is heard on the first tap.

>So are you trying to play a sound, or a song?

I'm playing a short sound (less than 1 sec).

>Also, until any unintended behavior has been confirmed as a bug, it might be best to post questions on the /r/bdx subreddit.

Good idea, will ask there in future.

**Comment by SolarLune** [comment]
Where did you put the sound file?

**Comment by SolarLune** [comment]
And if it doesn't work on desktop, it won't work on Android (generally, unless it's an Android-specific feature), so you should probably focus there for debugging and ensuring things work.

**Comment by GoranM** [comment]
A given sound is loaded on the first attempt to retrieve it from the bdx audio store, as can be seen [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/audio/AudioStore.java#L21-L28).

On android, libgdx sound loading [seems to be a non-blocking operation](https://github.com/libgdx/libgdx/issues/1775), so it's possible to receive a reference to a sound/music object that is not completely loaded, and if you try to play it at that point, nothing happens.

We could just load all the audio ahead of time, but this may not be a good idea for all games (those with a lot of audio resources, where loading all of them at upfront could be prohibitive).

Although, it might be worthwhile to provide a function that does that, as an option for cases where it does make sense.

**Comment by songproducer** [comment]
>Where did you put the sound file?

android/assets/bdx/audio/sounds

> And if it doesn't work on desktop, it won't work on Android (generally, unless it's an Android-specific feature), so you should probably focus there for debugging and ensuring things work.

It worked fine on desktop.

**Comment by songproducer** [comment]
>On android, libgdx sound loading seems to be a non-blocking operation, so it's possible to receive a reference to a sound/music object that is not completely loaded, and if you try to play it at that point, nothing happens.

Thanks, knowing this I got around the bug by setting the volume to 0, playing the sound then setting the volume back to 1.

>Although, it might be worthwhile to provide a function that does that, as an option for cases where it does make sense.

It might work better to enable per sound pre-loading, for games that have many sounds.

**Comment by GoranM** [comment]
> It might work better to enable per sound pre-loading, for games that have many sounds.

You should be able to "pre-load" by simply calling `Bdx.sounds.get("sound_name")` at initialization.

**Comment by SolarLune** [comment]
Can this be closed, or no?

**Comment by songproducer** [comment]
I am happy to just do the workaround, but I still consider it to be a bug.

**Comment by SolarLune** [comment]
OK, if you can confirm that you can pre-load the sounds on Android by calling `Bdx.sounds.get("sound_name")`, then we can add a function that does this for all available sounds to pre-load them. Because otherwise, it's not a bug, it seems to be just how LibGDX does things.

**Comment by songproducer** [comment]
I called like this so it mutes the sound in init:

Bdx.sounds.get("Jump001").play(0);

**Comment by SolarLune** [comment]
OK, but can you pre-load by simply calling the `get()` command? 

Or do you need to call `play()` to get it to work? 

Would calling `play()` and then calling `stop()` also work?
