### ISSUE TITLE
Suggestion: Store Descriptors on Inputs

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#763]
Hey, there. 

I'm trying to do an input remapping system, and to do this, it'd be useful to if I could get the descriptors (e.g. `k:left` or `g:a`) from the Inputs. However, they don't appear to be available on the Input? It'd be nice to expose those.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
OK, PR submitted.

**Comment by SolarLune** [comment]
Hey, this got merged, so I'll close this now. Thanks!
