### ISSUE TITLE
Physics: Lock Translation and Lock Rotation does nothing

### ISSUE THREAD

**Issue by satno** [GoranM/bdx#767]
Selecting axis in lock translation or lock rotation in physics properties has no effect, rigid body still moves and rotates in locked axis.

**Comment by GoranM** [comment]
As far as I remember, jbullet doesn't actually support that feature, so it's not an option that is implemented in BDX (basically, if it's not listed in the documentation, you can assume that we don't support it).

You can keep an object "locked" to a specific plane by just setting its position to whatever is appropriate, whenever it drifts out of some margin of error.

A similar method can work for rotation, using the alignAxisToVec method.

It's not that hard to write a component that does that.

**Comment by satno** [comment]
Thanks! There is another problem using:
position().setY(0) in main function
does not work, but im sure im doing something wrong, because im totaly new to 3d programming.

**Comment by SolarLune** [comment]
'Sup! There's no such function as `setY()` on a Vector3f. Check the reference [here](https://github.com/GoranM/bdx/wiki/API-Vector3f) and [here](http://docs.oracle.com/cd/E17802_01/j2se/javase/technologies/desktop/java3d/forDevelopers/j3dapi/javax/vecmath/Vector3f.html) to see what a Vector3f can do, or look at the code completion in your IDE if you have one and it's set up.

If you want to set the Y position on a vector, you can just set its attribute, like so:

```java
Vector3f p = position();  // Get a Vector3f of the object's position (in a function in a class derived from GameObject)
p.y = 0;  // Set the Y component to 0
position(p);  // Reassign the Vector to the Gameobject's position to reposition it
```

**Comment by satno** [comment]
This works, thanks! IntelliJ IDEA shows me the set functions, that is strange :)

**Comment by GoranM** [comment]
It seems that our version of vecmath has some methods that are not documented in the oracle link.
