### ISSUE TITLE
Suggestion: remove camera discrepancy between PERSPECTIVE and ORTHOGRAPIC

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#772]
Noticeable with EXTEND viewports when the aspect ratio (width / height) of the viewport size is smaller than the aspect ratio of the viewport resolution: PERSPECTIVE will preserve the height, whilst ORTHOGRAPHIC will not.

To illustrate this, here's two pictures of:

LETTERBOX - PERSPECTIVE & ORTHOGRAPIC
![letterbox_camera](https://cloud.githubusercontent.com/assets/10002909/18181111/f3ec12a8-7089-11e6-8c9e-7f7022fb2106.png)

EXTEND - PERSPECTIVE & ORTHOGRAPIC
![extend_camera](https://cloud.githubusercontent.com/assets/10002909/18181130/081ee96c-708a-11e6-853a-2111834c0b15.png)

However I'd like EXTEND - ORTHOGRAPHIC behave the same as with EXTEND - PERSPECTIVE:

![extend_camera_ortho_fix](https://cloud.githubusercontent.com/assets/10002909/18181343/1343ce24-708b-11e6-8bb9-6fdd95674090.png)

It's an easy fix.

Edit:
By the way, this also fixes an issue with Screen Rotation on Android. Before the screen would stretch, now the ratio and the height is preserved.

**Comment by GoranM** [comment]
Looks good.

Merged.

**Comment by rafcolson** [comment]
Thanks!
