### ISSUE TITLE
Suggestion: GameObject.recalculatePhysicsMesh()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#780]
Hey, there. So basically, there's no way to update the physics mesh of the game object should you adjust it? It'd be nice to have a `recalculatePhysicsMesh()` function to do this for us. 

We might later move the function (along with the other model-related classes like `useUniqueModel()` and `replaceModel()`) into the Mesh class, as well?

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
This was handled by the PR for #680, so I'll close this now. Thanks!
