### ISSUE TITLE
Bug: Orientation Resets After updateJoinedMesh()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#786]
Hey, there.

For static target GameObjects, after a certain amount of time (what appears to be Bullet's Sleep Timer), calls to `updateJoinedMesh()` will reset the calling object's orientation. 

[Here's](https://www.dropbox.com/s/6841k1vn6mgrbbh/UpdateJoinedIssue.blend?dl=0) a blend file that illustrates the problem. 

If you press "C", Sacky's sprite's collision and visual mesh will be replaced with the Platform above, and it will be facing and moving forwards. If you wait a certain amount of time (the sleep timer), and press "C" after Sacky's collision cube turns green, the platform will be located where it originally was, and move upwards from there. 

It should probably (?) always be the second behavior.

**Comment by GoranM** [comment]
@rafcolson should be able to help you with this.

**Comment by rafcolson** [comment]
Weird. I'll be looking into it.

**Comment by rafcolson** [comment]
>It should probably (?) always be the second behavior.

Yes, the first behavior doesn't make much sense.

PR submitted.

**Comment by SolarLune** [comment]
Thinking about it now, scale of the joined object should probably be preserved (it probably should show up joined the exact same as it appeared before-hand).

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
I'm a little stuck, but I will come to a solution soon enough. I noticed that my previous commits weren't actually as solid as I thought they would be. So, my apologies for the wait. I'll be working on it when I have the time.

@SolarLune 

However, think about it, preserving position, orientation and scale on the joiner object sure makes it complicated, and more expensive for performance, while I think we should keep the computation to a minimum. It's already very expensive.

So I wonder why you think this would be necessary. I mean, why is it important to preserve the position, orientation and scale? What are you trying to do? Or how do you want to use `updateJoinedMesh()`?

**Comment by SolarLune** [comment]
I said that the scale, position, and orientation of the _joined_ object should be the same after joining as before (so however the joined object appears, that's how it should look after being joined together with the main GameObject), not anything to do with the _joiner_. 

Basically, this bug, where the joined object changes how it appears after being joined, shouldn't exist.

> I mean, why is it important to preserve the position, orientation and scale? What are you trying to do? Or how do you want to use updateJoinedMesh()?

I'm not trying to do anything in particular, I just noticed this bug.

**Comment by rafcolson** [comment]
>not anything to do with the *joiner*.

With *joiner* I meant the object on which `updateJoinedMesh()` is called, you're calling it the *joined* object, but we're talking about the same thing.

>Basically, this bug, where the joined object changes how it appears after being joined, shouldn't exist.

I'm not sure about that. The joining functionality is rather special. I'm not even sure if it fits inside *GameObject*, because I intended it to be a utility for the sole purpose of reducing GL draw calls. In that context the *joiner* would be a newly created object. Remember that I originally intended it like that, but we weren't in agreement for a `Joiner.java` object.

I'll have to rethink this to find another implementation of this utility, so *not* preserving position, orientation and scale would be considered as a *bug*.

**Comment by SolarLune** [comment]
> With joiner I meant the object on which updateJoinedMesh() is called, you're calling it the joined object, but we're talking about the same thing.

Ah, OK.

>  I'm not even sure if it fits inside GameObject, because I intended it to be a utility for the sole purpose of reducing GL draw calls. 

Hmm. Well, since we have the Mesh class now, it might be better to put in there.

> I'll have to rethink this to find another implementation of this utility, so not preserving position, orientation and scale wouldn't be considered as a bug.

I'm not sure under what circumstances one wouldn't want the transform of the object being preserved when joining - wouldn't that mean that joining multiple objects would put them at the same location in space, regardless of where they actually are before joining?

**Comment by SolarLune** [comment]
To expand on my previous second point, maybe we could simplify it by simply having a `Mesh.add()` function to add together Meshes? Perhaps we could even cut out the `updateJoinedMesh()` function by having BDX automatically do this at the end of the frame (so `Mesh.add()` just adds the targeted Mesh / GameObject to a list, which BDX steps through at the end of the game frame to actually act on). The `add()` function could take a GameObject, which has a transform for where the GameObject's Mesh should show up when added, or perhaps it could take a Mesh and optional transform / PSR?

Recalculating the physics can be done by the developer by using `updateBody(mesh())` after Mesh alteration.

**Comment by rafcolson** [comment]
>I'm not sure under what circumstances one wouldn't want the transform of the object being preserved when joining - wouldn't that mean that joining multiple objects would put them at the same location in space, regardless of where they actually are before joining?

Typically, the *joiner* would be an Empty which would *replace* all objects in the `joinedMeshObjects` list, "joining" those objects into one object, when the `updateJoinedMeshObjects()` method is called. Those objects are not supposed to be animated, otherwise you would have to join on every logic tick in order to update the animation. For this reason it's only natural that also the Empty is not animated. But I agree that in some special cases it would be convenient to preserve the transform. Even more convenient would be if this would be optional.

>To expand on my previous second point, maybe we could simplify it by simply having a `Mesh.add()` function to add together Meshes? Perhaps we could even cut out the `updateJoinedMesh()` function by having BDX automatically do this at the end of the frame (so `Mesh.add()` just adds the targeted Mesh / GameObject to a list, which BDX steps through at the end of the game frame to actually act on). The add() function could take a GameObject, which has a transform for where the GameObject's Mesh should show up when added,

Joining objects to reduce GL calls will probably not be useful for most games, it's main purpose is to gain performance on mobile devices in cases where the game would have to render more than 20 or 30 objects inside the camera's frustum. So I think it should be kept out of the main loop.

That would mean there would have to be a `Mesh.join(ArrayList<GameObject>)`, or something like that, but then again, that wouldn't be much different from what we have now with `GameObject.updateJoinedMesh()`.

>or perhaps it could take a Mesh and optional transform / PSR?

I'm actually using a similar method in a game to replace the mesh of an object:
```java
replaceMesh(HashMap<String, ArrayList<Matrix4f>> map); // a list of transforms per mesh name
```
But such method in the `Mesh` class wouldn't be able to preserve any *transform*. If that's our goal we should stick with a method for `GameObject`, or at least that's what I think for the aforementioned reasons.

For now I'll just continue working on preserving the transform. After that we could brainstorm some more to find a more suitable implementation. But thanks for your insights.

**Comment by SolarLune** [comment]
> Those objects are not supposed to be animated, otherwise you would have to join on every logic tick in order to update the animation. For this reason it's only natural that also the Empty is not animated. But I agree that in some special cases it would be convenient to preserve the transform. Even more convenient would be if this would be optional.

Hmm... Let me start over: The problem that I observed earlier was just that _under certain circumstances_, objects that were selected to join wouldn't be added in from the correct location. I think it works fine as it is if the calling object is advised to be not scaled or rotated. 

If it's simpler to just add a note in the Wiki than to add a lot of compensating code, we can just add that note.

> Joining objects to reduce GL calls will probably not be useful for most games, it's main purpose is to gain performance on mobile devices in cases where the game would have to render more than 20 or 30 objects inside the camera's frustum. So I think it should be kept out of the main loop.

That's not true - it's very useful to join objects together for all targets. I'm using it for Gearend (which I only plan to release for desktop) because joining the terrain blocks together:

1) Reduces the draw calls from hundreds of objects to just a few, which is great for render optimization, and
2) Allows me to reduce the number of objects present in the game scene, optimizing physics and logic (in particular, raycasts).

I don't know if I could keep a consistent 60 FPS without doing this. I suppose I could join the terrain objects together before runtime, but I'm not sure if I can easily do that with object instances and if the materials would transfer to the new "terrain" object well.

Any kind of randomly generated game would also benefit from this tool.

> That would mean there would have to be a Mesh.join(ArrayList<GameObject>), or something like that, but then again, that wouldn't be much different from what we have now with GameObject.updateJoinedMesh().

That's true, I just thought it'd be a nice addition that would make the process a bit simpler to work with and more intuitive. 

It'd also properly segregate the process of joining GameObjects - it would update the visuals, and leave it to the developer to update the physical body (which matches the GameObject's current `mesh()` and `updateBody()` paradigm).

_____

An alternative approach would be to simply update the mesh at the end of an `add()` function that can take an ArrayList or sequence of Meshes. That wouldn't take any extra work for BDX to do at the end of the frame - you'd just pass into the function all of the Meshes you want to add together. Update the body when you want to / are ready.
_____

If we don't care about compensating for transforms, then we could move it to the Mesh class (since it makes more sense to have Mesh-altering functions on the Mesh). Otherwise, it's fine where it is.

**Comment by rafcolson** [comment]
>If we don't care about compensating for transforms, then we could move it to the Mesh class (since it makes more sense to have Mesh-altering functions on the Mesh). Otherwise, it's fine where it is.

Thinking about it again, I think a `Mesh.add(HashMap<String, ArrayList<Matrix4f>> map)` method would also allow compensating for transform. For controlled random generation it should just be a matter of multiplying the transforms with the inverted transform. With designed scenes it's also a matter of collecting and adjusting the transforms (preferably offline), loading those from file (adjusting here would require an extra loop to generate a new map), and finally join.

I'll make the suggestion in a different issue.

**Comment by SolarLune** [comment]
The PR was merged, so I'll close this now. Thanks.
