### ISSUE TITLE
Suggestion: Default Copy Mesh / Material Option

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#787]
With the new refactoring of the Mesh to tie Materials in with Meshes (which is closer to how Blender works), I was thinking that it would be nice to add the ability to have unique meshes and materials for each GameObject by default.

It is annoying to call `mesh(mesh().copy())` for all GameObjects whenever you want to alter their materials or mesh. This is especially the case when working on existing projects that, of course, depended on the old behavior (which, I believe, is usually desired).

Projects in progress would be able to proceed as usual by default with the option on, and the behavior of materials and meshes could be closer to Blender with the option off, if the developer so chooses to have it like that.

The default copy option would be a boolean option you could disable in Blender. It would tie in with a global boolean value somewhere, like in Bdx's namespace. That way, you could disable it through code if desired mid-game as necessary.

When it's on, mesh replacement and material replacement functions use a copy of the material or mesh provided.

**Comment by rafcolson** [comment]
I think a much simpler implementation would be to have a function:
```java
scene.addUnique("particle");
```

**Comment by SolarLune** [comment]
The problem with making an alternative `add()` function is that BDX will still spawn in automatically (either from objects or group instances in Blender) objects that share their meshes and materials. The point is to make something that we can enable to change the default behavior so that we don't have to manually add code to make unique meshes and materials for each GameObject in a project. 

On second thought, it doesn't have to change how the mesh or material replacement functions work in-game, since you can just make a copy of the material or mesh as necessary (or not, if you want them to share between GameObjects).

We can have two different options for the mesh and material.

**Comment by rafcolson** [comment]
>The problem with making an alternative `add()` function is that BDX will still spawn in automatically (either from objects or group instances in Blender) objects that share their meshes and materials. [...]

I can't imagine this to be true for mere objects in the scene (could you give an example?), but you sure have a point with Group instances. I think this would at least justify an option for Group instances only.

With the *addUnique()* function this would give more freedom. For example, if not reserved for Group instances only, loading scenes between game "levels", would require to keep track of *when* to disable/enable the option, just for the sake so group instances would be unique and spawned objects wouldn't. I think a function would give the necessary clarity about when and which objects are added with unique meshes and/or materials. Only thoughts.

**Comment by SolarLune** [comment]
> I can't imagine this to be true for mere objects in the scene (could you give an example?), but you sure have a point with Group instances. I think this would at least justify an option for Group instances only.

OK, I think I see what you mean - objects that have different meshes in Blender won't share meshes in BDX, but objects that are added through group instances will share meshes (as I mentioned). Of course, objects that are Link Duplicated (Alt + D) will share meshes (which is fine). However, different objects with different meshes can use the same materials (like, say, different enemies all using the same Enemy spritesheet), which can be problematic.

> With the addUnique() function this would give more freedom. For example, if not reserved for Group instances only, loading scenes between game "levels", would require to keep track of when to disable/enable the option, just so that group instances would be unique and spawned objects wouldn't. I think a function would give the necessary clarity about when and which objects are added with unique meshes and/or materials. Only thoughts.

I'm not quite sure what you mean here.

___

Let me back up.

The core reason for this suggestion is to avoid needing to make unique material copies for each GameObject when it is created. With it on, each GameObject would have its own unique set of materials by default on creation. 

Meshes can also be considered for a similar option, depending on how Materials' unique setting goes, as they are shared among GameObjects, and the fact that Materials depend on the Meshes (as of the Mesh Refactoring PR).

**Comment by GoranM** [comment]
I don't think there's a need to stray from the blender model. The Mesh owns the materials, and if there's an object that needs to use the same mesh, but with different materials, it should just use a unique copy of that mesh.

Are there really that many objects that would require you to explicitly make a copy of the mesh? I mean, if most of them are entities that utilize the SpriteAnim component, they should already have a unique mesh.

If not, you could just give them a component that would, like SpriteAnim, create a unique mesh.

**Comment by SolarLune** [comment]
> Are there really that many objects that would require you to explicitly make a copy of the mesh? I mean, if most of them are entities that utilize the SpriteAnim component, they should already have a unique mesh.

For me and Gearend, yeah, there are quite a few objects that need unique materials under the current system (all GUI objects that change color, any enemies that flash or change color, along with any other objects that share materials with any of these objects). It's not a huge deal - I'm hanging back with a previous build of BDX for use with Gearend for now (though I'll probably move forward and try to fix this stuff up when I can).

> I don't think there's a need to stray from the blender model.

I wouldn't stray from the Blender model either, and am not suggesting we do. I'm just suggesting that we add an option to use copies of the mesh and materials. In practice, I believe it to be easier for each GameObject to have its own unique set of materials, rather than sharing materials.

Making a component to create a unique mesh and materials is an idea, but that seems like a waste of a component. It's not much code, and it doesn't do anything I couldn't do already manually (since I have to add the component, it's just swapping one line of code for another one, unless I'm misunderstanding you). It also wouldn't actually solve any problems caused by objects changing a material's properties before another object could make its mesh and material set unique.

I suppose it's not a huge deal, since I can just look through my code in my project to make the mesh / materials unique for a Gameobject before it alters the materials' properties. I think it'd be a nice feature to add, though.

**Comment by GoranM** [comment]
Wouldn't things like enemies already have a unique mesh, because they use the SpriteAnim component? I'm not sure what you mean by "GUI Objects", but Text objects also have a unique mesh by default, so that shouldn't be an issue.

With the component approach, I just thought it would be convenient if you want to control it based on things like properties, or something like that, but I assume that it's not something that you'll have to do in too many places, to the point where you really need a new engine feature to deal with it.

**Comment by SolarLune** [comment]
> Wouldn't things like enemies already have a unique mesh, because they use the SpriteAnim component? 

Yes, that's true, they would usually. My mistake on that one.

> I'm not sure what you mean by "GUI Objects", but Text objects also have a unique mesh by default, so that shouldn't be an issue.

By "GUI Objects", I mean objects for the GUI, like GUI icons, gauges, indicators, etc. that share a material. Text objects have unique meshes, but they still share Material references.

> With the component approach, I just thought it would be convenient if you want to control it based on things like properties, or something like that, but I assume that it's not something that you'll have to do in too many places, to the point where you really need a new engine feature to deal with it.

Hmm, I don't quite get how a Component that makes unique meshes and/or materials would help me. Could you give an example?

**Comment by GoranM** [comment]
> By "GUI Objects", I mean objects for the GUI, like GUI icons, gauges, indicators, etc. that share a material.

Why are they sharing a material if they all need to have a unique material? Shouldn't they be set to different materials to begin with, in blender?

> I don't quite get how a Component that makes unique meshes and/or materials would help me.

In thinking about it further, I can't see it either, so I guess it wouldn't.

You would still have to write the code where it's needed, but I'm not sure if that represents an amount of work that would justify an engine feature.

**Comment by SolarLune** [comment]
> Why are they sharing a material if they all need to have a unique material? Shouldn't they be set to different materials to begin with, in blender?

Until now, that wasn't necessary, as objects had unique materials. They are "supposed" to share materials if their elements are on the same material - for example, my GUI icons and widgets are on the same sprite-sheet, so they share a singular material.

**Comment by GoranM** [comment]
Until now, BDX didn't properly reflect the material setup in Blender.

Now that it does, the Blender setup needs to be correct: If you want/need different materials, you need to set different materials.

> They are "supposed" to share materials if their elements are on the same material

Their elements are on the same texture, but that doesn't bind them to a single material; Multiple materials can use the same texture, but have different values for other properties (like color, opacity, etc).

**Comment by SolarLune** [comment]
> Now that it does, the Blender setup needs to be correct: If you want/need different materials, you need to set different materials.

OK, that's the final word on the matter. I guess I'll just hang back in a separate older branch until I finish Gearend - it'll take way too much time to correct things with Gearend.

Issue closed.

**Comment by GoranM** [comment]
> it'll take way too much time to correct things

You just need to click on the button that makes the material a "single user copy". Unless you have hundreds of different GUI elements, it doesn't seem like it would take too much time, even if you had to do it manually.

Of course, you could always write a python script to do it automatically.

**Comment by SolarLune** [comment]
I'd have to do that for all GUI elements, and any other objects that share sprite sheets - it's time I just don't want to take out.

**Comment by GoranM** [comment]
You could just write a script to do it. Something like:

```python
for o in objects:
    if o.type != "MESH":
        continue
    mat = o.data.materials[0]
    if mat.users > 1:
        o.data.materials[0] = mat.copy()
```

**Comment by SolarLune** [comment]
I'd have to modify it to duplicate the material for just the necessary elements and not all materials, but that would work. Thanks.
