### ISSUE TITLE
Todo: Move Material Shaders from Bdx.matShaders to Material class Itself

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#789]
Hey, there. 

I think it'd make sense for MaterialShaders to be used on the Material itself, since we now have access to the Material class. This would be instead of the current method of applying MaterialShaders, which is to add them to the `Bdx.matShaders` HashMap.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR merged. I'll close this now. Thanks!
