### ISSUE TITLE
Bugs: Blender 2.78 Python requires extra arg with removing scenes and texts

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#790]
Just for our information. The newest version of Blender causes at least one compatibility issue:

Compare [BlendDataScenes.remove(scene)](https://www.blender.org/api/blender_python_api_2_77_0/bpy.types.BlendDataScenes.html?highlight=blenddatascenes) with [BlendDataScenes.remove(scene, do_unlink=False)](https://www.blender.org/api/blender_python_api_2_78_release/bpy.types.BlendDataScenes.html#bpy.types.BlendDataScenes).

This method is used for the BDX profiler and so it will cause an error in 2.78 when the profiler is running for the first time. I'm searching for a good solution, that will work with both versions.

Perhaps it'll be worth to report this to the Blender tracker because it's probably a mistake to set `unlink=false` by default. It seems that previous versions had `unlink=true` by default.

**Comment by SolarLune** [comment]
Hmm, this is interesting and strange. What would removing a scene without unlinking it do, then?

**Comment by GoranM** [comment]
> Perhaps it'll be worth to report this to the Blender tracker because it's probably a mistake to set unlink=false by default. It seems that previous versions had unlink=true by default.

I doubt you'll be able to find anyone who cares enough to restore the old default (even though that would be the right thing to do).

> Hmm, would it be possible to add a line to check the Blender version and call remove(scene, true) if the version's larger than 2.78?

Yes: `bpy.data.version`

**Comment by rafcolson** [comment]
>I doubt you'll be able to find anyone who cares enough to restore the old default (even though that would be the right thing to do).

It appears that a sacrifice had to be made. If it wasn't for removing scenes, the default would be changed for removing something else, I assume. Anyway, you can read about it in [this Task](https://developer.blender.org/T49579).

I'm trying @SolarLune 's suggestion as soon as I can build current master.

**Comment by GoranM** [comment]
Ah, it was a wider API consistency thing.

That actually makes sense.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Thanks for merging.

I've submitted another PR for fixing the same issue with *Making internal java files external*.

We also have to investigate if this API change will also influence removing the extra created meshes when applying modifiers in [exporter.py](https://github.com/GoranM/bdx/blob/ad685883ff675776fa35567b61b104e04eba63a4/blender/bdx/exporter.py#L134).

**Comment by rafcolson** [comment]
PR's merged. Thanks.

**Comment by rafcolson** [comment]
Reopened. It seems that [with the new version Blender 2.79, the `unlink` argument by default will be `True` instead of `False`](https://developer.blender.org/rB44b691dc658). PR follows.

**Comment by rafcolson** [comment]
As far as I can tell everything seems to work fine with Blender 2.79, so I'm closing this.
