### ISSUE TITLE
Suggestion: Add multiple objects as instances for groups with multiple objects

### ISSUE THREAD

**Issue by christ182** [GoranM/bdx#798]
Blender groups can have multiple objects in a group. However, bdx adds only one object. 

This will help with instantiating objects with multiple components. 

For example, if I would like to have a non-rotating collision bound for my halo objects,
I would group the halo object with its collision object and then add it to the world via add group instance. 

I know scene.add works for parented objects, however, adding these objects as instances will greatly help in level design using blender.

anyone think this is a good idea?

**Comment by SolarLune** [comment]
BDX already supports multiple objects being instanced in a group, they just have to be parented to a root object in that group. 

For your example, you could parent the halo object to its collision bounds, and place both objects in the group.

**Comment by christ182** [comment]
I see, I also found out that they don't even have to be in the same group, they just have to be parented to the group instance. But I guess putting them at the same group will be better because they are rendered in blender.

I never really tried that before. thanks!

**Comment by SolarLune** [comment]
No problem!
