### ISSUE TITLE
Suggestion: Enums for GameObject.bodyType() and boundsType()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#802]
I suggest replacing the string constant approach with these functions with something that takes enums, so that one doesn't have to worry about spelling, and so that it's easier to infer the available types (i.e. you don't have to check the Wiki to know how to spell "NO_COLLISION").

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
OK, this seems like it works. Let me know if there's something problematic.

**Comment by rafcolson** [comment]
Nice change.

**Comment by SolarLune** [comment]
This was merged, so I'll close this now. Thanks.
