### ISSUE TITLE
Suggestion: GameObject.join(list) & GameObject.join(map)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#809]
Continuing from our discussion in #786:

To be removed:
- `GameObject.joinedMeshObjects`
- `GameObject.updateJoinedMesh()`

To be added:
- `GameObject.join(HashMap<Mesh, ArrayList<Matrix4f>>> map, boolean include=false)`
- `GameObject.join(ArrayList<GameObject>> list, boolean include=false)`

The method on `GameObject` then would also preserve the transform of that object.

Why "join" and not "add"?

Because "adding" implies that the initial mesh is still a part of the whole. We can add an optional argument to include the initial mesh though.

**Comment by GoranM** [comment]
I'm not really sure what `Mesh.join` actually does, given the arguments.

Also, if there's no `joinedMeshObjects` list, and no method that updates the mesh based on the current state of those objects, how are you going to update the mesh?

**Comment by SolarLune** [comment]
> Because "adding" implies that the initial mesh is still a part of the whole. We can add an optional argument to include the initial mesh though.

"Join" also, to me, implies that the initial mesh is part of the whole - you're joining the specified object to the calling one. 

I guess you're thinking like, "Join these meshes together in me, the calling GameObject"? I think of it like, "Add (join) these meshes _to_ me, the calling GameObject".
__________

 Similar to Goran, could you explain how meshes are joined under this suggested format?

**Comment by rafcolson** [comment]
Similar to Goran, could you explain how meshes are joined under this suggested format?

**Comment by rafcolson** [comment]
>I guess you're thinking like, "Join these meshes together in me, the calling GameObject"? I think of it like, "Add (join) these meshes to me, the calling GameObject".

A more descriptive name would probably be `Mesh.replaceJoined()`. But I'm open to `Mesh.add()` but then the extra argument would have to be `exclude=false` by default.

**Comment by SolarLune** [comment]
> Mesh.join() takes a map of lists of transforms per mesh. (I replaced String with Mesh to be able to join unique meshes too). It does the same thing what GameObject.updateJoinedMesh() does, except for updating things related to the GameObject, such as the transform and physics.

Cool, OK, I think I get it. 

I think it would be easier to have the `join()` function that takes GameObjects to be on the Mesh class as well. It does the same thing as the Mesh's `join()` function, it just takes into account the meshes' GameObject transforms. Putting it on GameObject would also mean that people have to look to a different place in the API to see what it does.

I think I see the utility of the Mesh / Transform joining approach (since you don't need to actually create GameObjects to merge these together), so that's fine.

> I think it was a mistake to have a joinedMeshObjects list on GameObject, while you might as well create such a list yourself before adding objects to it. So the list argument in GameObject.join(list, include=false) would function as that "joined mesh objects" list.

I agree - I think it's simpler to just have a list of GameObjects that you want to join and pass that to the joining function. Then we don't need an update function at all.

> But I'm open to Mesh.add() but then the extra argument would have to be exclude=false by default.

What about if the `add()` function were additive and didn't take an `include` argument, but we had another function that erases the vertices on a Mesh? So you could just call:

```java
empty.mesh().clear();                    // Clean start
empty.mesh().add(listOfMergingObjects);  // Graphics
empty.updateBody(empty.mesh());          // Physics
```

A `sub()` function to subtract vertices / meshes would be useful, too, especially for sandbox / building games. That's something for another issue, though.

**Comment by SolarLune** [comment]
> Mesh.join() takes a map of lists of transforms per mesh. (I replaced String with Mesh to be able to join unique meshes too). It does the same thing what GameObject.updateJoinedMesh() does, except for updating things related to the GameObject, such as the transform and physics.

Wait, a joining function on the Mesh shouldn't do anything with the physics, I think. I think it's supposed to be strictly the visual appearance of the GameObject, and Meshes shouldn't influence the physics body of the GameObject if it can be avoided.

**Comment by GoranM** [comment]
Why not just have something like `Scene.createMergedMesh(objects)`?

It seems like that would avoid the "join" ambiguities as they relate to Mesh and GameObject, and it would allow the user to include/exclude whatever objects they wish.

**Comment by SolarLune** [comment]
Ohh, so it would create a Mesh that you could use on a GameObject. That's one approach (and not a bad one), but it wouldn't allow us to modify a Mesh, which isn't ideal. It also seems a bit odd in that it's not something you might expect to find in the Scene class.

**Comment by GoranM** [comment]
> but it wouldn't allow us to modify a Mesh

Why not? A new mesh has the same accessibility as any other mesh (as far as I know).

... Note that updateJoinedMesh doesn't actually "update" the existing mesh; [It creates a new one](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/GameObject.java#L949).

> It also seems a bit odd in that it's not something you might expect to find in the Scene class.

Yeah, a static method on Mesh would probably make more sense.

**Comment by SolarLune** [comment]
> Why not? A new mesh has the same accessibility as any other mesh (as far as I know).

I meant that this doesn't do anything to establish a means to add to an existing mesh, it just makes a new one (like the solution we have now, as you pointed out). 

I thought we could take this opportunity to replace the existing mesh joining system with one that would, when it's finished, allow us to add to or subtract from existing meshes.

**Comment by rafcolson** [comment]
>I think it would be easier to have the `join()` function that takes GameObjects to be on the Mesh class as well.

I wonder if this would be necessary, because the same function already exists on `GameObject`. And I think it should remain there. If it were on `Mesh`, we wouldn't be able to preserve the transform of the potential object. And unless the function would have an extra argument `offsetTransform`, the potential object would have to positioned at (0, 0, 0) always, which more or like is the same problem we were having with `GameObject.updateJoinedMesh()` until yesterday.

The `Mesh.join(map)` method gives a more freedom. You can achieve the same thing by collecting the transforms manually. Instead of passing in a list of objects, you'd now pass in a map of meshes with transforms.
```java
HashMap<Mesh, ArrayList<Matrix4f>> map = new HashMap<Mesh, ArrayList<Matrix4f>>();
for (GameObject g : objects){
	Mesh mesh = g.mesh();
	ArrayList<Matrix4f> l;
	if (!map.containsKey(mesh){
		l = new ArrayList<Matrix4f>();
	}else{
		l = map.get(mesh);
	}
	l.put(g.transform()); // modify transforms here
}
mesh().join(map);
updateBody();
```
This would actually be the basis of the code for `GameObject.join(objects)`.

>Wait, a joining function on the Mesh shouldn't do anything with the physics, I think. I think it's supposed to be strictly the visual appearance of the GameObject, and Meshes shouldn't influence the physics body of the GameObject if it can be avoided.

It won't. As I said, it does the same thing what `GameObject.updateJoinedMesh()` does, *except* for updating [...] physics.

>I thought we could take this opportunity to replace the existing mesh joining system with one that would, when it's finished, allow us to add to or subtract from existing meshes.

This is already possible (and will remain so). In the Joiner testing apk I made some time ago, you can tap your finger on a cube so it would be subtracted from the mesh. The only problem is that you'd need invisible STATIC objects, which take a lot of physics calculation. However, there are other tricks to do the same in some circumstances. The transform of a "brick", for example, could be calculated by the hit position and normal of the wall (the joined object), I suppose.

**Comment by SolarLune** [comment]
> I wonder if this would be necessary, because the same function already exists on GameObject. And I think it should remain there. If it were on Mesh, we wouldn't be able to preserve the transform of the potential object.

How so? Why not just have the `GameObject.join()` function be on the `Mesh`? It wouldn't change how the function works, just where it is in the codebase.

> It won't. As I said, it does the same thing what GameObject.updateJoinedMesh() does, except for updating [...] physics.

Ah, OK, I misunderstood.

> In the Joiner testing apk I made some time ago, you can tap your finger on a cube so it would be subtracted from the mesh. The only problem is that you'd need invisible STATIC objects, which take a lot of physics calculation. 

Cool! I haven't seen the APK - it sounds like you're keeping the objects around so you can make a new mesh from them whenever you need to add or subtract from the terrain? So clicking deletes or adds the objects, and then re-creates the mesh for the terrain from the existing GameObjects?

> The transform of a "brick", for example, could be calculated by the hit position and normal of the wall (the joined object), I suppose.

Yeah, that's where I'd imagine the new `join()` function to come in handy (though I guess you could do the same by just using a single GameObject and moving it around to where you want).

**Comment by rafcolson** [comment]
>It wouldn't change how the function works, just where it is in the codebase.

Yes it would, unfortunately. On `Mesh` the function wouldn't be able to build the mesh relative to the transform of the potential object, on `GameObject` it would take the transform of that GameObject. That also means that with the `Mesh` function you're forced to position the potential object at (0, 0, 0). It would make the function as awkward as the `GameObject.updateJoinedMesh()` was before yesterday, as I have been saying.

With that function we're also not joining "meshes", but "objects". I think this implies that the result would be an object. 

>So clicking deletes or adds the objects, and then re-creates the mesh for the terrain from the existing GameObjects?

I'll have look it up. It has been a while, but I'll keep you posted.

**Comment by SolarLune** [comment]
> Yes it would, unfortunately...

Hmm, I see what you mean. 

I guess for usability, it's fine for a `join()` function to be on the GameObject. I guess it'd just internally call `Mesh.join()` with the transforms for each Mesh offset from the calling object's (at least position-wise)?

> With a join(list) function we're also not joining "meshes", but "objects". I think this implies that the result would be an object too.

I'm not sure what you mean by this - no matter what happens, the joining process doesn't produce GameObjects, but Meshes...?

> I'll have to look it up. It has been a while, but I'll keep you posted.

That's how I'm thinking it was done, because I don't know of another way to do it.

It seems wasteful to have to recreate (or keep around) objects that you want to merge in case you want to delete them, and recreate an entire Mesh whenever anything changes.

**Comment by GoranM** [comment]
> I meant that this doesn't do anything to establish a means to add to an existing mesh, it just makes a new one (like the solution we have now, as you pointed out).
>
>I thought we could take this opportunity to replace the existing mesh joining system with one that would, when it's finished, allow us to add to or subtract from existing meshes.

I could be mistaken, but I don't think you can simply "grow" an opengl vertex buffer. You can allocate a vertex buffer, and you can push data into that allocated space, but if you need more space, you'll need to create a new buffer of sufficient size.

> On Mesh the function wouldn't be able to build the mesh relative to the transform of the potential object, on GameObject it would, by taking the transform of that GameObject.

If your goal is to build it relative to some transform (instead of just world space vertices), why is there a need for `Mesh.join` in the first place?

I mean, wouldn't `GameObject.join` be sufficient to do everything you want?

**Comment by SolarLune** [comment]
> I could be mistaken, but I don't think you can simply "grow" an opengl vertex buffer. You can allocate a vertex buffer, and you can push data into that allocated space, but if you need more space, you'll need to create a new buffer of sufficient size.

Oh, really? If so, then we would need to make a new Mesh anyway. Hm...

**Comment by rafcolson** [comment]
>Oh, really? If so, then we would need to make a new Mesh anyway. Hm...

I'm afraid so. But if the `tvaMap` (transformed vertex arrays per material) and `lenMap` (number of indices per material) are stored, it should be possible to subtract vertexes from there. This would save a lot of computation. To support such method we could maybe construct the `join` method out of two other methods:
- `Mesh.joinData(map) - data
- `Mesh.join(data)`
Data being a tvaMap and lenMap. To subtract a mesh with transform, one would first get its data, and then remove the tva (list) from the stored tvaMap, and subtract the length from the lenMap. And finally join the new data.

It's a separate suggestion, but I think it could work.

>If your goal is to build it relative to some transform (instead of just world space vertices), why is there a need for `Mesh.join` in the first place?
>
>I mean, wouldn't `GameObject.join` be sufficient to do everything you want?

You're making a point. I couldn't think of a reason why `join(map)` should be on `Mesh`, and couldn't be on `GameObject`. Updating the body is more or like a necessity anyway, to be able to detect if an object is inside the camera's frustum or not. But we could something about that, by not getting `dimHalved` through the body, but through `dimensionsNoScale`.

So yes, I think it would be better to change my suggestion to:
- GameObject.join(list, include=false)
- GameObject.join(map, include=false)
With those I think I can do everything.

@SolarLune What do you think?

**Comment by SolarLune** [comment]
> So yes, I think it would be better to change my suggestion to:

Yeah, I think that sounds fine. Subtracting meshes does sound useful, but I think it sounds like it might be a bit much for this suggestion. I'd be fine with just focusing on changing up the `join()` functions first, as you suggested.

**Comment by rafcolson** [comment]
Okay. I'll go ahead. Thanks. I assume it's also good for you @GoranM ?

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged and API updated. Thanks.
