### ISSUE TITLE
Question: about GameObject.transform()

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#812]
I'm always forgetting that the transform doesn't include the scaling of the object. But I wonder, why is it like so? I noticed there are no methods to set or get a Vector3f scale from Matrix4f, only a float. I that the reason?

Edit: I also noticed that jbullet's Transform doesn't support scaling.

**Comment by GoranM** [comment]
Bullet requires the transform to be of unit scale, and it will actually enforce that; if you pass in a scaled transform, the physics simulation will make it unit scale, which wipes out whatever scaling was there previously.

So that's why scale is tracked separately.

**Comment by rafcolson** [comment]
That's unfortunate. But couldn't we return a scaled transform anyway? And when applying a scaled transform do what is done now, except also apply the scale by extracting it from the transform? Something like this:

```java
	public Matrix4f transform(){
		Transform t = new Transform();
		body.getWorldTransform(t);

		Vector3f v = new Vector3f();
		for (int i = 0; i < 3; ++i){
		    t.basis.getColumn(i, v);
		    v.normalize();
		    t.basis.setColumn(i, v);
		}
		
		Matrix4f m = new Matrix4f();
		t.getMatrix(m);
		
		// add scale
		m.setRow(3, scale.x, scale.y, scale.z, 0);
		
		return m;
	}
	
	public void transform(Matrix4f mat, boolean updateLocal){
		activate();
		
		// apply scale
		scale(mat.m30, mat.m31, mat.m33);
		
		Transform t = new Transform();
		t.set(mat);
		
		Vector3f v = new Vector3f();
		for (int i = 0; i < 3; ++i){
		    t.basis.getColumn(i, v);
		    v.normalize();
		    t.basis.setColumn(i, v);
		}

		body.setWorldTransform(t);

		// required for static objects:
		body.getMotionState().setWorldTransform(t);
		if (body.isInWorld() && body.isStaticOrKinematicObject()){
			scene.world.updateSingleAabb(body);
			for (GameObject g : touchingObjects)
				g.activate();
		}
		//
		
		updateChildTransforms();

		if (parent != null && updateLocal){
			updateLocalTransform();
		}
	}

```
However, transforming gets more expensive because scaling is, so it would probably not be a good idea.

**Comment by GoranM** [comment]
It may be best to have our own custom transform (a Matrix4f on GameObject), and have everything else operate based on that, instead of operating directly on the bullet body transform.

There are more than a few places where scale is being "injected", and it would be nice if we could reduce it to just one place.

**Comment by rafcolson** [comment]
Sounds like a good idea. Would you like to go into this, or could I?

**Comment by rafcolson** [comment]
Where should the scale be in the matrix? Should it be in the orientation components like it is in Blender with `matrix_world`? Would putting the scale in the 4th row (m30, m31, m32) be unconventional?

**Comment by GoranM** [comment]
> Would you like to go into this, or could I?

I don't plan to work on it, so if you want to, feel free.

> Would putting the scale in the 4th row (m30, m31, m32) be unconventional?

... As far as I know, that wouldn't even create the correct matrix, so I'm not really sure what you mean by that.

The scale must be encoded in the length of the axis vectors that define orientation. That's the only arrangement by which the scale will be applied when one matrix is used to transform another.

**Comment by rafcolson** [comment]
So, I'm working on the new implementation. But I have a question.

```python
transform = sum([list(v) for v in bpy.context.object.matrix_world.col], [])
```
Is there a reason why a transposed matrix is exported? I thought Blender's `matrix_world` and LibGdx's `modelInstance.transform` are similar, right?

**Comment by GoranM** [comment]
> Is there a reason why a transposed matrix is exported?

The exporter doesn't transpose the blender matrix, it simply serializes the blender matrix into opengl format, which is just an array of floats that represent column values, laid out in contiguous memory.

> I thought Blender's matrix_world and LibGdx's modelInstance.transform are similar, right?

They're both column-major order, so their layout should be identical.

> I found my answer. The modelInstance.transform is the transposed matrix_world.

Can you elaborate?

Based on what I said above, that should not be the case.

**Comment by rafcolson** [comment]
>The exporter doesn't transpose the blender matrix, it simply serializes the blender matrix into opengl format, which is just an array of floats that represent column values, laid out in contiguous memory.

As far as I can understand, the matrix is serialized by transposing data from the columns to what would be the rows, if the result was a matrix. I used this term to explain my problem, but I agree that I'd better speak about serialization next time because the result is a float array.

>They're both column-major order, so their layout should be identical.

Not exactly, if by "layout" you mean the behavior of both classes. Whilst `Matrix4` is in [column major order](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/math/Matrix4.html), which means the first column would typically be the three values to define orientation on the X-axis, this is not the case with `matrix_world`.

However, the layouts of `Matrix4f` and `matrix_world` are identical. That's why I chose to export in row major order (so not serialized). [Here](https://github.com/GoranM/bdx/blob/master/extern/gwt-vecmath/src/javax/vecmath/Matrix4f.java#L193-L194) you can see that `Matrix4f` supposes `m01=v[1]`, in contrary to [here](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/math/Matrix4.java#L33-L71), where `Matrix4` supposes `M01=4`.

`GameObject.transform() - Matrix4f` is in row based order, so `body.setWorldTransform(new Transform(transform()))` can be applied. But to set `modelInstance.transform` the transform first has to be serialized (by transposing).

**Comment by GoranM** [comment]
> As far as I can understand, the matrix is serialized by transposing data from the columns to what would be the rows, if the result was a matrix. I used this term to explain my problem, but I agree that I'd better speak about serialization next time because the result is a float array.

Whey you say "modelInstance.transform is the transposed matrix_world", you're implying that `mi_trans.val[mi_trans.M01] == matrix_world[1][0]` will always evaluate to true, which is not the case.

> Not exactly, if by "layout" you mean the behavior of both classes.

Saying that they have the same order/layout was incorrect.

The point I was trying to make is that they should be the same matrix, with the same values for each (row,col) coordinate; One should not be a transpose of the other, irrespective of the internal memory layout.

> However, the layouts of Matrix4f and matrix_world are identical. That's why I chose to export in row major order (so not serialized). Here you can see that Matrix4f supposes m01=v[1], in contrary to here, where Matrix4 supposes M01=4.

Right, but keep in mind that layout doesn't necessarily define how values are set, and what kind of transform the matrix actually represents. For example, the function that we're using to initially set the bullet transform expects column-major order.

**Comment by rafcolson** [comment]
>When you say "modelInstance.transform is the transposed matrix_world", you're implying that `mi_trans.val[mi_trans.M01] == matrix_world[1][0]` will always evaluate to true, which is not the case.

What I meant to say is that `modelInstance.transform.val` is the transposed `sum([list(v) for v in matrix_world.row], [])`, but I see your point. Wrong choice of words.

>The point I was trying to make is that they should be the same matrix, with the same values for each (row,col) coordinate; One should not be a transpose of the other, irrespective of the internal memory layout.

I think it's a matter of perspective. `matrix_world` is not an array but a collection of vectors, each representing a row. Assuming that the array would be the sum of the rows, this will not be equal to `modelInstance.transform.val`. Assuming that the array would be the sum of the columns, this will. Because the basis of `matrix_world` consists out of vectors, each representing a row, I was assuming that the former was true.

>Right, but keep in mind that layout doesn't necessarily define how values are set, and what kind of transform the matrix actually represents. For example, the function that we're using to initially set the bullet transform expects column-major order.

I'll do. After investigating all of this, I decided to export in row major order, in accordance to `Matrix4f`, and also changed the way the body is initialized, partially because I'm first extracting the matrix to get the scale and the unscaled matrix, to set the scale of the shape and to set the transform of the body, to avoid a `g.transform(new Matrix4f(trans)))` call. But that's for later.

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR updated. (should be done now)

**Comment by rafcolson** [comment]
PR merged! Thanks.
