### ISSUE TITLE
Suggestion: Scene.getBoundingArea()

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#813]
Hey, there. I thought it might be cool to add a function to returns the outer bounds of a collection of GameObjects / points?

I'm prototyping something that makes use of this, and so I made such a function. Just was wondering if it's worth adding to the core API.

**Comment by GoranM** [comment]
It doesn't really seem like something that has a sufficiently wide utility to justify engine inclusion.

**Comment by SolarLune** [comment]
Yeah, I thought it's kind of a specific use-case. Thanks.
