### ISSUE TITLE
GWT Not Compiling

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#814]
Hey, 'sup. So GWT isn't compiling on my machine due to the OutOfMemory class in [GameObject.java at line 955](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/GameObject.java#L955). Thanks to the LibGDX IRC for giving me a link to the [info](https://github.com/gwtproject/gwt-site/blob/408ba32d25e032026148e06287db0d3e64cead4e/src/main/markdown/doc/latest/RefJreEmulation.md) for what Java methods GWT emulates for us to peruse at our convenience.

Since it won't compile if we leave it in there, I imagine we have to go with another route. Either we could simply remove the `OutOfMemoryError` block (and whichever others that are in the codebase), or perhaps replace it with a generic `Error`? 

Replacing it with `Error` seems to work on my machine.

**Comment by GoranM** [comment]
I'm fine with whatever you decide, as long as it resolves the issue.

**Comment by SolarLune** [comment]
OK, PR submitted.

**Comment by SolarLune** [comment]
PR merged. I'll close this now and add some relevant GWT-building info to the Wiki.
