### ISSUE TITLE
Suggestion: Vector*f.scale(Vector*f v)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#817]
Sometimes we just want to scale the vector and not return a copy.

**Comment by GoranM** [comment]
We already have negate() and negated().

Also, scaling by a vector doesn't seem common enough to justify a new method.

**Comment by rafcolson** [comment]
>Also, scaling by a vector doesn't seem common enough to justify a new method.

Also `Vector3f.mul(Vector3f v)` was added to the BDX conveniences, which is the same thing, except for returning a new Vector3f. The reason why I'm asking is because in some circumstances, especially with many calls in one logic tick, I'd like to keep the garbage collector as empty as possible.

Each time a new Vector3f is created to be disposed immediately after, it gets into the garbage collector, right?

**Comment by GoranM** [comment]
> Also `Vector3f.mul(Vector3f v)` was added to the BDX conveniences

I'm questioning if that addition was really necessary. Assuming it was, it should have been called `scaled`. I also think that `mul(float)` should have probably been called `scaled(float)`, because that would actually be consistent with our existing naming convention.

I don't know how much code would break if we were to make those changes ...

> I was think of this operation

The meaning of `invert` is not that obvious for vectors.

Also, it doesn't seem like something that one would need often enough to justify a method.

**Comment by rafcolson** [comment]
>I'm questioning if that addition was really necessary. Assuming it was, it should have been called `scaled`. [...] I don't know how much code would break if we were to make those changes ...

It would brake a lot, which means such an addition was useful, right?

>I also think that `mul(float)` should have probably been called `scaled(float)`, because that would actually be consistent with our existing naming convention.

Unless `plus(Vector3f)` becomes `added(Vector3f)`, `minus(Vector3f)` becomes 'subbed(Vector3f)` and `div(Vector3f)` becomes `divide(Vector3f)` with a counterpart `divided(Vector3f) , I think `mul(Vector3f)` methods are not inconsistent with our existing naming convention.

I don't mind it like it is, but if you think it would be worth it to make all of these changes, I can. But that would be another suggestion.

So if I'm understanding correctly it's okay to add `Vector3f.scale(Vector3f)` and `Vector2f.scale(Vector2f)`?

**Comment by GoranM** [comment]
> Unless plus(Vector3f) becomes added(Vector3f), minus(Vector3f) becomes subbed(Vector3f) and div(Vector3f) becomes divide(Vector3f) with a counterpart divided(Vector3f) , I think mul(Vector3f) is not inconsistent with our existing naming convention.

Our naming convention is "operation" for methods that affect the calling object, and "operationed" for methods that return a copy without affecting the calling object.

The methods you list are also not consistent with that convention, but changing `add` and `minus` now would probably break a lot of code (not just in the engine, but in the game code for the few BDX projects that are currently under development), so it's probably best to leave that as it is.

It's ok to have a bit of inconsistency here and there, but I would like to avoid it wherever possible.

> So if I'm understanding correctly it's okay to add Vector3f.scale(Vector3f) and Vector2f.scale(Vector2f)?

Yeah, I guess that would be fine.

**Comment by rafcolson** [comment]
Thanks. PR updated.

**Comment by rafcolson** [comment]
Merged.
