### ISSUE TITLE
Suggestion: Matrix3f & Matrix4f - static methods to get identity matrix

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#819]
It would be nice to have a method to get the identity directly.
- `Matrix3f.identity() - Matrix3f`
- `Matrix4f.identity() - Matrix4f`

Question on the side:

We already have `Matrix3f.rotation(Vector3f axis, float angle)`, which is lower case. But I wonder, wouldn't it be better for static final methods to start with an upper case letter? Then there's a way to distinguish those from the rest.

**Comment by GoranM** [comment]
Ok.

**Comment by rafcolson** [comment]
As for my question on the side. @GoranM & @SolarLune , what do you think?

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Ok. Thanks.
