### ISSUE TITLE
Suggestion: Aseprite Integration

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#823]
Hey, there. So basically, when I do animations, I find that often times, I'm adding duplicate frames in to properly time animations. It's not horrible, but it is kind of awkward. Here's an intro animation, for example, from Gearend:

```java
spriteAnim.add("anim", 0, new int[]{0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 4, 5, 5, 5, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 10, 8,
        11, 12, 13, 14, 13, 14, 13, 14, 13, 14, 11, 12, 8, 8, 8, 8, 8, 8, 8, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 17, 18, 19, 20, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
        22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 24, 25, 26, 27, 27, 28, 28, 29, 29, 30, 30, 30, 30, 31, 32, 33, 33, 33, 34, 35, 35, 36, 36, 36, 37, 38, 38, 38, 39, 39, 39, 39, 38, 40, 41,
        42, 42, 42, 42, 43, 43, 44, 44, 45, 46, 47, 48, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49,
        49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49}, 30, false);
```

Some of that is necessary to get the animation across, but there's a lot of duplicate frames here, as well.

I was going to suggest some sort of object that could be added to an animation that the SpriteAnim component could read to indicate that a frame could be duplicated, but I think it would be more beneficial to add basic [Aseprite](https://www.aseprite.org/) integration into the engine. 

Aseprite can actually export a plain JSON file containing the timing and tag information in addition to the spritesheet image - it should be relatively trivial adding a function to load that info in from the exported JSON.

We'd have to change some things around a bit - I think we'd need to add a Frame class, add the amount of time a frame should last to the Frame itself, time the SpriteAnim using the Frame timings, and create some load functions to actually create the needed data, but I think the advantages (automatic animation loading, automatic animation creation, and tagging) would outweigh the additional code.

Thoughts?

**Comment by SolarLune** [comment]
Well, I ended up just doing this, so let me know how the code looks:

https://github.com/SolarLune/bdx/commit/2616ec1c1bcf7c4f5efa287281120d6622dddc6f

A point of interest is that the Animation class should probably have control over whether it plays backwards or not, but that is being directly written to by SpriteAnim.

**Comment by rafcolson** [comment]
Nice tool. A couple of thoughts:

- I noticed that Aseprite is not free software. However, the older version is, but it doesn't seem to support exporting to `*.json`, does it? I couldn't find anything in the GUI.
- Does integration actually require changes to the existing code-base? If not, why not make a Component `AsepriteAnimation.java`. If that works it doesn't really have to be part of BDX, unless it is confirmed that it would be something worth to add.
- In my own opinion, it shouldn't be entangled with `SpriteAnim`, especially because `SpriteAnim` was not intended to be dependent of other software, especially payed software. That's what I thought, but I could be wrong.
- As a component, I think this could perfectly serve as third-party software. Useful nonetheless. And who's to say that in the future there's a page in the Bdx Wiki, listing dozens of such useful components. Not part of BDX, but as some sort of community "add-on".

**Comment by SolarLune** [comment]
Thanks!

> I noticed that Aseprite is not free software. However, the older version is, but it doesn't seem to support exporting to *.json, does it? I couldn't find anything in the GUI.

Aseprite does indeed export to JSON. It's under the SpriteSheet export option.

> Does integration actually require changes to the existing code-base? If not, why not make a Component AsepriteAnimation.java. If that works it doesn't really have to be part of BDX, unless it is confirmed that it would be something worth to add.

Well, I could change this to be an `AsepriteAnim` component, but this fundamentally works very similarly to a normal `SpriteAnim` component while still altering SpriteAnim as much as necessary to provide the needed functionality. I guess I could make it work as a Component class derivative of `SpriteAnim`, though.

> In my own opinion, it shouldn't be entangled with SpriteAnim, especially because SpriteAnim was not intended to be dependent of other software, especially payed software. 

This addition changes how SpriteAnim *can* work, not how it has to. This addition would basically be completely backwards compatible (the only somewhat major change is that Animations themselves no longer have FPS fields, and negative FPS speeds on Animations no longer influence playback direction. This is correct, in my opinion, as FPS is supposed to be a value that indicates frames per second, not play direction). 

So if you wanted to do things the old way, you'd still be able to.

> As a component, I think this could perfectly serve as third-party software. 

Hmm, I guess I agree that it might be good to keep extraneous program-specific stuff out of master.

**Comment by GoranM** [comment]
> Hmm, I guess I agree that it might be good to keep extraneous program-specific stuff out of master.

I also think that would be best.

**Comment by SolarLune** [comment]
OK, I'll add it to my helper module, then. 

Thanks!

**Comment by rafcolson** [comment]
>Aseprite does indeed export to JSON. It's under the SpriteSheet export option.

Still can't find anything. Which free version are you using?

**Comment by SolarLune** [comment]
Oh, I'm not using the free version, I'm using the paid version. I wasn't sure if you were looking under that section - sorry.

If you want to build it yourself, that's an option. Otherwise, you can buy it.

**Comment by rafcolson** [comment]
Thanks.
