### ISSUE TITLE
Suggestion: Group instances -> multiply with scale of master

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#827]
I was not sure if this was intended, but at initialization the scale of the master object is replaced by the scale of the group instance object. While I think it should multiply with the scale instead. This is also done in Blender.

So:

``` java
g.scale(inst.scale());
```

Should be:

``` java
g.scale(g.scale().mul(inst.scale()));
```

**Comment by GoranM** [comment]
Yeah, that makes sense.

**Comment by rafcolson** [comment]
This got fixed with the referenced PR.
