### ISSUE TITLE
:html:superDev Fails

### ISSUE THREAD

**Issue by MatthewGitter** [GoranM/bdx#835]
Hi. I'm working (in Ubuntu v16.10) with BDX (v0.2.5) . Building the HTML module by running the :html:superDev Gradle task in an Ubuntu shell console fails. Gradle build details seem to imply that superDev can't process the Java OutOfMemoryError into its Javascript equivalent:
```
$ ./gradlew :html:superDev
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
[...]
Copying resources from ../android/assets to war/
/home/coder/BDXProjects/BDXTest/html/../android/assets
/home/coder/BDXProjects/BDXTest/html/assets
Compiling module com.example.bdxtest.GdxDefinitionSuperdev
   [ERROR] Errors in 'com/nilunder/bdx/Scene.java'
      [ERROR] Line 736: No source code is available for type java.lang.OutOfMemoryError; did you forget to inherit a required module?
[...]
  java.lang.StringIndexOutOfBoundsException
  com.badlogic.gdx.graphics.g3d.particles.ResourceData.AssetData
   [ERROR] Errors in 'com/nilunder/bdx/GameObject.java'
      [ERROR] Line 930: No source code is available for type java.lang.OutOfMemoryError; did you forget to inherit a required module?
:html:draftCompileGwt FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':html:draftCompileGwt'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
```
FWIW, the android module's build.gradle includes:
```
android {
    buildToolsVersion "25.0.1"
    compileSdkVersion 24
[...]
    defaultConfig {
        applicationId "com.example.bdxtest"
        minSdkVersion 8
        targetSdkVersion 20
   }
}
```
And the "Sources for Android SDK" is installed for API 20 and 24 (and for 21-23).

However, [the GWT project docs say](http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsCompatibility.html) that OutOfMemoryError should be converted into a generic JavaScriptException:

> - Exceptions: try, catch, finally and user-defined exceptions are supported as normal, although Throwable.getStackTrace() is not meaningfully supported in production mode.
>
>   - Note: Several fundamental exceptions implicitly produced by the Java VM, most notably NullPointerException, StackOverflowError, and **OutOfMemoryError**, do not occur in production mode as such. Instead, **a JavaScriptException is produced for any implicitly generated exceptions**. This is because the nature of the underlying JavaScript exception cannot be reliably mapped onto the appropriate Java exception type.

Running the same Gradle :html:superDev task in a separate libGDX project generated directly with gdx-setup.jar (for libGDX v1.9.4) builds the HTML module and runs/debugs it in the local httpd/browser as expected.

**Comment by SolarLune** [comment]
Hey, there. 

I believe we resolved this issue already in issue #814. The related commit, https://github.com/GoranM/bdx/commit/cf2716cfcf3c6b485b49754c4eee472f9d866bbc, switches out `OutOfMemoryErrors` with generic `Errors` so that HTML builds fine; there just hasn't been a release that included this fix. If you need a release ASAP, lemme know and I can just package and send you a build; otherwise, maybe @GoranM would be cool with just drafting a new release (perhaps after some minor profiler improvements / fixes).

> However, the GWT project docs say that OutOfMemoryError should be converted into a generic JavaScriptException:

That's interesting, because it definitely isn't doing that silently, haha. I think gradle / libGDX don't use the most recent GWT resources? I believe they use an older version, anyway; [here](https://github.com/gwtproject/gwt-site/blob/408ba32d25e032026148e06287db0d3e64cead4e/src/main/markdown/doc/latest/RefJreEmulation.md)'s a page that shows the list of supported language pieces.

**Comment by MatthewGitter** [comment]
Hiya. Thanks for the quick reply.

Yes, I'd love if @GoranM would draft a new release with those changes, so I don't have to be special (and the special case sysadmin tasks that would entail, even if just tracking a BDX zipfile), and so everyone else can share the joy. But if you could send me a build with that fix (and whatever others are ready, can't be too bugfixed, rich or thin ya know ;) ASAP that would be great. I'd love to work with the fix through this Thanksgiving long weekend.

BTW thanks to you and the BDX team for this excellent environment. I started building one myself on libGDX a couple years ago, but couldn't get it to anything usefu before I ran out of "free time"l. So I have lots of pent-up work in BDX waiting to do :).

**Comment by SolarLune** [comment]
OK, I'll wait to see what @GoranM says; if he'd rather wait a bit, I can e-mail you a build.

> BTW thanks to you and the BDX team for this excellent environment. 

Oh, you're welcome!

**Comment by MatthewGitter** [comment]
> OK, I'll wait to see what @GoranM says; if he'd rather wait a bit, I can e-mail you a build.

If possible, maybe you could wait only until Friday, and if Goran doesn't come across then email me a build so I can try working with it this weekend. Thanks again.

**Comment by GoranM** [comment]
New release is up: https://github.com/GoranM/bdx/releases/tag/v0.2.6

**Comment by MatthewGitter** [comment]
This is the most responsive project team ever: not just release on request at literally the eleventh hour to a new user commenter, but somehow released a week retroactively! That's positively tachyonic.

Thanks for Giving.

**Comment by MatthewGitter** [comment]
It works! :html:superDev brings Sacky to the browser :).

![bdx sacky superdev-test ok](https://cloud.githubusercontent.com/assets/9749212/20600945/13d5b002-b224-11e6-8625-830e4cb3239e.png)

**Comment by SolarLune** [comment]
Cool! 

Glad to hear everything worked out fine, and I hope you like working with BDX. Feel free to close the issue if everything's solved.

**Comment by GoranM** [comment]
> somehow released a week retroactively! That's positively tachyonic.

Heh, well, we can't move faster than the speed of light, but we can count on github to list the date of the last commit included in the release, instead of the date on which the release was actually created.

I hope you won't think any less of us now that we're revealed to be mere mortals :)

**Comment by MatthewGitter** [comment]
Actually, doing it without tachyons but with just Github idiosyncrasies is even more impressive :).
