### ISSUE TITLE
Physics Substeps for Bdx.speed

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#837]
So basically, thanks to the previous discussion on improving the profiler in #832, the idea of a global speed modifier was suggested. This is fairly simple to implement, save for one thing:

At high speed values, the forces exerted on the physics bodies becomes greater than the engine can resolve. This means that with the default gravity, objects start fairly visibly going through floors at around 4x speed. At around 16x speed, they go through far enough to be trapped (assuming the default test scene with the block floor).

So I think we might want to consider using physics substeps, unless there's another solution?

**Comment by GoranM** [comment]
Using substeps would introduce significant complexity, and potential performance issues (http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?t=10293).

Although, even if it didn't, changing the physics simulation interval wouldn't really make sense in a debug context, because that doesn't account for the rest of the system.

If you want the ability to step through each frame, you would need to control when the main loop executes, not how much time the physics engine simulates.

**Comment by SolarLune** [comment]
Yeah, I saw that post while looking up substeps.

OK, so there's two things here - the idea of a global speed field for gameplay mechanics, and my original desire to be able to easily slow down the engine and "step forward" to see quickly-occurring bugs.

I guess I'll just forgo slowing down scenes via the profiler for now; the profiler is for profiling, and shouldn't be "upgraded" into a debugger (which is a shame in my estimation, but that's fine).

Regarding the speed modifier as it stands, even without the substeps, I suppose it works well enough for general purpose gameplay usage that it could be merged.

**Comment by GoranM** [comment]
Given the issues you outlined in your original post, I'm not sure it would be proper to say that it "works well enough".

**Comment by SolarLune** [comment]
The issue I outlined isn't anything new - that's the way the physics engine works without substeps. If forces exerted on GameObjects are too high, they phase through each other. Raising the scene's gravity higher can cause the same issue.

As an example, seeing as the solution for keeping fast-moving objects from intersecting under Unity seems to utilize ray casting, I suppose this is about as far as we can go, in a sense.

In any case, if the current physics system works well enough for BDX, then this PR works well enough, too - this PR isn't doing anything to compound or resolve the core issue with the physics engine.

**Comment by GoranM** [comment]
Having `Bdx.speed` implies that you can reliably control the speed of the whole simulation, but there's more to the simulation than just physics.

There's gamelogic, and all the things that it drives (like animation, physics independent movement/rotation, etc), along with audio, and whatever else requires management with a varying time interval.

It doesn't seem as simple as just multiplying the provided force vector ... Actually, I don't think that would be correct in cases where you're just applying an initial force (like for a basic jump), because even if the physics engine is simulating on a different interval, I think it's still using the same algorithms to resolve position over time, so changing the initial force vector would change the ultimate result of the simulation.

**Comment by SolarLune** [comment]
OK, so:

> There's gamelogic, and all the things that it drives (like animation, physics independent movement/rotation, etc), along with audio, and whatever else requires management with a varying time interval.

That's true. Because adjusting `Bdx.time` adjusts Timer's intervals, SpriteAnim adjusts automatically, so no problem there. FAnim would need a bit of adjusting, though. 

I don't know if there's much use to triggering game logic multiple times per frame - at some point, a line needs to be drawn because we can't just trigger logic frames multiple times per frame, since we don't know if the user's device will be able to handle that, right?

Multiplying audio pitch to account for the increase in speed would be nice, but we'd have to keep track of all playing audio sources and update their pitch values to account for these changes - I don't think there's an easy way of making our own custom extended Sound or Music classes for this (or volume and panning adjustment).

Maybe simply renaming `Bdx.speed` to `Bdx.physicsSpeed` or `Bdx.timeSpeed` or something would be fine. 

> It doesn't seem as simple as just multiplying the provided force vector ... Actually, I don't think that would be correct in cases where you're just applying an initial force (like for a basic jump), because even if the physics engine is simulating on a different interval, I think it's still using the same algorithms to resolve position over time, so changing the initial force vector would change the ultimate result of the simulation.

I'm not quite sure what you mean - I tested it with jumps, and as I recall it was reliably the same trajectory, regardless of the speed value I was running at the time.

On the flip-side, the forces are more powerful (though they don't change from what I've seen in GameObjects' force() / velocity() functions). So, the collision _resolutions_ can change where physics bodies end up at the end.

**Comment by GoranM** [comment]
`Bdx.physicsSpeed` would make more sense.

> I'm not quite sure what you mean - I tested it with jumps, and as I recall it was reliably the same trajectory, regardless of the speed value I was running at the time.

I assumed that application of force was instant at a point in time, and that the resulting simulation would be the same irrespective of the simulation interval.

However, it seems like bullet applies a force for the whole duration of the given interval ... or, at least, that would explain why multiplying the force vector by 1/speed appears to produce correct results.

**Comment by SolarLune** [comment]
> Bdx.physicsSpeed would make more sense.

OK. What about the time multiplication - should both `Bdx.time` and the physics update rate be multiplied by `Bdx.physicsSpeed`, or should there be two different variables for that?

**Comment by GoranM** [comment]
`Bdx.time` has nothing to do with the physics simulation, so it wouldn't make sense for that to change when `Bdx.physicsSpeed` is modified.

**Comment by SolarLune** [comment]
OK, PR submitted.

**Comment by SolarLune** [comment]
Ah, I forgot about this. The PR was merged, so I'll close this now.
