### ISSUE TITLE
Color convenience functions would be nice

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#84]
It'd be nice to have a version of the color() function that allows you to pass a Vector4f, especially since:

- color() returns a Vector4,
- color(float, float, float, float) is a tad awkward to type out, and
- it's kinda weird because it goes (x, y, z, w) instead of (w, x, y, z). So, a "standardized" color() setting function for Vector4fs would be nice.

An additional color function that only takes r, g, and b instead of all four components would also be nice; the fourth alpha value would default to 1.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
Thanks. PR created: #87

**Comment by SolarLune** [comment]
PR Merged. Issue closed. Thanks!
