### ISSUE TITLE
BDX creating project error

### ISSUE THREAD

**Issue by shoaibakram-regexsoft** [GoranM/bdx#843]
Hi, I am creating a project in blender and got following  error

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 265, in execute
    self.create_blender_assets()
  File "C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons\bdx\ops\createproj.py", line 44, in create_libgdx_project
    subprocess.check_call(cmd)
  File "C:\Program Files\Blender Foundation\Blender\2.77\python\lib\subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', 'C:\\Users\\HP\\AppData\\Roaming\\Blender Foundation\\Blender\\2.77\\scripts\\addons\\bdx\\gen\\gdx-setup.jar', '--dir', 'C:\\Users\\HP\\Desktop\\abccc', '--name', 'abc', '--package', 'com.abc.xyz', '--mainClass', 'BdxApp', '--sdkLocation', 'C:\\Users\\HP\\AppData\\Local\\Android\\Sdk\\', '--extensions', 'controllers;tools']' returned non-zero exit status 2

location: <unknown location>:-1

please help if you know it

**Comment by SolarLune** [comment]
Hello. Did you [follow the prerequisites page and install the JDK](https://github.com/GoranM/bdx/wiki/Installation)?

**Comment by shoaibakram-regexsoft** [comment]
Yup I have installed and now I have fixed this issue there is an issue in createproj.py that when we create project there is space in path and this creates the issue here is my edit cmd in createproject.py file 
//createproject.py line 36
 cmd = 'java -jar "{program}" \
                --dir "{dir}" \
                --name "{name}" \
                --package {package} \
                --mainClass {mainClass} \
                --sdkLocation "{sdkLocation}"'
