### ISSUE TITLE
Suggestion: Only Export On Blend File Change

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#845]
Hey, there. 

So basically, we're always exporting all scenes in a blend file. For Gearend, my current project, it takes roughly 8 seconds spent exporting all the data, even when nothing's changed in the blend file. That quickly adds up when I'm just trying to, say, test out gameplay mechanics in code. So, we could optimize things somewhat by only exporting all scenes should the blend file be significantly altered. 

For example, when you press P to export and run, we can check `bpy.data.is_dirty` and see if the blend file has been changed. If so, I believe we should be able to automatically save the blend file by calling `bpy.ops.wm.save_mainfile`, and then export the data as usual. We can also export if data hasn't been exported since the blend file has been opened.

If the Blend file _isn't_ dirty, and we _have_ exported data before in this session, though, there's no reason to re-export the scenes, so we can just launch BDX.

This can all be tied to a simple toggleable option, of course, to always export data (the default), or to auto-save and export only when the blend file's dirty.

_____

An alternative would be to add a different shortcut and button for just `Run`, without exporting (possible Shift+Ctrl+Alt+P or something like that, though that doesn't really "roll off the fingers", haha).

EDIT: Oh, and I know that the ideal would be to drop the need to export at all by reading blend files directly, but we don't know if or when that could happen, and this should be relatively easy, quick, and light to add. I think it would impact BDX development for the better.

**Comment by SolarLune** [comment]
I just ended up making it, haha. Let me know your thoughts, as usual.

**Comment by SolarLune** [comment]
Oh, and I wanted to mention, with the option on, manipulating the default 3D view cam won't do anything  unless you turn the new option off or alter the blend file somehow (which is fine with me, I think).

**Comment by GoranM** [comment]
You could just build the project with gradle:

`gradlew desktop:run` should do what you want in those circumstances.

**Comment by SolarLune** [comment]
Ah, I see, I tried doing this by creating a configuration in IntelliJ that ran the DesktopLauncher. I was wondering why changing the code didn't do anything - just running the DesktopLauncher doesn't recompile the source files, duh, haha. 

Running gradlew works fine. I'll update the Wiki as necessary.
