### ISSUE TITLE
Workflow Improvement

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#853]
Hey, there. 

So, I'm getting to the stage where working in BDX is getting to be a bit on the slow side of things. Fortunately, I'm nearly done with Gearend, but BDX could still stand to be improved to deal better with slightly larger projects. Here's my ideas:

- Support for more than one blend file at a time. 

Currently, BDX only works with one blend file at a time. This is fine, but slightly larger projects could be split apart into multiple pieces (say, one blend for each zone, or set of levels). The advantage of doing this would be the ability to export only recently updated blend files, rather than all data from all scenes in the game. Also, Blender wouldn't have to load more data than is necessary - just the data from the current blend file, which could be a potentially much smaller section of the game. This would make the actual moment-to-moment development process go much faster.

For this, I imagine the export process could be altered to push out `.bdx` files for each scene, named according to the name of each blend file (or perhaps put into a folder for each blend file). We could also just disallow scenes that share names across blend files from existing (i.e. no scene named "Background" in both Level1.blend and Level2.blend).

We could also add a "Main Scene" selector to the BDX Render panel - this would be for you to select where the game starts, regardless of which blend file is open. If it's left blank, then it would work like it does now. That's a bit more code, but it'd eliminate the need to return to the intended playable scene when testing, like we have currently. I suppose we would also have to have some kind of settings file that would keep these kinds of project-wide settings available for access from any blend file.

- Ideally, our workflow should be one that allows usage of Blender as an editor while the game is running. 

It's a bit draining to have to wait several seconds for export, for Java to be invoked for compilation, and finally for the game to load just to test even a slight change. By keeping Blender available as an editor while the game is running, you could make changes in Blender, export, and then just restart the running game to see the changes live, so to speak.

As for implementation, my idea would be to rework the export process into a background process (like when you go to export an animation), and execute it on save. You'll be able to see the progress bar on the top as it goes through the process. You could then run the game from Blender, as usual, or from an IDE.

Let me know your thoughts.

**Comment by GoranM** [comment]
Based on our discussions in #839, I think we concluded that having BDX read the .blend files directly would be the best way to address all these issues.

**Comment by SolarLune** [comment]
I'll carry on discussion in that thread, then.

**Comment by GoranM** [comment]
The original purpose of that thread was to answer a question, not to discuss how the exporter could be improved, so I think it's probably best if we continue here.

Reading data directly from the .blend file would be ideal, but if it's too difficult, and you just want to tack on FBX files to the existing system, I think that's fine.

> I imagine the export process could be altered to push out .bdx files for each scene, named according to the name of each blend file (or perhaps put into a folder for each blend file). We could also just disallow scenes that share names across blend files from existing (i.e. no scene named "Background" in both Level1.blend and Level2.blend).

I don't see the need for automatically including the name of the blend file, or any kind of unique scene name enforcement. The BDX addon can just export scenes normally, from whichever blend file you want. If there are multiple .blends that have a scene with the same name, the one that's exported last will naturally override the one that was exported previously, and that would be fine, as long as it's documented.

> We could also add a "Main Scene" selector to the BDX Render panel

Yeah, that sounds useful, although I don't think that would require a "project-wide settings" file, or anything like that. You can just make it a text field, which would allow you to enter any name, including that of a scene that was generated by some other .blend file.

> As for implementation, my idea would be to rework the export process into a background process (like when you go to export an animation), and execute it on save.

That sounds fine.

**Comment by SolarLune** [comment]
> As for implementation, my idea would be to rework the export process into a background process (like when you go to export an animation), and execute it on save.

So I'm looking into this, and it seems like it's not really possible to set the export process to be something that doesn't block Blender. Making the operator modal didn't really help, as the core process of exporting the data is what's holding things up, not the fact that the operator isn't a modal. 

I then tried moving things to a thread, which I _believe_ did start to work, but crashed because none of bpy's context stuff was available. So that's not a doable approach, either. . .

I'll have to come back to this - it might not be even necessary if it's fast enough to export to FBX or even directly to G3DB (what we have to convert FBX files to after export; this is what I've been looking into recently).

I've submitted a PR for some improvements. The next thing to look into is to export data from multiple blend files.

**Comment by GoranM** [comment]
I thought you were just going to thread the part that runs the engine; That shouldn't require anything from bpy.

I don't see the benefit in threading the actual data export.

**Comment by SolarLune** [comment]
Well, that's also a good idea, but my idea was to thread the export process as well, as I have to wait around for the export to go through now. With the export process threaded, the user could continue to use Blender while exporting. It almost wouldn't matter if the export takes long, because it wouldn't impact the user's experience that much.

**Comment by GoranM** [comment]
Assuming that blender allows it, wouldn't changing the data during export have the potential to corrupt the export itself? IE: I start the export, and then go on to change a mesh while the export is still running, and before it had a chance to serialize that particular mesh.

Beyond the technical issues, the whole "export, and then go right back to working in blender" scenario seems irrational; Even if the export is on the long side, we're still talking about a matter of seconds, which is not really enough to do any kind of meaningful work, and even if it was, it would make more sense to do that work before exporting, so that you can see the complete results.

**Comment by SolarLune** [comment]
> Assuming that blender allows it, wouldn't changing the data during export have the potential to corrupt the export itself? IE: I start the export, and then go on to change a mesh while the export is still running, and before it had a chance to serialize that particular mesh.

Not sure about that - possibly? I don't think it's really feasible with our current setup, so that's OK.

> Even if the export is on the long side, we're still talking about a matter of seconds, which is not really enough to do any kind of meaningful work, and even if it was, it would make more sense to do that work before exporting, so that you can see the complete results.

Well, it's not necessarily about how much work can be accomplished in that much time, but how it interrupts the flow of development. If the tool "gets in the way", even if just for few seconds every few minutes, that's kind of a lot. It's not really possible to do anything about it at this stage (other than look into means to eliminate or lessen the amount of time to export), I think, but I think there's merit in looking into solutions.

**Comment by GoranM** [comment]
I understand how waiting to test would break flow, but I don't see how keeping blender unfrozen during export would help in that regard; Irrespective of blender state, you still have to wait until the export completes, before you can see the changes in-game.

If you're talking about something like "editing flow": You can maintain it by not hitting the export button prematurely.

**Comment by SolarLune** [comment]
Hey, so in testing this, I found that orphan data left by linking and removing scenes still remain in the blend file after exporting multiple blend files (which can make things difficult if you have, say, multiple groups with the same name in different scenes).

To resolve this, it seems a simple solution is to save and reload the starting blend file at the end of the export process, which is what the submitted PR is for.

**Comment by SolarLune** [comment]
Welp, this is more-or-less completed, I think, so I'll close this.

Thanks!
