### ISSUE TITLE
Blend Mode + Screen Shaders +  Issues

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#858]
Hey, there.

So basically, meshes rendered with alternative blend modes (like additive blending) are incorrectly composited with previous scenes when a screen shader is used. This has been a long-standing issue that I've been aware of, but haven't really had too much reason to solve it until now.

Basically, I'm pretty sure that it has to do with how we are compositing the scenes when applying filters.

You can see the issue in this screenshot:

![screenshot from 2017-02-01 13-13-44](https://cloud.githubusercontent.com/assets/4733521/22526486/5496fdc0-e880-11e6-9066-187bfeff0422.png)
![screenshot from 2017-02-01 13-14-04](https://cloud.githubusercontent.com/assets/4733521/22526487/5497c8b8-e880-11e6-976b-a42cce30346e.png)

On the top is the incorrect rendering with a default screen shader, and on the bottom is the correct render without a screen shader. 

I notice a slight over-bright tinting that seems to be going on that I need to check out, as well...

Anyway, the character sprite is set to additive blending, and the gray square is in a background scene. Notice how the sprite is tinted blue on top, rather than adding its color to the background, like on the bottom. [I believe that's because of how we're compositing the scenes when we apply our filters](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/gl/RenderBuffer.java#L43), which is tuned for transparency between scenes rather than blending. This is done so that a transparent object in scene A rendered on top of scene B still appears transparent.

One solution to this might be to allow us to tweak what blend function is used to composite when filters are applied, though I don't know if this would work effectively across all objects in the scene. Switching the blend function to GL_ONE and GL_ONE just made every mesh appear additive, when I tried it (which is to be expected).

Another solution might be to add an option (which is on by default, and possibly available per-scene) to allow us to "smush" scene renders together _before_ a shader is applied. It'd be the difference between applying bloom on top of several scenes individually and drawing them together, and drawing some scenes first and _then_ applying bloom over the result (kinda like how the BGE did it). This option should allow advanced blending modes to come through, since it would allow OpenGL to composite the scenes together naturally, and you can still "take over" where necessary with your own shader.

**Comment by GoranM** [comment]
I'm fine with whatever you decide to do here.

**Comment by SolarLune** [comment]
The PR was merged, so I'll close this. Thanks a lot!
