### ISSUE TITLE
2D Layering System?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#867]
Hey, there. 

So basically, I was thinking of maybe making a component that would basically function as a layering system for objects in 2D (mainly sidescrolling) games. The goal would be to have something light in code that would make it easy to consistently lock specific objects to specific depths. Ideally, this solution would also easily allow re-arranging those depths as the game grows and further needs are discovered. So, for example, as the game is created and a second Background layer is needed, it doesn't necessitate going through all already-created objects and tweaking their individual positions to fit the new needs.

The API would be relatively simple, I think - something like:

```java

// System.java

public void init() {
    LayerSystem ls = new LayerSystem("Y");  // Create the system with the name of the depth axis
    ls.layers.add("Main", 0);
    ls.layers.add("Background", 100);
    ls.layers.add("Foreground", -100);
    bdx.components.add(ls);
}

// Player.java

public void init() {
    LayerSystem ls = (LayerSystem) bdx.components.get("LayerSystem");
    ls.add(this, "Main");
}

// Enemy.java

public void init() {
    LayerSystem ls = (LayerSystem) bdx.components.get("LayerSystem");
    ls.add(this, "Main");
}

// FlameParticle.java

public void init() {
    LayerSystem ls = (LayerSystem) bdx.components.get("LayerSystem");
    ls.add(this, "Foreground");
}

```

Not sure if this would be necessary enough for inclusion as a component, though, which is why I wanted to get some feedback. Thanks.

**Comment by GoranM** [comment]
> Not sure if this would be necessary enough for inclusion as a component

It doesn't really strike me as something that needs to ship with the engine.

**Comment by SolarLune** [comment]
Yeah, I could see it being a bit niche. Thanks.
