### ISSUE TITLE
Utilizing Delta Time / Removing FPS Lock

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#874]
Hey, there. 

So basically, BDX is locked at, and expects to run at, 60 FPS. It might be a good idea to "undo" this FPS lock (particularly because on lower-end devices, anything below 60 becomes unplayable, as the game runs more slowly in all respects). I know this isn't trivial, but I think it's worth thinking about. I'm not certain if the ["update delta time spiral of death"](http://bulletphysics.org/Bullet/phpBB3/viewtopic.php?t=10293) has something to do with this particular issue, but if so, there might be a simple solution that allows us to unlock the FPS rate and still keep the engine's update core relatively simple.

Also, maybe we could have a function that controls whether the FPS is locked to a target value (old-style behavior) or unlocked with the delta given (proposed new-style behavior)?

**Comment by GoranM** [comment]
> I'm not certain if the "update delta time spiral of death" has something to do with this particular issue

That's one of the core reasons for the flat 60 target.

> if so, there might be a simple solution that allows us to unlock the FPS rate and still keep the engine's update core relatively simple.

What did you have in mind?

**Comment by SolarLune** [comment]
Well, you mentioned:

> Given a call like stepSimulation(delta, 7), where delta is 1/60f, I assume that there would be only one substep, and if **I'm running my game logic in the simulation tick callback**, that logic would only run once for this frame.

So I was thinking of just separating the logic and physics calls? Or maybe just having one physics substep (for now, at least, just to allow variable / unlocked FPS values)? 

We could also try spawning another thread for physics, on desktop, at least. That's neither cross-platform nor particularly simple, though it would probably be pretty great for performance, so that's something to keep in mind for later.

**Comment by GoranM** [comment]
Limiting to a single substep would automatically lose time in cases where the simulation delta is larger than the fixed time step. If you want to run at 30 fps, and have bullet simulate over a 1/30 second interval, with a fixed time step of 1/60, you need 2 substeps to properly simulate the full interval.

Running logic outside the substep callback means that gamecode will miss all the bullet state changes that occurred in all but the last substep.

**Comment by SolarLune** [comment]
> If you want to run at 30 fps, and have bullet simulate over a 1/30 second interval, with a fixed time step of 1/60,

Why not give Bullet 1/30 for the fixed time step in that case? 

Or are you saying "want to run at" to mean the game's running slowly, and we're aiming for 60 FPS?

Also, what exactly do you mean by "lose time"?

**Comment by GoranM** [comment]
> Why not give Bullet 1/30 for the fixed time step in that case?

Because that's a fairly wide slice of time, and it would probably lead to an inconsistent simulation (tunneling issues).

> Or are you saying "want to run at" to mean the game's running slowly, and we're aiming for 60 FPS?

No, I mean if you just want to render at 30 fps.

> Also, what exactly do you mean by "lose time"?

There are not enough substeps, at a given fixed time step, to properly simulate the requested delta time. So, if you're rendering at 30 fps, but a call to stepSimulation only simulates 1/60 seconds, that would be only half the actual requested time of 1/30 seconds, and the other half is "lost".

Or, at least, that's how I understood it, from reading about it here: http://bulletphysics.org/mediawiki-1.5.8/index.php/Stepping_The_World

**Comment by SolarLune** [comment]
Coming back to look at this:

> Running logic outside the substep callback means that gamecode will miss all the bullet state changes that occurred in all but the last substep.

I don't see where we're executing logic in the physics callback? Seems like we run logic before simulating the world for the current game frame?

**Comment by GoranM** [comment]
> I don't see where we're executing logic in a physics callback?

I'll assume that by "physics callback" you actually meant "substep callback", which is what I originally referenced.

In our existing setup, logic is *not* running inside a substep callback, and that was my point. 

If you wanted to simulate physics based on real "wall clock" time, independent of the frame rate, you would need to use substeps, and if you did that with the existing setup (where we're not running gamelogic inside a substep callback), you would miss bullet state changes in all but the last substep.

**Comment by SolarLune** [comment]
> I'll assume that by "physics callback" you actually meant "substep callback", which is what I originally referenced.

Yeah, that's what I meant. Thanks.

> In our existing setup, logic is not running inside a substep callback, and that was my point.
If you wanted to simulate physics based on real "wall clock" time, independent of the frame rate, you would need to use substeps, and if you did that with the existing setup (where we're not running gamelogic inside a substep callback), you would miss bullet state changes in all but the last substep.

Well, maybe we could run the engine's physics-related code in the callback (so colliding objects lists are updated, for example), and just run the user's game logic once every frame, as usual. I think it'll be OK if we document exactly how it works, and the trade-off is worth it, I think (unlocked FPS on desktop, and delta time capability).

**Comment by GoranM** [comment]
Objects could make and lose contact a number of times before the final substep is simulated (think of a bouncing ball), so it's not enough to just include hit objects in previous substeps.

More importantly: If variable amounts of time pass between when something happens in the bullet world, and when gamelogic has a chance to react to it, the overall simulation will be inconsistent: Actions initiated by collision events would happen earlier when framerate is high (less substeps), and later when framerate is low (more substeps)

**Comment by SolarLune** [comment]
> Objects could make and lose contact a number of times before the final substep is simulated (think of a bouncing ball), so it's not enough to just include hit objects in previous substeps.

I'm not sure I understand. Could you explain further? What do you mean by "just include hit objects in previous substeps"? I was proposing [using a callback that would update each object's collision list after each substep.](http://bulletphysics.org/mediawiki-1.5.8/index.php/Simulation_Tick_Callbacks) Every logic frame, you would be able to check your collision lists to properly check the accrued collision information from all previously executed substeps. 

Now, I do see that multiple substeps could prove problematic because data is "overwritten" by later substeps. For example, an object gets hit and has its velocity set in an early substep, but that force is altered in the last substep (which is what the logic execution phase reads - the last substep), but adding the level of complication to properly deal with such a situation might not be necessary for most games / situations. If it is, then we can add it later.

> More importantly: If variable amounts of time pass between when something happens in the bullet world, and when gamelogic has a chance to react to it, the overall simulation will be inconsistent: Actions initiated by collision events would happen earlier when framerate is high (less substeps), and later when framerate is low (more substeps)

That doesn't sound like a huge issue - it seems like it's not ideal, but it sounds better than the alternative.

I'm just talking here about adding options in. Adding the ability to unlock the FPS and utilize delta time shouldn't dramatically alter how BDX works. The developer could still set the maximum substep count to 1 or 0, set the max display (and physics?) FPS to 60, and basically have the same engine execution process as we do now. All I'd like is to add options to allow for better control over how the engine executes. 

For reference, my main particular use case is wanting to use delta timing so players running my game at lower FPS values could still conceivably play the game. Anything below 53 FPS is pretty much unplayably slow as it is, as everything happens significantly slower.

**Comment by GoranM** [comment]
> What do you mean by "just include hit objects in previous substeps"?

For each object, including all the objects that it collided with, in all previous substeps, as part of its complete hit list.

>  the accrued collision information from all previously executed substeps

I think we're talking about the same thing, but I'm not sure at this point. Feel free to clarify, if necessary.

> That doesn't sound like a huge issue

It would depend on the frame rate.

I think it would be better to just move all game logic execution into a substep callback. Most games are not logic bound, so the "death spiral" scenario is highly unlikely, and you would have delta time simulation capability without having to deal with inconsistency issues (or complicating the engine to remedy those).

> Anything below 53 FPS is pretty much unplayably slow as it is, as everything happens significantly slower.

What are your minimum system requirements, and why are you dropping below 60 fps when running on those specs?

**Comment by SolarLune** [comment]
> I think we're talking about the same thing, but I'm not sure at this point. Feel free to clarify, if necessary.

OK, yeah, I think we are talking about the same thing.

> I think it would be better to just move all game logic execution into a substep callback. Most games are not logic bound, so the "death spiral" scenario is highly unlikely, and you would have delta time simulation capability without having to deal with inconsistency issues (or complicating the engine to remedy those).

Hmm, but if we did this, then changing the number of physics substeps would change how often logic executes. For example, if you had a simple class that moves an object 0.1 blender units a frame, but Bullet was set to run 5 substeps, the object would jump 0.5 Blender Units in a single frame. This would happen even if you factored in delta time, unless delta time is internally scaled according to the number of substeps. This also would mean running all logic in the game 5 times more often for possibly no real reason, which is a pretty heavy hit if you're just looking for delta timing.

While I still think it might be worth testing just doing some collision setup stuff in the substep "loop", maybe a middle ground could be reached by means of a specific function on GameObjects and Components for substep-based logic execution? Or is that specifically what you're trying to avoid?

> What are your minimum system requirements, and why are you dropping below 60 fps when running on those specs?

I'm kind of at the stage of determining that by testing. Dropping below 60 seems like it might be the fault of the rendering process on my weak target (a laptop with an integrated graphics card). I'd say the "standard" of being able to play the game at 30 fps would probably be the minimum enjoyable level of play, which is where my laptop currently is if I turn off all screen filters and advanced lighting.

**Comment by GoranM** [comment]
Note that we can only specify the maximum number of substeps that bullet is allowed to take. Bullet determines how many are actually executed, based on delta time.

Logic is executed on every substep, not every frame, so it doesn't run "more often" - you're just rendering "less often".

As far as gamecode is concerned, the world simply advances by fixedTimeStep.

> maybe a middle ground could be reached by means of a specific function on GameObjects and Components for substep-based logic execution? Or is that specifically what you're trying to avoid?

I don't really see a good "middle ground" here. In my view, you either have a fully consistent world (along with a clean and simple programming model), or you have some hacky mess where game behavior can change based on framerate.

> I'm kind of at the stage of determining that by testing.

Yeah, figuring out the actual bottleneck is key. Without expensive shaders/effects, it should be possible to hit 60 fps, even on older integrated graphics chips.

Maybe this tool can help you profile graphics in detail (assuming intel graphics): https://software.intel.com/en-us/gpa/graphics-frame-analyzer

**Comment by SolarLune** [comment]
OK, so I tried implementing this, but [it doesn't seem like forces can be applied in a post-tick callback](http://bulletphysics.org/mediawiki-1.5.8/index.php/Simulation_Tick_Callbacks). See the "More complex example" section of the Bullet wiki - it advises creating a "pre-tick callback" to clear the forces first and then apply forces afterwards, but pre-tick callback creation doesn't exist in the jBullet port for whatever reason (maybe it's a later addition). There's only the "default" post-tick setInternalTickCallback function. When I try to apply forces with the default callback, the forces applied simply don't do anything (they're cleared, apparently).

Looking it up on the web seems to show that the post-tick callback is not the place for all general-purpose logic. See these posts [here](http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=3315#p14512) and [here](http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=9&t=3315#p14628).

For reference, [here's what I have so far](https://github.com/SolarLune/bdx/tree/UnlockedFPS).

> I don't really see a good "middle ground" here. In my view, you either have a fully consistent world (along with a clean and simple programming model), or you have some hacky mess where game behavior can change based on framerate.

I also would like such a consistent physics world and clean coding model, but I'm not sure about the "how" of the actual implementation.

**Comment by GoranM** [comment]
Assuming that bullet doesn't do anything more special in the execution of substeps than just running the call we currently run, but N times, where N = timeStep / fixedTimeStep, we may be able to get the same functionality by just modifying Scene.update:

```java
public void update (){
        float timeNow = time();
        float timeStep = timeNow - timeLast;
        timeLast = timeNow;

        requiredStepsFloat += timeStep / fixedTimeStep;

        int requiredSteps = requiredStepsFloat;

        if (requiredSteps > maxTimeSteps){
                requiredSteps = maxTimeSteps;
                requiredStepsFloat = 0
        }else{
                requiredStepsFloat -= requiredSteps;
        }

        for (int i = 0; i < requiredSteps; ++i){
                // existing code
        }

}
```

I didn't test this, so I'm not sure if it's going to work, but it should be the same process, at least in principle.

PS:

Note that, as with bullet executed substeps, this would only work properly when logic is *not* the bottleneck. So, when testing, be sure that you're simulating render load, not logic load.

**Comment by SolarLune** [comment]
OK, that seems to have done the trick. Thanks! I've updated the branch. 

However, I notice the problem I mentioned earlier - because we're executing logic each time a physics step executes, it's possible for multiple logic executions to happen in the span of a single frame. 

This means that if you have something that, say, turns on or off if a key is pressed, pressing the key once can toggle the event multiple times in a single frame if the engine's executing multiple substeps.

**Comment by GoranM** [comment]
The state of inputs must also be updated with each substep.

**Comment by SolarLune** [comment]
More work done on this, but I'm not quite sure what you mean - I tried adding one to GdxProcessor's tick value with each substep, which, I believe, worked, but broke when working with multiple scenes.

**Comment by SolarLune** [comment]
OK, I feel like this is slightly better, but it's still not exactly right - seems like forces are stronger at lower FPS than at higher FPS.

**Comment by GoranM** [comment]
You can't just put the update code into a scene update, because anything after the first scene is going to miss input changes that happened during the execution of all the first scene substeps.

So, while easy, and seemingly straightforward, you can't actually implement substeps directly in Scene.update.

You'll need to calculate substeps in a way that accounts for all scenes, so that all scenes execute the same number of substeps, and update in the same loop, per substep:

```python
for i in range(substeps):
    update_inputs();
    for scene in scenes:
        scene.update()
```

Something like that, conceptually.

**Comment by SolarLune** [comment]
Hello! 

So I started working on this again, and I think I'm almost done. Hurray! 

However, there was a discussion on /r/gamedev about delta timing, and someone brought up an idea of simply [skipping rendering](https://www.reddit.com/r/gamedev/comments/6yws4r/should_a_game_loop_be_dependent_on_a_frame_rate/dmqujeh/) should the FPS drop. I wonder if skipping the execution of portions of BDX's execution loop would be a simpler approach to adapt to the capability of the target computer. 

It seems like it might be, especially since it allows for more customization according to the needs of your game. We could allow the developer to decide to skip logic, rendering, or physics should the FPS drop sufficiently. This would be good as different games have different needs when it comes to framerate (some games might, for example, value display framerate higher than logic framerate, or physics framerate higher than the others). What do you think?

**Comment by GoranM** [comment]
I think it would be better if developers took the time to either optimize their game properly, or, failing that, raise the minimum system requirements to a level that is actually required to play their game at 60 fps.

> We could allow the developer to decide to skip logic, rendering, or physics should the FPS drop sufficiently.

The only thing that can be skipped without causing unwanted inconsistencies is rendering, and assuming that rendering is the core bottleneck, the setup we discussed in this thread is essentially doing that.

**Comment by Lucrecious** [comment]
Hey, going back to this, I don't mind whether or not there's an unlocked framerate, but I'd really like there to be a `Bdx.delta()`, so if there _are_ framerate dips (a large GC or something), delta() catches them.

Would that be okay to add?

**Comment by SolarLune** [comment]
A delta function's fine by me, sure. It's something that LibGDX provides for us anyway, so it's a very minor function to add (I wouldn't tie it in with BDX's internal timekeeping without substep / engine-wide delta timing, though).

**Comment by Lucrecious** [comment]
I think delta time should also be used for keeping velocity consistent as well though (if velocity doesn't already take into account delta time). I can't tell since I'm not sure where object position is updated after velocity is applied.

**Comment by SolarLune** [comment]
Ah, OK, I misunderstood you. The issue, then, is that to keep velocity consistent, we'd have to be able to specify more physics updates to prevent tunneling. Physics substeps is something I was working on in the branch for this issue - I have to look back at where I was to see if anything's missing.

**Comment by Lucrecious** [comment]
Well if velocity simply uses the target frame rate, wouldn't it be enough to replace the multiplier from Bdx.TICK_RATE to Bdx.delta() (or something similar)?

**Comment by SolarLune** [comment]
OK, PR submitted (#999).

**Comment by SolarLune** [comment]
Well, the PR was merged, so I'll close this now. Thanks, guys.
