### ISSUE TITLE
Music.available() returning empty

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#878]
Yo, sup. 

So if I call Music.available() in BDX, it will return the files available, but only when testing using gradle desktop:run. If I run the game from a compiled .jar file, the available() function return an empty list. This is apparently because classpath filehandles can't list. It also doesn't seem to [be something resolvable in LibGDX](https://github.com/libgdx/libgdx/issues/1375). 

This problem also probably extends to Scene.available() and Sound.available(), since they use the same function.

The general idea given to me over on LibGDX's IRC seems to be to generate a list of files using something (a Bash script, a Gradle task, whatever), and go from there. I'll look into options for resolving this.

**Comment by SolarLune** [comment]
[Here's](https://gist.github.com/Tom-Ski/2556b054c1899d4bd010c4a7d00dec9c) a gradle task snippet very generously made for me by Tomski over on LibGDX's IRC. Looks pretty easy. 

The problem with this approach, though, is that we'd have to modify our BDX created .gradle file to actually use this snippet. I know basically nothing about gradle, though, so maybe it'd be more complex than doing it with just, say, Java. We could assume the user would test on desktop to generate info about the assets folder before exporting. 

I believe another option would be to separate the assets folder from the .jar on compilation, so that the files would be readable as usual when distributed with gradle as a .jar file. Not sure how this would work with other targets, though.

Any thoughts?

**Comment by GoranM** [comment]
Making an index sounds like a fine solution.

You don't have to do it with gradle.

**Comment by SolarLune** [comment]
Hmm, looking through the options, it seems like this couldn't be a part of BDX or be run from BDX (because GWT doesn't support running external commands, or writing to files). I know it's possible to write platform-specific code, but I don't think we want all of that extra code.

So, we'd probably end up implementing this in Python and running it from Blender. The reason why I'm hesitant to do it this way is that you would have to use Blender to export and run to update the listing of files present, which isn't super desirable and doesn't make much sense.

Any other ideas, though?

**Comment by GoranM** [comment]
Do you have to pack all the resources into the jar? Couldn't you ship the resources as a regular directory?

**Comment by SolarLune** [comment]
Yeah, I could, but by default, the resources are packed in when `gradlew desktop:dist` is run. That's a solution that I mentioned earlier - that we could separate the assets from the jar, but we'd have to do stuff in Blender to modify the desktop's build.gradle file. We would also need to check the other platforms to make sure it's consistent, so it might be best to just do it in gradle.

**Comment by SolarLune** [comment]
The PR I submitted was accepted, so I'll close this now.

A simple solution for anyone who wants to choose from the available set of resources (music, sounds, scenes, etc) can be to just use something like this Python script. The script outputs a list of available resources (OGG files) in the target (music) directory:

```python

import os

p = os.path.join(os.getcwd(), "android", "assets", "bdx", "audio", "music")

with open(os.path.join(p, "available.txt"), "w") as f:

    for m in os.listdir(p):

        if m.endswith(".ogg"):

            f.write(os.path.splitext(m)[0] + "\n")

```

Once you have this script, you could just use the post-export program field in BDX's panel to run this script after the export process.
