### ISSUE TITLE
Group object not instantiating

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#88]
So yeah, I found this bug while investigating another one dealing with spawning objects from a group in when the group instance is parented to an object that gets spawned in (basically, a group instance of a level element is parented to a level layout).

Anyway, the bug in this report is that it seems like not all group objects are instantiating correctly somehow. In this simple example, the ground object isn't "placed" in the BDX scene with the others. Perhaps it's related to the previously mentioned bug, as well.

https://app.box.com/s/prx52ek9lb5ge33rcjei3ox72ygm5h73

Here's an example file.

**Comment by GoranM** [comment]
As I wrote in #72,  the system assumes that link groups are used to represent an instance of a *single* master object.

**Comment by SolarLune** [comment]
Hmm, so, for confirmation, everything in a group needs to be parented to something to spawn in correctly currently?

**Comment by GoranM** [comment]
I don't know what you mean by "spawn in correctly", but the system expects that one link group represents one master object.

That master object can have children, and those children can be members of the same link group, but only the master is registered as an "instance" (as you can see [here](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L77)).

**Comment by SolarLune** [comment]
OK, I think I see. Thanks for the information. Closed.
