### ISSUE TITLE
Temporary Vector Function?

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#887]
Hey, there.

I was thinking that it might be a good idea to add a function to return a temporary Vector - one that you can get and tweak before passing once, directly to another function. 

The idea is that the temporary vector would be an instance held by the Vector2f and Vector3f classes, and would be cleaned each time the temporary function is called. That way, you could avoid having to create new Vectors constantly. This could also be done for Colors.

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
Hmm, I tested it by creating literally a billion Vector3fs a frame in a for loop, but I didn't notice any enhanced heap usage in my profiler. Adding them to an ArrayList showed a much higher use of memory, but that's something you wouldn't do with a temporary vector (since it's just a "placeholder" variable to have operations applied to before using in a function or something).

So this probably just isn't really enough of a problem, in practice, to warrant this solution.

Closing issue.
