### ISSUE TITLE
*thank you*

### ISSUE THREAD

**Issue by BluePrintRandom** [GoranM/bdx#890]
All people whom use this software and enjoy it, comment below and thank the core developers.

**Comment by JavlinJoslin** [comment]
I've been using bdx to help me learn java and am hoping to use it to create my first android game, so thank you GoranM, rafcolson, SolarLune, and all others who helped develop this awesome engine.

**Comment by GoranM** [comment]
I'm glad you guys find the engine useful, but please remember that this is an issue tracker, for topics related to engine development.

Unrelated topics can be posted on our subreddit: https://www.reddit.com/r/bdx/
