### ISSUE TITLE
Suggestion: Additional info to Profiler.visible(boolean)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#896]
Currently the API shows:
><a name="visible-set" href="#visible-set">#</a> **visible**(boolean visible)
>
>Setting this to true turns it on (similarly to having the Framerate and Profiler option on in Blender).

However, _Framerate and Profiler_ should be enabled manually in order for this to work properly. For example:

```java
package myPackage;

import com.nilunder.bdx.*;

public class Sacky extends GameObject{

	private void toggleProfiler(){
		if (Bdx.profiler.visible()){
			Bdx.profiler.visible(false);
		}else{
			Bdx.profiler.visible(true);
		}
	}
	
	public void main(){
		if (Bdx.keyboard.keyHit("space"))
			toggleProfiler();
	}
	
}
```
This code will cause an error when hitting the space bar:
`Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: bdx\scenes\__Profiler.bdx (Internal)`

This bug could be properly fixed by exporting ___Profiler.bdx_ on creation time. But in the meantime, I would suggest to add this additional information:
> _Framerate and Profiler_ must be turned on in order to use this function.

Or something like that.

**Comment by GoranM** [comment]
I don't know if @SolarLune had a good reason for not addressing that issue when he initially made the change. If not, I think it would make sense to follow your suggestion.

**Comment by SolarLune** [comment]
Nah, I didn't have a good reason previously - just didn't catch this. We'll just export the profiler all the time, I guess (if it doesn't exist already as exported). 

PR submitted.

**Comment by rafcolson** [comment]
Thanks.
