### ISSUE TITLE
Issues detecting colliders with Sensor body type

### ISSUE THREAD

**Issue by TheShadyColombian** [GoranM/bdx#899]
When trying to set up a sensor for my player's attack range, I found that creating an object with a sensor body type and calling .touching() on it would never return true. 
If this is the intended use for this body type, something's wrong, otherwise, how could I achieve this behaviour?

**Comment by rafcolson** [comment]
>an object with a sensor body type and calling .touching() on it would never return true

I suspect that you must be doing something wrong because on my end an object with `BodyType.SENSOR` will return true when calling `touching()`. I've tested with current master. What's your code?

**Comment by TheShadyColombian** [comment]
Oh.... that's probably why. Is there a workaround? That's currently the way my game is supposed to work. 
Ironically enough, the code called on detection changes the body type of the detected collider from STATIC to DYNAMIC.

**Comment by rafcolson** [comment]
Well, you could probably use DYNAMIC for the object you want to detect and set to `dynamics(false)` in ìnit()`. In `main()` you then should activate the body at all times. You can either call `body.activate(true)` or `body.forceActivationState(1)`. I suspect the latter to be less expensive on performance.

```java
package YourPackage

import com.nilunder.bdx.*;

public class Collider extends GameObject{
	
	public void init(){
		dynamics(false);
	}
	
	public void main(){
		body.forceActivationState(1);
	}
	
}
```

**Comment by TheShadyColombian** [comment]
Thanks a lot for the help! I did try dynamics(false) before but i didnt know that put the body in a "Hibernation" state and that I manually needed to call body.forceActivationState(1) every frame I want the physics on it to update. Good to know!

**Comment by SolarLune** [comment]
Yo, 'sup!

In case you didn't see it, there's a [table](https://github.com/GoranM/bdx/wiki/General-Overview#physics-types) that explains what object types can collide with which other types.

Sensor type, for whatever reason, doesn't collide with static objects (even though it seems like it should). We could probably fix it so that it works by internally using an "ordinary" dynamic ghost body that isn't affected by gravity or other external forces.

**Comment by rafcolson** [comment]
My tests show that even when setting mass to zero it is still required to call `body.forceActivationState(1)` continuously. Maybe this information will be useful at some point.

**Comment by SolarLune** [comment]
OK, I think that last PR might've fixed it.

> it is still required to call body.forceActivationState(1) continuously

That's basically what I ended up doing, haha. Just calling `body.activate(true)` to force the awake state.

**Comment by rafcolson** [comment]
Nice! It seems like it's not even necessary to use DYNAMIC. Maybe good to add a reference to this issue.
