### ISSUE TITLE
How to make an object ignore collisions between other instances of itself but nothing else

### ISSUE THREAD

**Issue by TheShadyColombian** [GoranM/bdx#903]
I know I can use collision layers but these objects will have a lot of instances that will make it impossible to use this method.

Also, I would like to confirm that the Issues tab is an appropriate place for posting questions like these, even though it's not an issue with the BDX project, but more my lack of knowledge.

**Comment by rafcolson** [comment]
>Also, I would like to confirm that the Issues tab is an appropriate place for posting questions like these, even though it's not an issue with the BDX project, but more my lack of knowledge.

If this isn't an issue with the BDX project then https://www.reddit.com/r/bdx/ would be the appropriate place.

If using collision layers is no option, maybe using properties is.

```java
	public void main(){
		if (touching()){
			for (GameObject g : touchingObjects){
				if (!g.props.containsKey("ignored")){
					// do something
				}
			}
		}
	}
```

**Comment by TheShadyColombian** [comment]
Ah, so there _is_ a subreddit for everything. good to know! I'll post there from now on, but I'll finish this issue here so that everything is in one place.

I understand how to select the objects I'm colliding with, but what I meant with collisions is to let multiple objects take up the same area. More of a physics problem than a programming problem. Sort of like if it was a NO_COLLISION body type, but they should still be dynamic and should still collide with other objects that aren't being "ignored"

**Comment by rafcolson** [comment]
Since this use case seems to be more complex, a short answer may not be applicable. So maybe it would be best to continue on reddit.

**Comment by TheShadyColombian** [comment]
Alright, I'll make a post asap.
