### ISSUE TITLE
Bug: random logicCounter causes Random.seed(int) to fail

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#908]
After #875 the logicCounter gets a random float added to it on GameObject / Component creation. This allows multiple objects that have altered frequency value to not be executed all on the same game frame.

However, this causes some unexpected behavior when setting Random seed. Normally `Random.seed(int)` would always produce the same sequence, but now that execution times are random (within one logic tick), sequences will not always match up.

Here's an example: https://www.dropbox.com/s/vkl5jfrvdo7jrtd/joiner_two_materials.blend?dl=0

(just click the left mouse button a few times; before #875 the cubes would always be in the same spot)

I'm not sure how this could be solved. Maybe it would be a good idea to add another button next to the "priority" button in the Object panel, to be able to switch off random logicCounter?

**Comment by SolarLune** [comment]
Hey, thanks, I see the issue. PR submitted that seems to clear it up fine.

**Comment by rafcolson** [comment]
Great!
