### ISSUE TITLE
Parent all spawned objects in group to group instance's parent

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#91]
Hey, there. I think it might be a good idea to parent all unparented objects in a spawned group to whatever the instance is parented to (if it is parented). 

An example would be parenting a switch to a moving platform - you can create an instance of a Switch group and parent it to the platform, and the objects that spawn in will automatically follow the platform, correctly.

**Comment by GoranM** [comment]
As I said in other issues: the system assumes that link groups are used to represent an instance of a single master object. This can be fixed with a few ugly hacks, but, considering how much you seem to rely on this (or how much you want to), I think it would probably be better to refactor the spawning system to support link groups in a more elegant way - More in line with how link groups work in blender, and the BGE.

I'll look into into it (that code was kinda rushed to begin with).

**Comment by SolarLune** [comment]
OK, it's up to you how to proceed. I like to use group instances because it allows objects to share code that otherwise would be impossible (i.e. to have multiple "Spring" objects, for example, that run the same code and can therefore both run Spring.java). It also allows you to place things visually rather than having to rely on copying and pasting objects (which has a margin for error) or using an object to spawn your "target" objects. So having some additional work on group instances would be much appreciated.

**Comment by GoranM** [comment]
There's a bit of an issue with implementing link groups exactly as they work in blender. It can certainly be done, but it would be much easier, and it would take significantly less code to keep the existing arrangement (one link group represents one master object), where you can additionally specify parent-child relationships between link group instances.

IE: If I have object **A** represented by link group **a**, and object **B** represented by link group **b**, I can parent an instance of **b** to an instance of **a**, and that relationship will be preserved between instances of **A** and **B** that actually spawn there (new **A** would be parent to new **B**).

So, not exactly blender behavior, but I think it would essentially solve most of your problems, while keeping the code base fairly simple.

**Comment by SolarLune** [comment]
That sounds fine.

**Comment by GoranM** [comment]
Ok, try that.

**Comment by SolarLune** [comment]
Yep, that seems like it works really well on a simple test. More users testing it with more test cases will tell more about this for sure. Thanks a lot!
