### ISSUE TITLE
Unable to install BDX in Blender User Preferences

### ISSUE THREAD

**Issue by Mr-Manatee-Studios** [GoranM/bdx#910]
Hello. I have a question about BDX; When I try to "install from file" in Blender User Preferences, it doesn't show when I look it up. Any solutions?

**Comment by rafcolson** [comment]
You probably didn't select "Testing" under "Supported Level".

**Comment by Mr-Manatee-Studios** [comment]
OMG THANK YOU SO MUCH!

**Comment by rafcolson** [comment]
@Mr-Manatee-Studios You may close this issue if it is solved.

**Comment by SolarLune** [comment]
@GoranM I think this is resolved and is good for closing.
