### ISSUE TITLE
Dev: Multi-Blend Export false by default

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#911]
Right now by default Multi-Blend Export is enabled. The vast majority of BDX projects are probably small, not requiring more than one blend file. Especially when testing new builds, it would be more convenient if it were disabled by default, as I'm regularly copying and pasting small blend files to the source folder of my "Test" project.

**Comment by SolarLune** [comment]
Yeah, OK, I could see that. PR submitted.

**Comment by rafcolson** [comment]
Thanks!
