### ISSUE TITLE
Suggestion: Mesh upgrade

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#912]
Hi guys,

The `GameObject.join()` method contains code to get transformed vertex arrays. It seems that such function should be part of `Mesh` as `Mesh.verticesTransformed(int, Matrix4f)`. An additional function `Mesh.verticesTransformed(Matrix4f)` could also be useful.

`Mesh.vertTransform(int, Matrix4f)` doesn't calculate normals properly as can been seen in [this example](https://www.dropbox.com/s/lcrx6ppw08pwvj1/vertTransform_bug.blend?dl=0) (press the left key). So this function now could utilize `Mesh.verticesTransformed(int, Matrix4f)`. For more information, see [Normals are not calculated with Matrix4.transform() methods](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/graphics/Mesh.java#L903-L948).

How about renaming this function to `transform(int, Matrix4f)` and add `transform(Matrix4f)`? The same with `Mesh.vertTransformUV(int, Matrix3f)`. `Mesh.transformUV(int, Matrix3f)` sounds a little less confusing.

Additional functions to get offset, the number of indices, the number of vertices and to get and set vertices:
```java
Mesh.offset(int);
Mesh.numIndices();
Mesh.numIndices(int);
Mesh.numVertices(); // instead of Mesh.getVertexCount()
Mesh.numVertices(int); // instead of Mesh.getVertexCount(int)
Mesh.vertices();
Mesh.vertices(int);
Mesh.vertices(float[]);
Mesh.vertices(int, float[]);
```
Improves readability of existing functions to get and set position, normal and uv of a single vert also.

`Mesh.getInstance()` actually adds a new instance, so it would make more sense to rename this to `Mesh.addInstance()`.

`Mesh.serialized()` can be used to store the mesh. It only seems right to have a function to load from such stored data. Not sure about the name: `Mesh.deserialize(String)`?

Edit: I've attached a commit, which is built on top of the _(#812) GameObject.transform() now scaled GameObject.transform_ commits, so you guys can have a look.

Edit: Forgot to mention `Mesh.vertices()` setters.

**Comment by GoranM** [comment]
> Mesh.getInstance() actually adds a new instance, so it would make more sense to rename this to Mesh.addInstance().

I'm not sure if addInstance would make sense in this case, because unlike addObject, the addition here is just an internal implementation detail of creating a new ModelInstance.

I think getNewModelInstance would probably be fine.

The rest of the suggestions seem fine to me, but since @SolarLune wrote that code originally, it would probably be best to also get his input.

**Comment by rafcolson** [comment]
>I think getNewModelInstance would probably be fine.

Changed and rebased.

**Comment by SolarLune** [comment]
This all sounds fine. 

I wonder if it might be best to move scene.createModel into Mesh (as you never want a Model and not a Mesh in our codebase).

**Comment by rafcolson** [comment]
PR updated.

**Comment by rafcolson** [comment]
PR submitted.

@SolarLune 

If you're comfortable with these changes, I'd appreciate it if you could evaluate this when you have the time. Thanks.

**Comment by SolarLune** [comment]
OK, this looks fine.

**Comment by rafcolson** [comment]
Merged. Thanks a lot!

**Comment by rafcolson** [comment]
API updated.
