### ISSUE TITLE
Suggestion: Joiner upgrade - JoinData

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#917]
The joining functions `GameObject.join(objects)` and `GameObject.join(map)` can keep draw calls to a minimum. Especially on low-end and mobile devices this can be useful.

However, there's much more that could be done by using this joining functionality, that is, if adding or removing vertices could be done efficiently. This was already discussed in [a previous suggestion related to the joining functionality](https://github.com/GoranM/bdx/issues/809#issuecomment-253866699).

Imagine a puzzle game with hundreds of pieces laying around on the table. If all of those pieces were to be separate objects, the game could become slow because of two problems. First, there's the rendering issue with a lot of draw calls. Fortunately the joiner functionality already tackles this problem. But the other problem is physics calculation. Hundreds of invisible static ghost (yet detectable) objects could have a large impact on game play.

You can test [this apk](https://www.dropbox.com/s/05j2wpa4rwcy62s/512%20invisible%20static%20ghost%20planes.apk?dl=0) with 512 invisible static ghost planes on an Android device. I'm getting barely 10 fps.

This problem could be tackled by changing the detection method of the pieces, reducing physics calculation to a minimum. But this would also require to edit the joined mesh object, when removing or adding segments.

In order to edit the joined mesh faster the transformed vertex arrays should be stored initially. The purpose of this upgrade would be to provide not only this, but also a basis by which the joined data is accessed and modified, stored and restored rather easily.

The result is [this apk](https://www.dropbox.com/s/sb41mbuamm8g1sj/512%20segments%20with%20JoinData.apk?dl=0) with 512 segments, which can be removed or added. Additionally [the corresponding blend file](https://www.dropbox.com/s/ms5lcs303guru3v/512%20segments%20with%20JoinData.blend?dl=0), which works with the referenced branch of my repository (based on the Mesh upgrade commits).

More information about the changes will follow. Tell me what you guys think.

**Comment by rafcolson** [comment]
Thanks @GoranM. Commit updated with additional information.

**Comment by SolarLune** [comment]
Huh, I think I get the idea. Yeah, OK, this seems fine.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks!
