### ISSUE TITLE
API: Material Blending constants

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#918]
I would like to add some additional information about Blending constants to the General Overview.

...

#### Blending Factors

Blending modes can be set with `Material.blendMode(int src, int dest)`. OpenGL Blending Factors are explained in this table below. S, D, C, R, G, B stand for Source, Destination. Color, Red, Green, Blue and Alpha.

`com.badlogic.gdx.graphics.GL20` constant | RGB Blend Factors | Alpha Blend Factor
 :--- | :--- | :---
GL_ZERO | (0,0,0) | 0
GL_ONE | (1,1,1) | 1
GL_SRC_COLOR | (Rs,Gs,Bs) | As
GL_ONE_MINUS_SRC_COLOR | (1,1,1) – (Rs,Gs,Bs) | 1 – As
GL_DST_COLOR | (Rd,Gd,Bd) | Ad
GL_ONE_MINUS_DST_COLOR | (1,1,1) – (Rd,Gd,Bd) | 1 – Ad
GL_SRC_ALPHA | (As,As,As) | As
GL_ONE_MINUS_SRC_ALPHA | (1,1,1) – (As,As,As) | 1 – As
GL_DST_ALPHA | (Ad,Ad,Ad) | Ad
GL_ONE_MINUS_DST_ALPHA | (1,1,1) – (Ad,Ad,Ad) | 1 – Ad
GL_CONSTANT_COLOR | (Rc,Gc,Bc) | Ac
GL_ONE_MINUS_CONSTANT_COLOR | (1,1,1) – (Rc,Gc,Bc) | 1 – Ac
GL_CONSTANT_ALPHA | (Ac,Ac,Ac) | Ac
GL_ONE_MINUS_CONSTANT_ALPHA | (1,1,1) – (Ac,Ac,Ac) | 1 – Ac
GL_SRC_ALPHA_SATURATE | min(As, 1-Ad), min(As, 1-Ad), min(As, 1-Ad) | 1

...

So this can be referenced in the API.

...

<a name="blendMode-set" href="#blendMode-set">#</a> **blendMode**(int src, int dest)

Gets and sets the blend mode for the materials on the GameObject. The src and dest arguments are integers indicating the blending mode to use, and are one of the OpenGL constants. They can be found [here](https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/GL20.html), in LibGDX's gl package. A table with those constants and what they actually do can be found [here](), in the General Overview. To learn more about OpenGL blend modes, [see this page](http://www.learnopengles.com/android-lesson-five-an-introduction-to-blending/) and Google.

...

**Comment by SolarLune** [comment]
Sure. You also might want to put in this pic that's been floating around on the internet for a visual example:

![blendingmodes](https://user-images.githubusercontent.com/4733521/26899605-7273546c-4b84-11e7-8342-7a6aeb391131.jpg)

It's not super well structured or explained (it's probably a screenshot of somebody's OpenGL school project, haha), but it's still really helpful for visually explaining the blending process.

Also, you don't have to ask to document stuff - generally, more documentation's always better.

> S, D, C, R, G, B stand for Source, Destination. Color, Red, Green, Blue and Alpha.

You missed "A".

**Comment by rafcolson** [comment]
Thanks. About the picture. The original picture can be found [here](http://www.quake-1.com/docs/blending.jpg). But this site seems to be off-line for some reason. Anyway, I'm hesitant to use this picture because I'm not sure if it is part of the documentation of a commercial game or not.

**Comment by SolarLune** [comment]
Ah, I see what you mean. 

Maybe I'll make our own example to demonstrate this at some point, then.

**Comment by SolarLune** [comment]
That's true, yeah. I guess it can't hurt to get some feedback on theories for API changes / documentation.
