### ISSUE TITLE
Suggestion : Option to turn off fixed timestep and turn on Vsync

### ISSUE THREAD

**Issue by VinnieH01** [GoranM/bdx#924]
Instead of being forced to target 60 fps can we have an option to let the computer render as many frames as it can in one second and also have an option to turn on vsync to let the computer limit this number automatically? Sorry if this functionality already exist but I couldn't find it anywhere.

**Comment by SolarLune** [comment]
Yo, 'sup. This is basically an extension of #874, more or less. We're doing some stuff to look into utilizing delta time and unlocking the FPS, though vsync is something else that we're not currently messing with. 

As for v-sync, I've added a PR to do this.

**Comment by rafcolson** [comment]
@SolarLune @VinnieH01 So, I guess it is now possible to let the computer render as many frames as it can in one second and also have an option to turn on vsync to let the computer limit this number automatically?

**Comment by SolarLune** [comment]
More or less, yeah, though I haven't tried setting a high FPS value with VSync on. Not quite sure how delta timing and substeps will react.

**Comment by SolarLune** [comment]
Hey, this issue can probably be closed at this point - we more or less have unlimited framerate now, as well as VSync.
