### ISSUE TITLE
Suggestion: Profiler - copy assets on creation instead of exporting

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#929]
On export the scene of the profiler is temporarily loaded and added to the blend file in your bdx project, with `exprun.py`:
```python
if prof_scene_export:
	with bpy.data.libraries.load(j(ut.gen_root(), "profiler.blend")) as (data_from, data_to):
		data_to.scenes = ['__Profiler']
```
This is leaving excess data inside the project's blend file, for which reason the profiler's scene doesn't contain any lights, materials and a world. However, this can't be avoided for meshes and fonts. So ideally, the profiler's scene is not added to the project's blend file so it stays 'untouched', which is to be expected from a user's point of view. If not, it may only be confusing.

Because the profiler's scene is exported also issues with its assets can occur in some cases. One case would be where you would create a new project and overwrite the project's `game.blend` (or add some other blend) and run bdx. The `exporter.py` now expects to find a copy of `BDXFontMono.fntx` instead of the file itself. This issue seems to be related to #571, which may describe other cases.
```python
File "C:\Users\Raf\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\bdx\exporter.py"
line 246, in fntx with open(j(fntx_dir, t.font.name + ".fntx"), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory:
'D:\\BDX\\Projects\\Test\\Test\\android\\assets\\bdx\\fonts\\BDXFontMono.001.fntx'
```
This issue currently can be solved by first running bdx once after the project is exported, but it is very annoying. During development blend file templates are frequently used to test builds. I'm not sure if this would solve those other issues, but obviously these are also caused while exporting the profiler's scene.

So instead of exporting the profiler's scene, adding to the bdx project by copying its assets on creation time, would solve all issues. With bdx development this would mean that the profiler's assets are now created by the developer and copied to the `gen/profiler` folder. This is easy:

- create a new project
- copy `profiler.blend` and `BDXFontMono.ttf` from the `gen/profiler/dev` folder into the project's `blender` folder
- open `profiler.blend` and run the project to overwrite the assets of the profiler's scene
- copy `__Profiler.bdx`, `BDXFontMono.fntx` and `__FNT_BDXFontMono.png` from the project's `assets` folder into the `gen/profiler` folder

By doing this after making changes to the profiler's scene or the profiler's font, your repository should be fully updated. It might be a slight disadvantage, but I think it's worth it, considering that we shouldn't have to worry about those other issues anymore.

So what do you guys think?

**Comment by GoranM** [comment]
> This is leaving excess data inside the project's blend file

Is there no way to remove that data, after the export process completes?

> The exporter.py now expects to find a copy of BDXFontMono.fntx instead of the file itself.

I'm not really sure I understand: Shouldn't the required resources be created by the exporter, when it exports the profiler scene?

**Comment by rafcolson** [comment]
>I'm not really sure I understand: Shouldn't the required resources be created by the exporter, when it exports the profiler scene?

Yes it will. But if the excess data (`__PBackground`, `__PBar`, `BDXFontMono.ttf`, ...) is saved with the template blend file, then when the profiler's scene is added, all of those resources will be duplicated.

Another solution will be to make sure that all excess data is removed by opening and saving the template blend file two times.

>Is there no way to remove that data, after the export process completes?

I searched the Blender API, but I couldn't find anything to could remove it.

**Comment by rafcolson** [comment]
I think I may have found the reason why `BDXFontMono.001.fntx` is not found. In `exporter.py` @SolarLune's `FontWriter` naturally use the actual name of the font, instead of the name of the data block in Blender. Else identical fonts would be exported needlessly.

```python
command = 'java -cp "{}" com.solarlune.fontwriter.DesktopLauncher '.format(sep.join(jars))
...
command += '"{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}---{}" '.format(ttf, j(fonts_dir, font.name), size, shdo[0], shdo[1], shdc[0], shdc[1], shdc[2], shda, outt, outc[0], outc[1], outc[2], outa, outr, col[0], col[1], col[2], alpha)
os.system(command)
```
The `ttf` variable is derived from the font's file path, and so this contains the actual name of the font. But the second parameter `j(font_dir, font.name)` is derived from the font's name in Blender. You can test this:
```python
import bpy
objects = bpy.context.scene.objects
texts = [o.data for o in objects if o.type == "FONT"]
font_data_block_names = [t.font.name for t in texts]
actual_font_names = [t.font.filepath.split("\\")[-1].split(".")[0] for t in texts]
print(font_data_block_names)
print(actual_font_names)
```
The latter is also done to describe the texts, when added to `bdx["models"]` with [`srl_models_text.fntx(t)`](https://github.com/GoranM/bdx/blob/7c60dd9b8186a232f7bc139720bc0b7e351f6716/blender/bdx/exporter.py#L246). So this is fixed by extracting the actual name from the font's file path.

**Comment by GoranM** [comment]
> I searched the Blender API, but I couldn't find anything that could remove it.

We need to confirm that before we consider anything else.

Probably best to ask in the blender community.

**Comment by rafcolson** [comment]
Yes, I was thinking the same thing. I'll be posting on BlenderArtists this week. Keeping you updated.

**Comment by rafcolson** [comment]
PR submitted. The previous fix didn't cut it. This one does.

**Comment by rafcolson** [comment]
Another PR submitted. It's possible to remove all excess data anyway. [This BlenderArtists thread](https://blenderartists.org/forum/showthread.php?357724-Force-to-delete-datablock&highlight=remove+unused+dat) showes how this can be done. I didn't think this would actually remove every remnant of the data blocks.

Still have to see if the `remove(item, unlink)` will work as expected in Blender 2.79, but I think it should be okay.

**Comment by rafcolson** [comment]
PR's merged. Thanks.
