### ISSUE TITLE
init() and create() functions for GameObjects.

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#93]
Hey, there. So, I think both "init()" and "create()" functions might be useful for GameObjects. The main reason this would be a good idea, I think, is that BDX can, on scene creation, run all objects' init()  functions, and *then* run their create() functions. This would allow you to set up relationships, spawn scenes in, and otherwise set up the game from objects (in the init() function) and then be sure that they're actually usable before proceeding with them (in the create() function).

The main reason I'm asking for this is because I spawn a scene in from a game object's init() function, but I need to use an object in that spawned scene elsewhere. I could check to see if the scene exists in the main() function of the object that's going to access it, but that's a bit awkward. 

I suppose some level of "execution priority" would be really useful, alternatively; perhaps it could be implemented as a static variable in the GameObject's class (so just defining your custom class, extending it from GameObject, and then setting its executionPriority in the class itself would allow BDX to check it to make it run first, or last, or whatever)?

**Comment by GoranM** [comment]
One could probably just change [this line](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L609), to:

```python
"objects": srl_objects(sorted(objects, key=lambda o: o.name)),
```

And then, in BDX, initial execution order should be based on python's sort order for object names (strings).

So, assuming that all your object names start with regular letters, you could just prefix the name of the "priority" object with a number, and that should produce desired results.

... Well, to avoid potential confusion, it would probably be better to write a bit of extra code, and consider only names that start with numbers:

```python
priority_objects = [o for o in objects if o.name[0].isdigit()]
other_objects = [o for o in objects if o not in priority_objects]
objects = sorted(priority_objects, key=lambda o: o.name) + other_objects
```

**Comment by SolarLune** [comment]
It would seem that .java files and Java classes can't start with numbers, so that won't work. It's kind of a hack, but initial execution order based on Python's sort order for object names should work (so I guess you'd name whatever object you wanted to start first "AMyObject" or "AAMyObject" or whatever). 

I went with the first option to just alter the srl_objects line, but that didn't work because srl_objects uses a dictionary. So, I turned it into a SortedDictionary, but that still doesn't work. Looking into the issue currently.

**Comment by GoranM** [comment]
> It would seem that .java files and Java classes can't start with numbers, so that won't work.
> ...
> Looks like it might have to do with templates being a HashMap (so it doesn't preserve the order that objects are inserted into it).

Ah, that's right - It completely slipped my mind.

> OK, is this the ideal solution? Seems like for this to work, a lot of the code would have to be altered to use order-preserving arrays (for example, rootParents' creation as a variable in line #215 of Scene.java).

I don't know if it's "ideal", but I think it's much better than adding code to the public API.

We can just sort on the java side: In addInstances, instead of iterating directly through template.values(), we'll make an ArrayList, sort it as we wish, and then iterate through that.

Our naming convention could be a "E#_" prefix, so "E0_ObjectName" would init before "E1_ObjectName", and then the rest would follow.

**Comment by SolarLune** [comment]
> I don't know if it's "ideal", but I think it's much better than adding code to the public API.

I don't think so; I'd say adding some sort of official execution priority variable or additional function would be a better solution for usability purposes. It's easier for users to understand and use, and contributes less room for error due to potential misspellings. It enforces less of a rule on users, as well, and extends well with larger projects (just raise the numbers on the objects you want to run first, for example).

Most people who use BDX aren't going to need this until they're a ways into using the engine and so need to initialize the game state before play. By this point, they might already have a large amount of source files and game objects to the point where renaming them all is unrealistic.

The naming convention sounds unnecessary to me. If this is supposed to be an "official BDX" approach to things, I think it best not to hem users into suggested means of development. Users should be able to name their objects and source files whatever they wish, more or less. I could imagine being slightly annoyed at having fifteen (or more) source files all named "E1_Whatever" in my source folder. 

And, if you do adhere to this naming convention, what if you need to change the order of execution for an object to make it run before anything else? That'd mean you would need to rename every object and every source file (except for the "priority" object) to add at least one number to its name.

Overall, it seems like there must be a better way. Is this really the only solution?

**Comment by GoranM** [comment]
From what I understand (and correct me if I misunderstood), you need to run some code before objects in the scene are initialized (before their init method is called).

If that's what you need to do, then it doesn't seem like you would really need to define a specific "initialization/execution priority" for all objects.

You just need a way to run some code before anything else runs.

So, for that, you could just have a very simple convention, where an object prefixed with "init_" is initialized first, and that would solve the problem, without having to add anything more to GameObject, or any other part of the public API.

Realistically, is there a case where you would need to specify initialization order for more than one object?

**Comment by SolarLune** [comment]
> Realistically, is there a case where you would need to specify initialization order for more than one object?

Nope, that's basically it. If an object prefixed with "init_" runs first, then that should be good enough for most games. 

How exactly should this be implemented? Just as a check in the runObjectLogic() function to see if there's an object with "init_" in it first, and if so, to take it out of the list of objects to run logic on, and run it first?

**Comment by GoranM** [comment]
You only need to enforce initialization order (init() calls), not execution order (main() calls), so I guess you can just follow the same procedure I outlined before, to modify addInstances on Scene, but instead of sorting the ArrayList (created from template.values()), you would just pick out the object whose name starts with "init_", and put that in front.

Assuming I didn't overlook something, I think that should work.

**Comment by SolarLune** [comment]
OK, I think that did it. PR made - #99.
