### ISSUE TITLE
Suggestion: Profiler - using (upgraded) Text

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#930]
I've been working on a commit to improve the Profiler drastically. This would mean:
- major simplification of the code which improves workflow
- drastic decrease of draw calls which improves performance
- more options

The profiler's scene would not have numerous objects to visualize tick info, subsystems, gl statistics and props, but only two: one `Text` for all text and one `GameObject` for the subsystems' bars.

Additionally this upgrade would also add the option to show or hide the background and replacing the font to a shadowed font.

So what do you think?

Referenced commit will follow.

**Comment by SolarLune** [comment]
This all sounds fine. Simpler code is better, and more options is better. 

I still am of the opinion that if it's generic enough (something that pretty much every game could use), the Profiler could be extended to provide more functionality. More to do with development, and less to do with simply profiling game code or timing. Here's an example of a rather cool profiler / debugger: http://haxeflixel.com/documentation/debugger/

... But that's an aside to the topic at hand - I'm up for any Profiler refactoring. Sounds like a good idea.

**Comment by GoranM** [comment]
I think it would be best to focus on the first two points.

Including "more options" is something that can be done later, in a different PR.

Improving/simplifying the existing feature set should take priority.

**Comment by rafcolson** [comment]
Okay.

**Comment by rafcolson** [comment]
To be honest, I wasn't happy with the current state of the profiler. I'm not sure where things got wrong, but tests with current master are showing a lot of issues. Here's a `Sacky.java` I've been using:
```java
package yourPackage;

import com.nilunder.bdx.*;

public class Sacky extends GameObject{
	
	private boolean props;
	
	public void init(){
		Bdx.profiler.visible(true);
	}

	private void function(){
		if (props){
			Bdx.profiler.props.clear();
			props = false;
		}else{
			props = true;
		}
	}

	public void main(){
		if (props){
			Bdx.profiler.props.put("position", position());
			Bdx.profiler.props.put("scale", scale());
			Bdx.profiler.props.put("orientation", orientation());
			Bdx.profiler.props.put("transform", transform());
		}
		if (Bdx.keyboard.keyHit("space")){
			applyForce(0, 0, 300);
		}else if (Bdx.keyboard.keyHit("enter")){
			Bdx.profiler.start("function");
			function();
			Bdx.profiler.stop("function");
			Bdx.profiler.stop("functionA");
			Bdx.profiler.stop("functionB");
			Bdx.profiler.stop("functionC");
			Bdx.profiler.stop("functionD");
		}else if (Bdx.keyboard.keyHit("0")){
			Bdx.profiler.visible(!Bdx.profiler.visible());
		}else if (Bdx.keyboard.keyHit("1")){
			Bdx.profiler.tickInfoVisible(!Bdx.profiler.tickInfoVisible());
		}else if (Bdx.keyboard.keyHit("2")){
			Bdx.profiler.subsystemsVisible(!Bdx.profiler.subsystemsVisible());
		}else if (Bdx.keyboard.keyHit("3")){
			Bdx.profiler.glVisible(!Bdx.profiler.glVisible());
		}else if (Bdx.keyboard.keyHit("4")){
			Bdx.profiler.propsVisible(!Bdx.profiler.propsVisible());
		}else if (Bdx.keyboard.keyHit("5")){
			Bdx.profiler.scale(2f);
		}else if (Bdx.keyboard.keyHit("6")){
			Bdx.profiler.remove("function");
		}else if (Bdx.keyboard.keyHit("7")){
			Bdx.restart();
		}
	}
	
}
```
Pretty ashamed that I let this happen somehow. In any case, all of these issues are now fixed with this upgrade also.

In short:
- Functions to get categories as strings are added and kept public (making `gl.print()` superflous).
- All categories (as strings) are now joined in one Text object.
- The subsystems' bars are now joined in one mesh and the mesh is updated with a customized function to edit the position of the vertices.
- User created subsystems are separated from the internal subsystems with a line break.
- Props with Matrices and vectors, as well as strings with line breaks, are now shown with line breaks.
- The names of the user created systems and props are now shown fully. Columns are repositioned.
- But the profiler's viewport is still fixed to 1024 X 1024 pixels. This may change in the future.
- The profiler is now initialized always and never more than once.
- The profiler is not updated whatsoever unless it is active.
- The profiler now can be activated to get access to all data that's being updated, without updating the visual parts of the profiler.
- Static fields and methods are replaced by non-static fields and methods. In the future a functionality could be implemented to replace the profiler with a custom profiler.
- Overall it will be easier for developers to adjust or improve the profiler. The code is more organized and more dynamic. For example, replacing the font (with different "xadvance" and or "lineHeight") would be fairly straightforward since the position of the bars and the width of the background are now calculated, and not estimated, like they were before.

I'll be submitting a PR soon, but in the meantime, here's a reference to my repository if you'd like to have a look.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks.
