### ISSUE TITLE
Blender GUI Update: Execute Script Before Export and Run

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#938]
Hey, there. 

I think a low-effort, but fairly useful option that might be cool would be a field that you could fill in to have BDX execute a script or batch file prior to export and run. This would allow the user to easily customize the export and run process (i.e. so they can create a file consisting of available sounds, music, or scenes that you can read from during gameplay, or run external tools, or whatever).

**Comment by GoranM** [comment]
Ok.

**Comment by SolarLune** [comment]
PR was merged, so I'll close this now. Thanks.
