### ISSUE TITLE
Alternative JVM Language Support

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#941]
Hey, there.

So [Kotlin](http://kotlinlang.org/) is a statically-typed, slightly more easy-going language that compiles down on the JVM, and appears to interact just fine with Java. I was thinking that it might be pretty cool to support this under BDX. While it doesn't by default support the HTML5 GWT target, it might still be possible using external tools like TeaVM, so I think it'd be fine if we just document it for those who don't require that platform target.

My idea for support is just to have a language option you can set when you go to create a BDX project. Because Kotlin works with Java without any customization, we don't really need to do much more than just add some lines to `build.gradle` files - I managed to get an ordinary BDX project running under Kotlin in just a few minutes using [this LibGDX](https://github.com/libgdx/libgdx/wiki/Using-libgdx-with-Kotlin#configure-gradle) guide. I only had to make one slight engine change, which is where our `libgdx_version()` function from `utils.py` searches for the LibGDX version (which gets bumped down a line or two after adding Kotlin stuff). Everything else works automatically.

![screenshot from 2017-07-16 20 30 28](https://user-images.githubusercontent.com/4733521/28255464-279992e2-6a6c-11e7-877d-3ffab3204862.png)

What do you guys think? Could be good to help expand the user-base quickly and easily.

**Comment by GoranM** [comment]
> Could be good to help expand the user-base quickly and easily.

I don't think that our user-base size is significantly affected by our lack of support for \<some langauge other Java\>.

BDX is a Java engine. The wiki hosts documentation for a Java API, and Java is the only language that can be transpiled for the HTML5 target.

If people really want to use Kotlin with BDX, they can do what you did (since it's apparently so easy), but I don't think it makes sense to build explicit support for it (or any other language) in BDX.

**Comment by SolarLune** [comment]
> I don't think that our user-base size is significantly affected by our lack of support for <some langauge other Java>.

No, but I think the userbase size _could_ rise significantly if we provided actual support for other JVM languages (i.e. the userbase could grow from the communities of the supported languages). However, I feel like the users of those other languages would probably mostly appreciate an engine entirely written in that language (which isn't feasible).

In any case, it looks like it's going to be a bit more complex even to just build in support for the user to determine the language, as:
- The Instantiator isn't tuned to use classes in other kinds of files - it only looks for Java files. 
- Classes in the blend file are still tuned to export only if they end in `.java`. 
- I'll also have to alter a function in `utils.py`, as I mentioned, to look for the LibGDX version rather than assume that it's on line 21.

> BDX is a Java engine. The wiki hosts documentation for a Java API, and Java is the only language that can be transpiled for the HTML5 target.

All that's true, but I don't really see why any of that means that other languages _should_ necessarily be off the table universally. I think we can support the option to choose without too much issue.

**Comment by GoranM** [comment]
> I feel like the users of those other languages would probably mostly appreciate an engine entirely written in that language

Even with that, I think most of them would still probably decide to use Unity, or Unreal.

The ability to use a preferred language is a nice perk, but it doesn't compare with the perceived value of a well established (almost "standard") tool, and a large community with a list of successful projects.

> I don't really see why any of that means that other languages should necessarily be off the table universally

Additional languages introduce significant complexity, without providing a clear benefit that would justify that complexity.

If the core obstacle to using BDX was that "people don't like Java as much as X", then I think we would be justified in including support for X, but that doesn't seem to be the case.

**Comment by SolarLune** [comment]
You make some good points. I just made a PR for basic changes to allow the developer to use alternative JVM languages (so nothing new on our end apart from just looking for all files, not just .java ones, in Blender for export and in the source folder for instantiation).

**Comment by SolarLune** [comment]
The PR was merged, so I'll close this. Thanks!
