### ISSUE TITLE
Suggestion: Ghost Collision Groups

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#954]
How would I go about ghosting between specific objects?

For example, let's say I have the Player and an NPC. I want the Player and NPC to be able to walk through each other, but also detect when they're touching each other. The problem with using collision groups or collision masks is that collision is no longer detected between the NPC and the Player. The problem with making both the Player and NPC ghosts is that they will fall through the ground.

Is there already a solution for this? If there isn't, where should I look to add this in?

Is this a feature worth adding in?

**Comment by SolarLune** [comment]
Yo, 'sup.

To keep the player from touching the NPC, you can put them on different collision groups. Then, to detect collisions with each other, you can give them both additional Sensor objects. As of the latest release, I think it should work as long as both Player and NPC are Dynamic. The next release should have Sensors be able to detect any and everything. 

The next release would also have AABB testing, which would also be satisfactory for this purpose (assuming you maintain a list of valid NPCs you can quickly check, for example).

**Comment by Lucrecious** [comment]
> Then, to detect collisions with each other, you can give them both additional Sensor objects.

Thanks! This is a fine solution.
