### ISSUE TITLE
BDX Build Failure on Windows

### ISSUE THREAD

**Issue by LuckySvenn** [GoranM/bdx#96]
Hey, so I was following along with the tutorials you have on Youtube and seem to have run into a problem. When I hit 'P' to build and play the game supplied when creating a new BDX project, I get a build error with this output:

>Read new prefs: C:\Users\j.sweet\AppData\Roaming\Blender Foundation\Blender\2.70
>\config\userpref.blend
>found bundled python: C:\Program Files\Blender Foundation\Blender\2.70\python
>Android SDK location 'C:\Program Files\Blender Foundation\Blender\android-sdk' d
>oesn't contain an SDK
>Executing 'C:\Users\j.sweet\Documents\Dev\Games\GDX\BDX\testgame/gradlew.bat cle
>an'
>Configuration on demand is an incubating feature.
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>A problem occurred configuring project ':android'.
>> The SDK directory 'C:\Program Files\Blender Foundation\Blender\android-sdk' do
>es not exist.
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug
>option to get more log output.
>
>BUILD FAILED
>
>Total time: 3.046 secs
>read blend: C:\Users\j.sweet\Documents\Dev\Games\GDX\BDX\testgame\blender\game.b
>lend
>Error: File written by newer Blender binary (270.5), expect loss of data!
>
>Traceback (most recent call last):
> File "C:\Users\j.sweet\AppData\Roaming\Blender Foundation\Blender\2.70\scripts
>\addons\bdx\ops\createproj.py", line 236, in execute
>   self.open_default_blend()
>  File "C:\Users\j.sweet\AppData\Roaming\Blender Foundation\Blender\2.70\scripts
>\addons\bdx\ops\createproj.py", line 163, in open_default_blend
>    bpy.ops.wm.open_mainfile(filepath=fp)
>  File "C:\Program Files\Blender Foundation\Blender\2.70\scripts\modules\bpy\ops
>.py", line 188, in __call__
>    ret = op_call(self.idname_py(), None, kw)
>RuntimeError: Error: File written by newer Blender binary (270.5), expect loss o
>f data!
>
>
>location: <unknown location>:-1
>
>location: <unknown location>:-1
>
>------------ BDX START --------------------------------------------------
>
>Configuration on demand is an incubating feature.
>:core:compileJava
>warning: [options] bootstrap class path not set in conjunction with -source 1.6
>C:\Users\j.sweet\Documents\Dev\Games\GDX\BDX\testgame\core\src\com\jsweet\testga
>me\inst\Scene.java:12: error: cannot find symbol
>                        return new com.jsweet.testgame.Sacky();
>                                                      ^
>  symbol:   class Sacky
>  location: package com.jsweet.testgame
>Note: C:\Users\j.sweet\Documents\Dev\Games\GDX\BDX\testgame\core\src\com\jsweet\
>testgame\BdxApp.java uses unchecked or unsafe operations.
>Note: Recompile with -Xlint:unchecked for details.
>1 error
>1 warning
>:core:compileJava FAILED
>
>FAILURE: Build failed with an exception.
>
>* What went wrong:
>Execution failed for task ':core:compileJava'.
>> Compilation failed; see the compiler error output for details.
>
>* Try:
>Run with --stacktrace option to get the stack trace. Run with --info or --debug
>option to get more log output.
>
>BUILD FAILED
>
>Total time: 3.135 secs
>
>------------ BDX END ----------------------------------------------------
>
>Error: BDX BUILD FAILED

From the output, I'm not sure if it might be because I don't have an Android SDK supplied or perhaps my JDK isn't set properly in my PATH environment variable? Also, I should include that the textures do not appear on the models, they only appear white. When I check under the android/assets/bdx/textures I see they are supplied, though.

Thank you for the help!

**Comment by SolarLune** [comment]
What version of Blender are you using?

**Comment by LuckySvenn** [comment]
Just installed Blender 2.73a and it fixes everything! It builds the project and I can see the textures on the model now. Sorry, I thought 2.7 was usable with it.

Thanks again!

**Comment by GoranM** [comment]
It's pretty clear that he has the JDK; Java compile errors can only be produced by the java compiler.

This is actually a BDX bug. We failed to catch that python exception (`RuntimeError: Error: File written by newer Blender binary (270.5), expect loss o
f data!`), so the rest of the export process didn't have a chance to run, and, among other things, the package declaration in Sacky.java wasn't set to the package specified upon creation.

I don't know why Blender devs throw an exception for what should essentially just be a warning, but anyway: we should catch this one, and hopefully avoid similar problems in the future (people are likely to work with Blender versions that are a bit behind, while some of us may use the latest version to modify `blender/bdx/gen/game.blend`, making this a potential issue for many).

So, I'm going to re-open this, until we have code that handles this in master.

Thank you, LuckySvenn, for reporting!
