### ISSUE TITLE
Build errors on latest repo

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#960]
Here's the error I get, not sure how to fix it :/
http://pasteall.org/509704
```
build-fontwriter:
    [javac] Compiling 1 source file to /Users/lucrecious/dev/bdx/extern/fontwriter/build
    [javac] /Users/lucrecious/dev/bdx/extern/fontwriter/src/com/solarlune/fontwriter/DesktopLauncher.java:12: error: package com.badlogic.gdx.tools.bmfont does not exist
    [javac] import com.badlogic.gdx.tools.bmfont.BitmapFontWriter;
    [javac]                                     ^
    [javac] /Users/lucrecious/dev/bdx/extern/fontwriter/src/com/solarlune/fontwriter/DesktopLauncher.java:54: error: package BitmapFontWriter does not exist
    [javac] 						BitmapFontWriter.FontInfo fontInfo = new BitmapFontWriter.FontInfo();
    [javac] 						                ^
    [javac] /Users/lucrecious/dev/bdx/extern/fontwriter/src/com/solarlune/fontwriter/DesktopLauncher.java:54: error: package BitmapFontWriter does not exist
    [javac] 						BitmapFontWriter.FontInfo fontInfo = new BitmapFontWriter.FontInfo();
    [javac] 						                                                         ^
    [javac] /Users/lucrecious/dev/bdx/extern/fontwriter/src/com/solarlune/fontwriter/DesktopLauncher.java:56: error: package BitmapFontWriter does not exist
    [javac] 						fontInfo.padding = new BitmapFontWriter.Padding(1, 1, 1, 1);
    [javac] 						                                       ^
    [javac] /Users/lucrecious/dev/bdx/extern/fontwriter/src/com/solarlune/fontwriter/DesktopLauncher.java:73: error: cannot find symbol
    [javac] 						BitmapFontWriter.writeFont(data, new String[]{fileName + ".png"}, outputFolder.child(fileName + ".fnt"), fontInfo, resX, resY);    // Writes the .fnt file, I guess
    [javac] 						^
    [javac]   symbol: variable BitmapFontWriter
    [javac] /Users/lucrecious/dev/bdx/extern/fontwriter/src/com/solarlune/fontwriter/DesktopLauncher.java:74: error: cannot find symbol
    [javac] 						BitmapFontWriter.writePixmaps(parameter.packer.getPages(), outputFolder, fileName);
    [javac] 						^
    [javac]   symbol: variable BitmapFontWriter
    [javac] 6 errors

BUILD FAILED
/Users/lucrecious/dev/bdx/build.xml:75: The following error occurred while executing this line:
/Users/lucrecious/dev/bdx/extern/fontwriter/build.xml:26: Compile failed; see the compiler error output for details.
```

All I did was clone the latest repo, and tried to ant.

**Comment by SolarLune** [comment]
I think you need to grab the gradle dependencies for the font writer - try building a new BDX project from Blender and then running it - I think it should download the dependencies, and then you should be able to build.

**Comment by Lucrecious** [comment]
Alright, that worked, at least just to build BDX.

The next problem is exporting is broken, here's a pasteall of it, it's a lot, but seems to be a simple issue.
http://pasteall.org/509764

Lastly, apparently, this file is missing: bdx/shaders/2d/depthExtract.vert.

The latter two problems happen after a fresh `git clone` and hitting "Run BDX" to download the dependancies. After this, Exporting BDX doesn't work and the missing shader prevents running.

**Comment by SolarLune** [comment]
Try restarting Blender. If that doesn't work, what version of Blender are you using?

As for the missing shader file, it might be there, but just be named something different (I might have renamed the shader at some stage, like from `depth.vert` to `depthExtract.vert`). Are you working in an old BDX project, or a new project?

**Comment by Lucrecious** [comment]
It's a pretty old project haha, everything is pretty much fixed right now (it took forever to update everything, my BDX version was like from middle of last year). 

The profiler is broken on both my old project and the new project, if I enable it, I get the [errors I showed you above](http://pasteall.org/509764).

**Comment by SolarLune** [comment]
Oh, so it's the Profiler specifically. Delete the exported profiler scene file from your android assets scenes folder and re-export it.

**Comment by Lucrecious** [comment]
Nah, it doesn't do anything.
Here are the steps I took:
1. Delete __Profiler scene
2. Remove __Profiler asset
3. Turn off Profiler
4. Export - error

It's the same error:
http://pasteall.org/509764

**Comment by SolarLune** [comment]
So on a brand new project you can't export the Profiler?

**Comment by Lucrecious** [comment]
On a new project, I get this error: http://pasteall.org/509764

Which is part of the reason I can't make a small example for my other issue lol

**Comment by SolarLune** [comment]
Ah, what version of Blender are you using?

**Comment by Lucrecious** [comment]
Blender 2.77a?

**Comment by SolarLune** [comment]
OK, I thought this might be the case. They changed the API between 2.77a and 2.78 [(there is no `align_x` attribute on Text objects in 2.77a)](https://docs.blender.org/api/blender_python_api_2_77_0/bpy.types.TextCurve.html?highlight=textcurve#bpy.types.TextCurve.align). Update your Blender version to fix it.

**Comment by rafcolson** [comment]
>Update your Blender version to fix it.

It might be good to adapt exporting to Blender versions.

**Comment by Lucrecious** [comment]
It would probably be good enough to just document the version of Blender you need. Or even better, just package Blender with BDX already with the plugin installed and ready to go.

**Comment by SolarLune** [comment]
> It might be good to adapt exporting to Blender versions.

OK, I submitted a PR.

> Or even better, just package Blender with BDX already with the plugin installed and ready to go.

That's up to Goran, but I don't think that's really necessary (because now you have to force usage of different versions of Blender with BDX, have more, heavy downloads for BDX releases, have more stuff to download when doing development on BDX, etc).

**Comment by rafcolson** [comment]
>OK, I submitted a PR.

Great! Thanks a lot.

**Comment by Lucrecious** [comment]
>That's up to Goran, but I don't think that's really necessary (because now you have to force usage of different versions of Blender with BDX, have more, heavy downloads for BDX releases, have more stuff to download when doing development on BDX, etc).

Good point, but I meant more like a script. Download the lightweight BDX, run a script to download/upgrade/check dependencies (Blender, LibGDX and LibGDX extensions). Right now dependency downloading happens through Blender (which literally just runs a build.gradle) and it only does LibGDX and its extensions (which makes sense because you're using Blender to build the project).

I don't know, just food for thought haha

**Comment by SolarLune** [comment]
> Great! Thanks a lot.

No prob!

> Good point, but I meant more like a script.

That's a cool idea, but I feel like most people who use BDX already are familiar with and want to use Blender, so they probably already have it installed. Making a script to download and upgrade dependencies as necessary seems like more investment than really needs to be there when it comes to relatively simple code (`align` vs. `align_x`) and a relatively simple engine.

**Comment by Lucrecious** [comment]
Well, it could be as simple as running a `git clone` on some repository. But yeah, I agree, this extra amount of polish might not be worth the trouble haha

Anyways, I'm glad this is fixed! Closed!
