### ISSUE TITLE
Suggestion: capability to set Text capacity

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#966]
Currently we are exporting Text meshes in [exporter.py](https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L262), which seems unnecessary because BDX meshes of Text objects are regenerated in [Scene.init()](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L324), overwriting those.

Text capacity is also limited to the amount of characters you typed in Blender. Ideally Text capacity would be limitless, or at least be manageable.

The current design's flaw seems to be illustrated best with the Profiler. To be able to have a reasonable capacity for generating the Profiler's text, the exported data is exceedingly large. To such extremes that it is affecting the speed of the overall exporting process (and building process too probably).

**Comment by GoranM** [comment]
Originally, it was done that way so it can be treated just like any other object, which already has a set mesh. If you want to export text without mesh data, you could do that, but you would have to create that mesh data at runtime.

The static nature of the text was to avoid potential performance issues with having to recreate a vbo whenever you need more vertices for additional letters. Maybe it was a needless worry, but it's something you would have to test.

**Comment by rafcolson** [comment]
Okay, thanks. I'll look into it as soon as I'm getting the transform commit working. I'm really having a lot of trouble with it though...

**Comment by rafcolson** [comment]
>The static nature of the text was to avoid potential performance issues with having to recreate a vbo whenever you need more vertices for additional letters.

Thinking about this more, even if there would be an issue with having to recreate a vbo, this would only happen once when setting Text capacity. The idea I'm proposing is not to automatically update Text capacity (which would require recreating a vbo) every time text is being edited.

In case with the Profiler it then could be managed to update the Text capacity only with changes to the visibility of gl stats, props and user created subsystems. Initially there would only be a Text capacity large enough to be able to view the tick rate and internal subsystems, which is the default.

**Comment by GoranM** [comment]
Fundamentally, you have to create a new vbo whenever the number of characters exceeds the capacity of the existing vbo.

How often that happens depends on the what the program is doing with text. The worst case scenario would basically be a loop that's adding a character to the existing text, because every addition would go over capacity, and require a new vbo. You could remedy that by always making a vbo that's twice as large, to give yourself a bit of a buffer before needing to create a new vbo, but that's assuming that it would even be necessary - on the other hand, you don't want to needlessly waste gpu memory, so you have to strike a balance there.

**Comment by SolarLune** [comment]
You could set the first created VBO's size in relation to the number of characters in the text object in Blender. That way, you could create the "ideal" VBO size initially if possible, but BDX could expand upon it as necessary if you add more characters.

**Comment by rafcolson** [comment]
>You could remedy that by always making a vbo that's twice as large, to give yourself a bit of a buffer

That would be the idea. No automatic updates of vbo's. Just a means to set the length.

>but BDX could expand upon it as necessary if you add more characters.

I'm not sure. Some users may not be aware of the potential cost on the gpu, so I would opt for not being able to add more characters unless the length is set to a higher value manually. I could have misunderstood.

**Comment by rafcolson** [comment]
These commits are on top of the Mesh upgrade commit.

The Profiler's scene now roughly takes 64KB (previously more than 1MB).

>You could set the first created VBO's size in relation to the number of characters in the text object in Blender.

This is now possible with the extra argument for updating capacity: `Text.text(String txt, boolean updateCapacity)`. By default this argument will be `false`.

>You could remedy that by always making a vbo that's twice as large, to give yourself a bit of a buffer before needing to create a new vbo, but that's assuming that it would even be necessary - on the other hand, you don't want to needlessly waste gpu memory, so you have to strike a balance there.

The capacity of the Profiler's text is updated automatically. This could potentially cause issues with utilizing Profiler.props only. So I'll have to do some tests first to check if your proposed remedy would have to be necessary.

That said, for user cases I think it would be best to leave it up to the user to remedy this, which now is easily done with the new methods.

```java
package myPackage;

import com.nilunder.bdx.Text;

public class MyText extends Text{
	
	private final int BUFFER = 20;
	...
	
	public void updateText(String s){
		if (s.length() > capacity()){
			capacity(s.length() + BUFFER);
		}
		text(s);
	
	...
}
```

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
Merged. Thanks! API changes coming up. Closing after.
