### ISSUE TITLE
Question: ProfilerToggler component

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#967]
It was mentioned before that the component, explained in the [ProfilerToggler component tutorial](https://github.com/GoranM/bdx/wiki/Component-Tutorials%3A-ProfilerToggler), could be included. So, my question is: could it?

If not, could some version of a `ProfilerToggler` component be useful enough to justify engine inclusion?

Is so, what needs to be changed?

**Comment by GoranM** [comment]
> could some version of a ProfilerToggler component be useful enough to justify engine inclusion?

Virtually any feature can be incredibly useful in a specific set of circumstances, but if those circumstances are fairly uncommon, and there are existing methods to deal with them (which are not overly inconvenient for the user), then the overall benefit of that feature is usually not high enough to justify engine inclusion.

Typical use case for a profiler is to simply have the information visible on screen, while the game is running. If there's an occasional need/desire for toggling visibility, users can set that up with minimal effort.

With that in mind, I'm not really sure how one could justify including a "ProfilerToggler" component into the engine code base.

**Comment by rafcolson** [comment]
Okay. Thanks.
