### ISSUE TITLE
Suggestion: only apply modifiers when "RENDER"

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#971]
Right now modifiers are applied when "PREVIEW" is enabled. Setting to "RENDER" will have the advantage that we can preview the modifier in Blender without having to apply it in BDX, which is intended. The BGE also doesn't apply the modifier, unless "RENDER" is enabled.

Edit:

Since I expect that this change is justified, I've submitted a PR.

**Comment by GoranM** [comment]
Sounds reasonable.

It's merged - Thanks.

**Comment by rafcolson** [comment]
Thank you.
