### ISSUE TITLE
Suggestion: adding support for custom normals

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#974]
Meshes in Blender can also have customized normals. This is activated like so:
```python
ob = bpy.context.scene.objects.active
me = ob.data
me.use_auto_smooth = True
bpy.ops.mesh.customdata_custom_splitnormals_add()
me.normals_split_custom_set_from_vertices([v.normal for v in me.vertices])
```
Normals could now be edited, for instance by using the _Data Transfer_ modifier:
```python
cn = ob.modifiers.new(name="Copy Custom Normals", type="DATA_TRANSFER")
cn.object = ob_base
cn.use_loop_data = True
cn.data_types_loops = {"CUSTOM_NORMAL"}
bpy.ops.object.modifier_apply(modifier=cn.name)
```
I'm using this to fix the borders of split sections of a terrain.

However, BDX doesn't export these custom normals. I'm submitting a PR to fix the issue.

**Comment by rafcolson** [comment]
PR updated.

Omitted:
```python
mesh.calc_normals_split()
```
It probably should be expected that users are updating the `normal` attribute of `Mesh` themselves, after modifying custom normals. However, generally users may forget about this requirement for getting access to custom normals. So it may be good to mention this in the API.

**Comment by GoranM** [comment]
Merged.

**Comment by rafcolson** [comment]
Thanks!

**Comment by rafcolson** [comment]
There seems to be a problem in Blender with custom normals. After saving and reopening a blend file with objects with custom normals the normals need to be recalculated again. I'm not sure if this is a bug or if this is intended. For now I'm just re-adding:
```python
mesh.calc_normals_split()
```

**Comment by rafcolson** [comment]
Thanks!
