### ISSUE TITLE
BDX fails build related to internal text file

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#98]
Hey. So if you have a script file in a blend file named correctly and then change it to error out, even if you change it back, BDX won't build. It looks like BDX exports the internal text files to actual text files in the src/classpath directory, but fails to clean them up if they don't exist in Blender any longer.

**Comment by GoranM** [comment]
This one is really irritating, because I can't just "nuke" all the files that are not in the .blend (people may mix internal with external), and I also want to give people the option to simply "take over" saved-out internal code with an external editor.

The only clean way I can think to resolve this is to create a subpackage specifically for internal files, and work within that isolated environment.

If anyone has better ideas, please share.

**Comment by SolarLune** [comment]
You could write the .java files to the source directory on run, and then clean those files up after BDX exits, perhaps? That way you could keep track of the files that were written and destroy them afterwards. If someone's writing their source in Blender, then they probably don't care / don't want the files in their source directory anyway. If they want to move to an external editor, they can just copy and paste the files, and BDX wouldn't need to export them anymore (I'd imagine BDX would basically only export the internal text file if it doesn't exist already).

I guess you might could also use a list to keep track of the source files that are exported each time you use BDX, and check them against what's currently in Blender after running BDX? E.G.

- Run 1 -

* Player.java
* Platform.java
* Whatever.java

- Run 2 -

* Player.java
* Platform2.java
* Whatever.java

Would delete Platform.java, since it's the one that did exist in Blender and no longer does between runs? But yeah, that would delete it even if they were using it in an external app, which isn't great...

For "taking over" source files:

You could make "writing" the source files out to the directory permanently a button on the BDX Render panel (or wherever); that way people have the decision to jump when they want to. Generally, though, you probably don't need to support this too much since Blender's text editor is not built for Java or even very comfortable, so I wouldn't think a lot of people would use it for anything substantial. Copying and pasting should be a pretty simple task if someone made the decision to jump.

**Comment by GoranM** [comment]
> You could make "writing" the source files out to the directory permanently a button on the BDX Render panel

It bothers me that I have to make a new operator just for this, but all in all, I think it's probably the best option, so I went with that.

**Comment by SolarLune** [comment]
Yeah, it looks like this should be solved. Seems like external files "trump" internal ones with the same name; I'm going to document that.

Thanks.
