### ISSUE TITLE
Suggestion: Particles

### ISSUE THREAD

**Issue by Lucrecious** [GoranM/bdx#980]
I think it'd be nice to have a separate object (not GameObject) for "particles" something very lightweight and simple so they can be pooled easily.

For example, scene.addParticle("Whatever") coud add this new lightweight particle with the mesh from the "Whatever" GameObject.

A Particle would not contain any functions or logic itself aside from `move(x, y, z)` and would always be set to a NoCollision collision type.

A Particle would only contain fields like "speed", "direction", "lifeTime" and "color" (which is contained in mesh).

Then we could have a ParticleEmitter which updates each of the particles with the "wind", "damping" and other stuff.

This is all similar to @SolarLune's [particle emitter](https://github.com/SolarLune/SolHelp/wiki/Particles) except this one would pool and use Particle instead of GameObject, and Particles themselves would not control their own behaviours - emitter would.

Any thoughts on whether this is worth doing? I'm getting up to Particle emitting in my project, and since it's an aesthetic thing, I'd rather it use as little memory and GC time as possible (if I plan on having 1000+ particles floating around or something).

**Comment by GoranM** [comment]
As for any other proposition, there needs to be a non-contrived use case that would justify adding the feature in question.

You need to have an actual problem, that would actually require a particle system.
