### ISSUE TITLE
Suggestion: export only if "use_render"

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#981]
In some cases it would be convenient to be able to keep some objects from exporting. For example objects that exist for the sole purpose of illustrating or informing things about objects or scenes.

In a current case I'm using several objects that make up the entire area of the game, but should be divided into sections. To allow easy editing and preserving normals I'm exporting the sections to a json file, so I can load and create the sections dynamically in BDX. This means that the base objects don't need to be exported, and preferably are not exported. To show what I mean you can check out the [Plane Sectionalizer](https://github.com/rafcolson/bdx-tools/wiki#plane-sectionalizer).

**Comment by GoranM** [comment]
> To allow easy editing and preserving normals I'm exporting the sections to a json file

I don't see how json is more "editable" than data exported by BDX. Also, as far as I know, BDX should be able to export normals correctly, so I'm not sure what you mean by "preserving normals".

> objects that exist for the sole purpose of illustrating or informing things about objects or scenes.

Just set them to no collision, and invisible. Having a specific option just for that doesn't seem like significantly more convenient.

**Comment by rafcolson** [comment]
>I don't see how json is more "editable" than data exported by BDX. Also, as far as I know, BDX should be able to export normals correctly, so I'm not sure what you mean by "preserving normals".

With more "editable" I was referring to editing the base object. Consider a bumpy landscape with trees and such. This could be created in Blender but take up too many data for BDX to process. By applying all modifiers and slicing into sections it would be manageable. But then you are losing a lot of editing freedom. Normals at the borders are not really manageable unless there's a base object to copy the normals from.

>Just set them to no collision, and invisible. Having a specific option just for that doesn't seem like significantly more convenient.

Setting to invisible and no collision doesn't change the fact that meshes are exported needlessly, but I guess arrows, text and other small objects wouldn't make much difference.

**Comment by rafcolson** [comment]
Another solution could be using the decimate modifier with only "render" activated to reduce polygons so large meshes are not exported needlessly. This would be to specific anyway. So I'm closing this.
