### ISSUE TITLE
Suggestion: Matrix3f methods for Mesh.transformUV(Matrix3f t)

### ISSUE THREAD

**Issue by rafcolson** [GoranM/bdx#995]
- `static Matrix3f position(float x, float y)`
`static Matrix3f scale(float x, float y)`
`static Matrix3f rotation(float angle)`
- These methods help defining the transform for `Mesh.transformUV(int ms, Matrix3f t)`. Additional method could be convenient: `Mesh.transformUV(Matrix3f t)`.
- `SpriteAnim` component update.

**Comment by GoranM** [comment]
Seems reasonable to me.

**Comment by rafcolson** [comment]
PR submitted.

**Comment by rafcolson** [comment]
PR merged. Thanks!
